### ISSUE TITLE
Post Librecat migration cleanup

### ISSUE THREAD

**Issue by nics** [ugent-library/biblio-backoffice#1000]
- [ ] investigate export/import errors + 1 publication was not migrated
/vol/share/nsteenla/filtered_files_fixed.jsonl
/vol/share/nsteenla/pubs_with_fixed_sizes.jsonl
- [ ] remove old production librecat* indexes, databases, files, rpm

**Comment by nics** [comment]
@mietcls @nicolasfranck keeping these for a while longer, used them for inspection only last week

**Comment by mietcls** [comment]
@nics should we keep this around in #1099 or can we start with this?

**Comment by nics** [comment]
benign neglect: keep the files
