### ISSUE TITLE
Keywords get lang "und" instead of "eng"

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1002]
# Bug

Keywords get lang "und" instead of "eng" for datasets and publications

Impact:
- FRIS rejects dataset records that lack the right language for keywords
- GISMO therefore rejects datasets too

Example publications: https://bibliotest.ugent.be/oai?verb=GetRecord&identifier=8703190&metadataPrefix=mods_36
![Image](https://user-images.githubusercontent.com/1572885/214844552-2c6799de-555e-4d6c-8eda-63ba91fe997d.png)

Example datasets:  https://bibliotest.ugent.be/oai?verb=GetRecord&identifier=8759641&metadataPrefix=mods_36
![Image](https://user-images.githubusercontent.com/1572885/214844629-261c9705-5fed-436c-8727-146287e06b61.png)

Example datasets from different repositories, with and without language tags:
- ❌ Zenodo = no language tag
- ❌ OSF = no language tag
- ❌ MD = no language tag
- ✅ Dryad = language tag

MDA (Marine Data Archive, VLIZ)
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/1572885/214849450-e0defa6e-bb0e-41cb-adb8-09bb55979177.png)

Dryad
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/1572885/214849629-eeeff7e7-eb9d-448b-ac44-aa53870ec1b5.png)

## Search for a solution

A. [not a durable solution] Can we import the language as well?
_Hard, not all data repositories define this. This means we have to lie for the keywords that do not have any language tags._
B. [researching] Can FRIS also accept the ISO language code "UND"? Other universities will have the same issue.
_Under discussion_
C. [not a durable solution, we will still lie] Can we assume "EN" unless it's defined in the dataset?
D. [rather not] Can we force the language "eng" if we cannot? However this would be lying.
E. [rejected, FRIS will still block these datasets] If there's no language available at all, would they get accepted? We cannot assume all keywords are English.

**Comment by mietcls** [comment]
Comment by Kevin:

"I've not seen anything with them having a specified language in the metadata, and I don't think keyword language is in most metadata schemas"

We might have to set the language manually in that case.

**Comment by nics** [comment]
Not a bug to me, we haven't checked the language, so undetermined is correct. Like Kevin says, most schemas don't bother with keyword language, it's more a particularity of the fris schema. Pouring effort in detecting the language of keywords is to me a resource waste.

**Comment by mietcls** [comment]
Original bug report

# Bug

Keywords get lang "und" instead of "eng" for datasets and publications

Impact:
- FRIS rejects dataset records that lack the right language for keywords
- GISMO therefore rejects datasets too

Example publications: https://bibliotest.ugent.be/oai?verb=GetRecord&identifier=8703190&metadataPrefix=mods_36
![Image](https://user-images.githubusercontent.com/1572885/214844552-2c6799de-555e-4d6c-8eda-63ba91fe997d.png)

Example datasets:  https://bibliotest.ugent.be/oai?verb=GetRecord&identifier=8759641&metadataPrefix=mods_36
![Image](https://user-images.githubusercontent.com/1572885/214844629-261c9705-5fed-436c-8727-146287e06b61.png)

Example datasets from different repositories, with and without language tags:
- ❌ Zenodo = no language tag
- ❌ OSF = no language tag
- ❌ MD = no language tag
- ✅ Dryad = language tag

MDA (Marine Data Archive, VLIZ)
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/1572885/214849450-e0defa6e-bb0e-41cb-adb8-09bb55979177.png)

Dryad
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/1572885/214849629-eeeff7e7-eb9d-448b-ac44-aa53870ec1b5.png)

## Search for a solution

A. [not a durable solution] Can we import the language as well?
_Hard, not all data repositories define this. This means we have to lie for the keywords that do not have any language tags._
B. [researching] Can FRIS also accept the ISO language code "UND"? Other universities will have the same issue.
_Under discussion_
C. [not a durable solution, we will still lie] Can we assume "EN" unless it's defined in the dataset?
D. [rather not] Can we force the language "eng" if we cannot? However this would be lying.
E. [rejected, FRIS will still block these datasets] If there's no language available at all, would they get accepted? We cannot assume all keywords are English.

**Comment by mietcls** [comment]
Crisis averted. GISMO will add the English keyword "EN" to datasets for now.
