### ISSUE TITLE
Some projects do not have a name [list still in progress]

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1008]
# Bug

## Context

Some projects do not have a name

### Questions
- Is there a way to discover which projects do not have a name?
- What if there is no English name available?

## List still of projects (still in progress)
- 3179I91A17
![Image](https://user-images.githubusercontent.com/1572885/216608649-55be3596-909e-4bfa-b858-86eef2f03827.png)
- 3G0B8817W
![Image](https://user-images.githubusercontent.com/1572885/216920817-a6234d32-0098-4d8b-8412-3277975fa4e3.png)

**Comment by mietcls** [comment]
Related improvement: https://github.com/ugent-library/biblio-backoffice/issues/969

**Comment by nics** [comment]
[projects_no_title.csv](https://github.com/ugent-library/biblio-backoffice/files/10673315/projects_no_title.csv)

@miet maybe most of the empty ones are projects marked as deleted by gismo? have to check...

**Comment by mietcls** [comment]
Thanks, I'll check them @nics

**Comment by nics** [comment]
@mietcls i'm going to delete nameless projects (and remove them from the publication if they are linked), ok?

**Comment by mietcls** [comment]
No, please do not remove them, they are in use

**Comment by mietcls** [comment]
This is an incredibly long list. TBD during the GISMO meeting what they expect?

**Comment by mietcls** [comment]
We will have to fix this with the project service

**Comment by mietcls** [comment]
Closing this one, we just need to focus on the project service.
