### ISSUE TITLE
[urgent] Person conflict; ID has been added to the wrong person.

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1013]
# Bug / Question

Person conflict; ID has been added to the wrong person.

## Fix

Move ID `801001000369` from Bart Claessens with personnel number `802000277595` to Bart Claessens with personnel number `801001000369`.

The rest will be taken care of by the Biblio review team. Assign Miet when you are done please.

-----------

# Context

There are two "Bart Claessens", one in RE03 and WE12:
- https://biblio.ugent.be/person/802000277595 (WE12)
- https://biblio.ugent.be/person/801001000369 (RE03)

These two profiles display the same information in the Biblio front-office:
- https://biblio.ugent.be/person/FB24F05A-F0ED-11E1-A9DE-61C894A0A6B4 id: 802000277595, etc. (WE12)
- https://biblio.ugent.be/person/298726AC-F0EE-11E1-A9DE-61C894A0A6B4 id: 801001000369, etc. (RE03)

## Current IDs:

One Bart Claessens has too many IDs:

### Bart Claessens
- Department: UGent
- UGent IDs:
  - 802000277595
  - 059714421792
  - 002001295714
  - 801001000369 `wrong`
  - 919020665044

### Bart Claessens
- Department: UGent
- UGent ID: 000100162297

# Desired situation

#### Bart Claessens
- Department: UGent `Question: should be RE03 – can we fix this or is this a GISMO issue?`
- UGent IDs:
  - 802000277595
  - 059714421792
  - 002001295714
  - 919020665044

#### Bart Claessens
- Department: WE12
- UGent IDs:
  - 000100162297
  - 801001000369 `needs to be moved here`

Analysis by reviewer:
![Image](https://user-images.githubusercontent.com/1572885/218438212-c6112280-72e0-4c91-a997-3bd61591ff88.png)

**Comment by mietcls** [comment]
Putting the old information here, as context:

# Bug / Question

Person conflict; have two different people been merged?

## Info discovered via our review team

There are two profiles in use in the Biblio front-office:
- https://biblio.ugent.be/person/FB24F05A-F0ED-11E1-A9DE-61C894A0A6B4 id: we12, 802000277595, etc.
- https://biblio.ugent.be/person/298726AC-F0EE-11E1-A9DE-61C894A0A6B4 id: RE03, 801001000369, etc.
- Een niet gekoppelde publicatie: http://hdl.handle.net/1854/LU-389062, maar lijkt op eerste zicht bij WE12 te horen

These people seem to be merged:
- https://biblio.ugent.be/person/801001000369
- https://biblio.ugent.be/person/802000277595

Which is now this person: https://biblio.ugent.be/person/FB24F05A-F0ED-11E1-A9DE-61C894A0A6B4

– But is seems there are two "Bart Claessens": one in RE03 and WE12 (based on their records)

In GISMO we can find two people, one that is probably WE12 (not visible) and one that is RE03 (visible)
![Image](https://user-images.githubusercontent.com/1572885/218437489-0f69013e-d3e7-4e54-8148-0e54dee5ee71.png)
![Image](https://user-images.githubusercontent.com/1572885/218437488-4656ef8d-4108-46df-ad1a-219e5c84e498.png)

It's possible that we added too many IDs to one of those "Bart Claessens". There are 4 Bart Claessens available in our Biblio back-end. We think one of those IDs is supposed to be added to an other profile:
![Image](https://user-images.githubusercontent.com/1572885/218438212-c6112280-72e0-4c91-a997-3bd61591ff88.png)

Is this possible?

## Original question

From our colleagues at GISMO
> Echter komen we nu een geval tegen waarbij we onze twijfels hebben, nl Bart Claessens 802000277595 en 801001000369.
> Als we kijken naar de persoonlijke gegevens van deze 2 personen dan zien we dat zowel geboorteplaats als geboortedatum verschillend zijn…
> We denken dus dat het hier wel degelijk om 2 verschillende personen gaat, met dezelfde naam weliswaar…
> Kan het zijn dat jullie deze verkeerdelijk hebben samengevoegd? Of hadden jullie mss meer info?
> En is het eventueel mogelijk om dit dan terug ongedaan te maken? Zodat wij weten aan wie wij welke publicaties moeten hangen?

**Comment by mietcls** [comment]
Is this more clear now?

**Comment by nics** [comment]
@mietcls changed in database

**Comment by mietcls** [comment]
Thank you, communicated

**Comment by mietcls** [comment]
GISMO mention they still see the wrong information for https://biblio.ugent.be/publication/122693 – and ID 801001000369 still appears for this record. Should we reindex or should GISMO still do something? Figuring it out.

Information they get back:
```
<ns2:name authority="ugent" type="personal">
     <ns2:namePart type="given">Bart</ns2:namePart>
     <ns2:namePart type="family">Claessens</ns2:namePart>
     <ns2:displayForm>Bart Claessens</ns2:displayForm>
     <ns2:role>
         <ns2:roleTerm authority="marcrelator"
             authorityURI=http://id.loc.gov/vocabulary/relatorstype="code">aut</ns2:roleTerm>
         <ns2:roleTerm lang="eng" type="text">author</ns2:roleTerm>
     </ns2:role>
     <ns2:nameIdentifier type="ugent">802000277595</ns2:nameIdentifier>
     <ns2:nameIdentifier type="ugent">059714421792</ns2:nameIdentifier>
     <ns2:nameIdentifier type="ugent">002001295714</ns2:nameIdentifier>
     <ns2:nameIdentifier type="ugent">801001000369</ns2:nameIdentifier>
     <ns2:nameIdentifier type="ugent">919020665044</ns2:nameIdentifier>
     <ns2:affiliation>WE12</ns2:affiliation>
 </ns2:name>
```

**Comment by mietcls** [comment]
Can records affiliated to the other Bart Claessens (Affiliation: WE12, IDs: 000100162297 + 801001000369) be updated as well? It's not flowing through just yet. 

e.g. the new ID added to this Bart (801001000369), is not shown yet here: https://biblio.ugent.be/oai?verb=GetRecord&identifier=365774&metadataPrefix=mods_36

```
<name type="personal" authority="ugent">
  <namePart type="given">Bart</namePart>
  <namePart type="family">Claessens</namePart>
  <displayForm>Bart Claessens</displayForm>
  <role>
  <roleTerm authority="marcrelator" authorityURI="http://id.loc.gov/vocabulary/relators" type="code">aut</roleTerm>
  <roleTerm type="text" lang="eng">author</roleTerm>
  </role>
  <nameIdentifier type="ugent">000100162297</nameIdentifier>
  <affiliation>UGent</affiliation>
</name>
```

**Comment by nics** [comment]
@miet this pr will fix this https://github.com/ugent-library/biblio-backoffice/pull/1040
the other person had only 2 publications, so I updated these manually

**Comment by mietcls** [comment]
Do we need to reindex or is it okay for GISMO and other places too? Thanks!
