### ISSUE TITLE
Search on department name eg. TW07

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1015]
# Story

Make it possible to search on department name, such as https://bibliotest.ugent.be/organization/LW01, as listed on https://bibliotest.ugent.be/organization

## Success criteria
- [ ] I can look for a department, with and without capitals
- [ ] The results show me all records from that specific department

For example:
![Image](https://user-images.githubusercontent.com/1572885/217595419-5b784b62-53a7-4a38-8c0e-8185a5184da8.png)
![Image](https://user-images.githubusercontent.com/1572885/217595297-cda7dfa0-6062-4404-a768-e258cd996c3e.png)

**Comment by nicolasfranck** [comment]
More specifically, the department identifier. Problem is though that the identifier is case sensitive. People often overlook that ("I don't find anything for tw01?"). So that requires an extra field in elasticsearch and reindexing.

**Comment by mietcls** [comment]
@nicolasfranck Good catch, so we can add that. Is this similar to looking for a project?

**Comment by nicolasfranck** [comment]
not really. For projects we have an autocomplete, and a separate modal to pick the right record. No autocomplete here.
So "CA" won't give you "CA20".

**Comment by nicolasfranck** [comment]
Also, a query like "ugent tw01" won't give you any results. Result of https://github.com/ugent-library/biblio-backoffice/commit/5e0c5db3df3fa92fc5280291492cc3b5fae59f37 where we removed the split on whitespace
as it gave problems. (so it tries to look for a department with "ugent tw01" which does not exist)
