### ISSUE TITLE
Add "locked" "unlocked" filter to datasets

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1017]
# Story

Add "locked" "unlocked" filter to datasets – between "Biblio Status" and "Faculty"

Just like publications:
<img width="327" alt="Scherm­afbeelding 2023-02-16 om 10 17 20" src="https://user-images.githubusercontent.com/1572885/219322091-88623998-17c4-43cd-a953-d5f0de6d47e6.png">

**Comment by mietcls** [comment]
If more info is needed, please ping.

**Comment by netsensei** [comment]
Added a "locked" filter for datasets curation search between biblio status & faculty.
