### ISSUE TITLE
[urgent] Double project in Biblio, only one in GISMO: Models and algorithms for ultra-reliable ultra-mobile communication networks.

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1018]
# Bug

Double project in Biblio, only one in GISMO: Models and algorithms for ultra-reliable ultra-mobile communication networks.

Steps to reproduce:
- Go to a record, scroll to projects
- Search for "Models and algorithms for ultra-reliable ultra-mobile communication networks." as a project
- See two projects: 
![Image](https://user-images.githubusercontent.com/1572885/218404724-a0148636-d9dc-462e-8947-5aef1632bef0.png)

Case where both are assigned:
- https://backoffice.biblio.ugent.be/publication/8772988?redirect-url=%2Fpublication%3Fq%3DToward%2Bfine-grained%2Bindoor%2Blocalization%2Bbased%2Bon%2Bmassive%2BMIMO-OFDM%2Bsystem%2B%253A%2Bexperiment%2Band%2Banalysis%26sort%3Ddate-updated-desc#projects
- The project is assigned twice:
![Image](https://user-images.githubusercontent.com/1572885/218404545-de647d83-0243-4737-9778-31f489c23dd2.png)

Context in GISMO:
"in GISMO-backend vind ik alleen 3G098020 : onvolledig in GISMO en niet gekend bij FRIS. Het andere nummer vind ik niet, ook niet als ik op titel zoek. '

## Expected behaviour
- Only keep "3G098020" searchable and assignable (remove "3G036120") in projects
- All records that have been assigned project 3G036120, will move to project 3G098020.

**Comment by nics** [comment]
done
