### ISSUE TITLE
Replace custom keywords css by component library css

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1020]
# Enhancement

Replace custom keywords css by component library css

## To do

Add the new css, preview on https://biblio-backend-ugent-prototype-ugent-library.vercel.app/styleguide/c-tags.html to the back office.

## Context

The keywords work as expected, people are happy.

It only sometimes looks broken when copy-pasting blocks of information that are not splitting as expected, and the style is not as imagined by Emily. Both have been fixed.
![Image](https://user-images.githubusercontent.com/1572885/219039473-91f23c00-d2ff-4f0b-a56f-e885107b4b9d.png)

**Comment by nics** [comment]
ok
