### ISSUE TITLE
[urgent] Person cannot log in. Can be found in phone book, cannot log in, and cannot be found in "view as"

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1023]
# Story

Person cannot log in. Can be found in phone book, cannot log in, and cannot be found in "view as"

Phone book:

https://telefoonboek.ugent.be/nl/people/802003946522

Message about logging in:

> Dear all,
> Following your email from January 20, I’m trying to update my last publications in the system, but I can’t connect. Every time I try, I have an error message, either saying “unknown user” or “something went wrong”.
> Could you please check what could be wrong with my account?
> Thank you very much,
> All the best,

View as:
![Image](https://user-images.githubusercontent.com/1572885/219363018-8ae7ed28-d32e-482a-adb0-3e370a652f23.png)

**Comment by nics** [comment]
@mietcls deleted conflicting profile, should be ok now

**Comment by mietcls** [comment]
Rien says thanks!
