### ISSUE TITLE
"/role/*" API's set biblio-backoffice cookie twice

### ISSUE THREAD

**Issue by verheyenkoen** [ugent-library/biblio-backoffice#1027]
**Describe the bug**
When you switch between roles Researcher and Librarian an API call is made to `/role/user` or `/role/curator`. The response contains two "set-cookie" headers, both for the "biblio-backoffice" cookie but with different values.

This doesn't seem to be a problem in the browser but it makes it impossible for Cypress to test the switching scenario in full as Cypress intercepts these cookies and passes them on to the test runner.

**To Reproduce**
1. Log in as a libarian
2. Open the browser devtools network tab and filter for XHR requests
3. Switch between roles Researcher and Librarian using the model button in the lop left corner
4. Check the logged requests.

**Expected behavior**
The biblio-backoffice should only be set once, or at least have the same cookie value. I guess it is invalid to set the same cookie twice via response headers. The [docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie) don't explicitly state that it is invalid but I don't see how browsers could deal with this (except for arbitrarily picking one over the other). 

**Screenshots**
<img width="557" alt="image" src="https://user-images.githubusercontent.com/599538/222092354-b13aeea2-e800-4442-8522-e3633fe12d38.png">

**Desktop (please complete the following information):**
 - OS: Mac OS Ventura 13.1
 - Browser: Chrome
 - Version: 110

**Comment by nicolasfranck** [comment]
Route `POST /impersonation` also seems to be having this problem.
@verheyenkoen that is the route that is used for switching to another user.

Let's have a look if we are maybe misusing the way sessions are saved..

**Comment by nicolasfranck** [comment]
I tried to disable this [line](https://github.com/ugent-library/biblio-backoffice/blob/dev/internal/app/handlers/base.go#L101) where the flash messages are not only fetched from but saved also to the session. Saving more than once, maybe that does it?

**Comment by nicolasfranck** [comment]
mm, Matthias reason for deleting flash messages when reading makes sense (otherwise you end up with these messages forever).

I would propose:

* set flash messages in session to an empty array when reading
* create a more global handling for saving sessions. Now every handler can do this, without knowing that some wrapper or method can do the same, and so create duplicate session cookies.

**Comment by nicolasfranck** [comment]
autosession from deliver should fix, and avoid the multiple "Save" actions; but is not ready to be put into a separate package to use.

**Comment by mietcls** [comment]
@nicolasfranck you removed your assignment, what is the next step? How can we get this fixed?

**Comment by nics** [comment]
@mietcls i made an autosaving cookie library that fixes this and is currently used in deliver
todo: split off into it's own library, update backoffice in many places

**Comment by nics** [comment]
this will be fixed by a simpler approach in https://github.com/ugent-library/biblio-backoffice/pull/1118

**Comment by nics** [comment]
fixed by #1118
