### ISSUE TITLE
Editing keywords does not save

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1028]
# Bug

Editing keywords does not save.

## Steps to reproduce

1. Go to a publication
2. Scroll to "edit additional information"
3. Edit the keywords
4. Double click a keyword
5. Save
6. See it not update

Editing:
![Image](https://user-images.githubusercontent.com/1572885/223686946-2da4e213-3783-4ec0-af9d-09215f44d64a.png)

Saved:
![Image](https://user-images.githubusercontent.com/1572885/223686986-7314a6f1-7ebb-4548-acd7-e1395c488517.png)

No console log.

**Comment by nicolasfranck** [comment]
My bad. I only looked for "add" or "remove" events, and never for "update" events.
