### ISSUE TITLE
Cannot see publications linked to a dataset as a researcher

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1030]
# Bug

Cannot see publications linked to a dataset (but you can see the datasets linked to the publication) as a researcher.

## Example

Publication https://backoffice.biblio.ugent.be/publication/8655311?redirect-url=%2Fpublication&show=datasets (Change-point detection of peak tibial acceleration in overground running retraining)

should be linked with dataset https://backoffice.biblio.ugent.be/dataset/01GRW2GR0H44MXGBQWQ9RS655M?redirect-url=%2Fdataset&show=publications (Data from: “Change point detection of peak tibial acceleration in over-ground running retraining”)

### Problem

When being logged in as Pieter Van den Berghe (802002160611) – you can only see the link in the publication, but not in the dataset.

You can see the linked data set as a researcher
![Image](https://user-images.githubusercontent.com/1572885/223715830-5fe64e12-c56a-4dbf-8ce1-d51a4fbbb3ac.png)

But not the publication as a researcher
![Image](https://user-images.githubusercontent.com/1572885/223715774-c2cbb172-da67-4af0-855d-f152e3925135.png)

When being logged in as a librarian, you can.

![Image](https://user-images.githubusercontent.com/1572885/223715646-20fff0e4-4d59-4991-a8d4-9e4562598e4c.png)

# Steps to reproduce

1. Go to Biblio, and view as https://telefoonboek.prd.rad.ugent.be/nl/people/802002160611
2. Go to publication https://backoffice.biblio.ugent.be/publication/8655311?redirect-url=%2Fpublication&show=datasets, and see the linked dataset
3. Go to the dataset, and discover how you cannot see the linked publication https://backoffice.biblio.ugent.be/dataset/01GRW2GR0H44MXGBQWQ9RS655M?redirect-url=%2Fdataset&show=publications

**Comment by nicolasfranck** [comment]
This is probably the cause: https://github.com/ugent-library/biblio-backoffice/blob/dev/internal/backends/repository/repository.go#L726 (uses `CanDeletePublication`)

Compare with opposite rule: https://github.com/ugent-library/biblio-backoffice/blob/dev/internal/backends/repository/repository.go#L704 (uses `CanViewDataset`)

Intended?

**Comment by mietcls** [comment]
@nicolasfranck who is this question for, so we can help?

**Comment by nicolasfranck** [comment]
@nics
