### ISSUE TITLE
Wrong project name in Biblio

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1032]
# Bug

Wrong project name in Biblio.

_A project name was wrong in GISMO. This has been updated, but did not flow through to Biblio.
Currently a manual fix is needed, later we can make the data update automatically._

## Steps to reproduce

Front-office
- Go to record https://biblio.ugent.be/publication/01GJA47RZNCYJ96PEZTY09P09J
![Image](https://user-images.githubusercontent.com/1572885/224050920-0b7f441b-dda6-4904-8958-f765dccb2777.png)

- When clicking the project, you can see it here too: https://biblio.ugent.be/project/12K078B19
![Image](https://user-images.githubusercontent.com/1572885/224051257-aac5da07-10ac-46d1-9a51-5ab1c26701bc.png)

## Expected behaviour 

Faulty title:
Project: From the ally to the wew. The rise of illicit drug trade on cryptomarkets and the involvement of Belgian buyers and vendors - CRYPTODRUG

Is corrected to: 
Project: From the alley to the web. The rise of illicit drug trade on cryptomarkets and the involvement of Belgian buyers and vendors - CRYPTODRUG

**Comment by mietcls** [comment]
I see two projects now. I'm not sure which ID they should connect, but the "ally – wew" title is faulty. Should I gather more insights, or do you have a clear overview of what needs to happen @nics?

**Comment by nics** [comment]
@miets seems ok to me. There are 2 projects with same name (Project ID: 12K078B19 and Project ID: 12K078A19)
