### ISSUE TITLE
[urgent] UGent authors list incomplete in export

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1034]
# Bug

UGent authors list incomplete in export.
Whenever you export records, the UGent authors are not all shown in the list.

# Steps to reproduce the behaviour
1. Search for ge30 publications that are withdrawn via https://backoffice.biblio.ugent.be/publication?q=ge30&sort=date-updated-desc&f%5Bstatus%5D=returned
2. Export the records
![Scherm­afbeelding 2023-03-13 om 13 51 09](https://user-images.githubusercontent.com/1572885/224706922-89d142a2-770a-40ac-aabc-342c19529c39.png)
3. See an incomplete list of UGent authors. Not all of them flow through.
![Scherm­afbeelding 2023-03-13 om 13 51 58](https://user-images.githubusercontent.com/1572885/224707095-b499b113-333d-4f6c-b99e-45d66c01ac45.png)
![Scherm­afbeelding 2023-03-13 om 13 53 20](https://user-images.githubusercontent.com/1572885/224707628-998851b4-15a7-4028-8a42-262372256a5d.png)
![Scherm­afbeelding 2023-03-13 om 13 51 01](https://user-images.githubusercontent.com/1572885/224707633-e6bced97-04e4-478f-8933-8081f6a6efa7.png)

# Expected behaviour

All UGent authors are visible in the author column in the export.

**Comment by nicolasfranck** [comment]
Related https://github.com/ugent-library/biblio-backoffice/issues/1037
