### ISSUE TITLE
Cleanup contributors in publication records

### ISSUE THREAD

**Issue by nicolasfranck** [ugent-library/biblio-backoffice#1036]
We keep records of contributors in two places:

* in the authority table `person`
* in each contributor record that is attached to a publication

Analysis has learned that ..:

* there are differences between a person record and the contributor with that same identifier due to historical differences:
  * In LibreCat for example the `full_name` was written as `first_name last_name`, while the authority version is `last_name, first_name`. We copy that `full_name` into a contributor record.  Therefore, for old records that originate from LibreCat, the full_name is written as `first_name last_name`, while for newer records it is written as `last_name, first_name`
  * the writing of `first_name` and `last_name` is not always consistent. Sometimes the authority version is in all capitals, and the contributor version not; and vice versa. Sometimes the `first_name` becomes an abbreviation (`N.` instead of `Nicolas`).
* sometimes the full name is only stored in `last_name` (e.g. `Fantahun Wassie Bizuneh`) 
* there will always be differences between the person record and the contributor, especially when person records are updated by updates from upstream (LDAP, GISMO in the future), while the related contributors are not.

IMPORTANT: if we want to fix this, these changes will have a severe impact on the change log, i.e. full reindexing will be required, and more importantly GISMO will receive a lot of changes. Is it always worth it to push these as changes, knowing that these are merely aesthetic  changes?

**Comment by nics** [comment]
fixed by #1110
