### ISSUE TITLE
Keep contributors in sync with authority version

### ISSUE THREAD

**Issue by nicolasfranck** [ugent-library/biblio-backoffice#1037]
When we import people from the authority database into a publication (as a contributor),
we copy the attributes, but that information starts a different life from then on.

When an update is done to the authority database, the related contributor
is not updated.

This becomes important when of one these attributes are updated:

* ugent_id
* orcid

IMPORTANT: changes to these attributes generate changes in the OAI for GISMO.

**Comment by nicolasfranck** [comment]
Now that we have a commando to update data in the publication contributors from the authority database,
we need to think about removing the need to refetch authority information during indexing for the biblio frontend.

The following attributes are ALSO used in the biblio frontend index and fetched from the authority mongodb database, but are NOT present in the contributor model:

* `preferred_first_name`
* `preferred_last_name`
*  `object_class`
* `researcher_id`
* `scopus_id`

**Comment by mietcls** [comment]
What is the priority for this @nicolasfranck @nics?

**Comment by nics** [comment]
can be closed
