### ISSUE TITLE
Unable to add contributors with null values in authority database

### ISSUE THREAD

**Issue by nicolasfranck** [ugent-library/biblio-backoffice#1038]
# Bug description

Some people in the authority database have `null` values in attributes
like `first_name` or `last_name`. The current code merely tries to
assert a string, which may fail.

# Steps to Reproduce

* open up modal to add an author
* fill in `Tran Thi Thuy` into `last_name`, and click "Add author"
* nothing seems to happens, but internally it crashes

# Notes

* It is hard to discover such records in mongodb as mongodb does not make a difference between "an attribute is not present" and "that value is null". It is probably better to guard the code against such cases
* There is a requirement that both first_name and last_name need to be present. So eventually adding this contributor will fail on validation.

**Comment by nics** [comment]
fixed by #1039
