### ISSUE TITLE
[urgent] Error when surfing to researcher profile on Biblio Front-office

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1048]
# Bug description

Error when surfing to researcher (https://telefoonboek.prd.rad.ugent.be/nl/people/801000738267) on Biblio Front-office.

Front-office link: https://biblio.ugent.be/person/F4728EE8-F0ED-11E1-A9DE-61C894A0A6B4
![Scherm­afbeelding 2023-04-03 om 11 05 37](https://user-images.githubusercontent.com/1572885/229463878-bb82f2db-bba8-4a5a-9eec-036014be3925.png)

# Steps to Reproduce

1. Go to https://biblio.ugent.be
2. Search for researcher 801000738267
3. Click on profile

# Extra information

Back-office: no search results when looking for researcher on first name nor personnel number.
![Scherm­afbeelding 2023-04-03 om 11 08 57](https://user-images.githubusercontent.com/1572885/229464712-9f014d70-a44a-4cae-bff3-7bd8643fe2b6.png)

### Likelihood
How often does this happen?
For this profile: 1, Frequent,
For other profiles: 5, improbable (happened 3 times now)

### Consequences

What's the impact?
For this researcher: 1, Catastrophic
Entirety: 3, Marginal

**Comment by nics** [comment]
fixed by https://github.ugent.be/Universiteitsbibliotheek/biblio/commit/7036e88d8982df69f5e7846c5e057bca2d28bd5a (don't die if person is not found in people database)
