### ISSUE TITLE
Aleph merge does not come through

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1049]
# Bug description
Aleph merge does not come through: 
https://lib.ugent.be/en/catalog?q=Kinderrechten+en+strafrechtelijke+verantwoordelijkheid+%3A+een+kritische+analyse+

![Scherm­afbeelding 2023-04-04 om 09 31 37](https://user-images.githubusercontent.com/1572885/229720169-de93f508-56ce-482e-b418-95c270eb922c.png)

## Expected behaviour
The records are merged – and there is a link available to Biblio.

# Report
> Dit is een dubbel in lib, de beheerder van Aleph heeft twee weken geleden al de beide records gekoppeld (dus 1 aleph record en 1 biblio record). Normaal duurt dat dan een nacht voordat de twee records zijn samengevoegd, maar nu gebeurt er niets

## Extra context

> Er is een papieren doctoraat, dat is geregistreerd in Aleph. En de pdf is geregistreerd in Biblio. Alle publicaties in Biblio (niet alleen doctoraten) zitten automatisch ook in lib. Om te vermijden dat een doctoraat twee keer in lib zit, moeten die twee (de digitale versie en de papieren versie) gekoppeld worden

**Comment by netsensei** [comment]
@phochste Looks like a potential issue merging a pug01 into a rug01 record in lludss-import?

**Comment by nicolasfranck** [comment]
cf. https://github.ugent.be/Universiteitsbibliotheek/lludss-import/pull/171

**Comment by nicolasfranck** [comment]
on its way to development server; will have to wait another night apparently.

**Comment by nicolasfranck** [comment]
Seems to work on development: https://auster0.ugent.be/en/catalog?q=Kinderrechten+en+strafrechtelijke+verantwoordelijkheid+%3A+een+kritische+analyse+

pushing this to production. Will take another two days..

**Comment by mietcls** [comment]
It works! Thanks @nicolasfranck
