### ISSUE TITLE
Series title in front-office is not displayed in the same way, and is different in back-office.

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1055]
# Bug description

Series title in front-office is not displayed in the same way, and is different in back-office.

Do we need to reindex?

Compare these two publications:
- https://biblio.ugent.be/publication/8656680
- https://biblio.ugent.be/publication/3106246

One has the word "in" and has a dot in between, the other one does not
![Scherm­afbeelding 2023-04-06 om 13 41 51](https://user-images.githubusercontent.com/1572885/230366605-4de697d9-6107-4d98-9b6b-80ac428fe4eb.png)
![Scherm­afbeelding 2023-04-06 om 13 41 30](https://user-images.githubusercontent.com/1572885/230366616-4df1e433-ee10-43e9-9936-26f599673915.png)

In the back-office, the information is different as well
- https://backoffice.biblio.ugent.be/publication/8656680?redirect-url=%2Fpublication%3Fq%3D8656680%26sort%3Ddate-updated-desc
- here, the series title is missing https://backoffice.biblio.ugent.be/publication/3106246?redirect-url=%2Fpublication%3Fq%3D8656680%26sort%3Ddate-updated-desc
![Scherm­afbeelding 2023-04-06 om 13 43 04](https://user-images.githubusercontent.com/1572885/230366784-e9b4f152-bfe3-4a4d-8206-91594378700d.png)
![Scherm­afbeelding 2023-04-06 om 13 43 58](https://user-images.githubusercontent.com/1572885/230366945-4b283531-5086-4f39-893d-f6b569f92a6d.png)

**Comment by netsensei** [comment]
The first record is valid.  The "Architectuurboek Vlaanderen" string is stored as a Series Title field, and you can edit that in the Backoffice.

The second record (https://biblio.ugent.be/publication/3106246) is a legacy record. The "Architectuurboek Vlaanderen" string is stored in the `Publication` field in the backoffice.

Both publications are fo type `book_editor`. For this publication type, the field `SeriesTitle` is editable in the backoffice, the `Publication` field isn't.  The `Publication` field is currently only available for types "book_chapter", "conference", "issue_editor", "journal_article" & "miscellaneous".

The value in the `Publication` field for 3106246 was set in Librecat or even an earlier version. The FrontOffice code still checks whether the field is filled and shows, depending on the presence of the Series Title field, the corresponding value.

By my count, this issue affects about 1.295 records.

Suggested solution:

We might make the Publication field available again for book_editor publications. But we have to re-consider the reasons why it wasn't included in this new version of the backoffice.

**Comment by mietcls** [comment]
Extra info from Nicolas responding to reviewer reporting this:
"Bij de ene zit de series title in het series_title veld, de andere is een legacy publicatie met series title verkeerdelijk in het publication veld (mag aangepast worden)."
"Als er een series is, toont de frontend ‘In <serietitel>'"

Does this mean we do not ned to adapt this?
