### ISSUE TITLE
[GRPC Client] strategy for deploying the biblio CLI client

### ISSUE THREAD

**Issue by netsensei** [ugent-library/biblio-backoffice#1056]
Related to #485 

The CLI client is intended to be used as a standalone executable on local machines (laptop, desktop).  In order to make this possible, we need a strategy on how to make the client available to users so they can install the client.

Typically, projects on GitHub would start a Continous Delivery (CD) pipeline when a new git tag is pushed. This pipeline would compile the code into a set of binary executables (windows, linux, osx,...) which are then made available as a versioned "release". (examples: https://github.com/nats-io/natscli/releases or https://github.com/robinovitch61/wander/releases)

**Challenges**

The entire biblio-backoffice project is currently a mono-repository. The client is a sub-part of the codebase, living at https://github.com/ugent-library/biblio-backoffice/tree/dev/client.  The other part is the backoffice server itself which compiles into its own binary executable that gets deployed across our infrastructure.

It's not really recommended to generate two separate binaries for different applications and push them as a single release on GitHub since that will create potential conflicts and confusions with respect to semantic versioning and building releases.

Separating the client into it's own GitHub repository would be the obvious way forwards; however, the gRPC specific code used by the server and the client is generated from a shared protobuf scheme: https://github.com/ugent-library/biblio-backoffice/blob/dev/api/v1/biblio.proto  Splitting the codebase and duplicating the protobuf scheme across repositories creates split-brain  challenges. 

This is a known problem across gRPC based architectures where multiple services rely on shared protobuf scheme

Solutions include:

* ... keeping the protobuf scheme, client and server services in 3 separate repositories and using gitmodules to propagate changes to the protobuf scheme across all services. (e.g. https://www.lesswrong.com/posts/xts8dC3NeTHwqYgCG/keep-your-protos-in-one-repo && https://jozefcipa.com/blog/sharing-grpc-protobufs-between-microservices/)
* ... treating protobuf schemes as dependencies which you can package and distribute through a central register: https://buf.build/ (this is a non-free proposition)
* ... keep the current mono-repo setup, create a custom github action which generates the client binary executables and uploads them to some other host from which they can be downloaded (e.g. S3, Deliver, etc. and then e.g. send a mail with the link to all involved)  (even though, the issue with separate git versioning for the client remains)

1&2 are the "best practices" solutions; 3 is the KISS solution which would work well in an small, limited setting.

**Steps forward**

- [ ] Needs to be discussion in the team
- [ ] Explore alternative solutions / strategies

**Comment by mietcls** [comment]
@netsensei thanks for this, can you plan a moment to discuss with the team? I've given Nicolas S a short update, but we need to discuss technical / user impact.

**Comment by mietcls** [comment]
Not needed short term, we will not involve other people right now. So it is not needed.
