### ISSUE TITLE
Export from back-office does not list UGent promoters / supervisors as UGent for all publications.

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1057]
# Bug description
Export from back-office does not list UGent promoters / supervisors as UGent for all publications.
In front-office, this is correct.

When looking for publications that have not been matched to the right supervisor (in this case https://telefoonboek.prd.rad.ugent.be/nl/people/801000630658), one of our reviewers discovered that the export does not always show the right information.

# Steps to Reproduce

Examples:

Record 7902170 = wrong
- Supervisor is linked in back-office, as UGent https://backoffice.biblio.ugent.be/publication/7902170?redirect-url=%2Fpublication%3Fq%3D7902170%26sort%3Ddate-updated-desc&show=contributors
- Supervisor is shown in front-office https://biblio.ugent.be/publication/7902170
- Supervisor is not shown in export of back-office
![Scherm­afbeelding 2023-04-06 om 16 34 12](https://user-images.githubusercontent.com/1572885/230410672-c55ebec3-d9ed-411a-bf6b-68fafb542694.png)

Other records that are wrong:
- 5843089
- 4337021

Record 8575126 = correct
- Supervisor is linked in front-office https://biblio.ugent.be/publication/8575126
- Supervisor is linked in back-office https://backoffice.biblio.ugent.be/publication/8575126?redirect-url=%2Fpublication%3Fq%3D7902170%26sort%3Ddate-updated-desc&show=contributors
- Supervisor is shown in export of back-office
![Scherm­afbeelding 2023-04-06 om 16 33 46](https://user-images.githubusercontent.com/1572885/230410474-16f2a1eb-e9e1-40e6-a30f-d8c519a010c0.png)

Other records that are correct:
- 01GXB99J92KG4JX0Q02YJHV3P5
- 01GXBAB0KAYFFPJBYWCR1TJWSX
- 8575126
- 8577555

# Additional context

- Records that have been edited recently are usually correct.
- Records that have not been edited recently, with following information seem to be incorrect:
  - "System update 10 months ago. Legacy"
  - "Last edit 10 months ago by Peter Reyniers."
- Sometimes, records without a recent edit that were wrong, have "Rudi Beyaert" as a UGent-author but without the correct IDs.

Example without IDs https://backoffice.biblio.ugent.be/publication/5843085?redirect-url=%2Fpublication%3Fq%3D5843085%26sort%3Ddate-updated-desc&show=contributors
<img width="1058" alt="Scherm­afbeelding 2023-04-06 om 16 42 32" src="https://user-images.githubusercontent.com/1572885/230414312-b0c9763c-863b-4fdd-bfb5-79d1cdc0b5e2.png">

Example with IDs https://backoffice.biblio.ugent.be/publication/8575126?redirect-url=%2Fpublication%3Fq%3Dbeyaert%26sort%3Ddate-updated-desc&show=contributors
<img width="1059" alt="Scherm­afbeelding 2023-04-06 om 16 43 01" src="https://user-images.githubusercontent.com/1572885/230414720-cd1f75b0-803b-426c-a918-3834f7d6530f.png">

**Comment by nicolasfranck** [comment]
Also has to do with outdated information in the contributor list of the biblio-backoffice.
In this case, the contributor has an `id` (and therefore recognized) as an ugent member,
but the `ugent_id` is not in the list. Manually editing this will assign live data and "fix" this.

See also that new grpc command that should update all of these outdated records.

The biblio frontend is correct because it adds this information from the authority table `person` (based on the id),
even if the biblio-backoffice does not store it.

**Comment by mietcls** [comment]
How do we move on from here @nicolasfranck? Is the gRPC command ready soon?

**Comment by nicolasfranck** [comment]
@mietcls the commando is ready, and probably already deployed (right @nics ?) to production, but it is a command to be executed manually. It introduces a lot, lot of changes, something we were waiting for?

**Comment by mietcls** [comment]
@nicolasfranck can we plan this next week on Monday at 10:00, so I can let GISMO know in time?

**Comment by mietcls** [comment]
What does this mean @nicolasfranck? I cannot log in on that link. When I export that record, it looks like the UGent supervisors have been exported as UGent supervisor – as expected.

I've ran some tests, it looks good. I do notice some people are labelled external in the back-office that should have been UGent, but they just have not been flagged as UGent by the person editing the record.

**Comment by nicolasfranck** [comment]
never mind, did read it wrong
