### ISSUE TITLE
[Rogue] Remove time field from publication forms, keep information around.

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1058]
# Improvement

Remove time field from publication forms, keep information around.

For dissertations, we ask for the **Time of defense**:
<img width="434" alt="Scherm­afbeelding 2023-04-11 om 13 50 55" src="https://user-images.githubusercontent.com/1572885/231154301-23531520-91fa-43f5-99d5-265b2b47bdd3.png">
![Scherm­afbeelding 2023-04-11 om 14 08 28](https://user-images.githubusercontent.com/1572885/231158085-e7df5980-cb29-40c8-979c-86b5b8840c80.png)

When I asked around who uses this information; nobody could answer me.
People often do not know when it happened or fail to find that information, and since it is a required field people just fill out _something_.

Example: https://backoffice.biblio.ugent.be/publication/01GX7YWD4DCT65Q80Z23761P66?redirect-url=%2Fpublication%3Fq%3D%26f%255Btype%255D%3Ddissertation

### When this ticket is done

- [ ] Nobody needs fill out this field – it is not required any longer.
- [ ] Nobody needs to see this field.
- [ ] The historic information is kept around, but it is hidden.
- [ ] [TBD] we keep the infrastructure around for one year, if nobody complains, we throw it all out.
- [x] The information is not shown in our front-office.

Please comment if I did not foresee specific problems.

### Next year

- If nobody complained before 01/04/2024, we remove this joke completely.

## Who to blame if anyone asks

Send them to @mietcls

**Comment by nicolasfranck** [comment]
@mietcls but is visible in the frontend:

e.g. https://biblio.ugent.be/publication/8551640

see left column and look for `2018-03-02 15:00`

**Comment by mietcls** [comment]
@nicolasfranck okay, what if we hide it for now (not delete it yet)? Slowly remove this information, without triggering too much work or drawing too much attention?

**Comment by mietcls** [comment]
The plot thickens: in September 2018 this has been added according to Nicolas F. The issue does not state why it was added.

**Comment by nicolasfranck** [comment]
see https://github.ugent.be/Universiteitsbibliotheek/librecat/blob/master/ugent/views/backend/generator/fields/defense.tt

**Comment by nicolasfranck** [comment]
If we hide it in the backoffice, we have to hide it in the frontend too.

Safest option would be to split off the time section in the view.
Ugly, but visible.

**Comment by nicolasfranck** [comment]
@mietcls I see the defense date also used here:

* publication csv export
* BOF export (docx)
* mods xml (OAI)

The only external party here is BOF, so maybe that is the source of this field?

**Comment by mietcls** [comment]
Great background, I will figure it out @nicolasfranck

**Comment by mietcls** [comment]
@nicolasfranck how is this information used, can you see that? Because Anniek and Marthe are unsure whether this is used actively by BOF or just sent.

**Comment by mietcls** [comment]
Good news from the BOF side. Our colleague asked around at BOF:
> Wat BOF betreft, schrappen die handel. Wij hebben hier nog nooit gebruik van gemaakt en ik zie ook niet meteen relevantie voor anderen.

The head of research coordination also confirms:
> Het uur mag inderdaad geschrapt worden. De datum is het enige belangrijke.

Will do a last check with Dries.

**Comment by nics** [comment]
>  [TBD] we keep the infrastructure around for one year, if nobody complains, we throw it all out.

@mietcls the code will have bitrotted by then and stuff like that pollutes the codebase, better to just delete it. It can always be fished out of the git history if necessary.

**Comment by nics** [comment]
@mietcls also remove? it's still in the audit history

**Comment by mietcls** [comment]
@nicolasfranck did we already resolve the time issue in the front-office? I can't see it yet. Should I create a separate issue?

**Comment by nics** [comment]
@mietcls in the end we decided to keep the existing data around for a while as a hidden, deprecated attribute
we can remove it later
