### ISSUE TITLE
[urgent] Person cannot log in with merged mail address

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1060]
# Bug description

Person cannot log in with merged mail address

Context:
- Two email addresses have been merged into one at the personnel department.
- The currently used address cannot log in anymore.
- Summary here for privacy reasons: https://ugentbe-my.sharepoint.com/:w:/g/personal/miet_claes_ugent_be/EX2nv9y2L9dKrq6QTb1bONABsweE-c7ASm3m4NQCs2R_2Q?e=WUvWBy

Extra information:
- I can find this person in Biblio as "view as" https://telefoonboek.prd.rad.ugent.be/nl/people/802004117684 
- Related #1059

**Comment by nics** [comment]
@miet I don't think there is a problem in biblio, her account was automerged successfully. Seems like something for ugent helpdesk. Is she trying to login with her email instead of ugent username?

**Comment by mietcls** [comment]
I asked, in the meantime, this is the screenshot of what she's seeing:
<img width="638" alt="Scherm­afbeelding 2023-04-13 om 20 46 47" src="https://user-images.githubusercontent.com/1572885/231854659-c28b0bee-ad95-4442-87bd-2ff90b054632.png">

**Comment by mietcls** [comment]
Discussed with nics; probably something went wrong somewhere around key cloak and DICT infrastructure...

**Comment by nics** [comment]
@mietcls reimported her record in keycloak
better tell her to try again Monday, give all systems some time to get in sync

**Comment by mietcls** [comment]
@nics fixed with your hunch that removing the information and letting it restore might fix it! They can log in now.
