### ISSUE TITLE
Add "Flanders Make" to faculty search dropdown

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1065]
**Describe the improvement**

Add "Flanders Make" to faculty search dropdown
<img width="336" alt="Scherm­afbeelding 2023-04-17 om 14 49 52" src="https://user-images.githubusercontent.com/1572885/232488975-c133f407-9873-4c89-9d7b-3f6a66ec3256.png">

- [ ] For publications
- [ ] For datasets

Related: https://github.com/ugent-library/biblio-backoffice/issues/775

**Comment by mietcls** [comment]
Can you deploy this on test, so I can verify and we can deploy on production later?

**Comment by nics** [comment]
@mietcls done
