### ISSUE TITLE
[Bulk actions librarians] MVP batch upload records

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1072]
# Story

Minimum viable batch upload for records.
Feedback welcome. Find more context below under "Case".

_Based on the decision made in https://github.com/ugent-library/biblio-backoffice/issues/1069 – we decided not to create a terminal interface for librarians to do bulk operations._

## Wireframes – feedback welcome

Location: in "Batch", below "Batch add projects"

![Image](https://user-images.githubusercontent.com/1572885/234611625-ec96a4f0-dd72-458c-b5bb-f6866647820a.png)

Normal state:
- fill out record type `TBD`
- record in JSON
_Would be good to have an example for datasets and publications (TBD) in json?_
![Image](https://user-images.githubusercontent.com/1572885/234612236-530036f9-d8da-43f8-9b5a-17a67ae87e63.png)

Error state:
<img width="1280" alt="Scherm­afbeelding 2023-04-26 om 16 47 23" src="https://user-images.githubusercontent.com/1572885/234613511-c7434dde-7425-4408-ac3d-6f0261187b0e.png">

Success state:
![Image](https://user-images.githubusercontent.com/1572885/236155082-f4f90f6f-e909-4e75-9efb-d32955b11c03.png)

Scaffolding in code can be found in this branch:
https://github.com/ugent-library/biblio-backoffice/tree/feature/batch-import

___

## Case

To make this an end-to-ed valuable case, we can use the alternative identifiers for datasets as a first step.

### Problem statement value for researchers and university

- Different faculties use different platforms to deposit their datasets. This results into different identifiers.
  - There are _a lot_ of identifiers. Connecting and mapping them all with result into a lot of work and maintenance.
  - Some identifiers are not fully grown. The market still needs to stabilise.
  - There are not a lot of trusted aggregators in the market we can use.

- The temporary solution: manual import of datasets.
  - This goes into the idea that researchers would never start from 0 in the future.

- Opportunity
  - We can, as a university, support researchers by already exploring the web and find relevant datasets.
  - We could do this by bulk uploading those datasets for them (in json or excel, mapped on our data structure), so they do not have to start from 0.

- Future
  - We can use the "Plato import case" to turn this into a better experience
  - We can be ready for a future where we only use trusted parties and link to their information from our platform, if we log those identifiers already.

### Technical value

We can call this a "good excuse" project to make sure we can do asynchronous (bulk) actions that take a long time to complete, and you can navigate away while the job completes.

**Comment by nicolasfranck** [comment]
"Add project" is already, right?

**Comment by mietcls** [comment]
@nicolasfranck Yes, see https://backoffice.bibliotest.ugent.be/publication/batch for other options as well. This is a separate feature.

**Comment by mietcls** [comment]
We will for now ask for examples first.

**Comment by mietcls** [comment]
Tracked in https://github.com/ugent-library/biblio-backoffice/issues/1099
