### ISSUE TITLE
{filters} Make it possible to filter on records with "missing" values

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1075]
# Story

Make it possible to filter on records with "missing" values

- [ ] without a publication status
- [ ] records without faculty
- [ ] without files

## Success criteria

- [ ] The filter option stands on top of the list
- [ ] The label says:
  - [ ] No publication status
  - [ ] No affiliation
  - [ ] Without files
- [ ] When selected, all the records without a publication status, faculty or files are shown
- [ ] Librarians and researchers can both see this feature

## Screenshot

Example:
<img width="339" alt="Screenshot 2023-09-08 at 12 01 31" src="https://github.com/ugent-library/biblio-backoffice/assets/1572885/445a3320-918d-4fe9-a019-a812aec6db2d">
![Screenshot 2023-09-08 at 15 09 35](https://github.com/ugent-library/biblio-backoffice/assets/1572885/a0552148-9e4a-4d70-bdfe-d9415a0fae10)

Discussions about this topic: https://github.com/ugent-library/biblio-backoffice/issues/874

**Comment by nicolasfranck** [comment]
cf. #915

**Comment by mietcls** [comment]
Thanks, I'll think of a label that people outside of our development world can quickly understand as well.

**Comment by mietcls** [comment]
See https://github.com/ugent-library/biblio-backoffice/pull/1078

**Comment by nicolasfranck** [comment]
@mietcls for the files, I have made `With files` and `Without files` because there are two options

**Comment by nicolasfranck** [comment]
@netsensei I have also "fixed" the link from the dashboard to the list of publications and datasets for a missing faculty
