### ISSUE TITLE
Documents uploaded in back-office can not be downloaded via the front-office

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1079]
# Bug report

Documents uploaded in back-office can not be downloaded via the front-office

They all result into a 404.

## Screenshots

![Image](https://user-images.githubusercontent.com/1572885/234583241-688d8489-20b8-473c-b9b9-26d787ee2fcf.png)
![Image](https://user-images.githubusercontent.com/1572885/234583242-bfe0094f-5155-4927-a810-2efcf7c88b72.png)

**Comment by nics** [comment]
Was an apache config error, will be fixed by https://redmine.inuits.eu/issues/111019
