### ISSUE TITLE
Content type sniffing very limited

### ISSUE THREAD

**Issue by nicolasfranck** [ugent-library/biblio-backoffice#1084]
When you upload a file, only a small amount of file types are recognized,
others are marked as `application/octet-stream` (default).

Use case: upload tif file; it will be marked as `application/octet-stream`.
Because `http.DetectContentType` only takes web viewable content types
into account?

**Comment by netsensei** [comment]
Currently, the file type is only used to differentiate between PDF and other file formats in the front-office. The backoffice doesn't use the `ContentType` property. A concrete, future use case would be showing a thumbnail of the cover of the PDF.

As-accurate-as possible file characterization is an archival / pre-ingest concern. At that point, we would rely on PRONOM, a vetted authority offering file format signature lists, rather then a 3rd party tool which has its own signature list baked in. [Siegfried](https://github.com/richardlehane/siegfried) is a Go application build by archivists and based on PRONOM.

Do we want as-accurate-as-possible file characterization when a file is first uploaded in Biblio Backoffice? Or are we happy with "good enough" just to satisfy the functional requirements of the backoffice / frontoffice? (e.g. show a cover, an indication of the file type)

File characterization may impact the upload process performance, so implementing as an async process would be the better option. Once the necessary infrastructure (job orchestration) has been made operational; we might consider how to implement this properly.  At that point, we can always apply a file characterization process retro-actively on all uploaded files.

I suggest postponing this.

**Comment by nicolasfranck** [comment]
> Currently, the file type is only used to differentiate between PDF and other file formats in the front-office. The backoffice doesn't use the `ContentType` property. A concrete, future use case would be showing a thumbnail of the cover of the PDF.
> 
> As-accurate-as possible file characterization is an archival / pre-ingest concern. At that point, we would rely on PRONOM, a vetted authority offering file format signature lists, rather then a 3rd party tool which has its own signature list baked in. [Siegfried](https://github.com/richardlehane/siegfried) is a Go application build by archivists and based on PRONOM.
> 
> Do we want as-accurate-as-possible file characterization when a file is first uploaded in Biblio Backoffice? Or are we happy with "good enough" just to satisfy the functional requirements of the backoffice / frontoffice? (e.g. show a cover, an indication of the file type)
> 

I sort of agree, but I am just a bit considered, that if something trivial like well known image types are not recognized, we will see this more often.

> File characterization may impact the upload process performance, so implementing as an async process would be the better option. Once the necessary infrastructure (job orchestration) has been made operational; we might consider how to implement this properly. At that point, we can always apply a file characterization process retro-actively on all uploaded files.
> 

file detection is already done by reading part of the file

> I suggest postponing this.
