### ISSUE TITLE
[urgent] User cannot log in

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1097]
# Bug

User cannot log in.

This person: https://telefoonboek.prd.rad.ugent.be/nl/people/802002968135

Can not log in anymore since they have changed positions within UGent. This is the screen they get:

## Context

> Ik heb recent mijn doctoraat afgerond en ben onlangs gestart als postdoc. Sindsdien heb ik problemen met aanmelden op:
> 
> biblio.ugent.be
> lib.ugent.be

Seems like a similar problem to #1060

**Comment by nics** [comment]
@mietcls his keycloak account was only sync this morning, should work now
