### ISSUE TITLE
[urgent] Project confusion: remove project and add title to other project code

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1098]
# Bug description
Project confusion: remove project and add title to other project code

- [ ] Remove project: 3G020020 "Reflection Spectra: Predicative Mathematics and Beyond" (not available any longer in GISMO)
- [x] Add title tot project 3G030620: Reflection Spectra: Predicative Mathematics and Beyond

Source: https://research.ugent.be/web/result/project/71fb7540-a4cc-11ea-a3ab-b3cf34b158a9/details/3g030620-reflection-spectra--predicative-mathematics-and-beyond/en

## Steps to Reproduce

Wrong project can be found in back-office
<img width="1440" alt="Scherm­afbeelding 2023-05-09 om 15 03 13" src="https://github.com/ugent-library/biblio-backoffice/assets/1572885/b4bc86a1-1fea-4a4e-bc48-7118047fa41d">

Project without title can be found in back-office and front-office:
<img width="1440" alt="Scherm­afbeelding 2023-05-09 om 15 03 38" src="https://github.com/ugent-library/biblio-backoffice/assets/1572885/3f43c9ea-ab75-4391-b088-f57afbd1ecfd">
<img width="1184" alt="Scherm­afbeelding 2023-05-09 om 15 04 28" src="https://github.com/ugent-library/biblio-backoffice/assets/1572885/afade250-896b-4da9-9b19-3262062e5028">
https://biblio.ugent.be/project/3G030620

### Likelihood
How often does this happen? 3: Occasional
We need al long-term solution.

### Consequences
What's the impact? 2-3: Critical-marginal
Wrong projects assigned, confusion. Long term: more critical.

**Comment by mietcls** [comment]
3G020020 is still available, needs to be removed (should not be found in GISMO either). It is not linked to any publication any longer.

3G030620 is correct now
<img width="1485" alt="Screenshot 2023-08-08 at 16 57 52" src="https://github.com/ugent-library/biblio-backoffice/assets/1572885/24872312-ce35-4a38-8bbd-d44ab97f7155">

**Comment by nics** [comment]
@mietcls ok nu
