### ISSUE TITLE
Find way to make sure record that once were public, but now are withdrawn / concept / .... is reflected in the OAI

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1100]
# Enhancement

Find way to make sure record that once were public, but now are withdrawn / concept / .... is reflected in the OAI

Helps our third party consumers:
- GISMO
- UGI
- ... others

**Comment by netsensei** [comment]
@mietcls Additionally, the OAI-PMH spec is quite explicit about the status of a record. 

http://www.openarchives.org/OAI/openarchivesprotocol.html#Record
http://www.openarchives.org/OAI/openarchivesprotocol.html#DeletedRecords

> an optional status attribute with a value of deleted indicates the withdrawal of availability of the specified metadata format for the item, dependent on the repository support for [deletions](http://www.openarchives.org/OAI/openarchivesprotocol.html#deletion).

If we want to adhere to the OAI-PMH spec, there isn't really room for additional values like "withdrawn" or "concept" or "draft".

**Comment by mietcls** [comment]
@netsensei I don't mean to make that exact translation, but we do need to find a way to deal with it and to communicate about it to our stakeholders in a meaningful way. TBD

**Comment by mietcls** [comment]
Tracked in #1099
