### ISSUE TITLE
Add correct project UUID to project 3G030620

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1103]
# Story

Add correct project UUID 71fb7540-a4cc-11ea-a3ab-b3cf34b158a9 to project 3G030620 so GISMO can process the link.

Sorry, I apparently did not comprehend the issue fully when creating #1098

**Comment by nicolasfranck** [comment]
The project identifier itself cannot be so easily updated. It is referenced in 3 publications, and not only by in the controlled attribute `project`, but also in the reviewer notes.

@nics I also see that identifier duplicated in attribute `iweto_id`. What exactly is that?
