### ISSUE TITLE
Put <dcterms:license> back in OAI

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1112]
# Bug description
Put <dcterms:license> back in OAI. It is now not visible in our OAI output, which obstructs our data flow to GISMO.

Fix tested by @nicolasfranck on dev: works correctly
https://bibliotest.ugent.be/oai?verb=GetRecord&identifier=8759641&metadataPrefix=mods_36
<img width="754" alt="Scherm­afbeelding 2023-06-01 om 15 37 26" src="https://github.com/ugent-library/biblio-backoffice/assets/1572885/5b2e59ed-5c47-4b1b-8484-b27fa6521f56">

Example of broken output:
https://biblio.ugent.be/oai?verb=GetRecord&identifier=01GR14095FJ4SD4PCXAK5TXAJT&metadataPrefix=mods_36
<img width="876" alt="Scherm­afbeelding 2023-06-01 om 15 37 02" src="https://github.com/ugent-library/biblio-backoffice/assets/1572885/16f7455b-e2e5-4696-823f-e40b9969a491">

**Comment by nics** [comment]
@mietcls should be fixed by https://github.ugent.be/Universiteitsbibliotheek/biblio/pull/89

**Comment by mietcls** [comment]
Great. I'll leave my name on it and leave it open until GISMO has received it all. They've done a check with one example that already passed.
