### ISSUE TITLE
Add "locked" message when record is locked.

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1125]
# Enhancement
Add "locked" message when record is locked.

## Expected behaviour
When a record is locked, I want do understand why and what to do if I want to add changes or have questions.

## Implementation suggestion
- When a librarian locks a record, a message appears in the "Description" tab.

![Scherm­afbeelding 2023-06-12 om 12 04 26](https://github.com/ugent-library/biblio-backoffice/assets/1572885/3e65b268-c2ef-44e8-8aef-6ef499ff8955)

### Copy

Title:
This record has been reviewed and locked.
If you have any other change requests or questions, get in touch via <a href="mailto:biblio@ugent.be">biblio@ugent.be</a>. Thank you for your contribution!

### Code

To be placed **inside the `u-scroll-wrapper__body p-6` div**
```
<div class="alert alert-info mb-5">
    <i class="if if-info-circle-filled"></I>
    <div class="alert-content">
        <h3 class="alert-title">This record has been reviewed and locked.</h3>
        <p class="mb-2">For any change requests or questions, get in touch via <a href="mailto:biblio@ugent.be">biblio@ugent.be</a>. Thank you for your contribution!</p>
    </div>
</div>
```

### Component to be used
https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-alerts.html#component-01-b-alert-info

# Automatic testing scenario
See #1124

**Comment by verheyenkoen** [comment]
Added failing test on branch fix_issue_1125

**Comment by verheyenkoen** [comment]
The tooltip on the locked icon is broken. There is a default HTML title but the popup script seems kaput.
