### ISSUE TITLE
Provide error: JSON not recognised

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1135]
# Enhancement
Provide error: JSON not recognised
> JSON Validation errors => The Crossref JSON itself is invalid (it's not a JSON string; but garbled data)

For context, see epic #1091 

## Success criteria
Whenever we can resolve the DOI but the JSON is not recognised, I see an error toaster. See implementation suggestions.

### Publications
![Scherm­afbeelding 2023-06-15 om 14 45 22](https://github.com/ugent-library/biblio-backoffice/assets/1572885/e0f69584-a6a2-4c97-9614-c9c354540537)

To be adapted:
- The route to other import options (now just a link)
- The error code

```
<div class="toast show" role="alert" aria-live="assertive" aria-atomic="true" data-autohide="false">
    <div class="toast-header">
        <div class="u-divide-x">
            <span class="c-subline">DOI import</span>
            <span class="c-body-small text-muted ml-3 pl-3">404</span>
        </div>
        <button class="close" type="button" data-dismiss="toast" aria-label="Close">
            <i class="if if-close"></i>
        </button>
    </div>
    <div class="toast-body">
        <i class="if if-alert-fill if--warning"></i>
        <div class="toast-content">
            <h3 class="alert-title">The publication could not be imported.</h3>
            <p class="mb-3">The DOI was recognised, but the metadata could not be retrieved because of a problem with  <a href="https://www.crossref.org" target="_blank" class="text-muted">Crossref</a>'s service.</p>
            <p>Try again later, or <a href="https://backoffice.biblio.ugent.be/publication/add">use a different import option</a>.</p>
        </div>
    </div>
</div>
```

### Datasets

![Scherm­afbeelding 2023-06-15 om 14 45 43](https://github.com/ugent-library/biblio-backoffice/assets/1572885/30a4f54c-d443-47e8-aaa7-3a7f23380c15)

To be adapted:
- The route to other import options (now just a link)
- The error code

```
<div class="toast show" role="alert" aria-live="assertive" aria-atomic="true" data-autohide="false">
    <div class="toast-header">
        <div class="u-divide-x">
            <span class="c-subline">DOI import</span>
            <span class="c-body-small text-muted ml-3 pl-3">404</span>
        </div>
        <button class="close" type="button" data-dismiss="toast" aria-label="Close">
            <i class="if if-close"></i>
        </button>
    </div>
    <div class="toast-body">
        <i class="if if-alert-fill if--warning"></i>
        <div class="toast-content">
            <h3 class="alert-title">The dataset could not be imported.</h3>
            <p class="mb-3">The DOI was recognised, but the metadata could not be retrieved because of a problem with <a href="https://datacite.org" target="_blank" class="text-muted">DataCite</a>'s service.</p>
            <p>Try again later or <a href="https://backoffice.biblio.ugent.be/dataset/add">manually add your dataset</a>.</p>
        </div>
    </div>
</div>
```

**Comment by nicolasfranck** [comment]
@mietcls About the error message `DOI is recognized but ..` -> I am not sure if one can make that distinction. If there is something wrong with crossref, then crossref probably won't be able to do any database lookups (or return a result)

**Comment by mietcls** [comment]
This is based on a conversation with @netsensei: https://github.com/ugent-library/biblio-backoffice/issues/1088#issuecomment-1533113247
Does this make sense?

**Comment by nicolasfranck** [comment]
ah `Record Validation errors => the CrossRef JSON is valid; but fields are empty, or data is missing)` ...?

If a resource returns valid json, but the schema/structure of that json does not make any sense (missing fields),
I would label that also as a json validation error. You expect a certain format, right? Anyway we do no have a
crossref schema available to validate the records first?

**Comment by mietcls** [comment]
@netsensei worded it like this in the discussion (also mentioned in the issue above)"
> JSON Validation errors => The Crossref JSON itself is invalid (it's not a JSON string; but garbled data)
Do we still need the crossref schema to fix this one?

This error we will not fix, you can read more about it in the [epic](https://github.com/ugent-library/biblio-backoffice/issues/1091):
> "Record Validation errors => the CrossRef JSON is valid; but fields are empty, or data is missing)

**Comment by mietcls** [comment]
To be revisited
