### ISSUE TITLE
Provide error: The import service for DOIs cannot be reached (Crossref or DataCite)

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1137]
# Enhancement
Provide error: The import service for DOIs cannot be reached (Crossref or DataCite)
> Connection errors => CrossRef is unreachable (The wire between the Backoffice & Crossref is blocked for whatever technical reason; or the CrossRef API is offline)

For context, see epic #1091 

## Success criteria

Whenever there are connection issues, and the import service for DOIs can not be reached (Crossref or DataCite), I see an error toaster. See implementation suggestions.

### Publications
![Scherm­afbeelding 2023-06-14 om 17 35 54](https://github.com/ugent-library/biblio-backoffice/assets/1572885/be166555-7f90-4bf5-a6c2-d129b5f77bd9)

To be adapted:
- The route to other import options (now just a link)
- The error code

```
<div class="toast show" role="alert" aria-live="assertive" aria-atomic="true" data-autohide="false">
    <div class="toast-header">
        <div class="u-divide-x">
            <span class="c-subline">DOI import</span>
            <span class="c-body-small text-muted ml-3 pl-3">404</span>
        </div>
        <button class="close" type="button" data-dismiss="toast" aria-label="Close">
            <i class="if if-close"></i>
        </button>
    </div>
    <div class="toast-body">
        <i class="if if-alert-fill if--warning"></i>
        <div class="toast-content">
            <h3 class="alert-title">The publication could not be imported.</h3>
            <p class="mb-3">The import service <a href="https://www.crossref.org" target="_blank" class="text-muted">Crossref</a> could not be reached.</p>
            <p>Try again later, or <a href="https://backoffice.biblio.ugent.be/publication/add">use a different import option</a>.</p>
        </div>
    </div>
</div>
```

### Datasets

![Scherm­afbeelding 2023-06-14 om 17 29 33](https://github.com/ugent-library/biblio-backoffice/assets/1572885/06304691-512c-4ca2-a61b-249671488a79)

To be adapted:
- The route to other import options (now just a link)
- The error code

```
<div class="toast show" role="alert" aria-live="assertive" aria-atomic="true" data-autohide="false">
    <div class="toast-header">
        <div class="u-divide-x">
            <span class="c-subline">DOI import</span>
            <span class="c-body-small text-muted ml-3 pl-3">404</span>
        </div>
        <button class="close" type="button" data-dismiss="toast" aria-label="Close">
            <i class="if if-close"></i>
        </button>
    </div>
    <div class="toast-body">
        <i class="if if-alert-fill if--warning"></i>
        <div class="toast-content">
            <h3 class="alert-title">The dataset could not be imported.</h3>
            <p>The import service <a href="https://datacite.org" target="_blank" class="text-muted">DataCite</a> could not be reached.</p>
            <p>Try again later, or <a href="https://backoffice.biblio.ugent.be/dataset/add">manually add your dataset</a>.</p>
        </div>
    </div>
</div>
```

**Comment by mietcls** [comment]
@netsensei is this the type of error you expect? Does it still need extra codes for developers?

**Comment by netsensei** [comment]
@mietcls Yes. I think it should be informative enough for users. Maybe replace "The import service CrossRef..." with "The CrossRef database is currently unreachable"? + make CrossRef linkable to crossref.org? Do the same for Datacite?

I don't think codes or request ID's will be helpful here. If these services become unavailable, we'll be notified via the review team anyway. If the problem exists on the side of these services, there isn't anything we can do except wait until they become available again.

**Comment by mietcls** [comment]
@netsensei I'm using language that people that don't use technical language understand, which is why I'm using service instead of database. They key is that we need an other service to complete this, and that one is unavailable.

I also had a design with links to crossref and datacite but it drew a lot of attention, people need to be able focus on the solutions. I'll check if I can make the links subtle.

**Comment by netsensei** [comment]
> Do we get error codes here as well, such as 4** or 5**?

Sure, something along the lines of "the publication could not be found with the Crossref service" (404) or "the publication could not be retrieved from the Crossref service at this time." (50x). 50x errors usually are transient, whereas 40x errors may be permanent (e.g. the publication never gets published via the service,... YMMV)
