### ISSUE TITLE
Extend current batch operations

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1148]
# Enhancement
Extend current batch operations

## Context

1. Go to Biblio / Batch https://backoffice.bibliotest.ugent.be/publication/batch
2. See current operations (as described here: https://booktower.gitbook.io/product-docs/producten-en-diensten/biblio-academische-bibliografie-en-repository/handleidingen/batch-operaties)

<img width="1285" alt="Scherm­afbeelding 2023-06-22 om 11 37 55" src="https://github.com/ugent-library/biblio-backoffice/assets/1572885/2685d97f-5378-4cce-912d-515535d44cfd">

## Requested operations

- `Set` Journal title
- `Set` abbreviated title

![MicrosoftTeams-image (6)](https://github.com/ugent-library/biblio-backoffice/assets/1572885/392a6c23-5ac0-4fba-b2ee-ba62fa8dd2a7)

- `Add` and `remove` IDs:
  - ISSN
  - E-ISSN
  - ISBN
  - E-ISBN

<img width="538" alt="MicrosoftTeams-image (7)" src="https://github.com/ugent-library/biblio-backoffice/assets/1572885/f7dd65c0-28c1-4e52-a38e-7dfa2ccb1581">

# Success criteria
- [ ] I can set the Journal title
- [ ] I can set the Abbreviated title
- [ ] I can add an ISSN
- [ ] I can add an E-ISSN
- [ ] I can add an ISBN
- [ ] I can add an E-ISBN
- [ ] I can remove an ISSN
- [ ] I can remove an E-ISSN
- [ ] I can remove an ISBN
- [ ] I can remove an E-ISBN
- [ ] The extra operations are clarified in the documentation
- [ ] The documentation is linked with the examples below

**Comment by mietcls** [comment]
Instructions need to be extended

**Comment by mietcls** [comment]
@nicolasfranck can you give me the specific instructions for how to add what so the documentation can be extended?

**Comment by nicolasfranck** [comment]
@mietcls 
```
1234,journal_title.set,"my journal"
1234,journal_abbreviation.set,"my journal abbreviation"
1234,isbn.add,"0268-1161"
1234,isbn.remove,"0268-1161"
1234,eisbn.add,"0268-1161"
1234,eisbn.remove,"0268-1161"
1234,issn.add,"0268-1161"
1234,issn.remove,"0268-1161"
1234,eissn.add,"0268-1161"
1234,eissn.remove,"0268-1161"
```

**Comment by netsensei** [comment]
@mietcls @nics This lacks the ArxivID and PubMedID per #1179. @nics I'll add them and make a PR.
