### ISSUE TITLE
Backoffice test

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1149]
# Bug description
Backoffice test epic

- [ ] #1152 [Question]
- [ ] #1153 (not urgent)

**Comment by netsensei** [comment]
@mietcls Your screenshot says `biblio.ugent.be` which is the production site. The `/publication01H4JXXHMF6K2FT0PKSV6RKWQY` url returns an 404 there. However, the publication ID does work on the biblio test environment.

I can also see the pubmed abstract of that record when I search for DOI [10.1104/pp.110.156018](https://doi.org/10.1104/pp.110.156018) on both production and test biblio frontend sites. The abstract is also available on both backoffice environments as well.

**Comment by mietcls** [comment]
@netsensei thanks for checking.

When you add a _new_ publication the abstract is not added: https://backoffice.bibliotest.ugent.be/publication/01H4NTHQ20J8R9CQWM97HK6MBT/add/description?show=description. It has been added manually in the production site.
There is no way to check whether a new publication gets a working front-office link. I was not referring to existing ones.

**Comment by netsensei** [comment]
@mietcls Okay, so, this issue needs a bit more information / context, because it's unclear what's going on when and where.

* I've tried importing the DOI of the publication on both the `dev` and `main` branches on my laptop, and I can see an abstract appearing.
* It's unclear to me what you mean by "404" error in the front-office for "new public publications".

**Comment by mietcls** [comment]
Thanks for the feedback! I'll clarify.

**Comment by mietcls** [comment]
@netsensei Only one remains an "urgent" question: https://github.com/ugent-library/biblio-backoffice/issues/1152. The other bugs still needs to be looked into, as I am not sure how urgent and frequently used this functionality is.
