### ISSUE TITLE
Person cannot log in

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1150]
# Bug description
Person cannot log in: https://telefoonboek.ugent.be/nl/people/002004407693

## Information

Error received: 
<img width="478" alt="Screenshot 2023-07-06 at 09 44 35" src="https://github.com/ugent-library/biblio-backoffice/assets/1572885/961dcc29-892a-4c4b-b5a5-9d0d316c6c0b">

1. Person can be found in phone book: https://telefoonboek.ugent.be/nl/people/002004407693
2. Person is set to active in Biblio front-office: https://biblio.ugent.be/person/184A5CA0-8E27-11E9-8035-D3015707D3EF?format=json
3. "View as" works, and can be added as an author

**Comment by nicolasfranck** [comment]
@mietcls I cannot find this error message anywhere in code of biblio-backoffice. Are you sure that this user ends in biblio-backoffice, and not somewhere else (keycloak, or even the ugent login page)?

**Comment by mietcls** [comment]
Confirmed, person can log in.
