### ISSUE TITLE
Empty manually added records are not added as a draft.

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1151]
# Enhancement
Empty manually added records are not added as a draft.

Right now, empty manually added records result into meaningless drafts:
- This gives librarians a skewed view on how many drafts are still open and need to be published.
- This requires people that are just looking around having to clean up.
_e.g. you create a new note in your notes app, don't add anything and you leave -> it's gone. When you did edit (and save) it remains._

## Steps to reproduce

Publications:
1. Add a publication https://backoffice.bibliotest.ugent.be/publication/add
2. Click "Enter a publication manually" https://backoffice.bibliotest.ugent.be/publication/add?method=manual
3. Pick any type and add publication, do not fill out anything.
4. Go back to the overview, and see an empty draft:
![Screenshot 2023-07-06 at 11 00 25](https://github.com/ugent-library/biblio-backoffice/assets/1572885/d1081fbd-5c51-4c34-aa97-b5b7544ba8a0)

Datasets
1. Register a dataset https://backoffice.bibliotest.ugent.be/dataset/add
2. Click "Register a dataset manually"
3. Go back to the overview, and see an empty draft:
![Screenshot 2023-07-06 at 11 01 26](https://github.com/ugent-library/biblio-backoffice/assets/1572885/293f2fcd-fd41-4dd1-8f6b-440ef0ec6735)

## Expected behavior
- [ ] Empty new manually added publications are not saved as a draft, they are discarded
- [ ] Empty new manually added datasets are not saved as a draft, they are discarded

**Comment by nicolasfranck** [comment]
@mietcls by this you mean that the publication is removed automatically?

**Comment by mietcls** [comment]
@nicolasfranck yes, that would be the intention.

We will not implement autosave any time soon. Are there any other ways?

**Comment by nicolasfranck** [comment]
This, together with other types of import, all have the same common problem: the records already appear in the overview before the reviewer has even pushed the "save as draft" or "publish" button.

But luckily they also share something: imported publications have an internal "batch_id" which is used to make the list possible.

My proposal:

* filter out any publications with a "batch_id" in the normal overview
* when the button "save as draft" or "publish" is clicked the batch_id is removed from those records. Of course one cannot see anymore that this record has been imported. Now batch_id is only used during import, and remains there, unused.
* add a context menu somewhere that shows "(x number of unfinished batch imports)". This way you can close your browser, and you do not need to store the records in the client browser (which was proposed an alternative for saving server side).

**Comment by mietcls** [comment]
@nicolasfranck there's been some ideas around a new way to import records. I can show you this week, this might simplify things.

**Comment by nicolasfranck** [comment]
@mietcls what new idea's?

**Comment by mietcls** [comment]
Not for now
