### ISSUE TITLE
Is the public biblio location available in the dev environment?

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1152]
# Question/bug
Is the public biblio location available in the dev environment?
Public Biblio Location throws a 404 for new public publications.

# Steps to Reproduce

1. Go to https://backoffice.bibliotest.ugent.be/publication/add
2. Add a new publication, for instance https://pubmed.ncbi.nlm.nih.gov/20460583/ via "Import your publication via an identifier", use the PubMed ID function: 2899902
3. Publish
4. Click on "Public Biblio location" in the dropdown of the record on the overview search page
![Screenshot 2023-07-10 at 11 55 37](https://github.com/ugent-library/biblio-backoffice/assets/1572885/12855f9d-aeb4-461c-bcda-0c2b6947d8b3)
5. See error
![Screenshot 2023-07-10 at 11 56 21](https://github.com/ugent-library/biblio-backoffice/assets/1572885/09a585c4-19d5-406f-a59c-4a60ff47d02a)

## Automatic testing scenario
1. When clicking on "Public Biblio location" in the dropdown of the record on the overview search page
2. You go to the location of this record in the front-office, which resolves and does not throw a 404

### Likelihood
1: Frequent

### Consequences
? Not sure if this would also break in production. If so 2. Critical
*What's the impact? 1: Catastrophic, 2: Critical, 3: Marginal, 4: Negligible*

# Expected behavior
When clicking on "Public Biblio location" in the dropdown of the record on the overview search page, you go to the location of this record in the front-office.

**Comment by netsensei** [comment]
@mietcls Noticing two things here.

1/

You're on the test environment, yet the biblio link points to the production URL. Looking at the template, the `views/publication/search_hit.gohtml` template, I can see that that base URL is hard coded:

```
{{if eq .Publication.Status "public"}}
<a class="dropdown-item" href="https://biblio.ugent.be/publication/{{.Publication.ID}}" target="_blank">
    <i class="if if-book"></i>
    <span>Public Biblio Location</span>
</a>
{{end}}
```

So, importing data in the test environment will yield a record with a biblio id which won't be available in the production environment. Hence the 404.

Solution: the base url should be made configurable in backoffice, so it can point per environment to the corresponding biblio frontend instance.

2/

Having created a new record in biblio backoffice test => I don't see it appear on the biblio test frontend. Still yields a 404 for me.  So, something is off with the syncing in the test environment? @nicolasfranck

**Comment by nicolasfranck** [comment]
Note to self:

* there is an environment variable `BIBLIO_BACKOFFICE_FRONTEND_URL` available containing the full frontend base url. This was used in the past to access the "person service" as implemented by the frontend, so that variable is now unused (especially the username and password).
* that variable is available within the application as `viper.GetString("frontend-url")`
