### ISSUE TITLE
Double project found in Biblio, one needs to go

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1165]
# Bug description
Double project found in Biblio, one needs to go

# Steps to Reproduce

1. Go to a publication in production https://backoffice.biblio.ugent.be/publication/01GR1E7FYKNB35YWHMQ46J5TXB?redirect-url=%2Fpublication%3Fq%3D01GR1E7FYKNB35YWHMQ46J5TXB%26sort%3Ddate-updated-desc&show=description#projects
2. Add a project, 3G0F3121
3. See two projects arise with the same name, but different code.
<img width="1442" alt="Screenshot 2023-07-27 at 15 04 03" src="https://github.com/ugent-library/biblio-backoffice/assets/1572885/3798de46-86f5-45b8-8683-36438aab9486">
4. The correct code: 3G0F3121 (correct title)
The wrong code: 3G0F3121N (title in all caps)

### Likelihood
1: Frequent
It happens quite often, but we are working on the high-level approach with a projects service in the future.

### Consequences
2: Critical
Lowers the chances of connecting the right project. Funding depends on it.

# Expected behavior
The correct code and title appear:
3G0F3121
Readers as statistical learners: an individual differences approach

**Comment by nics** [comment]
3G0F3121N is a gismo project
