### ISSUE TITLE
Cannot find professor in Back-office with "view as" functionality, that can be found in front office.

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1166]
# Bug description
Cannot find em. professor in Back-office with "view as" functionality, that can be found in front office.
User cannot be found in phone book.
Is this normal as this person cannot be found in the phone book any longer?

# Steps to Reproduce
1. Go to Biblio Back-office
2. "View as" https://ugentbe-my.sharepoint.com/:w:/g/personal/miet_claes_ugent_be/EeYOaP3w0DBBrM9t3D6wJyQBnAVeB1trxRyc7PvRlN6oOw?e=BLOJOS
3. See error
<img width="846" alt="Screenshot 2023-07-28 at 10 56 26" src="https://github.com/ugent-library/biblio-backoffice/assets/1572885/bcf33eba-65a2-4af4-8e6c-1d1ed772a292">

## Automatic testing scenario
TBD

**Comment by nicolasfranck** [comment]
@mietcls yes that is normal. Only users active in LDAP, are mapped as "active" users in biblio frontend and biblio backoffice. What are they trying to do here?

**Comment by mietcls** [comment]
@nicolasfranck it was more of a question on my side to be able to see what rights people have on other records (especially for dissertations). If this is as designed, that's okay.
