### ISSUE TITLE
Create bibliodev.ugent.be

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1171]
# Enhancement
Create bibliodev.ugent.be – we cannot fully test the dev environment without it.

## Steps to reproduce
When viewing the public biblio location of a record:
<img width="1401" alt="Screenshot 2023-08-08 at 16 49 50" src="https://github.com/ugent-library/biblio-backoffice/assets/1572885/41072346-4f42-4f5a-8c01-be08bff723cd">

We get this:
<img width="946" alt="Screenshot 2023-08-08 at 16 48 54" src="https://github.com/ugent-library/biblio-backoffice/assets/1572885/fe50a216-c014-4798-982d-5c4ef8c1fa21">

Cannot test issue:
- https://github.com/ugent-library/biblio-backoffice/issues/1063
- https://github.com/ugent-library/biblio-backoffice/issues/896

## Expected behavior
We can see the public record in the public biblio location.

**Comment by nics** [comment]
@mietcls @netsensei  conclusions:
- setting up bibliodev.ugent.be is a lof of work
- we switch to shorter lived feature branches that merge in the main branch
- main is always kept in a working state
- when happy we tag main and deploy
- progress can be followed on backoffice.bibliotest.ugent.be coupled to bibliotest.ugent.be
- backoffice.bibliodev.ugent.be shows the dev branch and is used to demo new developments, features that need feedback etc
