### ISSUE TITLE
OIDC state cookie not set on safari during login

### ISSUE THREAD

**Issue by netsensei** [ugent-library/biblio-backoffice#1174]
# Bug description

Users can't login on Safari when the site is run without HTTPS (e.g. local development).  Login will fail and an error "http: named cookie not present" will be shown in the logs.

# Steps to Reproduce

1. Set up the application locally and run it with `reflex`
2. Open Safari
3. Choose to login
4. You will land on an error page

## Automatic testing scenario

Not applicable

### Likelihood

*How often does this happen? improbable

### Consequences

*What's the impact? Marginal. This affects local development e.g. testing sections that are secured by authentication in Safari.

# Expected behavior

I can also login on a locally set up application with Safari.

**Comment by netsensei** [comment]
This is caused because cookie parameter `Secure` is hard coded to `true` in the [OIDC package](https://github.com/ugent-library/oidc) This will enable a browser check that a cookie can only be set if the page is served over HTTPS. Safari is stricter then other browsers (e.g. Firefox) when it comes to checking this flag when the page is served over plain HTTP.

Solution: make this flag configurable and tie it to the configuration flag for the environment in which the application runs (local, development, production,...)

**Comment by mietcls** [comment]
@netsensei should label this as nice to have as it is improbable? Or ready to build because of low hanging fruit?

**Comment by netsensei** [comment]
@mietcls Already fixed. :-) Needed to fix this first in order to be able to fix #540.
