### ISSUE TITLE
DOI import for datasets does not check for doubles any longer

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1181]
# Enhancement
DOI import for datasets does not check for doubles anymore, neither in published nor drafts records.

⚠️ Cannot test on dev as creating datasets no longer works as expected, it does not show up in the search overview #1182 

## Steps to reproduce
1. Go to https://backoffice.bibliotest.ugent.be
2. Add a dataset through DOI such as 10.5281/ZENODO.4625218
3. Get no prompt this is a double
4. Complete and import:
![Screenshot 2023-08-11 at 16 57 59](https://github.com/ugent-library/biblio-backoffice/assets/1572885/8f7a5e42-daa5-47c3-8472-17123e456cb2)

**Comment by netsensei** [comment]
@mietcls Should be fixed. Deploying to dev.

**Comment by mietcls** [comment]
@netsensei unfortunately I can still add doubles via DOI.

**Comment by netsensei** [comment]
@mietcls I just did a deploy to dev. Should work now.
