### ISSUE TITLE
Dataset import via DOI no longer shows up on dataset search overview

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1182]
# Bug description
Dataset import via DOI no longer shows up on dataset search overview nor during search. Publications do work.

# Steps to Reproduce

1. Go to https://backoffice.bibliodev.ugent.be/dataset/add to add a dataset via DOI
2. Add 10.17605/OSF.IO/NPSR7 
3. Complete all required fields
4. Publish

See nothing on the overview: https://backoffice.bibliodev.ugent.be/dataset
![Screenshot 2023-08-11 at 17 03 59](https://github.com/ugent-library/biblio-backoffice/assets/1572885/3d2b290a-4631-42cd-86a9-51b64048792b)

Also not on search:
![Screenshot 2023-08-11 at 17 07 12](https://github.com/ugent-library/biblio-backoffice/assets/1572885/2e364608-9743-4d05-a5e4-e07638b50dc1)

However you can still find the record directly via URL: https://backoffice.bibliodev.ugent.be/dataset/01H7JHXAV74FYVT9J25BZRHEYS
![Screenshot 2023-08-11 at 17 04 32](https://github.com/ugent-library/biblio-backoffice/assets/1572885/de46b631-f0f1-4699-876f-ccbe717bb0c4)

**Comment by mietcls** [comment]
@nicolasfranck I do see datasets in the overview.

This comment is not very helpful in figuring it out, could you add images or steps to reproduce?

**Comment by nicolasfranck** [comment]
@mietcls oops, my bad, I was in the "researcher view" with less capabilities.

**Comment by nicolasfranck** [comment]
@mietcls I tested this locally, and I could only reproduce this once. After a full reindexation of the datasets, all went fine.

@netsensei can you reindex the datasets on dev?

**Comment by mietcls** [comment]
Works as expected, thanks!
