### ISSUE TITLE
Clarify datasets names

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1190]
# Enhancement
Clarify datasets name

- [x] Rename BioProject to ENA BioProject
_As there is also an NCBI BioProject, to avoid confusion._

**Comment by nics** [comment]
@mietcls @nicolasfranck the string you changed is an entry in a type map for dynamic lookup and should not be changed. If you want labels, add them to translations.go or another appropriate place.

**Comment by mietcls** [comment]
Thanks for fixing it @nics it's more clear to me now! :-)
