### ISSUE TITLE
Implement Signposting for every download link

### ISSUE THREAD

**Issue by nicolasfranck** [ugent-library/biblio-backoffice#1202]
See also https://github.ugent.be/Universiteitsbibliotheek/biblio/issues/104.

That issue requires to add link headers on every download link,
but the biblio frontend points directly to files in the biblio backoffice,
so this becomes a biblio-backoffice issue.

**Comment by netsensei** [comment]
@nicolasfranck Can you use the GitHub Issue templates to describe this issue? It's unclear what this story is about, and what the intended outcome / success factors are.
