### ISSUE TITLE
Remove LU prefix in our handles

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1210]
# Enhancement

Remove LU prefix in our handles.

# Success criteria

To be extended

**Comment by nics** [comment]
@mietcls the LU- prefix was introduced to prevent clashed with old dspace identifiers. For the new identifiers we mint now in backoffice, we could eliminate this prefix. But it doesn't improve anything except the aesthetics of the handle url, so not worth the effort? I would just close this.
