### ISSUE TITLE
Align modal focus behaviour for modals we are going to keep after the redesign

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1213]
# Enhancement

Align modal focus behaviour for modals we are going to keep after the redesign.
When opening a modal, put the cursor in the search field / focus on the first form element.
This will make filling out fields go smoother and faster.

Example where it does not work as expected:
When adding a project to a publication, put the cursor in the search field.

Example where it already works as intended:
Authors.

List of items we will keep:
- [ ] projects
- [x] authors, editors, supervisors, creators
- [ ] departments
- [ ] links
- [ ] datasets
- [ ]  Librarian tags
- [ ] Librarian note
- [ ] Messages from and for Biblio team

## Steps to reproduce
1. Go to https://backoffice.bibliodev.ugent.be/publication/01H9J7PT3C3ABBP8JRMBKZWZKT?redirect-url=%2Fpublication#projects
2. Add a project
3. See focus on first link instead of search field
<img width="1512" alt="Screenshot 2023-09-05 at 16 10 34" src="https://github.com/ugent-library/biblio-backoffice/assets/1572885/fac3af37-495c-4ce6-bc19-3e85a13b2073">

Expected result: cursor in search field instead of focus on link.

**Comment by nicolasfranck** [comment]
Same accessibility consideration applies here too, as reported by @netsensei. See https://github.com/ugent-library/biblio-backoffice/issues/1214#issuecomment-1706778764

**Comment by nics** [comment]
@mietcls this can now be closed I think
