### ISSUE TITLE
When adding a publication or dataset via identifier, put the cursor in the field

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1214]
# Enhancement
When adding a publication or dataset via identifier, put the cursor in the field.
This will make filling out fields go smoother and faster.

## Steps to reproduce
1. Go to https://backoffice.bibliodev.ugent.be/publication/add?method=identifier to add a publication or to https://backoffice.bibliodev.ugent.be/dataset/add to add a dataset
2. See no focus on the field
![Image](https://user-images.githubusercontent.com/1572885/265728107-00704ab6-a00e-4379-b16b-dabd34e0101c.png)

Expected result: cursor in identifier field

**Comment by netsensei** [comment]
@mietcls Do you mean adding `autofocus` on this field? 

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autofocus

There's an accessibility consideration there:

> Automatically focusing a form control can confuse visually-impaired people using screen-reading technology and people with cognitive impairments. When autofocus is assigned, screen-readers "teleport" their user to the form control without warning them beforehand.

**Comment by mietcls** [comment]
@netsensei Thanks for thinking about this! However, they will come from a block titled project, undertook the action "add project" and then they will then land on a field that searches through those projects. It will not feel like teleporting. The other search fields in the modals are also configured like this.

However, our entire application needs an accessibility review, I'm quite sure there are a dozen other loopholes.

**Comment by mietcls** [comment]
Will revisit when revisiting import flow
