### ISSUE TITLE
I can see two buttons that allow me to switch between "list view" and "thumbnail view".

### ISSUE THREAD

**Issue by nics** [ugent-library/biblio-backoffice#122]
Switching between to "thumbnail view":

- [ ]  I can see a grid of publications instead of a list.
- [ ]  The cover image of the publication is shown large, making the cover readable / legible.
- [ ]  The same metadata / options is shown below the cover image. This is the same metadata / options as in "list view".

**Comment by mietcls** [comment]
There is no need for this right now
