### ISSUE TITLE
Empty librarian tags started showing up

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1223]
# Bug description
Empty librarian tags started showing up.
Edit 23 January 2024: still there.

On Test, Dev and Production:
![Screenshot 2023-09-13 at 10 25 09](https://github.com/ugent-library/biblio-backoffice/assets/1572885/72c37c86-aab5-4a58-9909-01e4747bd7b6)
![Screenshot 2023-09-13 at 10 25 22](https://github.com/ugent-library/biblio-backoffice/assets/1572885/3e656d5b-97de-4d92-b3e3-7d281262d49b)

# Steps to Reproduce

1. Go to the publications overview on https://backoffice.bibliotest.ugent.be/publication
2. Click on the librarian tags filter and see the empty status
3. Try filtering on the empty status, and see it not work. No console log.

![Screenshot 2023-09-13 at 10 28 35](https://github.com/ugent-library/biblio-backoffice/assets/1572885/5e255d23-1ae7-4a8d-9ff7-52a50b9185c2)

I cannot seem to reproduce records that are added to that filter.

**Comment by nicolasfranck** [comment]
Will probably be fixed, again, by reindexing. If reindexing fixes the problem, it was probably a mistake that was fixed by an end user, in which case one cannot find any publication with that value. Values stay in the index..

**Comment by nicolasfranck** [comment]
In development found these publications:

01GK16JB2ERX1BJV09YC34X2EG
8767782
8769171

When I looked into their values there where empty values added in the list

e.g. for 01GK16JB2ERX1BJV09YC34X2EG they where:

```
"esci"
""
"funding to do: bof"
""
```

So I guess the reviewer tags should be cleaned on empty values in the list?
I guess this may happen elsewhere too

**Comment by nics** [comment]
@nicolasfranck the vacuum filter should remove these, i'll look into why not

**Comment by nicolasfranck** [comment]
If we remove the brackets and the indexes from the names, we need to check the following:

* does every browser send the input fields in the same order as they were in the HTML document?
* are the form elements decoded in the same order server side? This is especially important for fields with the same name.

**Comment by nicolasfranck** [comment]
@nics I just remembered that we are going to return to the "all in one page" forms" (as was in LibreCat) in the future. That will require structured field names like `abstract[0]["text"]` and `abstract[1]["text"]` in order to know what value belongs to what element in the struct(ure).

**Comment by nics** [comment]
@nicolasfranck that doesn't matter for a simple array of text values, we can mix the 2 styles

**Comment by nics** [comment]
@mietcls this can be closed?

**Comment by mietcls** [comment]
The behaviour still shows up unfortunately, both on dev and production:

dev
![Image](https://github.com/ugent-library/biblio-backoffice/assets/1572885/50491a8b-8cac-4c37-9464-2f0400fbf663)


production
![Image](https://github.com/ugent-library/biblio-backoffice/assets/1572885/5eb4eb8c-1ea1-44d1-9b75-c1009bb94ad7)

**Comment by nicolasfranck** [comment]
mm, apparently I only fixed the input from the website, and not the indexation of existing records.

Will look into it.

**Comment by nics** [comment]
@nicolasfranck you can add it to the CleanupPublications (and Datasets) grpc method (see keyword cleanup)
it the input is already being sanitized, they should disappear after cleanup+reindex
