### ISSUE TITLE
[home page improvements] When there are actionable items on the home page, a notification sign appears

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1224]
# Enhancement
When there are actionable items on the home dashboard page (see #1197 and #1196), a notification sign appears in the sidebar – when viewing the app as a researcher.

Can be developed after issues #1193, #1196 and #1197 have been completed.
![Screenshot 2023-10-19 at 15 54 37](https://github.com/ugent-library/biblio-backoffice/assets/1572885/e917ca00-e35f-425d-93b0-234291b865cf)

Implementation suggestion: add the classes `if--notification if--notification-warning` to the home icon in the sidebar.

```
<i class="if if-home if--notification if--notification-warning"></I>
```

**Comment by nics** [comment]
there's a check for pending tasks every 5 seconds
