### ISSUE TITLE
Cannot lock record after editing

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1226]
# Bug description
Cannot lock record after editing. Only when you refresh after editing you can. No console error.

# Steps to Reproduce

1. Go to https://backoffice.bibliodev.ugent.be and pick a dataset or publication.
2. Edit one or more fields and save.
3. Try hitting lock. It does not work, and there is no error to be seen.
4. After refresh, it does work.

**Comment by nicolasfranck** [comment]
I do see a network request, which leads to this message:

``
`
Publication has been modified by another user. Please reload the page.

Close
```
