### ISSUE TITLE
Close button on toast does not work

### ISSUE THREAD

**Issue by verheyenkoen** [ugent-library/biblio-backoffice#1246]
# Bug description
The close button on a toast should dismiss the toast but that doesn't seem to happen.

# Steps to Reproduce

Happens on multiple toast instances:

1. After deleting a publication
1. After publishing a publication
1. After withdrawing a publication
1. After republishing a publication
1. After locking a publication
1. After unlocking a publication

### Likelihood

1. Frequent (always)

### Consequences

3. Marginal

# Expected behavior

The toast should disappear immediately.

# System information

## Desktop
 - OS: MacOS
 - Browser: Chrome

# Additional context

Maybe the toast should also close upon hitting the `ESCAPE` key.

**Comment by mietcls** [comment]
@nics do you have any idea? I noticed in the toast.js it says `bc-toast` instead of `toast`, but when adapting this, it did not do the job. I did however have to overwrite some css to make them visible.

**Comment by nicolasfranck** [comment]
@mietcls see https://github.com/ugent-library/biblio-backoffice/pull/1250
