### ISSUE TITLE
User menu popup hidden behind publication details

### ISSUE THREAD

**Issue by verheyenkoen** [ugent-library/biblio-backoffice#1247]
# Bug description
In the view publication page, if you click the user menu, the popup does appear to open, but only the very top is visible and the rest of the menu is hidden behind other elements on the page.

# Steps to Reproduce

1. Open a publication detail page
2. Click on the user name in the top right corner
3. The popup menu should be visible now.

## Automatic testing scenario

Write a high-level way to test this with Cypress if applicable.

### Likelihood

1. Frequent

### Consequences

4. Marginal

# Expected behavior
Popup menu's should always be on top.

# Screenshots

<img width="371" alt="image" src="https://github.com/ugent-library/biblio-backoffice/assets/599538/42859fdd-b1e9-476d-912b-535de92db95a">

# System information

## Desktop
 - OS: MacOS
 - Browser: Chrome

**Comment by mietcls** [comment]
I have fixed this today on https://backoffice.bibliodev.ugent.be – where did you test this?
It worked on chrome, firefox and safari for me.

**Comment by verheyenkoen** [comment]
Dev on chrome

**Comment by nicolasfranck** [comment]
@mietcls I seems to be working on all pages, except for the dataset/publication detail pages.

**Comment by verheyenkoen** [comment]
Maybe useful to look at the [`isolation: isolate`](https://developer.mozilla.org/en-US/docs/Web/CSS/isolation) CSS property to put these kinds of popovers in a separate stacking context so they can never interfere with other elements based on `z-index`. 

Quick intro: https://www.youtube.com/shorts/NXu2vN052xM

**Comment by mietcls** [comment]
@verheyenkoen interestiiiing, thanks! The z-index things are solved normally, but if it starts interfering I'll use it.

**Comment by verheyenkoen** [comment]
Branch [fix_issue_1247](https://github.com/ugent-library/biblio-backoffice/tree/fix_issue_1247) already created.
