### ISSUE TITLE
Hide Biblio team member names for researchers

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1258]
# Enhancement
Hide Biblio team member names for researchers only

- [x] For researchers: Instead of the name, show "A Biblio team member"
- [x] For librarians: Librarians _should_ be able to see the names of each other.
- [x] In the publications and datasets search overview
![Screenshot 2023-10-13 at 09 06 50](https://github.com/ugent-library/biblio-backoffice/assets/1572885/245a167a-3ddc-409e-a684-3c99d8ec1e96)
- [x] On record level for datasets and publications
![Screenshot 2023-10-13 at 09 11 18](https://github.com/ugent-library/biblio-backoffice/assets/1572885/f868bce8-ec25-4784-919f-0bbc77dd72e7)
- [x] In the upcoming activity features; epic #1225 

## Context

When a librarian adapted a record, their names should not be open to researchers immediately to protect their privacy. This also makes sure researchers contact a generic helpdesk instead of people.

## Out of scope

- Inside the helpdesk it can be clear there is a person behind the screen, but they should not be able to "shoot" the messenger.
- Rejected name: "[A metadata librarian](https://journals.ala.org/index.php/lrts/article/view/4906/5926)" (too much of a library perspective, less product- and service-first)
- People that _used_ to be librarians

**Comment by mietcls** [comment]
We can perhaps start with the current names as helpdesk issues are mostly about current records, and see how we can evolve from there. Will adapt the issue.

**Comment by verheyenkoen** [comment]
Since for the overviews and detail pages we allow curators to see other curator names there, I aligned this behaviour with the recent activity list on the dashboard. Up until now, curators names would always be hidden there. I changed that so curators are visible to other curators to have the same behaviour in 3 places.
