### ISSUE TITLE
add/rename metadata fields for datasets

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backoffice#126]
**Describe the improvement**
This [overview of metadata fields](https://ugentbe.sharepoint.com/:x:/t/CA20.DataStewardTeam/EXpvANokKKFLk-CtFHgHwOsB9Y2Orh-omCrnECboNt3fYw?e=qQsesL) for datasets is a simplified version of the [overview shared earlier](https://ugentbe.sharepoint.com/:x:/t/CA20.DataStewardTeam/EQZscJYa78dGlRIXrDujlbIBEACHYbyVK4Epo57G0CT3lw?e=fC1b6l).

This file contains the following fields to be addressed, as well as examples and info on expected behavior (DOI-based and alternative identifier-based). Fields with "1" and in bold are priority fields.

- [x] **Data - Identifier** 1 - V
- [x] **Data - Identifier type** 1 - V (auto)
- [ ] Data - Alternative identifier no
- [ ] Data - Identifier type no
- [x] **Data - Abstract** 1
- [x] Data - Abstract language
- [x] **Data - Creator Name** 1 - V
- [x] Data - Creator Identifier
- [x] **Data - Creator Affiliation** 1 - V (auto)
- [x] **Data - Title** 1 - V
- [x] **Data - Publisher** 1
- [x] **Data - Publication year** 1 - V
- [x] Data - Embargo date
- [ ] Data - Date type
- [x] **Data - Keyword(s)** 1 - V
- [ ] Data - Contributor type
- [ ] Data - Contributor name
- [ ] Data - Contributor NameIdentifier
- [ ] Data - Contributor NameIdentifierScheme
- [x] **Data - Format** 1 - V
- [x] Data - Licenses - V (from 2023 onwards)
- [x] **Data - Access Rights** 1 - V
- [x] **Data - link to Project(s)** 1 - V
- [x] **Data - link to Publication** 1
- [ ] Data - link between Datasets 
- [ ] Data - Research disciplines

**Comment by sdebodt** [comment]
"rightsList": [
    {
      "rights": "Creative Commons Attribution 4.0 International",
      "rightsUri": "https://creativecommons.org/licenses/by/4.0/legalcode",
      "schemeUri": "https://spdx.org/licenses/",
      "rightsIdentifier": "cc-by-4.0",
      "rightsIdentifierScheme": "SPDX"
    },
    {
      "rights": "Open Access",
      "rightsUri": "info:eu-repo/semantics/openAccess"

for licenses: only extract SPDX licenses and their rightsIdentifier
for access rights: only extract if rightsUri is an openAIRE access right (See example above and excel)

**Comment by sdebodt** [comment]
predefined list of licenses: https://github.com/spdx/license-list-data/blob/master/json/licenses.json
predefined list of formats: media types https://www.iana.org/assignments/media-types/media-types.xhtml

**Comment by sdebodt** [comment]
@nics can embargo date and data type (of the embargo date) by added for datasets, as is done for publications? This is needed to decide on which datasets to provide to FRIS at a certain point in time.

**Comment by sdebodt** [comment]
predefined list of contributors: Contact Person
Creator
Data Collector
Data Curator
Data Manager
Distributor
Editor
Other
Producer
Project Leader
Project Manager
Project Member
Related Person
Researcher
Rights Holder
Sponsor
Supervisor
Work Package Leader

**Comment by mietcls** [comment]
Stale issue, has a mix of "done", "important now" and "important later" tasks, and tasks that are unclear whether they are important or not at all – and comments that are about different topics. Need to split this out into actionable issues once the intent and priority is clear. Will track this in #1099

**Comment by sdebodt** [comment]
- [ ]  Data - link between Datasets
- [ ]  Data - Research disciplines

These are two metadata fields which are still relevant to implement when time permits, but were not implemented as not set as 1st priority. For the research disciplines, we could borrow info from the project (as mentioned in https://github.com/ugent-library/biblio-backoffice/issues/81), but that is assuming that a project is linked and the scope of the project and the dataset is similar.

**Comment by mietcls** [comment]
Thank you for the info!
