### ISSUE TITLE
required asterisk positioned incorrectly when label is long

### ISSUE THREAD

**Issue by nics** [ugent-library/biblio-backoffice#128]
See screenshot:
<img width="496" alt="Screenshot 2021-11-19 at 11 21 20" src="https://user-images.githubusercontent.com/35421/142607099-dc01e8f4-f95b-4da0-91d8-08d70b57b5d9.png">

Also it's not visible enough

**Comment by netsensei** [comment]
Stale issue, because superseded by newer design iterations. Closing.
