### ISSUE TITLE
Hook tern migrations into biblio-backoffice deployment

### ISSUE THREAD

**Issue by nics** [ugent-library/biblio-backoffice#1298]

**Comment by netsensei** [comment]
This setup should resemble what we have in the [project-service](https://github.com/ugent-library/projects-service/tree/dev):

- [ ] Create a `/docker` directory with two files:
  - [ ] `app.Dockerfile` contains the docker setup for the application
  - [ ] `tern.Dockerfile` contains the docker setup for tern + the migration files
  - [ ] `tern.sh` file which does a check to ensure that the migrations are executed on only one Nomad node.
- [ ] Configure the docker repo for biblio-backoffice in dockerhub to build from `app.Dockerfile`
- [ ] Set up a new docker repo called biblio-backoffice-tern in dockerhub.
- [ ] Configure the Nomad job file to run two tasks. Use the `prestart` hook in the `lifecycle` stanza for the task that's responsible for the migrations.

Implement this first for the development version of biblio-backoffice.

**Comment by netsensei** [comment]
Needs to be changed to mimic the projects & people service: bake tern into the dockerfile of the main app, instead of creating & maintaining a separate docker image.

**Comment by nics** [comment]
done
