### ISSUE TITLE
Pagination hiccup: when you delete the only record on a page, you see an internal server error

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1299]
# Bug

Pagination hiccup: when you delete the only record on a page, you see an internal server error.

## Steps to reproduce

1. Go to the last page of the dataset or publication overview, and make sure there is only one record to be seen:

![Image](https://github.com/ugent-library/biblio-backoffice/assets/1572885/376aac6e-5ea6-48f0-8e00-bc7361aa0126)

2. Delete the record

![Image](https://github.com/ugent-library/biblio-backoffice/assets/1572885/402e3397-b405-4e82-8df2-b7f223064af1)

3. See internal server error

![Image](https://github.com/ugent-library/biblio-backoffice/assets/1572885/6a8daf9b-7226-4f7b-9617-e67098a9d018)

## Expected behaviour
You are directed to a page that has records.

Suggestion:
You go to the first adjacent page that has records (for example current page -1). If there is only 1 page, you remain on that page. If there are no records left at all on that page, you see the blank state on that page.

![Image](https://github.com/ugent-library/biblio-backoffice/assets/1572885/efc5e133-01ad-44c2-8221-8ab3d1688bf3)

**Comment by nicolasfranck** [comment]
mm, seems logical. 

Deleting a record should reset the page counter back to 1.

**Comment by mietcls** [comment]
It doesn't make sense to go back to page 1, if you're explicitly on the last page to go through some information, you'd have to go back to that page again. It would make sense to go to "current page -1" if there is more than 1 page.

Saying "you're on the wrong page" does not help the audience, we should guide them to a place where they can do things again.
