### ISSUE TITLE
Cannot return to profile after using "view as"

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1309]
# Bug description
Cannot return to profile after using "view as"

# Steps to Reproduce

1. Go to https://backoffice.bibliodev.ugent.be
2. Click on the user name and choose "view as"
3. Choose someone else to view Biblio as
4. Now try returning to your own profile using the return to button
5. See error

<img width="340" alt="Screenshot 2023-11-14 at 10 03 05" src="https://github.com/ugent-library/biblio-backoffice/assets/1572885/010d4642-cb1f-4b76-a20c-a99f9e55f90b">
<img width="230" alt="Screenshot 2023-11-14 at 10 03 19" src="https://github.com/ugent-library/biblio-backoffice/assets/1572885/eedc2c77-5674-4a80-9cbe-58786383bf23">
<img width="925" alt="Screenshot 2023-11-14 at 10 03 27" src="https://github.com/ugent-library/biblio-backoffice/assets/1572885/2265f019-d5a4-4202-a67d-43fe03e0f01d">

# Expected behaviour
I return to my own profile.

## Automatic testing scenario
When I view Biblio as a different person, and I want to return, I see my own profile again.

### Likelihood
1: Frequent

### Consequences
2: Critical (only librarians)

**Comment by mietcls** [comment]
@verheyenkoen Is this a suitable feature to be tested?

**Comment by verheyenkoen** [comment]
@mietcls Yeah, sure.

**Comment by nics** [comment]
dit heeft iets met MethodOverride te maken denk ik, wacht ik op een branch @verheyenkoen?

**Comment by verheyenkoen** [comment]
@nics Ik zal dan snel een test schrijven eerst.

**Comment by verheyenkoen** [comment]
@nics Failing test added in branch [1309-cannot-return-to-profile-after-using-view-as](https://github.com/ugent-library/biblio-backoffice/tree/1309-cannot-return-to-profile-after-using-view-as)

To execute:
```sh
$ npm install
$ npm run test -- --spec=cypress/e2e/issues/issue-1309.cy.ts
```
