### ISSUE TITLE
Add "Biblio status" to batch operations for librarians

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1310]
# Enhancement
Add "Biblio status" to batch operations for librarians.
_± 500 records need to be set from withdrawn to public._

Notes:
- this needs to happen on the **main branch** and needs to be deployed _before_ the launch.

## Expected behaviour (if we decide to make it a feature)
- [ ] When going to https://backoffice.biblio.ugent.be/publication/batch, I can use an operation to adapt the "Biblio status" of a publication
- [ ] The statuses I can switch it to are `Public`, `Withdrawn` and `Draft`
- [ ] It's impossible to have a publication without a status

## Suggestion
`8701504,status.set,public`
In line with options such as classification https://booktower.gitbook.io/product-docs/producten-en-diensten/biblio-academische-bibliografie-en-repository/handleidingen/batch-operaties#voorbeelden-batch-operaties

We also have a "publication status" so it should not be confused with this.

## Context
Short term: AAM / withdrawn problems in our workflow with helpdesk
Long term: new statuses

**Comment by nics** [comment]
@mietcls you also want lock/unlock

**Comment by mietcls** [comment]
Old information:

## Expected behaviour
- [ ] When going to https://backoffice.biblio.ugent.be/publication/batch, I can use an operation to adapt the "Biblio status" of a publication
- [ ] The statuses I can switch it to are `Public` (Withdrawn and Draft are not needed for this one)
- [ ] It's impossible to have a publication without a status

## Suggestion
`8701504,biblio_status.set,public`
In line with options such as classification https://booktower.gitbook.io/product-docs/producten-en-diensten/biblio-academische-bibliografie-en-repository/handleidingen/batch-operaties#voorbeelden-batch-operaties

**Comment by mietcls** [comment]
@nics no, only the Biblio status. They already are unlocked.

**Comment by nicolasfranck** [comment]
Probably no need to use the translated name `biblio status`. These are keywords, not translations. We set `public` and not `Public`, right?
