### ISSUE TITLE
Add "Locked / unlocked" to batch operations for librarians.

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1311]
# Enhancement
Add "Locked / unlocked" to batch operations for librarians.

## Expected behaviour (if we decide to make it a feature)
- [ ] When going to https://backoffice.biblio.ugent.be/publication/batch, I can use an operation to adapt the "Locked" status of a publication
- [ ] The statuses I can switch it to are `locked` and `unlocked`
- [ ] It's impossible to have a publication without locked or unlocked

![Screenshot 2023-11-14 at 15 24 47](https://github.com/ugent-library/biblio-backoffice/assets/1572885/9644e64c-31ed-4a5a-a46c-c02e32134939)

## Suggestion
`8701504,lock.set,locked`
In line with options such as https://booktower.gitbook.io/product-docs/producten-en-diensten/biblio-academische-bibliografie-en-repository/handleidingen/batch-operaties#voorbeelden-batch-operaties

**Comment by mietcls** [comment]
@nicolasfranck what is the syntax? I cannot seem to reproduce it, I am not sure whether this is because it's broken or because I'm not using the correct syntax.

**Comment by nicolasfranck** [comment]
@mietcls `lock` and `unlock`
