### ISSUE TITLE
[Plato imports] As a librarian, I can follow up on all the to-be-claimed dissertations of researchers

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1327]
# Enhancement
As a librarian, I can follow up on all the to-be-claimed dissertations of researchers.
<img width="1512" alt="Screenshot 2024-04-26 at 11 00 12" src="https://github.com/ugent-library/biblio-backoffice/assets/1572885/cca589a5-6f59-4f9e-9940-fe2cd61db430">

Prototype: https://booktower-ugent-ui.vercel.app/biblio/reviewer/reviewer-suggestions.html

### Overview
- [x] Before dissertations are suggested in Biblio, a duplication check happens on title or identifier whenever possible. If the dissertation is not in Biblio yet, they are suggested to reviewers (see next tasks).
- [x] As a reviewer, I can see which records are automatically suggested from other platforms
  - [x] In a separate tab "Suggestions"
  - [x] When there are suggestions, I can see a notification appear in the sidebar (in line with dashboard)
  ```
    <span class="c-sidebar__icon">
      <i class="if if-draft if--notification if--notification-warning"></I>
    </span>
  ```
  - [x] Paginated (in line with publications and datasets)
- [x] I can see the following metadata:
  - Source (Plato image, see image in comments.)
  - Biblio status (Biblio suggestion via Plato)
  - Type (e.g. Dissertation)
  - Access levels (in line with overview pages)
  - Title
  - Publication year
  - Publisher
  - [x] Authors, supervisors, editors, ...

#### 

Example implementation:
```
<ul class="list-group list-group-flush">
    <li class="list-group-item bg-transparent">
        <div class="w-100">
            <div class="c-thumbnail-and-text align-items-start w-100">
                <div class="c-thumbnail c-thumbnail-1-1 c-thumbnail-img c-thumbnail-small c-thumbnail-lg-large">
                    <div class="c-thumbnail-inner">
                        <img src="path-to-images-/plato-logo.svg">
                    </div>
                </div>
                <div class="c-thumbnail-text">
                    <div class="hstack-md-responsive align-items-start gap-3 w-100">
                        <div class="vstack gap-5">
                            <div class="vstack gap-2">
                                <div class="d-inline-flex align-items-center flex-wrap">
                                    <span class="badge rounded-pill badge-default me-3 my-2">
                                        <span class="badge-circle"></span>
                                        <span class="badge-text">Biblio suggestion via Plato</span>
                                    </span>
                                    <span class="c-subline text-nowrap me-2 pe-3 my-2 border-end">Dissertation</span>
                                    <span class="c-subline ps-2 my-2">Embargoed access</span>
                                </div>
                                <h4 class="list-group-item-title mb-0">Using frequency tagging to investigate social processing in autism</h4>
                                <ul class="c-meta-list c-meta-list-inline">
                                    <li class="c-meta-item">2023</li>
                                    <li class="c-meta-item">Ghent University. Department of Experimental clinical and health psychology</li>
                                </ul>
                                <div class="c-author-list">
                                    <div class="c-author">
                                        <i class="if if-ghent-university" data-bs-toggle="tooltip" data-bs-placement="bottom" aria-label="UGent author" data-bs-original-title="UGent author"></i>
                                        <span>Danna Oomen</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="c-button-toolbar flex-row-reverse flex-lg-row">
                            <a class="btn btn-link btn-link-muted" href="#" type="button" data-bs-toggle="modal" data-bs-target="#deleteSuggestion">
                                <div class="btn-text">
                                    Hide suggestion
                                </div>
                            </a>
                            <a class="btn btn-outline-primary" href="#">
                                <div class="btn-text">Import as draft</div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </li>
</ul>
```

#### Preview

https://github.com/ugent-library/biblio-backoffice/issues/1411

#### Importing
- [x] I can import a suggestion as a draft
  - This is a regular draft, as already implemented (new forms out of scope).
  - Any involved authors or supervisors can see the draft / published record in their search overview.
  - Drafts and published dissertations also appear in the "Recent activity" on the dashboard for the person adding the dissertation and the authors / supervisors connected to the dissertation.
<img width="1176" alt="image" src="https://github.com/ugent-library/biblio-backoffice/assets/1572885/f0912bf6-54b8-48e5-b35f-33b9cfd8ded9">
<img width="468" alt="image" src="https://github.com/ugent-library/biblio-backoffice/assets/1572885/55bf7736-aece-4edd-9320-707f0f002596">

#### Hiding a suggestion
- [x] I can hide a suggestion and get a fail-safe modal
- [x] align/adapt copy
<img width="616" alt="Screenshot 2024-04-26 at 11 00 37" src="https://github.com/ugent-library/biblio-backoffice/assets/1572885/480ff1ac-7475-4282-94c2-80423d90df45">

- [x] We can always, behind the scenes, see which suggestions have been flagged as a duplicate, or have been hidden. We can retrieve them if needed.

```
<div class="modal show" id="deleteSuggestion" tabindex="-1" role="dialog" aria-modal="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <div class="c-blank-slate c-blank-slate-muted">
                    <div class="bc-avatar">
                        <i class="if if-alert"></i>
                    </div>
                    <h4>Are you sure you want to hide this suggestion?</h4>
                    <p>You cannot undo this action.</p>
                </div>
            </div>
            <div class="modal-footer">
                <div class="bc-toolbar">
                    <div class="bc-toolbar-left">
                        <div class="bc-toolbar-item">
                            <button class="btn btn-link">No, cancel</button>
                        </div>
                    </div>
                    <div class="bc-toolbar-right">
                        <button class="btn btn-danger">Yes, hide suggestion</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
```

### Empty state

- [x] When there are no more suggestions left, there is an empty state:
<img width="1512" alt="Screenshot 2023-12-19 at 12 26 42" src="https://github.com/ugent-library/biblio-backoffice/assets/1572885/74524dbf-13f7-418e-976e-c61ff753be65">

https://biblio-backend-ugent-prototype-ugent-library.vercel.app/biblio/reviewer/reviewer-suggestions--empty.html

Example implementation:
```
<div class="u-scroll-wrapper__body w-100 p-6">
    <div class="c-blank-slate c-blank-slate-default c-blank-slate-large">
        <img class="mb-4" src="/images/inbox-illustration.svg" alt="" width="auto" height="32">
        <h3 class="c-blank-slate-title">No suggestions, all caught up!</h3>
    </div>
</div>
```

### Optional
- Search (in line with publications and datasets)
- Sort (in line with publications and datasets, keep in mind https://github.com/ugent-library/biblio-backoffice/issues/1364)

## Out of scope
- Flagging of duplicates or faulty suggestions (later)
- Tabs to differentiate between "to import", "imported", "rejected" (by whom and why)

## Context
- This is a first small step in rolling out Plato suggestions
- Administrative support will not be able to see these import suggestions, as we see the researcher as responsible to upload information into Biblio. However, not every research group is organised for this, and administrative support takes over this task. We need our reviewers to be a fail-safe here.
- Groups that are organised differently still are at risk of losing track of dissertations when people have left. We need our reviewers to be a fail-safe here.

**Comment by mietcls** [comment]
Plato SVG image:  ![plato-logo](https://github.com/ugent-library/biblio-backoffice/assets/1572885/9e2c0860-83cb-491b-8b15-d2a3ba6de577)

**Comment by nics** [comment]
done
