### ISSUE TITLE
Filtering and dashboard broken

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1328]
# Bug description
Filtering and dashboard broken

[UNDER CONSTRUCTION]

Related
- https://github.com/ugent-library/biblio-backoffice/issues/517 [With librarians request knowledge institutions]
- https://github.com/ugent-library/biblio-backoffice/issues/601
- https://github.com/ugent-library/biblio-backoffice/issues/601

Context

> Binnen "Publications - Faculties" => UGent was oorspronkelijk toegevoegd voor alles wat nog geen faculty had, of enkel gekoppeld was aan "UGent department".
> Dan kwam dat "Publications - SOCS" er later bij. Die filter is daar gewoon over genomen. SOCS worden ook in het faculty veld geïndexeerd. Dan krijg je GUK, UZGent en VIB samen met PS of LW in één zak. UGent staat daar bij om dezelfde reden als bij "publication - faculties" => alles wat geen SOC heeft maar wel gekoppeld aan "UGent".  Daardoor komt het allemaal nogal bizar over.

- filters werken niet altijd
- All is niet all
- De UGent kolom moet verduidelijkt worden, of ergens anders ondergebracht worden – en moet getoond worden in de filters als je er op filtert zodat je weet dat je maar een selectie ziet
- Niet alle departementen worden getoond in het dashboard
- Niet alle departementen worden getoond in de filters

# Steps to Reproduce

1. Go to https://backoffice.biblio.ugent.be and visit the dashboard https://backoffice.biblio.ugent.be/dashboard/publications/faculties
2. Click on the top left number under "All". You will get this query: https://backoffice.biblio.ugent.be/publication?f%5Bclassification%5D=U&f%5Bfaculty_id%5D=CA&f%5Bfaculty_id%5D=DS&f%5Bfaculty_id%5D=DI&f%5Bfaculty_id%5D=EB&f%5Bfaculty_id%5D=FW&f%5Bfaculty_id%5D=GE&f%5Bfaculty_id%5D=LA&f%5Bfaculty_id%5D=LW&f%5Bfaculty_id%5D=PS&f%5Bfaculty_id%5D=PP&f%5Bfaculty_id%5D=RE&f%5Bfaculty_id%5D=TW&f%5Bfaculty_id%5D=WE&f%5Bstatus%5D=public
Publication count:
![Screenshot 2023-11-24 at 13 17 19](https://github.com/ugent-library/biblio-backoffice/assets/1572885/df15c992-4774-4476-b2bb-d550cd77c50a)

3. Select the faculty dropdown. See not all faculties have been selected.
![Screenshot 2023-11-24 at 13 17 43](https://github.com/ugent-library/biblio-backoffice/assets/1572885/f1de88b3-8c1f-44c6-8ab4-9ed6db327367)

4. Now add "VIB". See the results not add in the below results
https://backoffice.biblio.ugent.be/publication?q=&f%5Bclassification%5D=U&f%5Bstatus%5D=public&f%5Bfaculty_id%5D=CA&f%5Bfaculty_id%5D=DS&f%5Bfaculty_id%5D=DI&f%5Bfaculty_id%5D=EB&f%5Bfaculty_id%5D=FW&f%5Bfaculty_id%5D=GE&f%5Bfaculty_id%5D=LA&f%5Bfaculty_id%5D=LW&f%5Bfaculty_id%5D=PS&f%5Bfaculty_id%5D=PP&f%5Bfaculty_id%5D=RE&f%5Bfaculty_id%5D=TW&f%5Bfaculty_id%5D=WE&f%5Bfaculty_id%5D=VIB
![Screenshot 2023-11-24 at 13 17 56](https://github.com/ugent-library/biblio-backoffice/assets/1572885/bab68f74-e40e-49ae-81ca-bfa005c8748c)
![Screenshot 2023-11-24 at 13 18 10](https://github.com/ugent-library/biblio-backoffice/assets/1572885/eb8e2150-ffeb-4034-81cf-c99ad547904d)

## Expected result:

- [ ] The column all in the dashboard combines *all* possibilities under faculty.
![Screenshot 2023-11-24 at 13 55 36](https://github.com/ugent-library/biblio-backoffice/assets/1572885/b714cfc4-86f2-47f5-acbb-7c01d70b781f)
- [ ] Missing faculty KR01 is also added to faculties and the dashboard (https://telefoonboek.ugent.be/nl/korea/kr01)
![854aa645-e1a8-44a6-a4e4-10785ec99032](https://github.com/ugent-library/biblio-backoffice/assets/1572885/0cc89c3c-3e0e-491c-847e-a3dfc1e56ddd)
- [ ] In the dashboard, you can see all of the faculties that you can find under the filter faculties (also VIB, ...)

**Comment by nicolasfranck** [comment]
@mietcls apparently that dashboard has a different opinion about what "all faculties" mean than the list of publications (i.e. real faculties of ugent). Besides, organizations like "VIB" and "UZGent" are no faculties, but are merely put there in that facet because there is no other place for it.

**Comment by mietcls** [comment]
Need to rewrite this one
