### ISSUE TITLE
which publications/datasets can I add as related resources?

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backoffice#133]
**Describe the improvement**
For both publications and datasets, related resources can be added. Can I select from all my datasets/publications or only my registered datasets/publications or only the datasets/publications that I am an author/creator of? Would it be possible to also add datasets of others (e.g. in the case that admin support staff needs to make the link of a dataset to a publication but has not registered the dataset her/himself)? 
Currently, I can select from all my datasets/publications, both draft and published.

**Screenshots**
![image](https://user-images.githubusercontent.com/72742841/143227428-067102c0-9a35-41c2-a3c8-81f25b4c3fb7.png)

**Comment by mietcls** [comment]
Right now you can add any dataset or publication that is public. Drafts are not possible, nor withdrawn.
