### ISSUE TITLE
Can't delete a project with a non-IWETO ID from a publication

### ISSUE THREAD

**Issue by netsensei** [ugent-library/biblio-backoffice#1332]
# Bug description

Some projects aren't identified by a string that consists solely of alphanumeric characters (IWETO id's) but by a string that string which contains non-alphanumeric characters as well.

The BOF id contains the `/` character which causes breaks removing a project from a publication. Clicking on "remove from publication" doesn't work and yields a `404` response code in the console.

This issue affects 365 projects with a BOF id.

# Steps to Reproduce

1. Go to the detail page of a publication.
2. Hit "Add a project"
3. Look for `What Does Style Do? Neoclassicism and the Performativity of Style` with BOF id `BOF/STA/201909/006`.
4. Add the project to the publication.
5. Now try to remove the project from the publication. Notice how it fails.

Caused by:

The `/` character in an identifier isn't URL encoded.

## Automatic testing scenario

N/A

### Likelihood
*How often does this happen? 3: Occasional*

### Consequences

*What's the impact? 3: Marginal*

# Expected behavior

I should be able to remove a project regardless of the characters used in the id to identify said project.

# Screenshots

![image](https://github.com/ugent-library/biblio-backoffice/assets/105355/14194cbd-a1bd-42f0-b294-d240def50992)

# Additional context

**Comment by nicolasfranck** [comment]
I saw this problem before, back when we used Gorilla.

**Comment by mietcls** [comment]
Related https://github.com/ugent-library/biblio-backoffice/issues/1325
