### ISSUE TITLE
[presence API] Show who is present and editing a record

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1336]
# Enhancement
Show who is present and editing a record

![Screenshot 2023-12-05 at 09 53 16](https://github.com/ugent-library/biblio-backoffice/assets/1572885/85335de1-9bf7-476a-bef5-6d985ec88f18)
![Screenshot 2023-12-05 at 09 53 44](https://github.com/ugent-library/biblio-backoffice/assets/1572885/dbe1732a-618a-47da-8415-619b11b681f1)
https://biblio-backend-ugent-prototype-git-bootstr-307d84-ugent-library.vercel.app/biblio/researcher/publications/detail/full-view.html

## Success criteria
- [ ] When there is _more than one_ browser window connecting to the same record...
  - [ ] I can see a badge appear for each of the browser connection
  - [ ] Each badge contains the initials (first- and last name if available, drop whichever is not available) of the person looking at that record.
  - [ ] When I hover over that badge, I see the name of the person looking at the record
- I can see activity happening live:
  - [ ] When I am looking at a record, and someone else opens a browser window that looks at the same record, a new badge appears instantly.
  - [ ] When a person leaves, or I close one of my browser connections, the badge for this connection disappears instantly.

**Rules**
- When I am alone in a record – I do not see any badge.
_Do not flood people with information that is irrelevant or a given_
- When I am looking at a record in two browser windows – I see two badges with my own information
- When I am looking at a record in three browser windows – I see three badges with my own information
- When one or more person is looking at the same record – I see a badge appear for each person with their information

**Comment by verheyenkoen** [comment]
Removed the "cypress-test-requested" label here since this requires two separate simultaneous sessions in separate windows, which is not something Cypress can do.

**Comment by mietcls** [comment]
Duplicate of #1229 which will be picked up later
