### ISSUE TITLE
Make breadcrumb path available in topbar for easy navigation

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1337]
# Enhancement
Make breadcrumb path available in topbar for easy navigation.
This is preparation to reach multiple interfaces.

<img width="559" alt="Screenshot 2023-12-05 at 10 00 43" src="https://github.com/ugent-library/biblio-backoffice/assets/1572885/05163bce-d0ce-4ec3-b4ce-cd4980015be3">

https://biblio-backend-ugent-prototype-git-bootstr-307d84-ugent-library.vercel.app/biblio/researcher/publications/detail/full-view.html

## Expected behaviour
For each step down the line – I see a breadcrumb appear. When I want to go back one step, I can click the breadcrumb. 

Current steps:
- Ghent University Library
  - Biblio
    - Dashboard (researcher)
    - Dashboard (librarian)
    - Publications
      - Publication detail
      - New publication (we do not drill down further as we will make a different import flow later)
        - Import via Web of Science
        - Import via identifier
        - Add manually
        - Import via BibTex
    - Datasets
      - Dataset detail
      - New dataset (we do not drill down further as we will make a different import flow later)
        - Import via identifier
        - Add manually
    - Batch import

Out of scope: import flow

**Comment by nicolasfranck** [comment]
Step "biblio" seems maybe out of scope? That suggests that we are going to roll out the same breadcrumb for all of our applications

**Comment by mietcls** [comment]
This suggestion is indeed correct. We're preparing our application to be able to navigate to different services we offer as a librarty. This ties into the "layers" story we've set out from the beginning (even before I arrived). If you want I can explain this better in a call, as this goes way too far to include in this issue.

**Comment by verheyenkoen** [comment]
This ticket probably outdates the Plato imports/suggestions stuff, so I added a breadcrumb there as well:

![image](https://github.com/user-attachments/assets/5784aa78-202f-4069-9e06-225e4edfec20)
