### ISSUE TITLE
Project service feedback

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1342]
# Feedback

Outcome from testing the new project service

## Behaviour
- Every time when you search and remove your search query, a different result is shown. This is quite strange and unexpected behaviour. e.g. after two searches on different words:
  - <img width="1512" alt="Screenshot 2023-12-11 at 16 58 50" src="https://github.com/ugent-library/biblio-backoffice/assets/1572885/a66a66b6-015f-4c02-94aa-38f0355c718f">
  - <img width="1508" alt="Screenshot 2023-12-11 at 16 59 13" src="https://github.com/ugent-library/biblio-backoffice/assets/1572885/98b66906-c133-4025-95fe-0551f497988f">

## Content optimisations
- Right now the abstracts are rendered with html tags. Would need to write down possibilities; only live discussions have happened about this. Please document your insights below or in a new issue.
- Missing information (gotten some input from others):
  - EU project ID (maybe not missing?)
  - EU funding programme (e.g. Horizon Europe)
  - FWO / BOF / VLAIO funding if available? + funding type
  - Projects without titles could be called: "Untitled project". However – is there a way to spot and enhance them? <img width="1449" alt="Screenshot 2023-12-11 at 17 07 42" src="https://github.com/ugent-library/biblio-backoffice/assets/1572885/e7e6ae0b-f359-49c6-81fd-fc875a15dfbf">

## Design optimisations
- There is not always an acronym available. When missing, there should be graceful degradation. Now it is imbalanced

## Information needed in the OAI
- EU project ID
- FWO / BOF / VLAIO ID

**Comment by netsensei** [comment]
**Behavior**

If the user leaves the input box empty, the default state should be a message along the lines of "Please type a few keywords so we can suggest projects to you". I don't think we have that right now.

**Sanitization**

See: #1344

**Missing information**

Missing EU information 
=> we're still working with information from the old authority database. This database does enrich projects with EU information, but the enrichment isn't refreshed regularly.  We plan on adding this once the new pipeline with up-to-date GISMO data has been put into place.

FWO / BOF / VLAIO funding if available? + funding type 
=> we currently don't have that information in the authority database. If this info needs to come from external sources, we'll need to identify them and consider whether or not it's feasible to add them as enrichments; and what the added value would be in doing so from the perspective of users looking at a publication record in the UI and OAI. (=> How much extra metadata do we need / want to pull into a publication record that doesn't directly describes a publication record? What's the scope here?)

Projects without titles could be called: "Untitled project". However – is there a way to spot and enhance them?
=> I can add a `[missing project name]` placeholder

**Comment by mietcls** [comment]
I will create a blank state; however the results are also different for each search, even if you use the same search query:
<img width="1490" alt="Screenshot 2023-12-12 at 14 55 56" src="https://github.com/ugent-library/biblio-backoffice/assets/1572885/4c903b28-da3e-49d8-a5bd-bdba2887735a">
<img width="1500" alt="Screenshot 2023-12-12 at 14 56 01" src="https://github.com/ugent-library/biblio-backoffice/assets/1572885/79511193-07c6-41a3-ad70-8aa9eeff20ae">
<img width="1512" alt="Screenshot 2023-12-12 at 14 56 05" src="https://github.com/ugent-library/biblio-backoffice/assets/1572885/de8b54b3-0f38-47d9-9367-dff1b177181a">

**Comment by netsensei** [comment]
Short status update: this issue is blocked because of #1380. We intend to move the projects service into biblio backoffice proper, using the new architecture that follows what we're currently doing in the people service. So, once that's done, we can revisit this issue.

**Comment by mietcls** [comment]
Stale, might pick this up later.
