### ISSUE TITLE
BibTeX does not work any longer when exporting from scopus or other platforms

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1343]
# Bug description
BibTeX does not work any longer when exporting from scopus or other platforms:
- when the file is not formatted in the correct way
- when you upload a file that _is_ formatted in the correct way after an error already appeared

**Needs to be fixed in production.**
If we cannot fix this in a reasonable amount of time [TBD depending on suggestion], we have to hide this feature for now. It causes a lot of work and helpdesk requests right now for both the Biblio team and our team.

# Steps to Reproduce
1. Go to Scopus https://www.scopus.com/search/form.uri?display=basic&clear=t#basic and download one or more records into a file
2. Go to http://backoffice.bibliotest.ugent.be, dev or production – it does not work any longer.
3. Upload the file
5. If you now upload a file that _is correct_, it fails anyways.

Here is a collection of files that _should_ work (old files that used to work, exports from scopus and other universities): https://ugentbe-my.sharepoint.com/:f:/r/personal/miet_claes_ugent_be/Documents/Biblio%20Back%20Office/Biblio%20Back-Office%20Features/Bugs/files%20that%20should%20work%20from%20bibtex?csf=1&web=1&e=BKUFQX

## Success criteria
🚧 To be extended – please add other reasons why .bib fails 🚧

_Not sure which ones are already fixed, because I cannot test any of the previously working examples._

- [ ] Escape `@`s in emails
- [ ] Remove trailing comma's
- [ ] Remove spaces in field names
- [ ] Strip off preamble from exports, e.g.
```
Scopus
EXPORT DATE: 12 December 2023
```

### Other expectations
- [ ] Works with .txt and .bib

### Other solutions

If there is a generic BibTeX converter somewhere, and we can decide which BibTeX type we need; we could ask people to run it through the converter first. e.g. "LaTeX escaping" – or choose specific parameters:
https://flamingtempura.github.io/bibtex-tidy/index.html

## Automatic testing scenario
TBD
Write a high-level way to test this with Cypress if applicable.

### Likelihood
1: Frequent

### Consequences
2: Critical

## Context
Old issue, where it still used to work _a bit_
https://github.com/ugent-library/biblio-backoffice/issues/801

It is not an option to remove this functionality as it is used by researchers that are moving from one university to ours – and certain administrative users.

**Comment by netsensei** [comment]
@nics @nicolasfranck 

Additionally, I've also discovered a potential caching bug.

How to reproduce:

1. Upload a valid bibtex file, notice how it will successfully convert to publications.
2. Change the bibtex file by adding an unescaped `@` in one of the fields, rendering it invalid.
3. Go back to "add publications" and select "bibtex", re-upload the file. Notice how the upload fails.
4. Change the bibtex file. Remove the unescaped `@` character, rendering the file valid again.
5. Go back to "add publications" and select "bibtex", re-uplaod the file. **notice how the upload keeps failing**

Variations on this theme:

* Do the first two uploads in Firefox, the last upload in Chrome. This excludes browser cache: notice how the upload fails in Chrome as well, even though it's a valid file.
* Make a copy of the valid file (e.g. `mv test.bib test2.bib`) and re-upload via firefox or chrome: notice how it fails (this excludes file name being an issue)

Now to do this to fix this issue:

1. Shutdown the server process (ctrl-c)
2. Restart the server (`reflex -d none -c .reflex.conf`)
3. Go into chrome or firefox, hit "add publications", "bibtex" and re-upload the file. **Notice how the upload succeeds**

So, my suspicion is that some kind of reference to the uploaded data is somehow accrued in memory and doesn't get flushed when decoding fails.

**Comment by nicolasfranck** [comment]
Seems like an older problem, which was found before: https://github.com/ugent-library/biblio-backoffice/issues/462

**Comment by nics** [comment]
@netsensei you could be right, the underlying yacc parser is reentrant but probasbly not threadsafe: https://github.com/nickng/bibtex/blob/381e70ce030e5ed7953852535518c878ece88939/bibtex.y.go#L19

**Comment by netsensei** [comment]
@nics Yes. I was looking at the same variable just now, wondering how threadsafe this is. (Likely not)

**Comment by nics** [comment]
fyi writing a better parser based on the Perl one here: https://github.com/ugent-library/bibtex
