### ISSUE TITLE
Content sanitization

### ISSUE THREAD

**Issue by netsensei** [ugent-library/biblio-backoffice#1344]
# Enhancement

Our data model includes full text fields with data which either is imported from external sources, or entered by a user. These fields  may contain HTML tags and potentially executable code. We need to consider:

* Right now we escape HTML tags, but we also may consider rendering HTML which would be useful for e.g. hyperlinks.
* Content may be tag-heavy making them hard to read e.g. copied from an MS Office file.
* Content may contain tags like `<style>` and `<script>` which may cause styling and scripting issues.

Sanitization is a key step before we display content to the end-user.

## Fields

Currently, this issue appears on the project description & message fields. But it's also possible to add tags e.g. in the link description field. 

We'll need to identify all fields that potentially require sanitization.

## How

[Bluemonday](https://github.com/microcosm-cc/bluemonday) is a fast and secure sanitization library. We could add it as a separate template function and call that for applicable fields.

Bluemonday comes with a few default policies, but it's also possible to create a custom policy defining which elements are allowed, and which will be filtered from the output.

**Considerations**

* Filtering out tags doesn't guarantee that content will be shown in a readable format to the end-user. Especially since we don't control how content is created and imported from outside sources. We'll need to test this thoroughly.
* We could implement different policies for different types of fields / input.
* HTML escaping is still a valid fallback approach when it comes to string fields that shouldn't contain tag-like structures at all (e.g. keywords)

**Comment by mietcls** [comment]
Two questions:
- Did this work hand-in-hand with markdown (e.g. for messages)?
- Can we also use this for abstracts (and lay summaries in the future)?

We can use this for different parts of the app in this case.

**Comment by nicolasfranck** [comment]
@mietcls markdown, at the least the one we would allow our users to enter, has to be converted yet to html, so there we do not risk executing possibly malicious code (e.g. javascript). That being said, in markdown, also html tags are allowed. Not sure about tags like style of javascript, but I think not.

I think Matthias is talking about html data as imported from external sources (description from projects?). HTML like that not only possibly imports malicious code (which I doubt), but may also break
layout.

**Comment by mietcls** [comment]
I'm referring to an earlier conversation, I think @netsensei knows what I mean – there is a nice toolchain he referred to.

**Comment by netsensei** [comment]
@mietcls 

>  Did this work hand-in-hand with markdown (e.g. for messages)?

This works hand in hand with the [blackfriday](https://github.com/russross/blackfriday) markdown parser.  

1. Users post are able to post whatever markdown they want; 
2. Blackfriday will convert the markdown to html
3. Bluemonday filters the html rendered content and only allows the html tags defined in a whitelist / policy.

> Can we also use this for abstracts (and lay summaries in the future)?

Yes. Basically, for every field that potentially may contain unsafe html tags. abstracts, lay summaries, etc. anything that researchers may input, or may be imported from a 3rd party source.

> One requirement for now that is useful for projects, abstracts and messages: links

This can be implemented on short notice.

**Comment by mietcls** [comment]
The stripping probably won't be necessary as the reviewers will do this in any case. That means we can stick to your first idea. Looking forward to seeing a first prototype to test and play with 🤓, and get some insights from the reviewers 🧐

**Comment by mietcls** [comment]
Clarifying expectations towards everyone: first build a prototype to gather feedback from our team and people working in Biblio, then build the actual thing.

**Comment by nics** [comment]
@nicolasfranck we should store the field exactly as we receive it and only strip on display, so no stripping on import.
I know this is less efficient, but it's important we keep the original data.

**Comment by mietcls** [comment]
Okay, could you try both ways in two quick prototypes and write down the pros and cons of the implementation @nicolasfranck? This way it'll be easier to discuss.

**Comment by nicolasfranck** [comment]
Also: non HTML tags are also used in the source texts.

e.g. https://biblio.ugent.be/publication/8758495

where `<ae>/<ē>` and `<ae>/<ĕ>` are phonetic transcriptions.
Now they are accidentally shown the way they are intended by
escaping them. Without the html escaping they would be invisible
as they are not known html tags.

That is probably what you mentioned @nics when you referred to mathematical signs that need to readable too? Not sure if html strippers can make that distinction.

**Comment by nics** [comment]
see #1696
