### ISSUE TITLE
[People] Remove models.ParseURN() dependency in people-service / backoffice

### ISSUE THREAD

**Issue by netsensei** [ugent-library/biblio-backoffice#1346]
# Enhancement

The people service integration contains this code pattern:

```
urn, _ := pmodels.ParseURN(id)
switch urn.Namespace {
case "orcid":
	p.ORCID = urn.Value
case "biblio_id":
	p.ID = urn.Value
case "historic_ugent_id":
	p.UGentID = append(p.UGentID, urn.Value)
case "ugent_username":
	p.Username = urn.Value
}
```

This code block heavily leans on people-service models as a public interface and wires them into the backoffice. This pattern causes a leaky abstraction and creates tight dependencies between applications e.g. if the `models.URN `model in people service changes or gets removed, this will break Biblio Backoffice.

From an architecture perspective, treating application methods and structs as a public library is a practice that needs to be avoided at all costs.  The only reason why people-service is imported as a library is to reuse its OpenAPI generated client, which is the only part that we'd treat as public library for other applications to be used.

Moreover, this use of a model to capture a part of urn formatted strings is unnecessary and can be avoided.

## Expected behavior

Alternate implementation:

```
ids := []string{"urn:orcid:12:::34"}

urns := make(map[string]string)
for _, id := range ids {
	parts := strings.Split(id, ":")
	if len(parts) < 3 {
		continue
	}

	urns[parts[1]] = strings.Join(parts[2:], ":")
}

if val, ok := urns["orcid"]; ok {
	log.Println(val)
}
```

Alternatively, URN's are only used in the people / project service to identify entities via API calls. Parsing URN's correctly is non-trivial. Consider retrieving the original value from the people service via a separate field; instead of trying to parse URN's.

**Comment by nicolasfranck** [comment]
agreed. Can you make a PR?

**Comment by netsensei** [comment]
I suggest you make a PR. I merely reviewed your code.
