### ISSUE TITLE
Move GUK from SOCs to faculty dashboard

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1349]
# Enhancement
Move GUK from SOCs to faculty dashboard

<img width="1560" alt="291589463-c9497727-ad20-4ae0-a394-c97e68a0e0e8" src="https://github.com/ugent-library/biblio-backoffice/assets/1572885/45baeb34-1dd4-4e7b-8a2b-7160749c186e">

- [ ] GUK has been moved from SOCs to faculty dashboard
- [ ] the totals are adapted for each dashboard as well

It is now on the "SOCs" dashboard, this does not make sense.

**Comment by nicolasfranck** [comment]
@mietcls the space becomes very crowded when I add GUK to the list:

<img width="1259" alt="Screenshot 2023-12-20 at 09 51 30" src="https://github.com/ugent-library/biblio-backoffice/assets/494636/3f4d9f1d-243d-466c-92e8-783c7fcb1268">

The scrollbars are there yes, but at the bottom

**Comment by mietcls** [comment]
That's fine, that's what the scrollbars are for. I'll fix it if someone complains or it doesn't work out..
