### ISSUE TITLE
Inconsistency in "View Online" Button and PDF Attachment

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1351]
# Bug description
Inconsistency in "View Online" Button and PDF Attachment:
Sometimes the "view online" button does not show up (via RBIB)

## Description

All examples below have a PDF attached in Biblio:

### Unexpected behaviour
"View online" button _not_ showing for https://lib.ugent.be/catalog/pug01:01H2B16SDG99NAFC8XDWQQF4GZ
![screenshot_2023-12-22_at_09 46 26](https://github.com/ugent-library/biblio-backoffice/assets/1572885/1f54d5c0-c1c0-46b3-8ef9-91be4278ee5f)
_This record has not been merged yet in the catalogue, it will be in the future with https://lib.ugent.be/en/catalog/pug01:01H2AGF5FKPQA9027Z75CS0C2W_

### Expected behaviour
"View online" button showing for https://lib.ugent.be/catalog/rug01:003164665
![screenshot_2023-12-22_at_09 46 18](https://github.com/ugent-library/biblio-backoffice/assets/1572885/64c28126-7005-43e5-9b7a-abcfdb194632)
Other example, a pure, non-merged record: https://lib.ugent.be/catalog/pug01:01HF3QYKHC5TYHA525RCSYYKRY

### Likelihood
How often does this happen?
4: Remote

### Consequences
What's the impact?
4: Negligible

**Comment by nicolasfranck** [comment]
Cause: https://github.ugent.be/Universiteitsbibliotheek/lludss-import/blob/master/lib/Catmandu/Importer/Biblio.pm#L201

File are not considered if the classification is equal to `B3`. Not sure what that means

**Comment by nics** [comment]
@phochste do you know why?

**Comment by nicolasfranck** [comment]
Related: https://github.com/ugent-library/biblio-backoffice/discussions/1199

**Comment by mietcls** [comment]
Closing for now, will create a new ticket if there is a solution available.
One question, how is #1199 related?
