### ISSUE TITLE
Google indexes backoffice PDF links

### ISSUE THREAD

**Issue by netsensei** [ugent-library/biblio-backoffice#1369]
# Enhancement

Not sure if this is a bug, but it's certainly an enhancement.

When searching Google, I can find direct download links to the PDF's in biblio. These links aren't frontoffice links: they are backoffice links.

e.g. https://backoffice.biblio.ugent.be/download/4302335/4302336 instead of https://biblio.ugent.be/publication/4302335/file/4302336.pdf

## Steps to reproduce

1. Go to ['https://www.google.com/search?client=firefox-b-d&q=site%3Abackoffice.biblio.ugent.be#ip=1'](https://www.google.com/search?client=firefox-b-d&q=site%3Abackoffice.biblio.ugent.be#ip=1)
2. See backoffice links

You can also see backoffice link going just searching for search terms from google with the `site:biblio.ugent.be` modifier: e.g. [https://www.google.com/search?q=site%3Abiblio.ugent.be+goe+juf](https://www.google.com/search?q=site%3Abiblio.ugent.be+goe+juf)

## Expected behavior

I don't see backoffice download links for PDF's in Google.

## Additional context

Assuming the backoffice application is exactly that: a backoffice application; I presume we don't want to see any references to the backoffice in public search engines.

**Comment by nicolasfranck** [comment]
cf. https://developers.google.com/search/docs/crawling-indexing/301-redirects

Apparently, when using permanent redirects (301), the resolved url is what you'll see in the search results. Not if you use a temporary redirect (302)

**Comment by nics** [comment]
Or we can just reverse proxy

**Comment by nicolasfranck** [comment]
@nics well yes, and it is already easy to add as the resolving is done statically by nginx:

```
location ~ "^/publication/([0-9A-Za-z]+)/file/([0-9A-Za-z]+)(\..+)?$" {
    return 301 "https://backoffice.biblio.ugent.be/download/$1/$2";
}
```

to

```
upstream backend {
  server backend.biblio.ugent.be;
  keepalive 2;
}
location ~ "^/publication/([0-9A-Za-z]+)/file/([0-9A-Za-z]+)(\..+)?$" {
    proxy_pass http://backend/publication/$1/$2;
}

```

**Comment by nics** [comment]
@nicolasfranck can you make a redmine issue?

**Comment by nicolasfranck** [comment]
@netsensei file links generated from biblio are now proxied. The backoffice links are still available too of course.

**Comment by nicolasfranck** [comment]
Reverted in the nginx configuration for now. URL's redirect now back to the backoffice links.
I did not consider that either `X-Forwarded-For` or `X-Real-IP` should be processed and trusted by
that ingress traefik node, which luckily does not happen automatically. Best to revisit this
when migrated to the dict infrastructure where apache is used.

**Comment by netsensei** [comment]
@nicolasfranck We've migrated to the new infra. Is this still working as intended?

**Comment by nicolasfranck** [comment]
works as expected in new environment
