### ISSUE TITLE
Make created, edited and system update timestamp more informative.

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1370]
# Enhancement
Make created, edited and system update timestamp more informative.

Please use the new card layout, if it is not in main yet, please use dev.

## Expected behaviour
Right now the text says "2 months ago". This is not helpful to researchers nor reviewers. They need to be able to see validation of their actions and be able to figure out when something went wrong.

Current:
![Screenshot 2024-02-07 at 10 58 15](https://github.com/ugent-library/biblio-backoffice/assets/1572885/97186f2b-4e8a-4c72-acfe-a67e6722f674)

Expected:
![Screenshot 2024-02-07 at 10 54 11](https://github.com/ugent-library/biblio-backoffice/assets/1572885/39bbd464-194a-4e1b-b735-34ddcd2f495f)
- Created DD/MM/YYYY hh:mm by _name_
- System update DD/MM/YYYY hh:mm
- Edited DD/MM/YYYY hh:mm by _name_

## Context
- Related improvements: 
  - https://github.com/ugent-library/biblio-backoffice/issues/1365
  - https://github.com/ugent-library/biblio-backoffice/issues/1364
- Which timezone to use: https://github.com/ugent-library/biblio-backoffice/issues/935

# Automatic testing scenario
Not sure how to test this one, but seems useful @verheyenkoen?

**Comment by verheyenkoen** [comment]
FYI: For publications/datasets with a system update (as last edit), you don't see the last human edited time but this:

> Created 18/03/2024 10:40 by Biblio Researcher. System update 18/03/2024 11:01. Last edit by Biblio Librarian.

If the last edit was a human edit, you see this:

> Created 18/03/2024 10:48 by Biblio Researcher. Edited 18/03/2024 10:48 by Biblio Researcher.

**Comment by verheyenkoen** [comment]
Update: format should be "YYYY-MM-DD HH:mm", not "DD/MM/YYYY HH:mm".
