### ISSUE TITLE
Author not recognised as UGent author in front office

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1371]
# Bug description
Author not recognised as UGent author in front office: https://biblio.ugent.be/person/F619163E-32EC-11E4-9DAC-2B5CB5D1D7B1
- Cannot find him in the phone book either, but he is UGent affiliated according to an other user, to `WE14`
- Found this on GISMO: https://research.ugent.be/web/person/benjamin-cappe-0/nl with the description "Deze persoon heeft niet langer een onderzoeksaffiliatie met Universiteit Gent."
- We do see him marked in blue in record [01H5A1X0B800G5NDRB1DJXGKDD](https://backoffice.biblio.ugent.be/publication/01H5A1X0B800G5NDRB1DJXGKDD?redirect-url=%2Fpublication%3Fq%3D01H5A1X0B800G5NDRB1DJXGKDD%26sort%3Ddate-updated-desc&show=contributors), but the department is missing and there's no UGent affiliation.

![Screenshot 2024-02-07 at 14 25 36](https://github.com/ugent-library/biblio-backoffice/assets/1572885/a290384d-513c-4269-81b9-0849c1f30ac4)

# Steps to Reproduce
1. Go to back office record: https://backoffice.biblio.ugent.be/publication/01H5A1X0B800G5NDRB1DJXGKDD?redirect-url=%2Fpublication%3Fq%3D01H5A1X0B800G5NDRB1DJXGKDD%26sort%3Ddate-updated-desc&show=contributors
2. See author assigned as UGent author, see department missing
4. Go to front office: https://biblio.ugent.be/publication/01H5A1X0B800G5NDRB1DJXGKDD
5. See non-UGent affiliation (also the case for other records)

**Comment by nicolasfranck** [comment]
Right now the list of affiliations is marked as follows in the biblio frontend:

* marked as member of ugent if there is a list of departments in ldap attribute `departmentnumber` assigned (empty). See https://github.ugent.be/Universiteitsbibliotheek/biblio/blob/master/views/person/vcard.tt#L14
* marked as member of uzgent if ldap attribute `objectclass` is `uzEmployee`. See https://github.ugent.be/Universiteitsbibliotheek/biblio/blob/master/views/person/vcard.tt#L28

This person is indeed still active in ldap, but there is nothing that marks him as a member of any department. e.g. objectclass is `["ugentFormerStudent", "ugentPerson"]`

**Comment by mietcls** [comment]
If he's an UGent member, that should also show up in the back office right?
