### ISSUE TITLE
Administrative support staff cannot see linked datasets/publications in a record if they are not assigned

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1372]
# Bug description
Administrative support staff cannot see linked datasets/publications in a record if they are not assigned.
Needs to be fixed in main.

- [ ] When closing this: Miet needs to inform Evelien. Ping Miet

# Steps to Reproduce

1. Go to https://backoffice.biblio.ugent.be/publication/01HMBCF80GVRGEKWH815G4MM3M?redirect-url=%2Fpublication%3Fq%3D01HMBCF80GVRGEKWH815G4MM3M%26sort%3Ddate-updated-desc
2. See linked datasets
3. View as https://telefoonboek.prd.rad.ugent.be/nl/people/801002035845
4. You cannot see the datasets

View as librarian:
<img width="1512" alt="Screenshot 2024-02-07 at 17 29 52" src="https://github.com/ugent-library/biblio-backoffice/assets/1572885/2c830da8-4f86-44ca-b2d1-66cd97a3db32">

View as [editor](https://telefoonboek.prd.rad.ugent.be/nl/people/801002035845):
<img width="1512" alt="Screenshot 2024-02-07 at 17 30 30" src="https://github.com/ugent-library/biblio-backoffice/assets/1572885/0aaaed53-2c25-4187-a42a-aae85a7a1396">

## Expected result

You can always see the linked datasets and publications inside a record that you are allowed to see, regardless of your role.

- rule 1: we always show the linked objects a user has the right to view, regardless of their current role
- rule 2: if there are linked objects that a user has no right to view, we show a version without links, you can only remove the object
- rule 3: we allow users to link objects if they have the right to edit the record they are currently editing and the right to view the object they are linking

I suggest not blocking the link to datasets/publications for now, so people can easily check whether it is the correct record that is linked.

**Comment by mietcls** [comment]
> By "not assigned" you mean:
> 
> - none of the related datasets mention this person in the list of contributors
> - this person is neither the creator nor a curator

Yes

> Why  would this person be able to see these datasets?

Because they need to complete the records by adding the metadata. Datasets can be metadata for publications and vice versa. They can already look through the different records when clicking "Add dataset" for instance, so this is not strange to show it.

**Comment by nicolasfranck** [comment]
If there is no direct trace in the record that makes this visible, then what can we do?

Or is this about "delegate" functionality? e.g. if someone has role "delegate" (example) and is member of department X, then he/she can see all records for that department?

**Comment by mietcls** [comment]
This is not about the delegate functionality.

If there is a way to see which records are connected
- in the overview
- as a librarian
- even in the OAI
and you can see the content in the search;
what am I missing?

**Comment by nicolasfranck** [comment]
There is some discrepancy between what you can do and what you can see:

* this record has been made by this user indeed. So I guess that is the user who tried to add the datasets, not?
* I see that, when adding datasets, the search is NOT limited to datasets that are not permitted to see based on your "function", but it does allow to search on publications with status "public".
* So if you click "add dataset" you see all public datasets, but when you click "add dataset" .. it does not show on the list of datasets, because that page only wants to show datasets when you are the creator, or a contributor or a reviewer in general. A bit strange though?

**Comment by mietcls** [comment]
Thanks for the clarification and further specification!

**Comment by mietcls** [comment]
Will be fixed with #1372

In principle, we violate rule `number 3`
> we allow users to link objects if they have the right to edit the record they are currently editing and the right to view the object they are linking

However with the implementation of #1372, users can see all of the datasets and publications, even if they don't have the right to see them.
e.g. here I am logged in as researcher1, and I can see John Doe's publication – even if it is not linked yet:
![Screenshot 2024-08-08 at 09 00 54](https://github.com/user-attachments/assets/737719c7-17a3-4298-b11a-584294170412)

This also results in having publications and datasets on top that have nothing to do with your record.
_But_ without delegations / proxies this will be very hard to do well.

Can be revised in a later stage.
