### ISSUE TITLE
Zenodo import publisher and keywords do not import as expected after DataCite Metadata Scheme update 

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1385]
# Bug description
Zenodo import publisher and keywords do not import as expected
- [ ] keywords do not split on semicolon
- [ ] publisher is displayed as: { "name": "Zenodo" }

Reason: https://schema.datacite.org/meta/kernel-4.5/ – added new sub-properties

## Steps to reproduce

- Go to https://backoffice.bibliodev.ugent.be/dataset
- Add dataset via [DOI](https://backoffice.bibliodev.ugent.be/dataset/add) 10.5281/ZENODO.7509270 
- See import publisher
![Screenshot 2024-03-04 at 12 00 26](https://github.com/ugent-library/biblio-backoffice/assets/1572885/8fb7aa46-6829-4856-9af3-160b22774e11)
- See import keywords
![Screenshot 2024-03-04 at 12 00 41](https://github.com/ugent-library/biblio-backoffice/assets/1572885/dec5209a-9daa-4c06-803c-1e9dcf2cb3fb)
- Edit keywords -> they split -> save -> they are okay
![Screenshot 2024-03-04 at 12 01 10](https://github.com/ugent-library/biblio-backoffice/assets/1572885/08d4fa8d-8cb9-400a-955b-e1dc69e4ae89)
![Screenshot 2024-03-04 at 12 01 30](https://github.com/ugent-library/biblio-backoffice/assets/1572885/d0b396fb-6846-4d21-9c9f-d15d36fb5839)

Context: https://github.com/ugent-library/biblio-backoffice/issues/938

**Comment by nicolasfranck** [comment]
Notes

* without request header `Accept: application/vnd.datacite.datacite+json` (as we apply) attribute `publisher` is still a string. In that case the returned content-type is `application/json`.

**Comment by mietcls** [comment]
Does not work

**Comment by nicolasfranck** [comment]
@mietcls this was done against the main branch, not the dev branch. 

So on backoffice.bibliodev.ugent.be it doesn't work (yet)
It does on backoffice.bibliotest.ugent.be 

I guess more recent hot-fixes should be merged back into dev from the main branch?

**Comment by mietcls** [comment]
Yes, almost always – so we don't diverge too much.
