### ISSUE TITLE
Cookies not cleared on logout

### ISSUE THREAD

**Issue by verheyenkoen** [ugent-library/biblio-backoffice#1390]
# Bug description
On logout, all stateful information should be forgotten. The `biblio-backoffice` cookie is updated so the current user becomes "anonymous", but it does still contain information about the librarian mode (researcher or librarian). This produces problems if you log in as a researcher when the mode previously was set to librarian.

It may be best to just clear the cookie altogether, or at least to reprogram it to researcher mode on logout.

# Steps to Reproduce

1. Log in as a librarian. You enter in researcher mode.
2. Switch to librarian mode.
3. Log out again. Sidebar background should be blue but is gray.
5. Log in as researcher (you may have to clear keycloak cookies first to not be automatically logged on again)
6. You get the "Something went wrong" screen.

## Automatic testing scenario

I tried to write a failing test for this but couldn't make it work because of the specific hacky (interference) nature of Cypress of dealing with with cookies/sessions.

### Likelihood
Improbable

### Consequences
Marginal

# Expected behavior
Logging out should clear all state. Not just the user session.

# Screenshots
![image](https://github.com/ugent-library/biblio-backoffice/assets/599538/e46d58e6-7e9d-4a4d-9572-8d81fad248a9)

# Additional context
This may not currently occur in real use cases in TEST or DEV since Keycloak automatically logs you back on with the same account, but in prod you don't get a Keycloak screen in between and login is delegated to UGent login (CAS) automatically. So you could have a situation where two users work in the same browser and stumble upon this problem (after automatic or manual logout from CAS).

I recognise this is low priority but probably also very easy to fix.

**Comment by nicolasfranck** [comment]
This comment https://github.com/ugent-library/biblio-backoffice/blob/main/handlers/authenticating/handler.go#L85 states that the current role should be remembered, but fails to say why:
```
// only remember user role
delete(session.Values, handlers.UserIDKey)
delete(session.Values, handlers.OriginalUserIDKey)
delete(session.Values, handlers.OriginalUserRoleKey)
```

While I can easily add `delete(session.Values, handlers.UserRoleKey)`. Anyone any idea?

**Comment by verheyenkoen** [comment]
Actually I can imagine why. For librarians (the Biblio team) it's probably cumbersome to always having to switch that.

Another way to approach this is, is to just remove this "setting" at the point where an unauthorized error would be thrown because of this and basically "downgrade" the role there. I guess something similar is also done when using the "view as" feature for a regular researcher account?

**Comment by nicolasfranck** [comment]
If this behaviour only has an impact on cypress tests, and end users do require this behaviour (of remembering the selected role), isn't better to just clear the cookies on the client side as a way to logout? That way you do not even have to know where the logout button or logout path is located.

**Comment by verheyenkoen** [comment]
It isn't related to Cypress testing but to manual testing. Cypress always clears the whole session between tests.

**Comment by netsensei** [comment]
> This comment https://github.com/ugent-library/biblio-backoffice/blob/main/handlers/authenticating/handler.go#L85 states that the current role should be remembered, but fails to say why:
> 
> ```
> // only remember user role
> delete(session.Values, handlers.UserIDKey)
> delete(session.Values, handlers.OriginalUserIDKey)
> delete(session.Values, handlers.OriginalUserRoleKey)
> ```
> 
> While I can easily add `delete(session.Values, handlers.UserRoleKey)`. Anyone any idea?

@nics Any particular reason why the user role isn't removed from the session cookie on log out? Looking at the code, logging out ought to do just that: remove all data from the browser, anything tied to a particular session in a "logged in" state.

**Comment by nics** [comment]
@netsensei because the reviewers don't want to switch roles all the time; most people only have the default role user, so that doesn't matter much

**Comment by verheyenkoen** [comment]
Another simple suggestion: how about making "librarian" the default mode for curators? Isn't that what they are gonna be using most of the time?

**Comment by nics** [comment]
better check with @mietcls if the desired behaviour is a default role or the last role used

**Comment by mietcls** [comment]
@verheyenkoen yes, that would be great! Now it's the last role they used, but for librarians this would be better.

**Comment by verheyenkoen** [comment]
Note to self: there is already a test for this but several tests will fail once this is implemented.
