### ISSUE TITLE
Projects with the same GISMO-UUID appears twice with different project codes 

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1400]
# Bug description
Projects with the same GISMO-UUID appears twice with different project codes.

This is the same project
https://biblio.ugent.be/project/3G098020 (correct)
https://biblio.ugent.be/project/3G036120 (old GISMO project)

They have the same GISMO UUID: 489bffea-225c-11ea-9b15-d7676230cb7f

Message from our colleague at GISMO:

> Het project dat nu code 3G098020 heeft, komt bij ons overeen met project met uuid 489bffea-225c-11ea-9b15-d7676230cb7f. (de technisch achterliggende id hiervan)
> Als ik terugkijk, dan zie ik dat het project 3G036120 vroeger ook in gismo bestond, eveneens met uuid 489bffea-225c-11ea-9b15-d7676230cb7f.
> Op 21/12/2020 is dit echter van code veranderd en is ook de vroegere code verwijderd uit de lijst van fedids…
> M.a.w hetzelfde project had eerst code 3G036120, en nadien is deze gewijzigd (eerst naar G098020N en meteen nadien naar 3G098020).
>  
> Ik vind het wel raar dat BIBLIO deze beide nog heeft, want wij communiceren ook altijd onze uuid door.. dus ik zou verwachten dat dit bij hen ook gematched wordt en dat zij weten dat dit effectief hetzelfde project is…
> En dat zij dus ook maar 1 lijntje tonen (namelijk met de juiste recente code..)

Can we do something about this with our current or future project service?

**Comment by netsensei** [comment]
The current development cycle re-uses the existing data as-is, stored in the old mongo database. Retroactively cleaning data is currently not in scope.

In a next phase, we want to fetch updates directly from GISMO via a dedicated still-to-be-build NATS pipeline. That's when we may consider introducing clean up operations to arrive at a more consistent state.

**Comment by nicolasfranck** [comment]
Also, the projects are referenced via their IWETO identifiers, both in the frontend, and from a publication. So updating project will require updates to the referring publications.
