### ISSUE TITLE
[templ] Gohtml conversion to Templ

### ISSUE THREAD

**Issue by verheyenkoen** [ugent-library/biblio-backoffice#1402]
This ticket is part of an effort to convert all Gohtml views to Templ. Some of these have already been converted but the bulk is yet to be addressed.

Most views are somehow dependent on other views which creates a virtual web of view dependencies which have to be converted all together which will be a massive effort and has to be concentrated on the shortest possible amount of time to avoid interference on other development. But some views (mostly loaded partially through HTMX, like eg. modal dialogs) can already be converted beforehand so that giant effort is reduced a little.

This ticket addresses those "smaller conversions" that don't impact the bulk of the views. We'll list the specific files that should be possible to convert individually (or with few related views - indented) here. We'll also try and identify unused views that can be removed here.

### Views to be converted

[✔️ = covered by Cypress tests] 

- [x] views/error_dialog.gohtml ✔️
  #1481 
- [ ] views/form_errors_dialog.gohtml
- [x] #1498
- [x] views/dataset/add_department.gohtml ✔️
  #1454
  - [x] views/dataset/_suggest_departments.gohtml ✔️
- [x] views/dataset/add_project.gohtml
  #1472 
  - [x] views/dataset/_suggest_projects.gohtml
- [x] views/dataset/add_publication.gohtml ✔️
  - [x] #1486
- [x] views/dataset/confirm_delete_abstract.gohtml ✔️
  #1444
- [x] views/dataset/confirm_delete_contributor.gohtml ✔️
  #1426 
_(other contributor related views have far more dependencies so are probably out of scope of this ticket)_
- [x] views/dataset/confirm_delete_department.gohtml ✔️
  #1461
- [x] views/dataset/confirm_delete_link.gohtml ✔️
  #1460 
- [x] views/dataset/confirm_delete_project.gohtml ✔️
  #1466 
- [x] views/dataset/confirm_delete_publication.gohtml ✔️
  #1465 
- [x] views/dataset/confirm_delete.gohtml ✔️
#1422 
- [x] views/dataset/confirm_publish.gohtml ✔️
  #1413 
- [x] views/dataset/confirm_republish.gohtml ✔️
  #1413 
- [x] views/dataset/confirm_withdraw.gohtml ✔️
  #1410 
- [x] views/media_types/suggest.gohtml ✔️
  #1424 
- [ ] views/modals/error.gohtml
- [ ] views/publication/add_dataset.gohtml ✔️
  - [ ] views/publication/_suggest_datasets.gohtml ✔️
- [x] views/publication/add_department.gohtml ✔️
  #1456 
  - [x] views/publication/_suggest_departments.gohtml ✔️
- [x] views/publication/add_project.gohtml
  #1473 
  - [x] views/publication/_suggest_projects.gohtml
- [x] views/publication/confirm_delete_abstract.gohtml ✔️
  #1437 
- [x] views/publication/confirm_delete_contributor.gohtml ✔️
  #1425 
_(other contributor related views have far more dependencies so are probably out of scope of this ticket)_
- [x] views/publication/confirm_delete_dataset.gohtml ✔️
  #1464 
- [x] views/publication/confirm_delete_department.gohtml ✔️
  #1462 
- [x] views/publication/confirm_delete_file.gohtml
  #1469
- [x] views/publication/confirm_delete_lay_summary.gohtml ✔️
  #1443 
- [x] views/publication/confirm_delete_link.gohtml ✔️
  #1441
- [x] views/publication/confirm_delete_project.gohtml ✔️
  #1467 
- [x] views/publication/confirm_delete.gohtml ✔️
  #1421 
- [x] views/publication/confirm_publish.gohtml ✔️
  #1415 
- [x] views/publication/confirm_republish.gohtml ✔️
  #1417 
- [x] views/publication/confirm_update_type.gohtml ✔️
  #1419 
- [x] views/publication/confirm_withdraw.gohtml ✔️
  #1410
- [ ] views/publication/pages/add.gohtml
  #1485 
  - [x] views/publication/add_multiple_sidebar.gohtml (TODO: remove .gohtml file)
  - [x] views/publication/add_single_sidebar.gohtml (TODO: remove .gohtml file)
  - [x] views/publication/pages/add_wos.gohtml
  - [ ] views/publication/pages/add_identifier.gohtml
  - [x] views/publication/pages/add_manual.gohtml
  - [x] views/publication/pages/add_bibtex.gohtml
- [x] `views/dashboard/*/*.gohtml`
  #1438
- [x] #1442
- [x] #1452
- [x] #1457
- [ ] ...

### Unused views (to be deleted)

- [ ] ...

I suggest we create individual PR's per set of related templates (as small as possible).

**Comment by mietcls** [comment]
Closing this issue to avoid confusion, please continue tracking your issues here: https://github.com/ugent-library/biblio-backoffice/issues/1487
