### ISSUE TITLE
User IDs mixed up: back- and front office issues

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1406]
# Bug

This user seems to have ID issues [assumption] https://telefoonboek.prd.rad.ugent.be/nl/people/802000019840, causing these issues:
- Cannot log in in back- nor front-office
- Another user is displayed when going to their profile
- Cannot be found in "view as"

## Details

Front-office:
- If we [look up this user in the front office](https://biblio.ugent.be/publication?text=Robby+Caspeele)
![Screenshot 2024-03-27 at 16 29 47](https://github.com/ugent-library/biblio-backoffice/assets/1572885/21728a20-c080-4a20-97de-2b76d5a1dcdd)

- And click their name in the research found, we are linked to _an other_ user:
https://biblio.ugent.be/person/F8467408-F0ED-11E1-A9DE-61C894A0A6B4

<img width="1512" alt="Screenshot 2024-03-28 at 10 58 13" src="https://github.com/ugent-library/biblio-backoffice/assets/1572885/1e365271-df11-42d1-9dcc-d53169bc631c">

Back-office:
- Cannot log in
- Not available in "view as":
![Screenshot 2024-03-27 at 16 22 57](https://github.com/ugent-library/biblio-backoffice/assets/1572885/aaa8c113-1f8b-4492-9b76-47ce63dbe541)

**Comment by nicolasfranck** [comment]
Noted:

* all publications refer to mentioned. So mentioned id MUST be the original record from Robby. That means that Robby's record got LDAP updates from Els (like first name, last name, locality, department ..). Fixing this will erase Els's record, but that will be restored upon the next run of ldap_sync
* in the list of authors in the backoffice the name "Els" appears as the author, while in the short author list bellow a publication entry, the name appears "correctly". So there the name is drawn via a different source?
