### ISSUE TITLE
Remove duplicate auth checks for candidate records

### ISSUE THREAD

**Issue by verheyenkoen** [ugent-library/biblio-backoffice#1407]
The authorization check that only curators can use candidate records is put in multiple places:

* Middleware: https://github.com/ugent-library/biblio-backoffice/blob/9922269a6a2f566a14d25785710e1b147383fc21/routes/register.go#L306
* Every handler function, eg: https://github.com/ugent-library/biblio-backoffice/blob/9922269a6a2f566a14d25785710e1b147383fc21/handlers/candidaterecords/candidaterecords.go#L24-L27

The checks in handler functions can be removed as the middleware covers that.

**Comment by verheyenkoen** [comment]
When writing tests for this, also write tests that cover publishing, withdrawing, repbulishing, locking and unlocking for both publications and datasets.

### Scenario

1. Log in as reseacher
2. Create a publication/dataset
3. Log in as librarian
4. Go to the page where the according action button is and grab the URL that would be executed when clicking (this can be inside of a modal popup).
5. Log in as researcher again
6. Go to the grabbed URL
7. Verify that a 403 Forbidden error is returned

**Comment by nics** [comment]
fixed
