### ISSUE TITLE
Duplicate records in LDAP for active users keep us from updating

### ISSUE THREAD

**Issue by nicolasfranck** [ugent-library/biblio-backoffice#1412]
# Bug description

For some active users in LDAP there appears to be multiple records in store,
one former record, and one active.

This user https://telefoonboek.prd.rad.ugent.be/nl/people/000200335918 has a record
as ugentFormerEmployee, and one as ugentEmployee (and ugentStudent). They both
share the same ugent id's. But one of them is not relevant anymore.

This results into two records in the authority database:

* https://biblio.ugent.be/person/f5f26fd3-f2ce-11ee-b5c2-f225db724dde. This is the one that has relevant information, but no publications are linked to the record, so the web page returns a 404.
* https://biblio.ugent.be/person/62c1c5b2-dce7-11ea-8880-b922706672a0. This is the one that has the outdated information, but to which the publications are linked. So now she appears without any association.

**Comment by mietcls** [comment]
If needed, we can move the records to the relevant active user ID, which could make it easier to deal with it.

**Comment by mietcls** [comment]
@nicolasfranck does my suggestion help? After that you can merge them?

**Comment by nics** [comment]
merged author profiles
