### ISSUE TITLE
Abstract and lay summary can be "cleared" when editing

### ISSUE THREAD

**Issue by verheyenkoen** [ugent-library/biblio-backoffice#1420]
# Bug description
For both publications and datasets, when you add an abstract or lay summary (for dissertations), the text field is required and you also get a required error if you just enter spaces. This validation (entering spaces) does not occur upon editing an existing abstract or lay summary. Fully clearing the field when editing, does trigger a validation error.

# Steps to Reproduce

1. Create a publication (of type dissertation) or dataset
2. Add an abstract or lay summary
3. Type spaces in the text
4. See the required validation error
5. Add actual text
6. Save the abstract or lay summary
7. Edit it again
8. Now replace the text with spaces again (clearing the field will work as expected)
9. The abstract/lay summary is saved without validation error

## Automatic testing scenario

(Same)

### Likelihood
1: Frequent

### Consequences
3: Marginal

# Expected behavior
Validation should be the same upon adding and editing forms.

**Comment by nics** [comment]
fixed by #1428
