### ISSUE TITLE
a place to refer to research tip "Biblio: how to register my publications?"

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backoffice#145]
**Describe the improvement**
https://onderzoektips.ugent.be/en/tips/00001664/

**Comment by nics** [comment]
@sdebodt okay if i remove the v2 milestone? this needs the footer in place

**Comment by sdebodt** [comment]
milestone removed.

**Comment by mietcls** [comment]
There are tips implemented (and the correct tips too).
