### ISSUE TITLE
Zenodo dataset doi import has a json publisher

### ISSUE THREAD

**Issue by nics** [ugent-library/biblio-backoffice#1490]
doi: [10.5281/zenodo.7129007](https://zenodo.org/doi/10.5281/zenodo.7129007)

<img width="408" alt="Screenshot 2024-05-07 at 08 05 22" src="https://github.com/ugent-library/biblio-backoffice/assets/35421/87aea0c0-b8b6-4cca-845a-03f7294f420f">

**Comment by nicolasfranck** [comment]
Duplicate of #1385, which is already fixed in the main branch by https://github.com/ugent-library/biblio-backoffice/pull/1401?

**Comment by nics** [comment]
closed as duplicate
