### ISSUE TITLE
Import dataset via DOI: publisher name is shown as a key/value JSON string

### ISSUE THREAD

**Issue by netsensei** [ugent-library/biblio-backoffice#1528]
# Bug description

When importing a dataset via DOI, the `publisher` field in the dataset details will show a JSON formatted key/value object, instead of the name of the publisher.

e.g. `{ "name": "Zenodo" }`

This bug appears on the dev environment, not the production / testing environments. So, this was introduced in the `dev` branch.

# Steps to Reproduce

1. Go to 'add dataset' & choose add via DOI
2. Add a DOI e.g. 10.5281/ZENODO.5201249
3. On the 'complete description' step, notice how the publisher field is filled out incorrectly.

## Automatic testing scenario

n/a

### Likelihood

Frequent.

### Consequences

*What's the impact? 1: Catastrophic, 2: Critical, 3: Marginal, 4: Negligible*

# Expected behavior

Publisher field should read `Zenodo` instead.

# Screenshots

![image](https://github.com/ugent-library/biblio-backoffice/assets/105355/3a957f4c-4825-486c-8036-96d79ddfab19)

**Comment by nics** [comment]
already fixed in main
