### ISSUE TITLE
Invalid embargo date feedback missing for publication files

### ISSUE THREAD

**Issue by verheyenkoen** [ugent-library/biblio-backoffice#1535]
# Bug description

When entering an invalid embargo date for a publication file, the feedback validation error line below the field is missing.

# Steps to Reproduce

1. Create publication
2. Upload a file
3. Configure embargoed access with an embargo date in the past
4. Save
5. The field is marked red but the feedback line is missing

# Expected behavior

# Screenshots

<img width="405" alt="image" src="https://github.com/ugent-library/biblio-backoffice/assets/599538/56a96688-fcaa-4e89-bf88-dc08fd273772">

This is how it was before Templ conversion:
<img width="389" alt="image" src="https://github.com/ugent-library/biblio-backoffice/assets/599538/2c0718e2-bb65-4299-9dc2-3f77fffe40dc">

# Additional context
Bug was introduced with Templ conversion. For datasets this is still ok.

**Comment by nics** [comment]
fixed by https://github.com/ugent-library/biblio-backoffice/commit/0af5d08a0ef6f42980d5cc7246b2fe97261bb04d
