### ISSUE TITLE
On a small screen, I cannot scroll to the end of the "Add references" page

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backoffice#158]
**Describe the improvement**
On the page https://eliot1.ugent.be/biblio-backend/publication/add-multiple, I cannot scroll to the end of the page to see the upload/drag and drop area of the "No Web of Science file?" panel.

**Screenshots**
![image](https://user-images.githubusercontent.com/72742841/143425319-4bc154bb-87f2-4e69-8ead-7a46bbe7b8a3.png)

Browser: chrome

**Comment by nics** [comment]
what is the devise used? the design, as a backend administrative app, is not optimized for small screens
