### ISSUE TITLE
Excel export displays weird sorting behaviour 

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1583]
# Bug description
Excel export displays weird sorting behaviour.
This results into reviewers not being able to have a decent overview.

# Steps to Reproduce

1. Go to https://backoffice.biblio.ugent.be/publication
2. Make an export
3. Sort from A-Z on fields such as projects, ISSN and ISBN
4. See a split sorting appear.

When you clear the fields that are "empty" the sorting is correct again.

![IMG_3623](https://github.com/ugent-library/biblio-backoffice/assets/1572885/bd1eb56d-d78d-45ee-9097-1b3a4ffb994f)
![IMG_3622](https://github.com/ugent-library/biblio-backoffice/assets/1572885/116de9f5-2a1a-480c-ab69-9fc5aec302dc)

### Likelihood
1: Frequent

### Consequences
1: Catastrophic
Impacts review and financial process

# Expected behavior
Sorting is not split, and corresponds to A-Z or Z-A

# System information
Happens on Mac and Dell, in excel

**Comment by nics** [comment]
@nicolasfranck isn't it because you don't explicitly set the cell type to string? https://xuri.me/excelize/en/cell.html#SetCellStr

**Comment by nicolasfranck** [comment]
@nics is already set as string: https://github.com/ugent-library/biblio-backoffice/blob/main/backends/excel/base_exporter.go#L37

**Comment by nics** [comment]
> @nics is already set as string: https://github.com/ugent-library/biblio-backoffice/blob/main/backends/excel/base_exporter.go#L37

ah sorry, must be a bug then, because cell type is General when the doc is opened

**Comment by nicolasfranck** [comment]
I reported this bug: https://github.com/qax-os/excelize/issues/1915

**Comment by nicolasfranck** [comment]
What turns out to be the problem:

* the method `SetCellStr` is not meant to mark text as text in a excel field, but is merely meant as a way to supply a go type as value
* any formatting needs to be done number formatting (sounds weird)

**Comment by mietcls** [comment]
@nicolasfranck @nics can we turn this, after deploy to dev so I can test, into a hot fix, as it still might take a while to deploy dev?
