### ISSUE TITLE
Data improvements Plato implementation

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1587]
# Bugs & improvements Plato implementation

- [x] Publication status: published
_always for Plato dissertations_
![Screenshot 2024-05-31 at 09 12 30](https://github.com/ugent-library/biblio-backoffice/assets/1572885/234e5938-eda5-4cf8-849a-efbaf9341918)

- [x] Place of Publication: Ghent, Belgium
_always for Plato dissertations_
![Screenshot 2024-05-31 at 09 52 01](https://github.com/ugent-library/biblio-backoffice/assets/1572885/c8810503-7362-41e2-8b8c-32527d27152c)

- [x] Abstract language: Dutch
_always for Plato dissertations_
![Screenshot 2024-05-31 at 10 12 52](https://github.com/ugent-library/biblio-backoffice/assets/1572885/0125c53c-7b1b-464a-a3d0-a37926f51044)

- [x] ISSN was shown on preview, but not imported
<img width="219" alt="Screenshot 2024-05-31 at 09 32 31" src="https://github.com/ugent-library/biblio-backoffice/assets/1572885/05da3d1c-a267-4163-9ed9-d97bce2c0e10">

![Screenshot 2024-05-31 at 09 32 24](https://github.com/ugent-library/biblio-backoffice/assets/1572885/f5dec0ac-22af-4882-8d0e-5d8b5bf654b5)

- [x] Departments: use departments from supervisors
As suggestion, so they can just remove the ones that are not correct
![Screenshot 2024-05-31 at 09 34 54](https://github.com/ugent-library/biblio-backoffice/assets/1572885/450f30d3-30d7-48cc-b140-3011e0d3745b)

- [x] [draft] supervisors in suggestions (to be designed by Miet)

**Comment by mietcls** [comment]
Questions:
- is the access level already automatically defined?

**Comment by netsensei** [comment]
> Questions:
> 
>     * is the access level already automatically defined?

Yes.

Incoming Plato metadata contains access level info. It's recorded on a per-file basis (e.g. embargo on primary file). The import logic automatically converts that to the Biblio data model including transposition to the `info:eu-repo/*` taxonomy.

**Comment by netsensei** [comment]
Reopening because of 

```
 [draft] supervisors in suggestions (to be designed by Miet)
```
