### ISSUE TITLE
Biblio issues before June release 

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1600]
# Bug description
Biblio issues before June release

_[do not close, will keep editing]_

### Critical
- [x] #1632
- [x] #1617
- [x] #1615 [ghost bug]
- [x] #1612
- [x] #1613
- [x] #1619

- [x] #1607

- [x] #1610
  
- [x] Perhaps related to https://github.com/ugent-library/biblio-backoffice/pull/1603: Cannot edit authors in https://backoffice.bibliodev.ugent.be/dataset/01J0B7KTSJCK7PVVG5FBSE0GFJ?redirect-url=%2Fdataset&show=contributors
![Screenshot 2024-06-14 at 17 50 58](https://github.com/ugent-library/biblio-backoffice/assets/1572885/0dfa6287-b409-4a7a-9443-5fddf8c1a383)
- [x] #1605 fixed by https://github.com/ugent-library/biblio-backoffice/pull/1603
- [x] #1606 fixed by https://github.com/ugent-library/biblio-backoffice/pull/1603
![Screenshot 2024-06-14 at 15 16 30](https://github.com/ugent-library/biblio-backoffice/assets/1572885/f57f049f-f5ec-459c-8491-4bff7cad805a)
- [x] #1609

**Comment by verheyenkoen** [comment]
1st and 3rd bulletpoint more than likely already fixed in #1603

**Comment by mietcls** [comment]
@nicolasfranck I don't understand what you mean? It processes with spaces as well?
