### ISSUE TITLE
Dissertation question answers not remembered

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1612]
# Issue

Answers for dissertations questions not remembered:

## Steps to reproduce
1. Answer questions
2. Save
3. See questions not answered
4. Edit questions again, see answers not remembered

# Screenshots
<img width="675" alt="Screenshot 2024-06-17 at 11 45 25" src="https://github.com/ugent-library/biblio-backoffice/assets/1572885/808bf114-569a-4e55-ba96-f178e851f145">
<img width="773" alt="Screenshot 2024-06-17 at 11 45 45" src="https://github.com/ugent-library/biblio-backoffice/assets/1572885/718588c5-0a4a-4378-8a7c-ca795687ee46">

**Comment by nicolasfranck** [comment]
Good catch: none of the radio-button-groups seem to work
