### ISSUE TITLE
Datasets access levels do not work

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1615]
# Bug
Datasets access levels do not always work

1. Create dataset manually
2. Edit access level
3. See dropdown not react - no console error

<img width="819" alt="Screenshot 2024-06-17 at 14 10 00" src="https://github.com/ugent-library/biblio-backoffice/assets/1572885/1bf9ca61-fd92-4376-a5dd-9c1364fe9f28">

**Comment by verheyenkoen** [comment]
Probably ghost bug

**Comment by mietcls** [comment]
👻
