### ISSUE TITLE
Librarian tags field does not work when you hit save before blurring the field

### ISSUE THREAD

**Issue by verheyenkoen** [ugent-library/biblio-backoffice#1617]
When you type a librarian tag, and it hasn't turned "blue" it disappears right before you hit "save".

  - Type tag ![Screenshot 2024-06-13 at 16 29 15](https://github.com/ugent-library/biblio-backoffice/assets/1572885/98cfb1f3-0878-47b2-acc9-0092b3c41c56)
  - Hit save ![Screenshot 2024-06-13 at 16 29 18](https://github.com/ugent-library/biblio-backoffice/assets/1572885/097948fc-828b-4ba6-876b-d87d2de96440)

**Comment by verheyenkoen** [comment]
@mietcls I found this is a general tags field issue. The same happens for Keywords fields

**Comment by nicolasfranck** [comment]
Keywords are only added after either "enter" or ";". Any else in between is temporary.
