### ISSUE TITLE
"Full text missing" does not show up in search overview card for conferences with only a colophon / title page

### ISSUE THREAD

**Issue by nicolasfranck** [ugent-library/biblio-backoffice#1619]
"Full text missing" does not show up in search overview card for conferences with only a colophon / title page:

https://backoffice.bibliodev.ugent.be/publication/01J0JQRC6G6R9YPHFXTWJHGF2T?redirect-url=%2Fpublication%3Fq%3D%26f%255Breviewer_tags%255D%3DMiet%2Btest&show=description

<img width="892" alt="Screenshot 2024-06-17 at 15 17 30" src="https://github.com/ugent-library/biblio-backoffice/assets/1572885/01d12760-8e04-4c27-bbf0-23bc50bdcc4c">
<img width="878" alt="Screenshot 2024-06-17 at 15 27 16" src="https://github.com/ugent-library/biblio-backoffice/assets/1572885/ac7ee5a6-f4db-4c89-9859-cd922805cc0f">

**Comment by nicolasfranck** [comment]
cf. https://github.com/ugent-library/biblio-backoffice/blob/3e1492cb94537fe8f4eed56850df419f6338cebd/views/publication/summary.layout.gohtml#L59

**Comment by nicolasfranck** [comment]
@mietcls this message was changed into a link `Add document type: fulltext`.

Also you flagged this publication as external:

![Screenshot 2024-06-17 at 17 00 48](https://github.com/ugent-library/biblio-backoffice/assets/494636/1e5a7ebd-93c4-4db5-815f-c2dbbaf995b3)

**Comment by mietcls** [comment]
Right, thanks!
