### ISSUE TITLE
Editors do not show up on WoS import

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1625]
# Bug description
Editors do not show up after WoS import:

## txt file content
![Screenshot 2024-06-21 at 10 07 38](https://github.com/ugent-library/biblio-backoffice/assets/1572885/20a99767-857f-496f-9b2e-b5012b893fda)

## imported file
![Screenshot 2024-06-21 at 10 08 55](https://github.com/ugent-library/biblio-backoffice/assets/1572885/9fb8cdec-8a0a-453d-b912-a6e3aa656888)

# Steps to reproduce
1. Go to https://www.webofscience.com/wos/woscc/full-record/WOS:000500696400004
2. Export as `plain text file`, select `full record`
3. Open file and see editors show up under `BE`
4. Import publication as WoS
5. See editors not show up

**Comment by nicolasfranck** [comment]
Editors are not mapped currently in the [RIS importer](https://github.com/ugent-library/biblio-backoffice/blob/main/backends/ris/decoder.go), and editors weren't mapped either in the old librecat interface (https://github.ugent.be/Universiteitsbibliotheek/librecat/blob/master/fixes/wos_mapping.fix).

**Comment by verheyenkoen** [comment]
@mietcls Can we find an example that uses both `BE` and `ED` codes so I can test both in one test?

**Comment by verheyenkoen** [comment]
@mietcls Implementation detail: for authors if both codes `AF` and `AU` are present, code `AF` is preferred and `AU` is ignored. For editors I didn't make that assumption for codes `BE` and `ED`. Not sure if that can ever occur. For testing, I added `ED` entries manually to the plain text export for the publication you referenced above.

**Comment by mietcls** [comment]
Extra information:
- Authors: `AU` = full name, `AF` used to result into duplicates with initials, which was considered annoying on import.
- Editors: Based on the documentation Nicolas Franck provided, I presume `ED` (editor) and `BE` (book editor) will not appear together. I will test.
- Book Editors: if we import a WoS or BibTex file as book editor type, could we import `BF` (preferably to `BE`)?

**Comment by verheyenkoen** [comment]
> * Book Editors: if we import a WoS file as book editor type, we prefer `BF` (book editor full name) to `BE` (book editor). Same rule as Authors.

@mietcls Just a note that "BF" data is not parsed/imported currently. Is that required within the scope of this PR?

**Comment by mietcls** [comment]
Status: looking for a decent example to test `BF` with. If there is no decent use case, `BE` could suffice.

**Comment by verheyenkoen** [comment]
@mietcls Updated PR to also import `BF` (preferred over `BE` when both are present). `ED` is still always imported as is. Added custom adapted WoS test files so if you can get hold of real WoS exports with this data, that would be better and I can adapt the tests.
