### ISSUE TITLE
arXiv no longer works

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1630]
# Bug description

arXiv import no longer works (also not in production)

# Steps to Reproduce import
1. Go to https://backoffice.bibliodev.ugent.be/add-publication
2. Select "Import your publication via an identifier"
3. Select arXiv
4. Use an arXiv identifier such as `2309.05768v1`, `2309.05792`, 10.48550/arXiv.2304.14545
5. See error
![Screenshot 2024-06-24 at 10 40 56](https://github.com/ugent-library/biblio-backoffice/assets/1572885/97d119a1-6ed3-4bf9-a84f-c61054c6fe4e)
![Screenshot 2024-06-24 at 10 41 33](https://github.com/ugent-library/biblio-backoffice/assets/1572885/7c33d204-c346-49a2-9a34-908ee6d25e7d)

**Comment by nicolasfranck** [comment]
In the error I see the following error appearing:

```
{"time":"2024-06-24T11:12:27.239864+02:00","level":"WARN","msg":"import single publication: could not fetch publication","errors":"arxiv: request failed: Get \"https://export.arxiv.org/api/query?id_list=2309.05768v1\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)","publication":"2309.05768v1","user":"0DCE4DB4-F0EE-11E1-A9DE-61C894A0A6B4"}
```

Apparently https://export.arxiv.org/api/query?id_list=2309.05768v1 takes a while to load. So this could have failed in production too.

**Comment by nics** [comment]
@mietcls the first 2 succeed for me, the last identifier fails, but because it isn't found

**Comment by mietcls** [comment]
Thanks for checking @nics, it's magically solved (or a PR fixed it a while back apparently), and the last identifier was a faulty one of mine which should have been `2304.14545`
