### ISSUE TITLE
Fix validation when clearing the classification field

### ISSUE THREAD

**Issue by verheyenkoen** [ugent-library/biblio-backoffice#1633]
# Bug description
For publications, it is possible to clear the classification field (dropdown) but it is required. However the field does not have the blue "Required" marker in the label. Also, the validation message is not properly translated.

# Steps to Reproduce

1. Edit a publication or create a new one manually
2. Click on "Edit" in publication details section (description)
3. Clear the classification dropdown (by default it should have value "U - Undetermined")
4. The validation message appears at the top and below the field as "validation.publication.classification.required"

## Automatic testing scenario

1. Login as librarian
2. Setup a publication
3. Visit the detail page
4. Edit the details
5. Clear the "Classification" field
6. Save
7. Assert that the edit modal is still open and the validation message in the `.alert` and below the field are properly translated.

### Likelihood
*How often does this happen?* 1: Frequent

### Consequences
*What's the impact?* 4: Negligible (only editable by curators)

# Expected behavior

- [x] The "Classification" label should have a blue "Required" marker
_Note; cannot differentiate "Required" label for librarians only. More important that researchers don't see this label because they can't and shouldn't influence this._
- [x] Maybe we should not have an empty option in the dropdown, but I guess that doesn't make the other checks above obsolete, as you can sometimes clear a required dropdown by hitting the `DELETE` key.
- [ ] ~The validation message should be translated properly~
_Note; if there is no empty option we don't need nor have to maintain a validation message – if the delete option is not possible._

# Screenshots

![image](https://github.com/ugent-library/biblio-backoffice/assets/599538/207af7a2-8e43-48b1-82b3-c9f5e4dad312)

# System information

N/A (all OS and browser setups)

# Additional context

Users: librarians. Researchers cannot edit this, only view it.
Use: librarians use it to keep control over their workflow. If there is no classification, they can't control their workflow.
Automation: every new record has classification "U".
There are no records without a classification (you can double check by selecting all classifications in the filter).

**Comment by mietcls** [comment]
Agreed!

> Maybe we should not have an empty option in the dropdown, but I guess that doesn't make the other checks above obsolete, as you can sometimes clear a required dropdown by hitting the DELETE key.

**Comment by nicolasfranck** [comment]
"Required" and "empty option" do not rule each other out.

Having no empty option requires us to set a default when no value
was set, or accept the select option happening to be on top (e.g. classification values are sorted values, so A will be "default"). In the second case you would get
a weird difference between the facets (where the record cannot be found via that value because it is not set), and value shown in the select input (because a select input shows the first option when none is selected).

Any way, I thought we agreed that no options should be preselected,
but explicitly chosen?

Adding a "required" and translate the error text could suffice.

**Comment by mietcls** [comment]
The default is `U` for this dropdown.

**Comment by nicolasfranck** [comment]
In which case we'll have to retroactively update all publications

**Comment by mietcls** [comment]
None of them have no classification, all of them have one (you can see this when selecting the classification field).

Risk: very low.
Users: librarians. Researchers cannot edit this, only view it.
Use: librarians use it to keep control over their workflow. If there is no classification, they can't control their workflow. Thus none are left unclassified.

**Comment by verheyenkoen** [comment]
Settled on removing the empty option and adding the required label for curators only. Unless you mess in devtools you will never see the validation message so no need to translate it.
