### ISSUE TITLE
on "Publish" step, I want to continue to add a new publication/dataset

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backoffice#164]
**Describe the improvement**
When I have finished the "add" workflow for a publication/dataset, I would like to add another publication/dataset without first having to go to the publications/datasets overview. I expect to have a button "Add publication/dataset" on this page (maybe next to the button "Continue to overview").

**Screenshots**
![image](https://user-images.githubusercontent.com/72742841/143469743-7c0c597d-9863-414f-b2fb-14ca4bedd089.png)

**Comment by mietcls** [comment]
<img width="1057" alt="Scherm­afbeelding 2023-05-31 om 09 18 58" src="https://github.com/ugent-library/biblio-backoffice/assets/1572885/25a331cf-fd42-4673-b7c7-544b925ec774">
Done
