### ISSUE TITLE
Duplicate project 41M07818

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1648]
# Bug description
Duplicate project 41M07818 (uppercase): 41m07818 (lowercase).

- Only one exists in GISMO: 41M07818
- All records have been assigned to 41M07818

# Expected behavior
Keep the one with uppercase (41M07818), remove the one with lowercase (41m07818).

## Risk classification
What's the impact? 1: Catastrophic – grants

**Comment by nics** [comment]
@mietcls deleted the project
