### ISSUE TITLE
[Simple proxies] View simple proxies for researchers and administrative personnel

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1684]
# Feature
View simple proxies for researchers and administrative personnel.
_Give people insight into who is chosen to manage their administration and vice versa._

## Settings page
https://booktower-ugent-ui.vercel.app/biblio/settings/proxies.html

- [x] I can see the people that proxy for me
![Screenshot 2024-08-29 at 11 27 15](https://github.com/user-attachments/assets/2a219d92-5f58-4275-ac0e-37d7f023bfb1)

- [x] If `People who can manage your research output` has no people: show empty state

https://booktower-ugent-ui.vercel.app/biblio/settings/proxies--empty.html
![Screenshot 2024-08-29 at 11 27 54](https://github.com/user-attachments/assets/a9c0c27e-7105-4a3e-83c6-7cc2e3c7b528)

- [x] If I am a proxy myself, I can see a call to action that guides me to the proxy dashboard
![Screenshot 2024-08-29 at 11 29 23](https://github.com/user-attachments/assets/1d7d75f7-18ed-4b82-b697-7d67cf3ea5df)

## Navigation
- [x] Go via `Username` -> `Settings` -> automatically get directed to `Proxies`
<img width="318" alt="Screenshot 2024-08-01 at 13 55 46" src="https://github.com/user-attachments/assets/d7318529-ac30-469c-81da-ecfc162c6cd3">

### Empty state navigation
- [x] If neither has people selected: hide settings dropdown
<img width="332" alt="Screenshot 2024-08-01 at 14 06 05" src="https://github.com/user-attachments/assets/48f29a70-e0b3-46d9-9830-3e5002c54c34">

# Out of scope
People manage their own proxies

**Comment by verheyenkoen** [comment]
@mietcls Is there already a data model for this? I can prepare some views but if there's no means to retrieve the data there's not much else to do for this. The other tickets in the proxies epic are still draft so I guess setting up the data model for proxies in their scope somewhere?
