### ISSUE TITLE
[Simple proxies] See which researchers you manage as a proxy

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1689]
# Feature
As a proxy, I can see which researchers I can manage, and switch to their profile perspective to manage their bibliography

https://booktower-ugent-ui.vercel.app/biblio/researcher/proxies/proxies.html
<img width="1512" alt="Screenshot 2024-08-23 at 11 57 54" src="https://github.com/user-attachments/assets/74c71949-9bdf-4d2e-85a9-f5a6f5f05920">

## Navigation
- [x] When I have proxies assigned, a menu item appears that guides me to the overview of researcher I am the proxy for
<img width="101" alt="Screenshot 2024-08-16 at 18 28 04" src="https://github.com/user-attachments/assets/e37e28d9-a1d3-46b9-bba7-f68027074890">

## Researcher proxy overview
https://booktower-ugent-ui.vercel.app/biblio/researcher/proxies/proxies.html
<img width="1512" alt="Screenshot 2024-08-23 at 11 57 54" src="https://github.com/user-attachments/assets/74c71949-9bdf-4d2e-85a9-f5a6f5f05920">

- [x] Per researcher I proxy for, I can see their name and IDs.
- Per researcher I can see...
  - Suggestions
    - [x] see how many suggestions there are, and go to the suggestions view
  - Publications
    - [x] `unlocked should be in URL` see how many unlocked draft publications there are, and go to the publications view with the draft and unlocked filter on
    - [x] `unlocked should be in URL` see how many unlocked withdrawn publications there are, and go to the publications view with the withdrawn and unlocked filter on
    - [x] go to all publications
  - Datasets
    - [x] `unlocked should be in URL` see how many unlocked draft datasets there are, and go to the datasets view with the draft and unlocked filter on
    - [x] `unlocked should be in URL` see how many unlocked withdrawn datasets there are, and go to the datasets view with the withdrawn and unlocked filter on
    - [x] go to all datasets
  - ... which I can manage from a proxy perspective

## Proxy perspective
https://booktower-ugent-ui.vercel.app/biblio/researcher/publications/overview--proxy.html
<img width="1512" alt="Screenshot 2024-08-23 at 12 02 01" src="https://github.com/user-attachments/assets/31b227ec-62b9-4976-b832-cd40bc00c421">

- [x] When I click one of the options on the Proxy dashboard, I go to the page from a proxy perspective (Publications, datasets, suggestions)
- I can manage the researcher's
  - [x] Publications
  - [x] Datasets
  - [x] I can do anything the researcher would be able to do, however, every action will be logged in my own name.
- [x] I stay in the proxy perspective until I click "Leave proxy"
  - When I click a record, I remain in the proxy context
  - When I create a new record, I go to the regular context

### Navigation
<img width="662" alt="Screenshot 2024-08-23 at 12 04 53" src="https://github.com/user-attachments/assets/e2c362f4-096e-42df-8257-41a22c720a2d">

- [x] Dashboard and Proxy dashboard navigation is hidden
- [x] The sidebar colour switches
- [x] A button appears to leave the proxy view, and if I click that button, the navigation turns back to 'normal'
- [x] I can see who I am proxying for in the title

### Publications and datasets
https://booktower-ugent-ui.vercel.app/biblio/researcher/publications/overview--proxy.html
<img width="1512" alt="Screenshot 2024-08-23 at 12 08 50" src="https://github.com/user-attachments/assets/310a274c-5c25-4b34-8e51-07a233dfb100">

- [x] The tabs have a different colour to make clear you are managing someone else's bibliography

## Out of scope
Suggestions, see https://github.com/ugent-library/biblio-backoffice/issues/1348

https://booktower-ugent-ui.vercel.app/biblio/researcher/researcher-suggestions/researcher-suggestions--proxy.html
<img width="1512" alt="Screenshot 2024-08-23 at 12 09 27" src="https://github.com/user-attachments/assets/e9ae9c39-0615-49d5-abd3-13af4fef499a">

**Comment by mietcls** [comment]
Feedback
- dropdown menu is confusing, make clear

**Comment by nics** [comment]
all done
