### ISSUE TITLE
Create Memorialis authors

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1690]
# Enhancement

Create memorialis authors:

- Willy Dekeyser ✅ memorialis profiel
    - https://www.ugentmemorialis.be/catalog/000001103
    - https://libstore.ugent.be/fulltxt/MEM10/000/001/103/MEM10-000001103_1960.pdf  
- Pierre Phariseau ✅ memorialis profiel
    - https://www.ugentmemorialis.be/catalog/000004947
    - https://research.ugent.be/web/person/pierre-phariseau-0/nl
    - https://www.ugentmemorialis.be/catalog/000004947 
- Gilbert Jacobs ✅ memorialis profiel
    - https://www.ugentmemorialis.be/catalog/000004531
    - https://www.ugentmemorialis.be/catalog/000004531  
- Wenefride Van der Vorst
    - https://lib.ugent.be/nl/catalog/rug01:000510047?i=66&q=forest&sort=title&sticky=type&type=phd 
- Severin Amelinckx ✅ memorialis profiel
    - https://www.ugentmemorialis.be/catalog/000001093
    - https://libstore.ugent.be/fulltxt/MEM10/000/001/093/MEM10-000001093_1960.pdf  
- Elie Van Bogaert ✅ memorialis profiel
    - https://www.ugentmemorialis.be/catalog/000000756
    - https://www.ugentmemorie.be/personen/van-bogaert-elie-1919-1993 

Ticket
https://otrsdoza.ugent.be/otrs/index.pl?Action=AgentTicketZoom;TicketID=8670

**Comment by nics** [comment]
added
