### ISSUE TITLE
Add clear button for affiliations modals

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1691]
# Enhancement
Add clear button for affiliations modals

We are not using the full potential of the search input field, by using `type="text"` instead of `type="search"`

- [x] Add `type="search"` to input field for adding affiliations
  - Authors
  - Editors
  - Supervisors
  - Creators
  - Departments
- [x] When using the clearing icon `x`, the search is refreshed

![Screenshot 2024-07-30 at 09 51 01](https://github.com/user-attachments/assets/a4794f33-8aa3-48ff-8acf-489235ffc1f6)

Extension of https://github.com/ugent-library/biblio-backoffice/issues/1673

## Out of scope

Component that makes the behaviour the same for all browsers

**Comment by nics** [comment]
@mietcls this can be closed?

**Comment by mietcls** [comment]
@nics no it's only done for https://github.com/ugent-library/biblio-backoffice/issues/1673, not for affiliations

**Comment by verheyenkoen** [comment]
@mietcls Also for impersonation dialog?

**Comment by verheyenkoen** [comment]
> @mietcls Also for impersonation dialog?

This is the same field so this is automatically fixed.
