### ISSUE TITLE
Missing author

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1693]
# Bug description
Missing author

# Steps to Reproduce

1. Go to https://backoffice.biblio.ugent.be/publication/01J4KB0BG6HT9Y4TJXJS9KA866?redirect-url=%2Fpublication%3Fq%3D01J4KB0BG6HT9Y4TJXJS9KA866%26sort%3Ddate-updated-desc&show=contributors
2. See [missing] author

See further description here for privacy reasons: https://ugentbe.sharepoint.com/:w:/r/teams/Group.PR202303913/Gedeelde%20documenten/General/P%20%E2%80%93%20Biblio/Bug%20reports/personen/Cases/person-management-ES.docx?d=w65814042cafb4052ba3dcda0ebd9732f&csf=1&web=1&e=A1xwxy

**Comment by mietcls** [comment]
I'll double check with Anniek first, based on Nicolas Franck's comment in the document.

**Comment by nicolasfranck** [comment]
[bb_publications_missing_rels.csv](https://github.com/user-attachments/files/16728431/bb_publications_missing_rels.csv)

I noticed a few missing relations when importing the production database (accompanied with people and project data) into my local instance:

* missing contributors
* missing creators
* missing projects

**Comment by mietcls** [comment]
Closing as outdated: person was with UGent until 2003. Not a pressing problem.
