### ISSUE TITLE
Two profiles for one person, but with the same IDs (3 separate cases)

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1719]
# Bug description
Two profiles for one person, but with the same IDs after restarting her career at UGent. There are three separate cases.

# Steps to Reproduce
https://ugentbe.sharepoint.com/:w:/r/teams/Group.PR202303913/Gedeelde%20documenten/General/P%20%E2%80%93%20Biblio/Bug%20reports/personen/Cases/person-management-BH.docx?d=w7492355b209e47608a74803ccc26335e&csf=1&web=1&e=abzfbO

# Expected behavior
Per person, one profile with all records and IDs, ORCID connected.
URLs remain persistent.

**Comment by nics** [comment]
@mietcls merged the profiles
