### ISSUE TITLE
[Plato imports] embargo date incorrect

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1726]
# Bug description
Plato imports: embargo date does not switch

# Steps to Reproduce

1. Go to suggestions: https://backoffice.biblio.ugent.be/candidate-records
2. See imported plato suggestion, with embargo date still active:
<img width="1488" alt="SCR-20241014-ouje" src="https://github.com/user-attachments/assets/afac05a6-f148-42ab-af09-019e3669639b">
- e.g. Towards the Next Generation of Geometric Phase Photonic Components Using Chiral Liquid Crystal
- Open access from 2024-10-01
- Claimed on On 2024-10-10
3. See import itself <img width="826" alt="Screenshot 2024-10-14 at 16 51 13" src="https://github.com/user-attachments/assets/368c81c4-d406-45d9-acf9-256379d96ffc"> (changed manually by Biblio team member)

## Automatic testing scenario
Possible @verheyenkoen ?

## Expected behavior
The "switch" for the embargo happens in the suggestion itself, just like for the ones we create ourselves in Biblio.
The Biblio team does not need to see that information in the suggestion if the embargo is already passed.

### Likelihood
How often does this happen?
3: Occasional

### Consequences
2: Critical

**Comment by mietcls** [comment]
@verheyenkoen I've removed on hold, the decision has been made to make the switch inside the suggestion already.
Later, when we have a more granular history, we can perhaps add a view that shows what data we got from Plato originally.

**Comment by verheyenkoen** [comment]
Removed "cypress-test-requested" label as this is not possible

**Comment by verheyenkoen** [comment]
@mietcls Ready for testing in #1735. Reseed your data to have one suggestion with embargo date 1/11/2024. Run `go run main.go update-embargoes` to fix it.
