### ISSUE TITLE
[Plato Imports] Make removed suggestion more nuanced: duplicate

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1728]
# Enhancement
[Updated content]

1. Make removed suggestion for Plato more clear: rejected as a duplicate.
Other rejection options will be needed for other sources, here we know there is little probability we are suggesting it to the wrong person.

![Screenshot 2024-11-15 at 09 48 49](https://github.com/user-attachments/assets/49692544-90cf-4959-82b8-a54561a97106)
![Screenshot 2024-11-15 at 09 48 40](https://github.com/user-attachments/assets/3cce8110-9a19-49c5-a5ba-d355c0f01c08)

2. Hide "View" after import for researchers for now
When you import a record, and then delete the publication, the view button does not work. This causes confusion. We will fix that later for all researchers, but now keep the button for reviewer workflows.

**Comment by verheyenkoen** [comment]
Just to make sure: if a curator rejects a suggestion, it doesn't get a "Restore" button but is still visible for 90 days?

Do we want to show the name of the Biblio team member here or rather "a Biblio team member"?

**Comment by mietcls** [comment]
> If a curator rejects a suggestion, it doesn't get a "Restore" button but is still visible for 90 days?
Correct, that would be great!

> Do we want to show the name of the Biblio team member here or rather "a Biblio team member"?
"A Biblio team member" is perfect, we do not want people to contact specific staff members but go through the general Biblio helpdesk if they have questions. There is a contact button if they need help in the nav bar.

**Comment by verheyenkoen** [comment]
@mietcls I assume, biblio team member will still be able to restore rejections made by other biblio team members?

**Comment by mietcls** [comment]
@verheyenkoen Yes, correct assumption.
