### ISSUE TITLE
when full text dialogue is ready, add guidance on access levels for dissertations

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backoffice#189]
**Describe the improvement**
For dissertations, submitters need more guidance on how to select the appropriate access level (cfr. dissertation questions taken up as metadata). Add this guidance to dialogue when uploading a file (see https://github.com/ugent-library/biblio-backend/issues/74).

@sdebodt to provide text to include after consultation with Anniek

**Comment by sdebodt** [comment]
as long term solution, explore how this can be taken up as part of review process, in communication of reviewer with researcher/promotor-supervisor

**Comment by mietcls** [comment]
Tackling this with Plato import flows.

**Comment by sdebodt** [comment]
We have started drafting a[ guidance document](https://ugentbe.sharepoint.com/:w:/t/CA20.DataStewardTeam/EdeWgBQNxc1GsInOxhWDUUUB2BI4g7gOnQ4qc8kwPyu_aw?e=HgKbo3) for selecting the access level for dissertations but have not finalized this yet. I will check with Myriam.
