### ISSUE TITLE
for dissertations, do not publish before review

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backoffice#211]
**Describe the improvement**
When clicking on "Publish to Biblio", a publication is sent for review and is immediately available for other users as well. As it might occur quite often that an incorrect access level is chosen for dissertations, upon sending a dissertation for review, do not yet make it publicly available in biblio.

related to https://github.com/ugent-library/biblio-backend/issues/189

**Comment by nics** [comment]
ok but too late for this milestone

**Comment by sdebodt** [comment]
can this be added to v2?

**Comment by sdebodt** [comment]
currently Biblio review team is checking incoming dissertations as soon as possible and changes access level when in doubt.

**Comment by mietcls** [comment]
Will rethink this with workflows.
