### ISSUE TITLE
provide predefined list of licenses from spdx

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backoffice#240]
**Describe the improvement**
Currently, when I enter a license for a dataset manually, any free text is accepted. I want to choose from a predefined list of licenses, from which the licenseIdentifier is stored. In addition, I want to be able to add a license that is not in the predefined list.

https://github.com/spdx/license-list-data/blob/master/json/licenses.json

**Comment by nicolasfranck** [comment]
@sdebodt isn't that a bit contradictory? Predefined lists are meant to prevent mistakes, but if you allow for manual input also, the predefined list is "useless", not?

**Comment by sdebodt** [comment]
I know. Unfortunately, the predefined lists are far from complete so we also need to allow free text input.

**Comment by nicolasfranck** [comment]
so more something like an autocomplete, rather than an input that is validated against a fixed list.

**Comment by sdebodt** [comment]
An autocomplete could be ok. A drop down to select from (without typing anything) allows to add the preferred options on top of the list though.

**Comment by nicolasfranck** [comment]
@nics @sdebodt something like this? https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_datalist
If you click in the input you see an automatic dropdown, but you can still fill in your own text.

Important: as it is a sort of autocomplete, there is no way to hide the full url of a license behind a short label,
so that might be a "problem".

**Comment by nicolasfranck** [comment]
related: https://github.com/ugent-library/biblio-backend/issues/239

**Comment by sdebodt** [comment]
The content of the dropdown menu with licenses does not seem to be correct. How is the matching done? Against licenseId and name?

When I enter "creative comm" as in screenshot, only Non commercial licenses are listed.

![image](https://user-images.githubusercontent.com/72742841/151986056-47daf301-e459-43bb-a21b-2d6b162a42bf.png)

**Comment by sdebodt** [comment]
How are results in the dropdown menu sorted? Could there be a way to have the most recent version first?

Can we put "preferred" licenses on top? Either hard-coded list of licenses or based on the licenses that are chosen frequently or both?

Can a hard-coded list of preferred licenses be shown on top of a dropdown menu that appears when clicking the text box, but not yet typing anything?

**Comment by nicolasfranck** [comment]
Seems to return only the top 10 results, and in this case the search cannot determine what is more important.

**Comment by sdebodt** [comment]
Take time to design the functionality needed to improve the user-friendliness.

In the meantime, a simplified solution could be better. @sdebodt to discuss with Thomas and Myriam and report back here on simplified solution.

**Comment by sdebodt** [comment]
based on discussion with Thomas and Myriam, implement temporary solution described in https://github.com/ugent-library/biblio-backend/issues/295

**Comment by sdebodt** [comment]
**To dos for v2 release:**
- As for data format for datasets, have 1 text box to enter value through select from autocomplete or free text. In the background, save each option as a different field.
- Treat old license info as free text. 

**Future work:**
- Old license info could be curated later on, either automatically if 1-on-1 mapping is possible or manually, in case of datasets.

**Comment by mietcls** [comment]
Note: both "license" and "other license" are now required fields. However, one of both is fine. This first dropdown shows a preferred list but the free text field allows for other (older) licenses). This is not clear from the interface.

**Comment by mietcls** [comment]
Will solve the above story later, will fix the temporary situation in the interface only: https://github.com/ugent-library/biblio-backend/issues/481

**Comment by mietcls** [comment]
Discussion has become large. When we review the used licenses, we can rethink the licenses interaction. Most of the requests have been covered in this issue.
