### ISSUE TITLE
How will a data curator know which info is extracted based on PID?

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backoffice#245]
**Describe the improvement**
Currently, metadata is filled based on the DOI from DataCite, after which a user can further complete and/or edit the metadata. How can a data curator know which of the metadata fields were automatically extracted and therefore should not be changed.

**Comment by mietcls** [comment]
Need to rethink this with import flows. Will reopen / refer to this when we tackle it, as this became stale. Currently impossible because of the way it works underlying, which means we cannot implement this practically.
