### ISSUE TITLE
from GRID to ROR by April 2022

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backoffice#260]
**Describe the improvement**
uit [FRIS ontwerpverslag](https://ugentbe.sharepoint.com/:w:/t/CA20.DataStewardTeam/EXy4eDFkdFRFrkqNiZytxpkBtfCyOdd3fsPVYL9VmizToA?e=4RvZh4) (14 december 2021):

GRID to ROR:
Aangezien GRID niet meer publiek toegankelijk is vanaf eind 2021, werd op het overleg in september beslist om over te gaan naar ROR als fed id op organisaties. Om in te gaan op de vraag van de dataproviders om de deadline voor de switch van GRID naar ROR uit te stellen, wordt 1/4/22 als nieuwe deadline voor het gebruik van ROR i.p.v. GRID vooropgesteld.

Currently, only UGent is added as organization using the GRID ID. This GRID ID will need to be replaced by the ROR ID https://ror.org/00cv9y106

**Comment by nics** [comment]
this only concerns the gismo team, they do the fris mapping

**Comment by mietcls** [comment]
GISMO has implemented this, we will consume their information when we are done with the organisation service and use their IDs.
