### ISSUE TITLE
simplify entry of keywords

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backoffice#270]
# Story

I can add multiple keywords at the same time

Related; make librarian tags work smoother: https://github.com/ugent-library/biblio-backend/issues/536

# Success criteria

- [ ] I can do this in one go without having to click around
- [ ] I can easily delete keywords that I accidentally added
- [ ] I get suggestions

## Suggestion

Perhaps with a comma or a different known way – like a tag input.

# Context

## Implementation

Best to write our own code, no third-party – unless they are very accessible. We can start with an HTML example.

## Example
![image](https://user-images.githubusercontent.com/72742841/150820363-28a619ed-8713-46eb-b25e-1e549a81fe6b.png)

## Current implementation

You need to add multiple keywords with a +, and then you need to click a new box.

**Comment by mietcls** [comment]
Will be designed in a next round.

**Comment by mietcls** [comment]
Will be fixed in #938
