### ISSUE TITLE
UGent authors/creators with multiple UGent IDs and differently formatted departments

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backoffice#272]
**Describe the improvement**
When searching some people through the author functionality, the following was observed (see picture). Multiple UGent IDs are shown for one person (employee and student ids). The department formatting for UZ Gent is different from the one from UGent.

Can IDs be restricted to the current id (or most recent id)?
Can department formatting be harmonized?

**Screenshots**

![image](https://user-images.githubusercontent.com/72742841/151000139-769f6b89-f7e6-44f2-9ee6-a31a2ac2f0e3.png)

**Comment by sdebodt** [comment]
For departments that ceased, the notation for the department name is Organization.DI04*

**Comment by nics** [comment]
closing this as outdated
