### ISSUE TITLE
Provide guidance to "Number of pages"

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backoffice#277]
# Story

When I am filling out the publication details, I will know what the "Number of pages" field is for.

## Suggestion
Add help text that says "Only provide the number of pages when the exact first and last page are not known"

### Component
https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-forms.html#component-04-form-with-help-text

## Context old Biblio
![image](https://user-images.githubusercontent.com/72742841/151005713-ae534d09-00cd-4668-a604-98aa6974faf6.png)

**Comment by mietcls** [comment]
will be fixed by #346
