### ISSUE TITLE
On publication error, the new flash error upon the previous one 

### ISSUE THREAD

**Issue by nicolasfranck** [ugent-library/biblio-backoffice#279]
If you submit a publication form multiple times,
and the form returns a validation error using the
flash box in the lower right corner, those flash
messages keep stacking up.

<img width="1439" alt="Screenshot 2022-01-26 at 10 24 00" src="https://user-images.githubusercontent.com/494636/151136971-484f141c-d766-41b9-9bb5-13f94e5f5ba0.png">

Is that ok, or do they have to replace each other? 

Or is this just handy, and does it indicate that you're making the same mistake over and over?

**Comment by sdebodt** [comment]
@nicolasfranck, is this a question to me?

I would only stack error messages if they are more specific and mention what gives errors. Alternatively, you could only show 1 error message upon save (or going to the next step) that lists all errors and have immediate response by having the red text box and message as shown in the screenshot.

**Comment by mietcls** [comment]
Not relevant any longer in current implementation
