### ISSUE TITLE
publications without completeness bars

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backoffice#281]
**Describe the improvement**
Inge reported some publications for which the completeness bars are not shown. Also something going on with the publication status.

- https://backend.bibliotest.ugent.be/publication/764155
- https://backend.bibliotest.ugent.be/publication/764221
- https://backend.bibliotest.ugent.be/publication/764110

**Screenshots**
![image](https://user-images.githubusercontent.com/72742841/151572834-08f7e269-9b1d-4e8d-8558-ec657bb5a23e.png)

**Comment by nicolasfranck** [comment]
@nics ik zie dat de fix `set_completeness_score` enkel toegepast wordt tijdens een update.
Dat kan verklaren waarom het attribuut `completeness_score` afwezig is.

**Comment by nics** [comment]
pas je het aan?

**Comment by mietcls** [comment]
Removed the entire functionality anyways, so the bug is gone.
