### ISSUE TITLE
when is pdf preview image shown

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backoffice#287]
**Describe the improvement**
For some publications, a pdf preview image is shown next to the main publication info. When is this pdf preview generated and when not?

no pdf preview: https://backend.bibliotest.ugent.be/publication/8500668
with pdf preview: https://backend.bibliotest.ugent.be/publication/5774068 

**Screenshots**
![image](https://user-images.githubusercontent.com/72742841/152130986-717b9778-e4eb-4335-b587-59b9609eddad.png)

**Comment by nics** [comment]
2 factors:
- it a batch job, so there's a small delay before generation
- only done for wellformed pdf's,some pdf's do not conform to the pdf spec, and then this job can fail
