### ISSUE TITLE
project list contains redundancy

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backoffice#288]
**Describe the improvement**
Example of a project with the same ID listed twice in the search (screenshot 1). When adding one of these two projects, the second one is automatically shown in the metadata as well (screenshot 2).

**Screenshots**
![image](https://user-images.githubusercontent.com/72742841/152767998-997c2b61-5c2d-4c57-808e-56109fd33371.png)

![image](https://user-images.githubusercontent.com/72742841/152767823-afb24aae-7d48-4ca2-9194-b793e5f688bc.png)

**Comment by mietcls** [comment]
We will fix this when we use GISMO's data, and fix cases by report. It is a very complicated implementation now, so it makes sense to focus on the future implementation with GISMO.
