### ISSUE TITLE
change link of DOI in publication/dataset details from dx.doi.org to doi.org

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backoffice#293]
**Describe the improvement**
Add a link (https://doi.org/...) using the DOI to allow to go to the publication/dataset at it's source.

**Comment by sdebodt** [comment]
Can the url be constructed using https://doi.org instead of https://dx.doi.org? This is the newer syntax.

**Comment by mietcls** [comment]
The back-office uses this URL. Added an issue to the front-office GitHub.
