### ISSUE TITLE
confusing button in "Complete description" step of multiple publications

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backoffice#296]
**Describe the improvement**
When you have uploaded a WoS export file to add multiple publications, you reach step 3 "Complete description". In this step, a list of the publications from the WoS export file is shown in a overview. Next, you need to click one of the publications to complete the description. On that single publication page, you cannot publish an individual publication but you need to go back to the list of publications to publish all of them in one go (which is fine). However, to go back to the list of publications, you need to click "<-- Publications overview" (screenshot 1), which looks the same as the "<--Publications overview" (screenshot 2) shown on a publication page outside of the "add" workflow that directs you to all your publications.

I was initially thinking that I would end up outside of the "add" workflow, on the "All publications" overview when clicking that button. Can we rename this button so that it is clear that you will not be leaving the "add" workflow? e.g. "Imported publications"

**Screenshots**
![image](https://user-images.githubusercontent.com/72742841/153882936-5a561ba8-1cc0-4c15-b3bc-189439721a4e.png)

![image](https://user-images.githubusercontent.com/72742841/153883319-87cc9f66-3b58-4f01-83e8-e313a355c28d.png)

**Comment by mietcls** [comment]
Will be picked up with new import flow and quick import. Will be simplified majorly.
