### ISSUE TITLE
Labels instead of IDs for data format

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backoffice#301]
**Describe the improvement**
Currently, the lengthy data formats from IANA are used.

application/...
text/csv
...

Can we show the label to the user instead, but still save the ID in the database?

related https://github.com/ugent-library/biblio-backend/issues/239

**Comment by mietcls** [comment]
@sdebodt what should these values translate too?
I found this list: https://www.iana.org/assignments/media-types/media-types.xhtml but I'm not sure which values are preferred.

**Comment by mietcls** [comment]
Thanks! Will reopen when the need arises.
