### ISSUE TITLE
warn me when adding a publication that already exists in Biblio via identifier

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backoffice#307]
**Describe the improvement**.
Currently, you can add metadata for a publication with a particular ID multiple times. I would like to be warned that a publication record for that ID already exists. Or even stronger, I should not be able to add a dataset with an ID that already exists.

This was already implemented for DOI in https://github.com/ugent-library/biblio-backend/issues/259.

Now also implement for the other currently used IDs:

- [ ] PMID
- [ ] ARXIV

**Comment by mietcls** [comment]
Priority: PMID

**Comment by mietcls** [comment]
Will fix this with new import flow – and make sure everything works similarly. Will transform into new issues applied to that.
