### ISSUE TITLE
warn me when importing already existing publications through WoS import

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backoffice#310]
**Describe the improvement**

Not only in the single publication, but also in the multiple publications workflow, a warning should be given when adding a publication that already exists (based on the ID). Give warning message, after uploading the WoS file.

related https://github.com/ugent-library/biblio-backend/issues/307, https://github.com/ugent-library/biblio-backend/issues/259

**Comment by nicolasfranck** [comment]
@sdebodt only a warning, or just simply refuse?

One or more warnings give you the opportunity to remove them
from the list (especially during the import wizard)

**Comment by sdebodt** [comment]
A publication with an ID that was already registered, should not be entered again. I would remove these publications from the imported publications.
So the warning message should list these already existing publications and indicate that the publications were removed from the import. Manual removal would be tedious and will probably be easily forgotten.

**Comment by sdebodt** [comment]
need for interface to allow selection of duplicate records to import anyway.

**Comment by mietcls** [comment]
Note for myself: warn me when adding a publication that already exists in Biblio #307

**Comment by mietcls** [comment]
Will refactor this with the import flow.
