### ISSUE TITLE
improve design to guide users through different tabs

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backoffice#311]
**Describe the improvement**

It might not be obvious that different tabs of the "Description" need to be completed. How can we guide users through the different tabs to ensure that they e.g. add the affiliation for UGent authors/creators, add a related dataset/publication?

related https://github.com/ugent-library/biblio-backend/issues/244

**Comment by sdebodt** [comment]
also consider to change order of tabs. have ID > publication details > authors > full text > related datasets instead of first full text

**Comment by sdebodt** [comment]
name of "Publish to Biblio" button in step 4 is interpreted as an immediate publish, not going to the next step where it can be decided to publish or not.

instead use "Proceed to publish"?

**Comment by sdebodt** [comment]
it is not clear that during the workflow a draft is automatically saved. add pop-up that says "draft saved" for each step?

**Comment by mietcls** [comment]
We will remove the tabs. Autosave will be solved later. The different steps will be simplified. Testing this with Plato.
