### ISSUE TITLE
share overview of currently implemented validation rules

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backoffice#312]
**Describe the improvement**
To check whether we are not missing anything or are too stringent, share the validation rules contained in JSON file. 

Note that other validation not part of this JSON might occur.

**Comment by nicolasfranck** [comment]
https://github.com/ugent-library/biblio-backend/wiki/Dataset:-validation-rules

https://github.com/ugent-library/biblio-backend/wiki/Book-:-Publication-details:-validation-rules

https://github.com/ugent-library/biblio-backend/wiki/Book-:-Additional-information:-validation-rules

https://github.com/ugent-library/biblio-backend/wiki/Publication-:-full-text-:-validation-rules

**Comment by sdebodt** [comment]
For the validation of publication, you mention that Title, Publication year, etc are required when status is public. However, I can publish a publication even if this metadata is missing. At which level/when is this requirement tested?

**Comment by sdebodt** [comment]
For license info for publications, we should maybe consider to add validation as for datasets, i.e. if license, other license and tick box "no license" is empty, return error.

**Comment by sdebodt** [comment]
validation on UGent author implemented?

**Comment by sdebodt** [comment]
I was able to publish a publication which did not have a publication year while the documentation says "required: only when status is public"

**Comment by nicolasfranck** [comment]
which one? Where?

**Comment by sdebodt** [comment]
https://backend.bibliotest.ugent.be/publication/8630580 for the publication year comment

**Comment by nicolasfranck** [comment]
> I was able to publish a publication which did not have a publication year while the documentation says "required: only when status is public"

That is copy and paste error on my part. Only the title is required when status is set to public.

**Comment by mietcls** [comment]
I appear to have missed this comment. Would you like to share information and see where we can improve? Or is this an issue in the current implementation?

**Comment by sdebodt** [comment]
@mietcls, can you share your documentation on whether fields are mandatory and possible exceptions, such that we can check whether some fields/info should be required upon publish.

e.g. full text is not required upon publish at this moment, because in some cases (which?) a full text cannot be added.

Goal is to require more fields upon publish, such that researchers are "pushed" to provide more info, instead of having to complete "mandatory" fields during the review process.
