### ISSUE TITLE
handling of initials of authors and inconsistency between external data and UGent employees

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backoffice#317]
**Describe the improvement**
question from a biblio user (via  Dorien):
“Mijn naam (alsook die van een resem andere UGent-auteurs!) is niet gelinkt. Dit komt regelmatig voor door het gebruik van een tweede initiaal, is het mogelijk om de import-tool daarmee overweg te laten kunnen?”

Misschien ook nog iets waar rekening mee gehouden kan worden in de nieuwe Biblio?

link might be missing because of  inconsistency in handling of initials between external data and UGent employees

**Comment by sdebodt** [comment]
Confirmed based on experience of curators. When the external repository has an initial for an author/creator which is not known in the UGent employee database, the initial needes to be removed before assigning UGent affiliation as otherwise the author/creator is not found.

**Comment by mietcls** [comment]
@nics @netsensei is this something that needs to be picked up with the UGent database, not in Biblio?

**Comment by mietcls** [comment]
Rethink with people service – also while importing we do not automatically link people or give suggestions. Need to rethink author suggestions (together with department and project suggestions). Keeping track in #1099
