### ISSUE TITLE
Sort search results of authors alphabetically

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backoffice#324]
**Describe the improvement**
When giving only a first name or a last name and then selecting UGent author, the proposed UGent members are listed randomly. Sorting the names alphabetically would help to find the correct UGent author.

**Screenshots**
![image](https://user-images.githubusercontent.com/72742841/162398693-a26d3eb3-235c-4e2b-aaa1-3d0ecc01bf82.png)

**Comment by mietcls** [comment]
Relevance ranking gets very complex this way, we need to pick this up in semantics.
