### ISSUE TITLE
Provide alternative, more striking design for mandatory fields

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backoffice#328]
# Improvement

Original title: make mandatory fields more obvious

Even though some mandatory fields are not validated upon clicking Publish, in the input form it should be clearer what is mandatory. The asterisk is not sufficient.

# Addition

Our learning curve should be as low as possible. The clearer the better. However – if we wind up having a lot of mandatory fields the form can become very busy.

# Related

related https://github.com/ugent-library/biblio-backend/issues/338

**Comment by mietcls** [comment]
Did we also get this remark by the pilot group by any chance? In which context was this an issue? It is a well-known pattern for most forms – did people miss anything?

**Comment by sdebodt** [comment]
This is a issue identified based on feedback from both test group and pilot group.

Asterisk is very small. 

In-form validation or feedback would be useful.

see related issue as well as feedback on check-box overview (not in github yet) and comments on fact that records can be published even e.g. the full text is missing.

**Comment by mietcls** [comment]
Extra validation: this is a widely known pattern for IT, but not at all for non-ITers. We do not have the luxury to assume a learning curve as we need as little as friction as possible for first-timers.

**Comment by mietcls** [comment]
**The badges**
The badges seem very good to me.
Is there already an HTML snippet available that we could use?

The alignment
I would like to try aligning the labels to the right as you suggested. However when guiding people through a form it will be harder to scan te form, and [the form will probably be filled out less fast](https://pratikhegde.medium.com/form-design-best-practices-801ceaaf9b67) – but _"There is really no hard and fast rule for aligning labels while designing forms."_. We could test what the result is when the labels are at the bottom too.

**Comment by emilyvandewalle** [comment]
Great, thanks for the article about the form alignment, really informative!

- [Example in documentation of required badges within standard stacked forms](https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-forms.html#component-01-form-standard)
- [Example in documentation of required badges within horizontal forms](https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-forms.html#component-04-form-horizontal)
- [In context example within the publication form](https://biblio-ugent-prototype-emily-v2.vercel.app/biblio/reviewer/publication-detail/description.html)

**Changes in content/scss/bootstrap-additions/_badges.scss**
Added small badge variant 
```
.badge-sm {
  height: 2rem;
  font-size: 1.2rem;
  padding: 0.3rem 0.6rem;
}
```

**Changes in content/scss/bootstrap-additions/_forms.scss**
Changed color of labels tog `$gray-600` and added margin-left to badges within labels by default

```
.col-form-label,
.form-label {
  font-weight: 500;
  color: $gray-600;
}

.col-form-label,
.form-label {
  display: flex;
  align-items: center;

  .badge {
    margin-left: 0.8rem;
  }
}

```

**Comment by mietcls** [comment]
Wonderful, thanks for providing the alternative layout for the future and the changes!

I did find a little weird behaviour, this looks a bit strange:
<img width="996" alt="Schermafbeelding 2022-07-12 om 11 36 48" src="https://user-images.githubusercontent.com/1572885/178460507-eab60c67-f2af-4a24-af74-0eb9629da27b.png">

**Comment by mietcls** [comment]
Design created; needs to be implemented with full view (without tabs) and quick import.
