### ISSUE TITLE
Metadata missing or wrong for PubMed ID import

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backoffice#330]
# Bug & improvement
When importing a publication using the PubMed ID, metadata is missing or wrong.
Example: https://pubmed.ncbi.nlm.nih.gov/20460583/

- [x] Abstract missing
<img width="857" alt="Screenshot 2023-08-10 at 10 08 01" src="https://github.com/ugent-library/biblio-backoffice/assets/1572885/0bb8cefc-ca42-4b48-bc15-a6991cf59ac5">
<img width="1171" alt="Screenshot 2023-08-10 at 10 12 53" src="https://github.com/ugent-library/biblio-backoffice/assets/1572885/cf42d8a7-cd97-41f9-aa94-70b64ea7fb0e">

- [x] Author names: first name not extracted, only initial
<img width="253" alt="Screenshot 2023-08-10 at 10 07 43" src="https://github.com/ugent-library/biblio-backoffice/assets/1572885/ae426d52-f53a-4553-9b42-e5a8e7b79dc7">
<img width="1159" alt="Screenshot 2023-08-10 at 10 13 51" src="https://github.com/ugent-library/biblio-backoffice/assets/1572885/6a635347-cc62-4c0b-898a-6347cc2ce4a3">

- [x] Journal title: shows journal title abbreviation
<img width="251" alt="Screenshot 2023-08-10 at 10 11 34" src="https://github.com/ugent-library/biblio-backoffice/assets/1572885/71cae009-1f3f-499d-8b78-7ce138e87060">
<img width="365" alt="Screenshot 2023-08-10 at 10 11 48" src="https://github.com/ugent-library/biblio-backoffice/assets/1572885/0dcd008b-8571-4297-9787-ea84395dae7b">

- [ ] Short journal short (journal title abbreviation) is missing
<img width="251" alt="Screenshot 2023-08-10 at 10 11 34" src="https://github.com/ugent-library/biblio-backoffice/assets/1572885/71cae009-1f3f-499d-8b78-7ce138e87060">
<img width="365" alt="Screenshot 2023-08-10 at 10 11 48" src="https://github.com/ugent-library/biblio-backoffice/assets/1572885/0dcd008b-8571-4297-9787-ea84395dae7b">

- [x] Language missing
<img width="136" alt="Screenshot 2023-08-10 at 10 14 41" src="https://github.com/ugent-library/biblio-backoffice/assets/1572885/06454a47-1e09-497e-a835-c52debca487a">
<img width="317" alt="Screenshot 2023-08-10 at 10 15 13" src="https://github.com/ugent-library/biblio-backoffice/assets/1572885/55a147df-7871-49cd-9951-d1d96ee46ead">

**Comment by sdebodt** [comment]
I used this example: [20460583](https://pubmed.ncbi.nlm.nih.gov/20460583/).

Trying it again, now the title is included in the publication details, the abstract is not.
Authors have initials only as above.

**Comment by nics** [comment]
everything except short journal title is ok in backoffice.bibliodev.ugent.be

**Comment by mietcls** [comment]
Do I make a new issue for short journal title @nics?

**Comment by nics** [comment]
@mietcls I fixed it with https://github.com/ugent-library/biblio-backoffice/commit/0e720f7736229372a84fe00efcb7c7448dde689f (deployed on bibliodev)
