### ISSUE TITLE
notify user when provided field is not correct

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backoffice#338]
**Describe the improvement**
When a mandatory or validated field is filled, give a message to the user when the provided content is not correct.

related https://github.com/ugent-library/biblio-backend/issues/328

**Comment by mietcls** [comment]
Validation in the sense of faulty information:
![Image](https://user-images.githubusercontent.com/1572885/186120330-029728ef-75db-47de-8665-50d36c61717d.png)

**Comment by mietcls** [comment]
Needs to become a more practical, actionable issue. Will revisit this later, issue has become stale.
