### ISSUE TITLE
Use keyboard shortcuts to ease usage?

### ISSUE THREAD

**Issue by nicolasfranck** [ugent-library/biblio-backoffice#362]
Wouldn't it be handy to have some keyboard shortcut
to ease the usage of the interface?

May be simple:

* submit form by pressing **enter in an input**. Normally a browser does this already, but it seems to be disabled for some reason. Not without risk though, as not many seem to realise that enter has this behaviour. P.S. textarea's do not have this behaviour as they contain multiple lines ;-) 
* use **escape** to close the current open form. A caveat: as the user does not click a "cancel", maybe there will be an expectation that all work is kept for later. A warning dialog should be added for unsaved changes. Well that applies also when you click that "cancel" button maybe.
* use **escape** to return to the publications overview. Should have the same effect as clicking the link "publications overview".

@mietcls @nics @sdebodt @netsensei

**Comment by mietcls** [comment]
@nicolasfranck thanks for this idea!

We were just talking about a similar issue as well, not for submit but for intermittent saving. Right now we only automatically save adding documents or authors / editors - when would we save text fields? What is the expected and accessible behaviour?

On the other hand we also want to save meaningful snapshots of the record, which we can use to resolve conflicts (which does not happen a lot). Autosave makes that hard, but the case you present to save when completing (or leaving) a field/part of the form might be more meaningful.

About the escape, this is related to keyboard shortcuts but with a different goal. We might also change the layout of the current form depending on the feedback (we might wind up removing the collapse for instance). We could treat both cases in a separate issue to keep an overview, perhaps tie it to a bigger epic to keep the context.

We can keep this information into account when planning ahead, and tie it to the feedback from the pilots @sdebodt?

**Comment by mietcls** [comment]
Would be awesome to make our application more accessible. This is a huge ticket right now though. Closing until we hash out what we will do where and how.
