### ISSUE TITLE
In the list view, I can see the most important information all at once in the list of records.

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#366]
# Story [in progress]

As a reviewer, I can see the most important information while I browse through the list of records, so I can see which records need which additions.

* = also useful to researchers

## Primary information 

Identification:
- [x] Record Title*
- [x] Publication (record) type *
- [x] Classification *
- [x] Biblio ID *

Shows pipeline status and relevance to reviewers or curators:
- [x] Biblio status *
- [x] Publication year *
- [x] Locked / unlocked (non-edit is superfluous) *
- [x] Open access of niet
- [x] Research data, datasets (new)

Indication of action required:
- [ ] Last changed date (= created if that was the only action) *
- [ ] Last changed date by (= created by if that was the latest state) *
- [x] Comments *

**Links** that help with completing a record _and_ give an indication of completeness:
- [x] Full text link to (PDF) (link) *
- [ ] Other files (link to files inside record)
- [ ] DOI (link)
- [ ] WoS ID (link)

Shows the state of completeness for reviewers:
- [ ] Publication short title (replaces full title – full title could be more interesting to researchers) *
- [ ] Volume
- [ ] Issue
- [ ] Pagination
- [ ] Number of pages
- [x] Partial list of authors / editors with UGent indicator *

Encouraging for researchers, double check for reviewers:
- [ ] Completeness (new) *

Help researchers
- [ ] Biblio link (click through to public side) *

## Secondary information

**Links** that help with completing a record:
- [ ] PubMed (link)

Shows the state of completeness:
- [x] Complete List of authors (to check for doubles + link to filter if possible)  *
- [x] Departments (link to filter if possible) *

Indication of action required:
- [x] Created date *
- [ ] Created date by *

## Tertiary information

_This information can be tucked away further, in the record details._

Links handy for researchers:
- [ ] Altmetric (link) *
- [ ] Biblio Handle, persistent URI (link) *

# Additional information

## Out of scope

- Actions, will be described in a different issue when applicable.

## Current interface

**Information you can see while browsing + "details" panel**
![Image](https://user-images.githubusercontent.com/1572885/168993100-d2285010-f364-4106-91c5-58ffd404133e.png)

## Current design

In the current design we moved the "checks" to a separate panel, inside the record. This can be useful to researchers. However, researchers need this information in the overview to avoid having to click open each record.

**Information you can see while browsing:**
![Image](https://user-images.githubusercontent.com/1572885/168992947-919f0259-261b-4208-9a7b-f1e9f20e63f4.png)

**Detailed information:**
![Image](https://user-images.githubusercontent.com/1572885/168993491-8b5e97aa-e4b0-4453-95fe-a119af2e3271.png)

**Comment by mietcls** [comment]
@sdebodt We've noticed some information was missing to easily check information in the list view for reviewers. We've had a short conversation about it with Emily VDW to see what possible, and I'd like her to take a second look at the design (because this is *a lot* of information).

I enquired two reviewers about the information they need (and for what). A data curation perspective would be great as well.
I'd like to wait until we got feedback from the pilot group as well before we adapt anything in code (or the prototype).

@nics @netsensei you often got questions about adding new information to the overview, am I missing out on any context or information?

**Comment by sdebodt** [comment]
> @sdebodt We've noticed some information was missing to easily check information in the list view for reviewers. We've had a short conversation about it with Emily VDW to see what possible, and I'd like her to take a second look at the design (because this is _a lot_ of information).

@mietcls, did you already get input on this question?

**Comment by mietcls** [comment]
Added problem: 

You can't copy parts of the title, since it is hyperlinked. This means checking for doubles is hard.

**Comment by mietcls** [comment]
Rethinking in progress
