### ISSUE TITLE
As a developer, I can easily add new information to card components

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#400]
# Story
As a developer, I can easily add new information to card components or form new card constellations without breaking the design.

# Success Criteria
- [x] We understand the way the cards work, and how to add information in a visually consistent way
- [x] Actions and information are displayed in a consistent way
- [x] Whenever we take away information in a card, the card design does not break
- [x] We do not need to write extra code to add extra elements
- [x] We can align element according to the context: vertical and horizontal

# Context

Right now we don't know what the best practice is to add information.

Example: project
<img width="1178" alt="Schermafbeelding 2022-06-02 om 15 42 54" src="https://user-images.githubusercontent.com/1572885/172610120-055282bd-ec49-4555-be26-66270bf33ee5.png">

Example: author
<img width="826" alt="Schermafbeelding 2022-05-19 om 11 30 09" src="https://user-images.githubusercontent.com/1572885/172610264-6da10408-9cd6-45f2-9afb-ab58d476b722.png">

# Outstanding questions

Headers that contain titles, actions, alerts and other information should probably have a similar system, or a separate one. What is recommended?

**Comment by mietcls** [comment]
During our meeting we discussed we need a couple of examples for complex cards and headers:
- What it will look like if you leave out certain parts of a card (for instance a "person card" with an image, heading, content, button, ... and without).
- What it will look like on different screens (responsive)
- What it will look like in a modal

**Comment by mietcls** [comment]
To be continued with new card designs.

**Comment by emilyvandewalle** [comment]
I've tried to document a variety of cards/list-group items in the [list group documentation](https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-list-group.html), let me know if this needs more clarification or if more examples should be added!


I set up the following construction for more complex variations:
- We can use a <code>list-group-item-inner</code> wrapper to add a flexbox layout and horizontally align the child items 
- We can use  <code>list-group-item-main</code> for the main content, which will make the content take up the available space
- For more simple variations where there are no horizontally stacked items we could leave out the <code>list-group-item-inner</code> construction and add the content directly 

``` html
<div class="list-group-item">
   <div class="list-group-item-inner">
     <div class="list-group-item-main">
         <!-- Main content goes here and expands according to width available -->
     </div>
     <div class="c-button-toolbar">
          <!-- Actions go here -->
     </div>
   </div>
</div>
```

**Comment by mietcls** [comment]
We have everything we need right now!
