### ISSUE TITLE
prefer publication year of print over publication year of online post

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backoffice#405]
**Describe the improvement**
The metadata of a publication can contain different types of publication year depending on whether it is about publicaton online, publication in print or other.

In case the publication is published in print, extract that publication year instead of the online publication year.

https://data.crossref.org/reports/help/schema_doc/5.3.1/crossref5_3_1_xsd.html#publication_date

I will add an example as soon as I receive it from the tester. I can only find examples where only one date type is given :-(.

**Comment by sdebodt** [comment]
example: https://doi.org//10.1093/rheumatology/keab653
crossref metadata: https://api.crossref.org/v1/works/10.1093/rheumatology/keab653

extract of metadata showing to publication dates:
```
journal-issue: {
issue: "5",
published-online: {
date-parts: [
[
2021,
9,
17
]
]
},
published-print: {
date-parts: [
[
2022,
5,
5
]
]
}
},
```

**Comment by nicolasfranck** [comment]
@sdebodt strange. Right now we use `issued.date-parts`, and if that doesn't exists `created.date-parts`.
Issue date looks to me like a print date, or not? I do see that `published-print.date-parts` is in 2022, while
`issued.date-parts` in september of 2021..

A bit confusion, the [website](https://academic.oup.com/rheumatology/article-abstract/61/5/2054/6371887?redirectedFrom=fulltext&login=false) you mention above also mentions `17 September 2021` as the publish date

**Comment by sdebodt** [comment]
I will check with a few people whether the print date is preferred as mentioned in the title. 

The naming of the different date types might be different on the Biblio side, not sure whether you stick with the CrossRef metadata field names.

**Comment by mietcls** [comment]
@nicolasfranck is this how it works in the old Biblio?

**Comment by nicolasfranck** [comment]
@mietcls yes, it was copied from that place. But that does not mean it was right..

**Comment by sdebodt** [comment]
I am checking this with Myriam and Inge. It needs some further discussion to come to a decision on whether we want to change it. It is not obvious from the Belgian open access legislation which date needs to be considered.

Could it be an option to, at least, in the backend, manage both dates?

**Comment by nicolasfranck** [comment]
> I am checking this with Myriam and Inge. It needs some further discussion to come to a decision on whether we want to change it. It is not obvious from the Belgian open access legislation which date needs to be considered.
> 
> Could it be an option to, at least, in the backend, manage both dates?

no, that does not solve anything, as the interpretation is postponed to a later stage. Two years in biblio, how to sort that? People will start asking were we got these years from..

**Comment by mietcls** [comment]
Adding information I just got from Anniek, that might be related:

Currently, a publication year is required – even when it is in press.
People fill out the early access date instead.

At first glance our reaction could be "then do not make it required if it is in press, this is lying"

However, this "fake date, early access" date is actually used
- to give information about the approximate date of release
- by librarians, to see in time which records need to be adapted with the real publication date
- in calculations by GISMO and FRIS to make the distribution keys

**Comment by mietcls** [comment]
Keeping track of this in light of when a field is used for what, when it is required for whom in which point in time.

Closing ticket as the whole idea of who is responsible for what is on the table, and in which point in time. Requires mapping out and possibly reforming processes around it, not just the software. Hence why this has been open for way too long, there is no consensus throughout approach for teams. Will pick this up when the time is ripe.
