### ISSUE TITLE
[Plato imports] As a supervisor, I can see which dissertations I supervised, and which publications I was part of in the overview

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backoffice#408]
# Enhancement

Depends on #1278. Part of Plato imports, but is a feature in itself.

_As a supervisor, I can see which dissertations I supervised, and which publications I was part of in the overview_
- _This is needed, because promotors assist often in filling out the information in Biblio._
- _In order to make sure people add the requested missing information and claim outstanding research, involved parties (author, supervisors) should be able to see the suggested Plato imports._

_The distinction is needed, because supervising is not the same as contributing as an author/editor, but important nonetheless._

### As a researcher, I can see which dissertations I supervised
- [x] In the publications search overview tab, I can now also see publications that I supervised
- [x] In the tab "My publications" I will only see publications that are mine (not supervised)
- [x] In the publications search overview tab, a new tab appears that shows my supervised publications
![Screenshot 2023-10-19 at 16 14 44](https://github.com/ugent-library/biblio-backoffice/assets/1572885/e9513ab3-4792-461e-a90f-3b14d55f63b4)

#### Implementation suggestion

```
<li class="nav-item">
    <a class="nav-link" href="/publication?f%5Bscope%5D%5B0%5D=supervised&amp;page=1&amp;page-size=20">
        Supervised by me
    </a>
</li>

```
## Automatic testing scenario
- [x] As a supervisor, I can see all the dissertations I supervised in the "Supervised by me" tab
- [ ] For each record, I can see which role I had for it

## Additional context

Front-office:
![Image](https://github.com/ugent-library/biblio-backoffice/assets/1572885/02b92de3-114e-42e2-a082-c820e640ff41)

Original issue by Stefanie:

> Currently, supervisors of dissertations cannot see the dissertation record of their PhD students in the backend. It would be better if they can see it not only in the frontend but also in the backend, such that they can help during the review process (e.g. for deciding on the correct access level).

**Comment by mietcls** [comment]
In line with Plato integrations

**Comment by mietcls** [comment]
Yes, I feel like we are saying the same thing? The filter in this case is the tab.
Supervising is not the same as contributing as an author/editor, they need a clear distinction.

**Comment by verheyenkoen** [comment]
@mietcls In case of no items, I put this text:

<img width="385" alt="image" src="https://github.com/ugent-library/biblio-backoffice/assets/599538/cd1b53de-841e-453c-986c-35a07272d525">

Ok?

**Comment by mietcls** [comment]
@verheyenkoen Thank you for thinking about changing this copy!

I suggest to align it:

**No registered supervising dissertations**
Register a dissertation for which you are supervisor.
