### ISSUE TITLE
When I add multiple publications at once, I want to make informed decisions and actions

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#415]
# Story

As a Research Associate or reviewer, whenever I add multiple publications at once, I want to make informed decisions and do informed actions.

# Success criteria

- [ ] I can add hundreds of publications at once
- [ ] I get pagination
- [ ] I can see which imports are successful and which ones have failed (wrong file, corrupt, ...)
- [ ] I can decide, from that list, to not to import multiple publications at once, and remove them from the list in bulk
- [ ] I can do so for multiple publications at once that are scattered throughout multiple pages in bulk
- [ ] I can see doubles immediately (based on WoS identifiers and DOI) – and decide for myself to import them or not in bulk
- [ ] I have my own autonomy to decide whether I'll allow a double or not – based on the information I get in the warning
- [ ] If there are more then x publications, the list becomes paginated
- [ ] I can search for specific publications in that list before I import them

# Additional information

We now have a good design base, but it would be good to have an idea of how this would work with the above requirements.

Current design: https://biblio-ugent-prototype-emily-v2.vercel.app/biblio/researcher/add-publication/multiple/step-3/select-publications.html

## Outstanding questions:

- What information am I missing?
- What copy do we need specifically for doubles (please do not import – if you need to upload a full text, edit, ... please get in touch)

**Comment by mietcls** [comment]
@nicolasfranck Am I still missing something? Anniek mentioned CERN, would we like to add this to our scope?

**Comment by mietcls** [comment]
Sorry @nicolasfranck, yes! Autosuggest bamboozled me.

**Comment by emilyvandewalle** [comment]
The design proposals can be found [here](https://www.figma.com/file/YKfocx0xpkuuyQUa3qt70P/Biblio---GitHub-issues?node-id=3%3A9942)

## Design proposal 1: With extra selection step:

**Step 1: User chooses method to add publication(s)**

![image](https://user-images.githubusercontent.com/36261498/176651017-6ebc94b1-785b-4dbc-a4fd-0a78a6a9f4ac.png)

**Step 2: User chose to import via Bibtex file and uploads the file:**

![image](https://user-images.githubusercontent.com/36261498/176637571-4480a93a-777d-48e9-b167-d7c908ab60df.png)

![image](https://user-images.githubusercontent.com/36261498/176637752-a49cb54a-c1bb-46e4-a9f4-4e09408fc699.png)

- Once the file is uploaded, the user can see a list of records found and explicitly choose which records to import into Biblio.


![image](https://user-images.githubusercontent.com/36261498/176641812-cafba2bc-6c1c-4944-819d-cd40f0a21650.png)

**Step 3: User proceeds with selected set and completes description of each publication where needed:**

![image](https://user-images.githubusercontent.com/36261498/176656605-ee08026f-9a86-4137-ba2b-17081c695c1a.png)


**Step 4:  User publishes to Biblio (or saves as draft)**


## Design proposal 2: No selection step, (bulk) delete publications you don't want to add

**Step 1: User chooses method to add publication(s)**

![image](https://user-images.githubusercontent.com/36261498/176651041-9e112fd5-1d96-4e92-95e6-a65e144ac8a4.png)

**Step 2: User chose to import via Bibtex file and uploads the file:**

![image](https://user-images.githubusercontent.com/36261498/176637571-4480a93a-777d-48e9-b167-d7c908ab60df.png)

![image](https://user-images.githubusercontent.com/36261498/176644806-b508f0d8-50a8-4527-a5be-2c2a7a96c19a.png)

**Step 3:  User checks imported set, deletes unwanted publications (in bulk) and completes description**

![image](https://user-images.githubusercontent.com/36261498/176650782-d4a23d36-eac6-4bb6-8cd2-d7dae14dac8e.png)

- Error message at the top when the import failed for 1 or more publications
- List is divided into sections based on the import status
- User can delete unwanted publications from the Bibtex file by selecting them and clicking delete at the top (or individually delete them via the ••• more options, maybe in this step we could even directly show the delete button for each item?)

**Step 4:  User publishes to Biblio (or saves as draft)**

## Questions

- Which flow makes the most sense to add multiple publications? What are your thoughts on the extra selection step from proposal 1?
- Do you always have to manually upload the full text for each publication when bulk importing? 
- I've checked bulk actions across different apps and most of the time you can select all items within a page, but not across pages so you can only do bulk actions for the items _visible_.  What do you recommend?

**Comment by mietcls** [comment]
**Which flow**
I think the first flow makes the most sense because you can see more of the publications at once. We would need to figure later what information they need to be able to make informed decisions.

The second flow however has the summary on top; I’d love to use that one in the first flow as well: total, total of records that are fine, total duplicates and errors.

**Full text**
I think they do need to always upload the full text manually – it doesn’t upload with the DOI or WoS, correct @nics?

**Bulk**
- “Select all” -> we could make it clear that it is just the page, indeed
- I’m sure there will be people selecting multiple records throughout pages. The way you made it clear, by showing how many are selected and the actions combined, is very good to catch that case.

**Comment by emilyvandewalle** [comment]
Thanks for the feedback! 🙏 

I've updated the screens (on the reviewer side) to add publications [here](https://biblio-ugent-prototype-emily-v2.vercel.app/biblio/reviewer/add-publication/step-1.html) and this would be the [screen with the selection step](https://biblio-ugent-prototype-emily-v2.vercel.app/biblio/reviewer/add-publication/step-2.html).

So this would be the flow:
1. Choose method to add publication(s)
2. Upload document and select which publications to import (if multiple)
4. Complete description
5. Summary and confirm publication

**Comment by nics** [comment]
hi @emilyvandewalle that's indeed the desired flow

**Comment by mietcls** [comment]
Rethinking bulk import flow, separating this from completion flow
