### ISSUE TITLE
map "in copyright" (new) to "I transferred the copyright of..." (old)

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backoffice#433]
**Describe the improvement**
As we made changes to how the user needs to indicate whether there is copyright on a full text document, the copyright info entered in the new Biblio backend is not visible in the old Biblio backend.

To be able to see whether the check box was ticked in the old backend for as long a the two backends co-exist, map the check box to the "I transferred the copyright", if possible.

new Biblio backend: check-box "no license (in copyright)
old Biblio backend: "I transferred the copyright of..." selected from dropdown menu (See screenshot)

![image](https://user-images.githubusercontent.com/72742841/176199600-5add29de-c0cf-4f4a-871a-03e0d2a1b76f.png)

**Comment by nicolasfranck** [comment]
@sdebodt @nics seems like something to be copied to that new (uncontrolled) field `other_license`.

**Comment by mietcls** [comment]
Since we are going to launch the librarian backoffice and researcher frontoffice, this mapping is probably no needed anymore?

**Comment by mietcls** [comment]
What will happen to the "I have retained and own the full copyright for this publication"?
