### ISSUE TITLE
what to do with older publications that do not validate anymore in newer interface?

### ISSUE THREAD

**Issue by nicolasfranck** [ugent-library/biblio-backoffice#459]
Some records from the old interface do not validate anymore
in the new one, or probably do not validate anymore in the old
one as well (as no one has pressed save for those one, and the validation
rules have changed in the meantime).

- the new interface requires at minimum one ugent author for public records

e.g. https://biblio.ugent.be/publication/1020134
e.g. https://biblio.ugent.be/publication/1038346

- the new interface requires a year for public records

e.g. https://biblio.ugent.be/publication/123281 (probably does not validate in old interface as well)

P.S. do deleted publication NEED to be valid in the first place? It's not like they can be revived from the dead

**Comment by sdebodt** [comment]
Unless we see systematic inconsistencies or the number of records with issues is very small, I would ignore this for now. They would need to go to the Biblio reviewer team again to check whether they can be corrected. Certainly in case the records are old, I would say that there is no urgency to correct them.

For the given examples:
- https://biblio.ugent.be/publication/1020134: the author was affiliated to UGent in the past (as professor-emeritus), but probably the UGent affiliation was not added in Biblio
- https://biblio.ugent.be/publication/1038346: the [author is affiliated to UGent](https://telefoonboek.ugent.be/nl/people/801000590444), but also here the UGent affiliation was not added.
- https://biblio.ugent.be/publication/123281: the publication year field is not completed, however, the publication year is in the title of the book. It is imported from Aleph, so probably that went wrong during the import.

So for all, they would not be validated by the old backen and/or would be corrected during the review process.

**Comment by nicolasfranck** [comment]
@sdebodt that's the problem: one cannot store the record, without passing validation..

**Comment by sdebodt** [comment]
ok, I did not get that impact. Can you give an estimate on how many records are not validated? Can you also indicate the status of these records (private/public/locked)?

**Comment by nicolasfranck** [comment]
@sdebodt some 15K of public records lack ugent authors. Historic data..

**Comment by sdebodt** [comment]
ok, thanks @nicolasfranck. I will check with Myriam, Inge, Anniek... on what to do with them.

**Comment by sdebodt** [comment]
> @sdebodt some 15K of public records lack ugent authors. Historic data..

@nicolasfranck does this number exclude records that have the box "Published while none of the authors are employed at UGent" checked?

**Comment by nicolasfranck** [comment]
@sdebodt apparently I did my tests on development, which has only synchronized once, and which never received any thought. But anyway. I've include 11K of public records with missing authors.
[public_invalid.csv](https://github.com/ugent-library/biblio-backend/files/9433096/public_invalid.csv)

**Comment by sdebodt** [comment]
@nicolasfranck we are looking into the table that you provided.

There are publications with classification D1 (i.e. dissertations) that do not have a UGent author. However, the promoter/copromoter is affiliated to UGent. In this case the records should be validated and shown in the new interface and public frontend.

More feedback to come.

Can you also provide such a list for the records that do not validate because of other reasons than UGent affiliation (e.g. missing publication  year)?

**Comment by nicolasfranck** [comment]
@sdebodt that is a validation rule I haven't heard about;

**Comment by sdebodt** [comment]
I guess that dissertations with a UGent promoter and a non-UGent author are currently not validated. However, we propose to add this as a validation rule to be able to allow these records.

**Comment by nicolasfranck** [comment]
@sdebodt validation will be added for "classification", that is based on its type.
If you can read some code, the choices are mapped here: https://github.com/ugent-library/biblio-backend/blob/dev/internal/models/publication.go#L193

If I add validation like that, 171 older records do not validate anymore. See short list in attachment
[pubs_with_invalid_classification.csv](https://github.com/ugent-library/biblio-backend/files/9496556/pubs_with_invalid_classification.csv)

**Comment by sdebodt** [comment]
@nicolasfranck can you upload the csv file again? I get a "Not found" message.

Does it mean that from the 6K, only 171 are now not validated?

**Comment by nicolasfranck** [comment]
@sdebodt reuploaded. Those 171 records have nothing to do with that other list about the ugent authors. These are 171 records out of the whole set of records.

**Comment by sdebodt** [comment]
@nicolasfranck as discussed in Slack, I will share this list of records for which the classification does not match with the publication type with Inge to check whether we can do something with those records.

**Comment by nicolasfranck** [comment]
@sdebodt here a list of public records without year: 
[public_no_year.csv](https://github.com/ugent-library/biblio-backend/files/9498243/public_no_year.csv)

**Comment by sdebodt** [comment]
@nicolasfranck, unfortunately, we did not have the time to look into this further. It will be a thing for after doomsday ;-).

**Comment by nics** [comment]
I'm closing this and adding a list of current errors and proposed solutions to the main issue #668

**Comment by nicolasfranck** [comment]
And what with live publications that have files with zero size?

e.g. https://biblio.ugent.be/publication/154699

it even has a link to a pdf on libstore, that does not exist

**Comment by mietcls** [comment]
I closed this one because it was in the "done" pile, is that ok?
