### ISSUE TITLE
Contributor should have `ugent_id` instead of `id` to indicate membership

### ISSUE THREAD

**Issue by nicolasfranck** [ugent-library/biblio-backoffice#460]
Currently every contributor is marked as an ugent contributor when its attribute `id` is set
to a non empty value. As we're trying to add an `id` to every relation (link, lay_summary, abstract ..),
this becomes problematic.

Use `ugent_id`? And leave `id` as the internal id?

**Comment by nicolasfranck** [comment]
More context: I'm trying to remove the parameter `position` from as many routes as possible, but with contributors this is more difficult as I cannot just use `id` here now.

**Comment by nics** [comment]
closing this
