### ISSUE TITLE
"Corporate editor" missing for "Editor – book" and "Editor – issue"

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#480]
# Story

Right now corporate editor is missing from the authors and editors.

## Solution

Option A: We allow for a more free field (e.g. "first- and last name in one") when adding authors and editors, and make it clear you can add people or corporations.
Option B: We add a separate field.

## Context

In the old interface we had a separate field:
![Image](https://user-images.githubusercontent.com/1572885/187276262-41b70d64-a145-41d2-b35b-284ba0b5dc0f.png)

**Comment by nicolasfranck** [comment]
@nics @netsensei so just a missing fields in the model, for which mapping and handling is needed?

**Comment by nicolasfranck** [comment]
@mietcls ik veronderstel dat dit dan in dezelfde tab moet staan als de authors/editors?

**Comment by nicolasfranck** [comment]
> ## Solution
> Option A: We allow for a more free field (e.g. "first- and last name in one") when adding authors and editors, and make it clear you can add people or corporations. Option B: We add a separate field.
> 

Authors/editors/contributor all have a similar structure; they all have a first name, a last name; Not something one can do for a corporate editor where only field would be usefull (full_name?). Would make it unclear in the code.

**Comment by netsensei** [comment]
Aiming at feature parity => let's just copy this field "as is" into the new application. Later on, we can look at how to model this in a better way.

**Comment by nicolasfranck** [comment]
> Aiming at feature parity => let's just copy this field "as is" into the new application. Later on, we can look at how to model this in a better way.

Yes. Overthinking this, and trying to reinvent the contributors for 130 records would make things too complicated. Maybe they'll ask for extra fields in the future that only apply to corporate editors? Keep humans and corporations apart ;-)

**Comment by netsensei** [comment]
It's still a smell in our modeling. It's definitely something we need to keep on our backlog.

**Comment by nicolasfranck** [comment]
@netsensei @nics mm, if I were to add this to the contributor tab, that would require some rewrite. That corporate editor looks like a text repeat, and therefore needs a form and display, that we do not have there at the moment..

**Comment by mietcls** [comment]
@sdebodt apparently, in practice, corporate editor often remains a field left unused. Apart from where to put it or what it looks like (free text, pre-filled list or something that works like creators/authors/editors in general); we need to know if it is worth solving.
- Is the case you mentioned important both for publications and datasets?
- What do we do with the data? What do we rely on?

**Comment by nicolasfranck** [comment]
What is the current status for this issue. Still required?

**Comment by mietcls** [comment]
I'm a bit stuck on this one, so I postponed it. There's no way to input it if you want to anymore, but it is not used very often.

It could just be a field for now just like in the old Biblio, but there's no design ready.
https://user-images.githubusercontent.com/1572885/187276262-41b70d64-a145-41d2-b35b-284ba0b5dc0f.png

**Comment by mietcls** [comment]
Will take a look at this later when we start improving adding authors via suggestions
