### ISSUE TITLE
are relations between datasets and publications transferred to GISMO?

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backoffice#494]
**Describe the improvement**
To be able to measure the number of publications that have a dataset linked to it, the relation between publication and dataset records need to be made available to GISMO.  As observed in https://github.com/ugent-library/biblio-backend/issues/252, the frontend (public website) does not display relations between datasets and publications. Is this info available to GISMO via OAI-PMH?

**Comment by mietcls** [comment]
Will be fixed in https://github.com/ugent-library/biblio-backend/issues/389

#252 is done

**Comment by mietcls** [comment]
- Relaties tussen datasets en publicaties
    - Related item: other type has related object
    - 260 <relatedItem otherType=“hasRelatedObject” otherTypeAuth=“pcdm”>¬
