### ISSUE TITLE
Info text not visible on Safari: also not visible in the DOM

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#540]
# Bug description

Whenever clicking the "info" icon on safari, the content is not visible.
The pop-over is not visible in the DOM either. Cannot be fixed with css.

## On Safari:
![Image](https://user-images.githubusercontent.com/1572885/187275496-885c3398-0fac-4024-aba9-5641cb38c77f.png)
No DOM update below script tag:
![Scherm­afbeelding 2023-04-17 om 15 32 17](https://user-images.githubusercontent.com/1572885/232500016-e45b8532-235f-4cef-95fa-18191672c72c.png)

## On Chrome and Firefox
![Image](https://user-images.githubusercontent.com/1572885/187275497-a4fa4fe1-a74a-447d-a358-616fe6634ef7.png)
DOM update: popover element appears below script tag:
![Scherm­afbeelding 2023-04-17 om 15 32 30](https://user-images.githubusercontent.com/1572885/232500070-99e99675-1557-47d6-9c70-e290f08c9ee7.png)

# Steps to reproduce

1. Go to backoffice
2. Click on a publication
3. Scroll down to the "Web of Science type" field in the "Description" tab under "Publication details" 
4. Click on "info" button

## Expected behaviour
Pop-over
![Image](https://user-images.githubusercontent.com/1572885/187275497-a4fa4fe1-a74a-447d-a358-616fe6634ef7.png)

# System info
 - OS: MacOS Monterey 12.5.1
 - Browser:
   - Safari version 15.6.1 (17613.3.9.1.16)

**Comment by mietcls** [comment]
Review which help text should stay and what should go

**Comment by nicolasfranck** [comment]
@mietcls it is present in the DOM, but not in the DOM of requested page,
which does not include the body that is present in the description section.
That page is requested separately via HTMX. Look for the same request
with suffix `/description` in the network log:

<img width="1687" alt="Screenshot 2023-12-13 at 16 33 13" src="https://github.com/ugent-library/biblio-backoffice/assets/494636/35ce968f-a42e-4e9c-bedc-79523060c764">

flash messages are for flash messages. Tooltips do not require the round trip to fetch the messages as they are static

**Comment by nicolasfranck** [comment]
@mietcls It does however "work" with `data-bs-trigger="click"`, but then it won't go away anymore

**Comment by nicolasfranck** [comment]
Can I reopen this?

On backoffice.bibliodev.ugent.be I now see that the popover works, but when you want to navigate to a part of the text (e.g. to select a link in that box) the box closes again. I remember that we used popover in the past and then switched to on-click-behaviour exactly for problem

**Comment by mietcls** [comment]
Not needed for this one, there are no links to be clicked or important text to be copied. For the ones that do need that, we do not have a popover.
