### ISSUE TITLE
Dashboard: unclassified publications without department (or UGent only)

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#601]
# Story

As a librarian, I can view unclassified records to be handled in my dashboard, that are not assigned to a faculty just yet, or only affiliated to "University of Ghent"

## Context

We probably need to think this feature through and make sure it is faster somehow – perhaps by splitting it up.

Find more information about how the dashboard is built here: https://github.com/ugent-library/biblio-backend/issues/517

# Design
![Image](https://user-images.githubusercontent.com/1572885/189073176-44908a26-d603-49b2-9874-156bf697b308.png)

**Comment by mietcls** [comment]
# Out of scope: with upgrade "Latest update"
![Image](https://user-images.githubusercontent.com/1572885/188128844-2ce90334-bccf-4fc0-a209-5719b8c360b0.png)

**Comment by nics** [comment]
@mietcls this isn't feature parity i think

**Comment by mietcls** [comment]
@nics no it is not. I've moved it back.

**Comment by mietcls** [comment]
Anniek: "Nu doe ik exports van een bepaalde selectie (jaargang of zo ) naar xlsx, en dan op zoek gaan naar lege velden"

**Comment by netsensei** [comment]
@mietcls I have deployed this change to the test version. It's ready for you to be tested.

**Comment by mietcls** [comment]
@netsensei works on test 🙌! I see when we click through on a record without a department, it adapts the filters in the URL because we do not have a filter set for this. I will make (or find) an issue for this and make a reference to this issue.
