### ISSUE TITLE
Change Biblio naming "back-end" to "back office" on all platforms

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#640]
# Story

Before 15 November:
Currently the term "frontend" and "backend" are being used for the graphical user interface of the public facing page and the entry page. This is confusing for development terms, and in our communication to the outside world.

## Suggestion

We change the name to front-office for the public facing page.
We change the name to back-office for the entry page.

We do this before the new launch, because it's hard to get rid of a name once it's introduced beyond our inner circle.

# Success criteria
 
- [x] Domain names
  - [x] Ask for new domain names at DICT
  - [x] Need for entry point from Inuits, which IP addresses
- [x] Links
  - [x] backend.bibliotest.ugent.be -> backoffice.bibliotest.ugent.be
  - [x] backend.biblio.ugent.be -> backoffice.biblio.ugent.be
- [x] Communication
  - [x] Wiki's
  - [x] Documentation
- [x] GitHub 
  - [x] https://github.com/ugent-library/biblio-backend -> https://github.com/ugent-library/biblio-backoffice
 - [x] Docker Hub repository name
 - [x] (Env) variable naming in biblio-backoffice

# Question

Am I still missing something?
Am I underestimating imapct?

**Comment by nics** [comment]
backoffice.biblio.ugent.be
backoffice.bibliotest.ugent.be
both point to 157.193.244.212 (btnomadprd3.ugent.be)

**Comment by mietcls** [comment]
In the wiki some "how to" instructions are still about the "back-end" but I'm not sure if these should be adapted.

**Comment by nics** [comment]
finally done
