### ISSUE TITLE
Validation impedes changing the type of a publication

### ISSUE THREAD

**Issue by netsensei** [ugent-library/biblio-backoffice#646]
# Story

When a publication is published, you cannot change the type of the publication anymore.

_Because it messes with the validation_

## Success criteria

- [ ] After publishing (not locked), the publication type field is locked
- [ ] After publishing (not locked), a help-text below the field shows _"You can no longer change the publication type after publishing."_

# Context

Changing a type of a publication triggers validation of the record against the validation rules of the target type. This leads to weird circular logic which makes it impossible to change the type of a publication.

e.g. it's not possible to change the type from a "conference" to a "dissertation". When the user tries to save the publication details, they will receive a "you need at least one supervisor" error.  However, the publication is still of the type "conference" and therefor doesn't have the "supervisors" table / block under the "authors & editors" tab. So, it's not possible for the user to satisfy the requirement of having a supervisor before changing the type to "dissertation"

## Reproduce

1. Create a publication of type "conference"
2. Try to change the type to "dissertation". Notice the "needs a supervisor" validation error
3. Try to add a "supervisor" to the publication. Notice how that's not possible.

**Comment by nics** [comment]
@mietcls not allowing this for public records fixes the validation issues, but we need some tooltip text explaining the action is not possible for public records

**Comment by mietcls** [comment]
Okay, I'll put it on my name for design and then open it when that is created

**Comment by mietcls** [comment]
Communicate this is something we are working on.

**Comment by netsensei** [comment]
We should explain this as "not recommended" and "should only be used to correct records that have a faulty type (e.g. imported from WoS, etc.)".

**Comment by mietcls** [comment]
@netsensei  I've adapted it, placeholder copy is fine – if the functionality is there I can adapt it later.
