### ISSUE TITLE
Abstract is imported in pieces

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#679]
# Bug

Abstract is imported in pieces

![Image](https://user-images.githubusercontent.com/1572885/195011906-bfee6780-a9d2-4ccc-a5cb-6548b3f745c4.png)

![Image](https://user-images.githubusercontent.com/1572885/195012213-083b37b1-296c-451e-bc1b-ec9271ea226e.png)

## Steps to reproduce

1. Go to datasets
2. Import datatset 10.5281/ZENODO.4625218
3. See abstract

## Context

For 10.5281/ZENODO.4625218 
![Image](https://user-images.githubusercontent.com/1572885/195012145-e388aa5d-4e9e-4841-af20-000fbc96c15f.png)

Other example
![Image](https://user-images.githubusercontent.com/1572885/195012305-14407dd4-4813-4da7-94d8-8b99c8b472a9.png)

**Comment by netsensei** [comment]
When we pull data from Datacite, we get an JSON object with a `descriptions` field which contains 1 or more `description` objects. Currently we just loop over the descriptions and import each of them as a new abstract.

However, this is the raw data as pulled from Datacite:

```json
  "descriptions": [                                                                                                                                           
    {                                                                                                                                                         
      "description": "We present redshift-zero synthetic observational data considering dust attenuation and dust emission for the thirty galaxies of the Auri
ga project, calculated with the SKIRT radiative transfer code. The set of thirty Auriga galaxies reproduce a wide range of present-day observables, in particu
lar, disk-dominated galaxies with appropriate stellar masses, sizes, rotation curves, star formation rates, and metallicities. The post-processing procedure i
ncludes components for star-forming regions, stellar sources, and diffuse dust taking into account stochastic heating of dust grains. This allows us to obtain
 realistic high-resolution broadband images and fluxes from ultraviolet to sub-millimeter wavelengths. Please visit auriga.ugent.be for more information. This
 dataset contains images/SEDs for Auriga galaxies 16-20, i.e. 5/30 galaxies.",                                                                                
      "descriptionType": "Abstract"                                                                                                                           
    },                                                                                                                                                        
    {                                                                                                                                                         
      "description": "Visit www.auriga.ugent.be for further information. This project received funding from the European Research Council (ERC) under the Euro
pean Union's Horizon 2020 research and innovation programme, grant agreement No. 683184 (Consolidator Grant LEGA-C). AUK, MB, DBA, and AT acknowledge the fina
ncial support of the Flemish Fund for Scientific Research (FWO-Vlaanderen), research projects G039216N and G030319N. IDL acknowledges support from ERC startin
g grant 851622 DustOrigin. LC is the recipient of an Australian Research Council Future Fellowship (FT180100066) funded by the Australian Government. The radi
ative transfer simulations carried out for this work used the Tier-2 facilities of the Flemish Supercomputer Center (https:// www.vscentrum.be/) located at th
e Ghent University.",                                                                                                                                         
      "descriptionType": "Other"                                                                                                                                  }                                                                                                                                                         
  ], 
````

Notice the `descriptionType` field.  Clearly, the first description is an `Abstract`. But the second description is of type `Other`.  It's unclear how we should handle that. 

Per the [DataCite documentation](https://schema.datacite.org/meta/kernel-4.0/doc/DataCite-MetadataKernel_v4.0.pdf), `DescriptionType` can hold these values (See page 41 of the PDF for a definition of each value)

```
Abstract
Methods
SeriesInformation
TableOfContents
TechnicalInfo
Other
```

Suggestions:

* We could ignore all types and only import `Abstract` data.
* We could merge everything  that isn't an Abstract in `Descriptions` into a single Abstract. However, what if there are multiple Abstract, Other,... values? Biblio Backend allows for multiple Abstracts, but does DataCite provide multiple Abstracts? The DataCite doumentation isn't clear on how this is moddelled.
* We import "as-is" but that would require us to create new fields in Dataset just so we can match with DataCite.

**Comment by mietcls** [comment]
Great summary! This information helps a lot.

- For now the curators know this is an issue, which might also arise in different registers. They will manually fix this for now.

- Later:
  - We'll check what the needs are here, what information we want to capture. I'll also check with the curators.
  - Differentiating on type is a possibility, we can show that on long term in the abstract field? Merging seems dangerous, as sometimes these are instructions.
  - Language is perhaps also a differentiating factor?

**Comment by mietcls** [comment]
Issues
- What do other data registers have as options?
- What if we ignore certain other types; what is the impact?
- Merging in one field = what with "other languages"?

**Comment by nicolasfranck** [comment]
@netsensei @mietcls Datacite clearly puts several things into the attribute `descriptions`, and differentiates them by adding an extra attribute `descriptionType`. But only of those types are explicitly marked as an `Abstract`. "import-as-is" ("add all descriptions as abstracts") therefore looks incorrect, as we are the ones who interpreted it this way (the attribute says `descriptions` not `abstracts` ;-) ).
