### ISSUE TITLE
Scrolling bug in Safari

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#682]
# Bug

When you scroll and switch between tabs, the page sometimes appears blank on Safari

## Steps to reproduce

1. Open a publication or dataset
![Image](https://user-images.githubusercontent.com/1572885/195014599-010c7fdf-24d3-4b6f-abe8-84c7c73f80e0.png)

2. Scroll way down in a tab with a lot of info
![Image](https://user-images.githubusercontent.com/1572885/195015009-10905fe9-fd20-4b75-8e95-cd652c474e15.png)

3. Go to a tab with little info and see bug
![Image](https://user-images.githubusercontent.com/1572885/195015075-8eca190e-bcd4-46da-b711-aa9aa3912de8.png)

**Comment by nicolasfranck** [comment]
@mietcls does this still happen? I cannot reproduce this bug.
