### ISSUE TITLE
PDF download does not work

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#684]
This will be fixed with the migrations #668 

# Bug

The PDF download does not work for publications records created in the old production

![Image](https://user-images.githubusercontent.com/1572885/195018089-87d74632-128f-45d8-9598-453e28cfd802.png)

## Steps to reproduce

1. Go to a publication record that has been added in the old Biblio, with a full text attached
2. Go to Full text tab
3. Click the pdf link

**Comment by mietcls** [comment]
To be tested

**Comment by mietcls** [comment]
Is it possible to use the checksum of the export instead of creating new ones? Will save us 2,5 hours

**Comment by nics** [comment]
@nicolasfranck if the librecat biblio backend files command takes the json export as an argument instead of an id list we can use the already calculated checksums to save time
