### ISSUE TITLE
mods36 needs to be extended with relations info

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#695]

**Comment by nicolasfranck** [comment]
related datasets and related publications are already added as `relatedItem`:

https://biblio.ugent.be/publication/8759527.mods_36

but the record identifier is incorrect: 

https://github.ugent.be/Universiteitsbibliotheek/biblio/blob/master/views/export/_mods_36_body.tt#L263
https://github.ugent.be/Universiteitsbibliotheek/biblio/blob/master/views/export/_mods_36_body.tt#L272

**Comment by nicolasfranck** [comment]
See https://github.ugent.be/Universiteitsbibliotheek/biblio/pull/47

**Comment by nics** [comment]
identifier fixed
