### ISSUE TITLE
Hide "withdrawn" publications and datasets when linking them to each other

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#702]
# Story

When I want to link a publication to a dataset, or a dataset to a publication, I cannot select withdrawn records.

- To avoid confusion
- Apparently some records are listed as withdrawn for confidential records (mostly dissertations) so even the metadata cannot be shown to other researchers.

## Related
- [ ] Encourage people to search when linking datasets to publications and vice-versa with a message

## Out of scope
- [keep, do not fix] you can link a dataset to a withdrawn record or a publication to a withdrawn dataset – we do not know the intended use
- Only showing your own publications
- Smart sorting

# Screenshots
![Image](https://user-images.githubusercontent.com/1572885/195381849-5c060224-5770-4a96-86d2-a872af247179.png)

**Comment by nics** [comment]
@mietcls Also: how do we handle status changes of the linked record?

**Comment by mietcls** [comment]
I'd keep the links, they can remove it if they want.

It's mostly icky for those confidential records. This is not super high priority as there are not many confidential records listed as withdrawn (they used this because they had no other means to register it without showing it to the public).

**Comment by nics** [comment]
@nicolasfranck is this also solved by GetPublicationLiveDatasets & GetPublicationLivePublications?

**Comment by nicolasfranck** [comment]
@nics the functions you refer to hide deleted records, not withdrawn records, as those records are still visible everywhere in the interface, as compared to deleted records.

**Comment by nics** [comment]
@nicolasfranck actually only records where CanViewPublication/Dataset should be shown

**Comment by nicolasfranck** [comment]
@nics ok, but since we are here in a search context (searching over an entire index), we need to duplicate some of that logic from CanViewPublication (that only takes on publication into account)

**Comment by nics** [comment]
only showing public records
