### ISSUE TITLE
Remove references to datasets in publication if dataset is "removed"

### ISSUE THREAD

**Issue by nicolasfranck** [ugent-library/biblio-backoffice#723]
Also, the other way around: remove the publications from `related_publication` in the dataset, if someone "removes" the publication.

**Comment by nicolasfranck** [comment]
Possible problem: revival of a dataset or publication. In that case the references are gone. Real problem?

**Comment by nics** [comment]
@mietcls no, this is about what we do when someone deletes a dataset that in a publication's list of related datasets and vice versa

**Comment by mietcls** [comment]
To confirm, deleted records are not visible in the back-office anymore, right?

**Comment by nics** [comment]
@mietcls correct

**Comment by mietcls** [comment]
Related conversation:

Miet:
[@Nicolas Franck](https://libugent.slack.com/team/U2FSRUNBS)
 vroeg me zojuist over de relaties van soft-deleted records (vb. Dataset connected met publicaties en visa versa). Die relatie mogen we sowieso niet meer mogen tonen in de back-office als er een van beide deleted is.
- Nicolas vroeg wat we dan moeten doen met die relatie, echt weggooien of niet meer tonen? _(Ik vermoed, vanuit het standpunt dat dat een soft-delete is en databehoud, dat we die relaties niet weggooien, maar wel verbergen.)_
- Wat als we een record terug tot leven brengen?
  - Doen we dat, records weer tot leven brengen? _(Dat weet ik niet, wat is jullie ervaring hier)_
  - Als we dat doen, en de relaties houden, tonen we die relatie dan weer voor beide records? _(Ik vermoed van wel)_
    - Wat met relaties met records die ook niet meer bestaan? Doen we daar een check? _(Ik vermoed van wel, we tonen enkel de relatie met records die niet deleted zijn)_

Wat ik nu vooral lees is dat die relaties inderdaad blijven bestaan maar verborgen worden, we zitten alleszins nu niet met het probleem van empty parents ofzo.

nicolas:
ik zou ze gewoon verbergen, de intentie om de relatie te leggen is niet veranderd
tot leven brengen kan nu niet via de gui, maar is perfect mogelijk en deed ik vroeger soms via de cli als iemand per ongelijk iets delete

**Comment by nics** [comment]
@nicolasfranck isn't this solved by GetPublicationLiveDatasets & GetPublicationLivePublications?

**Comment by nicolasfranck** [comment]
@nics yes

**Comment by mietcls** [comment]
This still seems to show up on the card bottom right; it says one publication is linked while that one has been deleted.
![Image](https://user-images.githubusercontent.com/1572885/200587923-3a9634f6-cb27-40bb-8d66-9e117a2ce91b.png)
