### ISSUE TITLE
If there is no error but there is no record to display, show and error state

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#728]
# Story

"Something went wrong with the import" -> also for empty files

## Success criteria

- [ ] I can see how many records have been imported
- [ ] I can see how many records have not been imported
- [ ] When there are records that have not been imported, I can see which ones.
  - [ ] We show the ID of the ones with an error (WoS - DOI can be added later as it is very out of the ordinary that this happens)
  - [ ] We show how many empty ones

Can we give more information about what has not been imported, like an ID?

## Screenshots

When we can make a difference between successful or unsuccessful imports:
![Image](https://user-images.githubusercontent.com/1572885/197184735-1388e21b-1ab9-428c-9622-f66982877af6.png)

When we can not:
![Image](https://user-images.githubusercontent.com/1572885/197184774-f937f5a0-ee71-4ec0-8c69-1d3fa0cd9bd3.png)

### Problem
```
<div class="alert alert-warning">
    <i class="if if-alert-fill"></i>
    <div>
        <h4>2 out of 3 records have been imported.</h4>
        <p class="mb-2">There were one or more records that were empty, or were invalid. The affected records:</p>
        <ul class="mb-2">
            <li>#789ghi (double)</li>
            <li>#123abc</li>
            <li>#456def</li>
            <li>Empty record</li>
        </ul>
        <p>You can complete the information of the imported records before publishing, or save the records as a draft for now.</p>
    </div>
</div>
```

### No problem
```
<div class="alert alert-success">
    <i class="if if-check-circle-fill"></i>
    <div>
        <h4>3 out of 3 records have been imported.</h4>
        <p>You can complete the information of your records before publishing, or save the records as a draft for now.</p>
    </div>
</div>
```

### Alert agnostic from problem if impossible
```
<div class="alert alert-info">
    <i class="if if-info-circle-filled"></i>
    <div>
        <h4>2 out of 3 records have been imported.</h4>
        <p class="mb-2">There were one or more records that were empty, or were invalid. The affected records: #123abc, #456def</p>
        <p>You can complete the information of the imported records before publishing, or save the records as a draft for now.</p>
    </div>
</div>
```

**Comment by nics** [comment]
@mietcls @netsensei it' almost never possible to say how many records would have been imported had no error occurred
we can handle some cases more gracefully though:
- empty file
- an error occured after this record
- an error occured when processing this line (sometimes)
validation errors will almost never prop up
we could, with some effort, detect that no metadata was mapped

**Comment by mietcls** [comment]
We imported 2 records, and then something went wrong

**Comment by mietcls** [comment]
We can fix this when we are also working on the checks after import

**Comment by mietcls** [comment]
Working on it with quick import
