### ISSUE TITLE
Identify incomplete metadata fields - inform on completeness bars

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backoffice#73]
**Describe the improvement**
The progress bars indicate the completeness of the record (e.g. in red, with 1 bar colored and with the message "Missing fieds"). However, it is not clear at first glance which metadata fields need further completion. You need to expand each section and check. An improvement could be to indicate the completeness on the level of different metadata section (i.e. per section that can be expanded/collapsed).
Alternatively, the summary shown in the "add publication' workflow (but do not check them in green if there are missing fields)?

**Screenshots**
![image](https://user-images.githubusercontent.com/72742841/140752757-151f4f2a-0261-48d7-acb6-e273b3e334db.png)

**Comment by sdebodt** [comment]
I received several comments on these completeness levels so moving this to v2.

**Comment by sdebodt** [comment]
As this requires quite some work, we want to first remove the completeness bars to avoid confusion and frustration and later fully develop the functionality to view which fields are expected/missing for each bar.

Therefore, removing v2 again.

**Comment by sdebodt** [comment]
first implement for datasets

**Comment by mietcls** [comment]
Note: Business rules are still under discussion here, same for https://github.com/ugent-library/biblio-backend/issues/331

**Comment by sdebodt** [comment]
The completeness bars are already removed. This is an issue to add them again once it is clear how to.

**Comment by mietcls** [comment]
Will be replaced long term with a minimal quick-input form.
