### ISSUE TITLE
Migrating datasets licenses

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#734]
# Story

Migrating licenses from the old biblio, that have been input in two different systems, to the new Biblio

## Mappings

`-` = did not exist

| Created in old back-office | Created in testing back-end | New back-office | Front-office | Info |
| -- |-- | -- | -- | -- |
| _Empty selection_  | _Empty selection_ | _Empty selection_ | **Get in touch with the rights holder for reuse rights.** | There is no "in copyright" for datasets |
| - | - | The license is not in this list |  **A specific license has been chosen by the rights holder. Get in touch with the rights holder for reuse rights.** |  Note; we will get this info in the new back-office in the "other license" field. That other license field will be shown when "The license is not in the list" is selected. |
| - | Other license | Other license |  **A specific license has been chosen by the rights holder. Get in touch with the rights holder for reuse rights.** |  This field is only shown after "The license is not in this list" is clicked. <br>We will not show this in the front-office for now, but further analyse it later. |
| - | _Selected CC 1.0 or 4.0 license (see list)_ | _Selected CC 1.0 or 4.0 license (see list)_ | _Shows the chosen license_ | e.g. Creative Commons Attribution 4.0 International Public License (CC-BY 4.0) 
| The Open Data Commons Public Domain Dedication and License (PDDL) v1.0 <br><br> The Open Data Commons Attribution License (ODC-By) v1.0 <br><br> The Open Database License (ODbL) v1.0 | _Move to "Other license" field_ | _Move to "Other license" field_ | **A specific license has been chosen by the rights holder. Get in touch with the rights holder for reuse rights.** | We will select "The license is not in this list" and move this information to the "Other license" field.

_CC list: CC0 (1.), CC BY (4.0), CC BY-SA (4.0), CC BY-NC (4.0), CC BY-ND (4.0), CC BY NC-SA (4.0), CC BY-NC-ND (4.0)_

# Mapping context for the old Biblio licenses
`TBD` Map the current values to the spdx licenseIdentifiers, so they can be classified as open datasets for reporting to FRIS.

- The Open Data Commons Public Domain Dedication and License (PDDL) v1.0  = [PDDL-1.0](https://spdx.org/licenses/PDDL-1.0.html)
- The Open Data Commons Attribution License (ODC-By) v1.0 = [ODC-By-1.0](https://spdx.org/licenses/ODC-By-1.0.html)
- The Open Database License (ODbL) v1.0 = [ODbL-1.0](https://spdx.org/licenses/ODbL-1.0.html)

## Screenshots
Old Biblio option
![Schermafbeelding 2022-10-19 om 17 07 05](https://user-images.githubusercontent.com/1572885/196730158-2133eef5-352e-436b-b0d9-664594509bd9.png)

New Biblio options ("other license" only appears after selecting "the license is not listed here")
<img width="495" alt="Schermafbeelding 2022-10-19 om 17 07 53" src="https://user-images.githubusercontent.com/1572885/196730256-9910f7e1-deba-40c3-960f-7287677eb62e.png">

**Comment by nics** [comment]
@nicolasfranck is this done?

**Comment by nicolasfranck** [comment]
@nics https://github.ugent.be/Universiteitsbibliotheek/librecat/blob/master/ugent/lib/Catmandu/Fix/dataset_to_biblio_backend.pm#L171. So yes

**Comment by mietcls** [comment]
Test with Bilbiotest.ugent.be

**Comment by mietcls** [comment]
Check if values come through
