### ISSUE TITLE
Don't make new version if nothing has changed to a record (dataset or publication)

### ISSUE THREAD

**Issue by nicolasfranck** [ugent-library/biblio-backoffice#738]
Every time you hit "save", a new version is inserted into
the snapstore. That leads to unnecessary versions where
nothing has changed.

Some systems (like Rails) have internal tracking of old attributes
to detect changes, and only then update the record.

In the libadmin/settings, I always get "Nothing has changed" after
hitting save, which is an important note, I think.

@mietcls 
@nics

**Comment by nics** [comment]
@nicolasfranck yes aware of that, certainly something we will look into shortly after the release, the mutantdb way of doing things also makes it a lot easier to avoid this

**Comment by nics** [comment]
already fixed
