### ISSUE TITLE
Generate faculty field from department field during LibreCat export

### ISSUE THREAD

**Issue by netsensei** [ugent-library/biblio-backoffice#749]
The faculty field was previously generated from the department tree sub-field by ElasticSearch using the `copy_to` function in the ES schema (`publication.json`)  However, this does not work properly in tree context where a tree sub-field looks like this:

```json
{
    "id": "GE10",
    "tree": [
        {
            "id": "UGent"
        },
        {
            "id": "GE"
        },
        {
            "id": "GE10"
        }
    ]
}
```

In this example, we want to move the `GE` value out of the field and into the  `faculty` field.  ElasticSearch doesn't allow such fine-grained control. The ES community seems to recommends to solve this in the source data, rather then as a stored field in the indexed document.

As a result, previously, the `faculty` field wasn't populated during indexation. The  `faculty` facet remained empty, and the dashboard didn't work at all.

So far, this has been solved in the GRPC command line tool. Adding JSON records with a `department` field having a `tree` subfield will extract the `faculty` data from said `ŧree` field.

**Still to do:**

Importing data via the regular `go run main.go publication add < export.json` command (non-GRPC) doesn't take this into account. It expects that the `faculty` field is already present in the records exported from LibreCat.

- [ ] Add `faculty` field to the export from LibreCat based off the `department` field
- [ ] Test the regular `go run main.go publication add` command. Make sure that the `faculty` field is present.

**Comment by netsensei** [comment]
See also: 7ad06978

**Comment by nicolasfranck** [comment]
Now that we have a model "IndexedPublication", we can add faculty only in the indexed version of the publication,
rather than auto-updating faculty internally also in the source record?

**Comment by nics** [comment]
@nicolasfranck yes

**Comment by netsensei** [comment]
@nicolasfranck I have added a `faculty` property to `models.Publication`. But maybe that could be moved to `es6.indexedPublication`? If we do this, probably also needs some adjustments in the facets, right?
