### ISSUE TITLE
View personal details: is it possible to use the active profile?

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#756]
# Story

Whenever I want to view the profile of a person when adding them as a creator/author/editor/... I can see their current UGent profile

View personal details: is it possible to use the active profile?

## Steps to reproduce

- Go to a publication or dataset
- Go to people & affiliations
- Add creator/author/editor
- Look for Stefanie De Bodt
- Click view profile

## Screenshots

Search
![Image](https://user-images.githubusercontent.com/1572885/198044119-c3fec407-a82f-4f1b-ade2-0c5b4ccc6fbf.png)

Click view profile
![Image](https://user-images.githubusercontent.com/1572885/198044513-a1b8089f-cea2-4d15-8d0d-2bb1ec5b5020.png)

## Expected behaviour

- Link points to https://telefoonboek.ugent.be/nl/people/801001609348 (instead of https://telefoonboek.ugent.be/nl/people/001997224441)

**Comment by mietcls** [comment]
This still happens – I think I've made a mistake by asking the "first" ID. Can we know which one is active?


![Image](https://user-images.githubusercontent.com/1572885/200555624-4448effb-fc33-4ac9-9dfb-dd5efbd5cf97.png)
![Image](https://user-images.githubusercontent.com/1572885/200555855-79bf1933-8551-48aa-afa5-6d0799b3266e.png)

**Comment by nics** [comment]
i'm using the 'best' id, the one starting with 80xxxx
but even that doesn't always work apparently

**Comment by nics** [comment]
won't be able to fix this before the release, it needs changes to the people database to mark the active ugent id and then expose that to the backoffice

**Comment by nics** [comment]
@mietcls datamodel of new person service already accommodates this
