### ISSUE TITLE
ORCID not shown in certain cases

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#757]
# Story

When I see a researcher profile, I can see their ORCID ID when it is connected.

Sometimes it is not shown.

## Success criteria

- [ ] In the publications overview list card
- [ ] In the datasets overview list card
- [ ] In the publications people & affiliations overview cards
- [ ] In the datasets people & affiliations overview cards
- [ ] When adding a person as a creator/author/editor

### When adding a person as a creator/author/editor

Missing when adding a Stefanie De Bodt:
![Image](https://user-images.githubusercontent.com/1572885/198045573-5027c3c3-992a-4787-93bc-a38561eab61c.png)

Showing when looking for Patrick Goethals:
![Image](https://user-images.githubusercontent.com/1572885/198045744-08be1a19-291a-4b18-949d-c6eac5f8500e.png)

### In list card overview

Sometimes this works:
![Image](https://user-images.githubusercontent.com/1572885/198046971-9530e01b-2868-4fde-ba6f-18e1d96d3a5c.png)

Sometimes it does not:
![Image](https://user-images.githubusercontent.com/1572885/198047123-8d6ccf4f-3481-4023-b1f7-66fe65b1c5da.png)

### In people & affiliations cards

Sometimes it is shown:
https://eliot1.ugent.be/biblio-backend/dataset/01GGA2621J6WF4FT3MKNYEE66G?redirect-url=%2Fbiblio-backend%2Fdataset&show=contributors

![Image](https://user-images.githubusercontent.com/1572885/198046314-12e1aa8b-f17f-47b8-aa9d-9c95fdb85fa6.png)

Sometimes it is not:
https://eliot1.ugent.be/biblio-backend/dataset/01GGA7N06Q9HDW4P85MKNP75WE?redirect-url=%2Fbiblio-backend%2Fdataset&show=contributors

![Image](https://user-images.githubusercontent.com/1572885/198046438-eff800d2-95c7-4213-b5e1-4da59b631389.png)

**Comment by nics** [comment]
@mietcls I think her orcid is simply not connected in the test data

**Comment by mietcls** [comment]
I'll ask!

**Comment by mietcls** [comment]
I created my own ORCID account and connected it via the sandbox, however it does not show. This is not dramatic so I'll add it to the backlog.

![Image](https://user-images.githubusercontent.com/1572885/200546286-dbe3870b-0bb3-42c7-ac3f-62d1e2d5ebbb.png)

**Comment by mietcls** [comment]
Two separate problems.
