### ISSUE TITLE
Add phone number to contact page

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#769]
# Story

Add phone number so people can call Biblio on https://biblio.ugent.be/contact

## Screenshot
![Image](https://user-images.githubusercontent.com/1572885/198227743-55fcf418-33d3-4399-82c4-22d71cf5fec7.png)

## Implementation suggestion

`<p><a href="tel:092649572" class="phone">09 264 95 72</a></p>`

**Comment by nics** [comment]
oops

**Comment by mietcls** [comment]
Anniek mentioned she did not remember this; and she was fine trying it out and seeing whether people would still be misdirected, or if it is correct now. Is this okay to try it, or would we rather not take the risk to repeat the same problem?
