### ISSUE TITLE
[Third party reuse and grants] Add "Flanders Make" for Faculty "Economie en Bedrijfskunde"

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#775]
# Story

Add "Flanders Make" for Faculty "Economie and Bedrijfskunde".

The IDs I got from GISMO:
- ROR-id = https://ror.org/02ndjfz59 
- Internal GISMO UUID = a1b3277c-653b-11ea-a39e-adacc4b2e7a8

The titles:
- EN: Flanders Make
- NL: Flanders Make

# Context

There is a new CVAMO research group. Question we got from a researcher:

> "Sinds 1 jan 2022 werd een nieuw Flanders Make labo opgericht aan de Faculteit Economie en Bedrijfskunde. Dit heeft als gevolg dat een aantal professoren nu zullen publiceren met een dubbele affiliatie. Is het mogelijk om dit aan te duiden in biblio? Dit zou voor ons ook heel handig zijn voor het opvolgen van de publicaties van ons lab."

Long term we want to use ROR-id, the ones we get from GISMO.

**Comment by netsensei** [comment]
Is this a new SOC that needs to be added?

**Comment by mietcls** [comment]
Yes, I still need to beef this story, put it in the wrong column 😇

**Comment by mietcls** [comment]
We hebben een code nodig

**Comment by nics** [comment]
@mietcls if we want to add it now, we'll have to invent an id like 'FlandersMake'

**Comment by mietcls** [comment]
@nics I thought you meant IDs like ROR-id or the internal GISMO UUID. Is there an extra ID I should search for, or can we just make this?
