### ISSUE TITLE
Old Biblio is not updating

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#776]
Following issues have been reported:

- PDF 404 issues – these have been added before noon but still show a 404 in the afternoon when trying to view the PDF
  - record 7046785 (https://biblio.ugent.be/publication/7046785)
  - record 8542311 (https://biblio.ugent.be/publication/8542311)
- Changes do not flow through in front office:
  - 8534246 (https://biblio.ugent.be/publication/8534246) – it takes longer than usual (44 mins upon reporting)
- Time stamp issues:
  - record 8770835 is public, but the hour of editing is wrong

**Comment by nics** [comment]
@mietcls should be ok again

btw timestamps in the frontend can be more recent than in the backoffice
if they are older, then there is an indexing problem

**Comment by mietcls** [comment]
Aha, there was an indexing problem then. I'll recognise it in the future. Thanks.
