### ISSUE TITLE
mark deleted records that were once public as was_public=true, map to pdeleted in frontoffice

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#783]
# Story

Before 15 November:
mark deleted records that were once public as was_public=true, map to pdeleted in frontoffice

## Context

We will make the entire history accessible to us somewhere else, but not move it to the new back-office. This is way too much work, with little return. We’ll only create new history, and make sure people know when the record has been imported when we are actually going to show new history in the new back office.

Related: https://github.com/ugent-library/biblio-backoffice/issues/737

What we do need to keep is the deleted status for services such as GISMO and oai.
We can solve this by adding a field like "WasPublic".

**Comment by nicolasfranck** [comment]
Important: some records are now marked in biblio with `status=pdeleted`, while they were never public.

e.g. publication 1025960 is "deleted", and none of its versions were ever public, but oai_deleted was set to 1, and therefore interpreted as pdeleted.

**Comment by nicolasfranck** [comment]
See https://github.com/ugent-library/biblio-backoffice/commit/77b6048b6b3f6525bab4f3ed8536bd24bdf145e9
See https://github.ugent.be/Universiteitsbibliotheek/librecat/commit/8351b0cb2d18b35bd03edb19616ca2ff92dbc1ad
