### ISSUE TITLE
Replace “add publications” link with new back office link

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#786]
# Story

On November 15:
Link the link "add publications" in the front office to the new back office.

![Schermafbeelding 2022-10-27 om 17 15 48](https://user-images.githubusercontent.com/1572885/198329525-43ab903d-d4ae-4ef4-a032-d5a72d8f2fb9.png)

**Comment by netsensei** [comment]
![image](https://user-images.githubusercontent.com/105355/202184886-91fe657c-aab2-4ae4-85f2-131565a48b7c.png)

It's done! Closing this.

**Comment by mietcls** [comment]
Huzzah!
