### ISSUE TITLE
Data import test via remote client

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#792]
# Story

Data migration test via remote client

## Context

**Comment by mietcls** [comment]
@nicolasfranck we'd like to ask your help for this one, @nics will be able to help out with defining the whats and the hows :-)

**Comment by nicolasfranck** [comment]
reason: proto buf has its own model again, so there can be differences

**Comment by nicolasfranck** [comment]
Missing properties in proto model publication:

* `publication_status`

Changed attribute names in proto model publication:

* `dataset` instead of `related_dataset`

**Comment by nicolasfranck** [comment]
Missing property in proto model File:

* `URL`. But is that property actually used by anything?

**Comment by mietcls** [comment]
Will this one be finished by December or should we move it to next year's milestone?

**Comment by mietcls** [comment]
What's the status here? Should we split this up?

**Comment by nics** [comment]
this issue is out of date, pb definitionsa are now much simpler and there are some tests
