### ISSUE TITLE
Split out file resolving to a separate binary / service

### ISSUE THREAD

**Issue by netsensei** [ugent-library/biblio-backoffice#795]
File resolving for the frontend needs to be split into a separate binary / service.

Rationale: if someone mass downloads PDF's / hammers the frontend, the load gets deflected to a separate & simple service rather then the main backoffice binary / service.

**Comment by mietcls** [comment]
Is this one to be finished in the December milestone or later?

**Comment by nicolasfranck** [comment]
.. in which case you'll have to share sessions with the main application, not?

I am not sure if IO (input-output) can be influenced here, especially given the fact
that there is a single Traefik instance in front of everything that processes all data
going back and forth. So a mass download is still going to influence all traffic going
to the main application, I'm afraid.

**Comment by netsensei** [comment]
This concern cropped up right before launch of the application. In the past 3 months, file download requests incoming via the frontoffice didn't cause immediate performance issues with the backoffice.

So, we take this from the "ready to build" board and re-scope the issue.
