### ISSUE TITLE
Adapt prod HCL

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#809]
## Success criteria

- [x] Adapt domain name in HCL file (should be ok – to check)
- [x] GRPC 
- [x] Files config should still point to dev environment
  - [x] Make a copy of all files, let them point to prod (rsync)
- [x] Keycloak can point to production
- [x] Elastic search to development
- [x] Postgres to development
- [ ] Copy cronjobs (HCL file) – one container for production

**Comment by mietcls** [comment]
Use scripts @nics made tomorrow

**Comment by netsensei** [comment]
All done.

**Comment by mietcls** [comment]
@netsensei there's still one open, any idea if this needs to be turned into a new issue?

**Comment by netsensei** [comment]
That's done. This can be closed.
