### ISSUE TITLE
Add "Research disciplines" in addition to "Research fields"

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backoffice#81]
**Describe the improvement**
Currently, one or more Research fields can be added to a publication in the "Additional information" section by selecting a field from a predefined list. Instead of this predefined list, I want to choose from the Research disciplines (https://www.ugent.be/en/research/research-ugent/research-discipline.htm, https://onderzoektips.ugent.be/en/tips/00001823/) which are also used by GISMO and by FRIS (for FOSB KPIs).

**To Reproduce**
If something does not work as expected, which steps did you take?
1. Go to 'publication' page
2. Scroll down to 'Additional information'
3. Click on 'Edit'
4. Click on arrows in Research field text box

**Expected behavior**

**Screenshots**
biblio
![image](https://user-images.githubusercontent.com/72742841/141139979-80abd528-9200-4bc1-a900-58e9c6fed025.png)

gismo
![image](https://user-images.githubusercontent.com/72742841/141140062-2d706ce2-7b05-4857-b205-852aa55b5d75.png)

**Additional context**
These research disciplines will also be relevant for datasets.

**Comment by sdebodt** [comment]
- predefined list of research disciplines recommended for **publications** (for use by ECOOM): this is a [different, shorter list than mentioned above](https://researchportal.be/sites/default/files/block-attachments/2017-11/Ecoom_classificatie_publicaties.pdf) 
- predefined list of research disciplines recommended for **datasets**: [list also mentioned above](https://www.ugent.be/intranet/nl/op-het-werk/onderzoek-onderwijs/onderzoek/financiering-admin/administratie/gismo/onderzoeksdiscipline.htm)

source: https://researchportal.be/nl/disciplines

If this information can be automatically extracted based on the linked project, we would not need to ask the researcher to provide research disciplines.

**Comment by mietcls** [comment]
Need to rethink this with GISMO, as they already have this data – we might be able to reuse it. Following the only once principle.
