### ISSUE TITLE
Import css to remove white space on bottom of page 🥲

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#821]
# UX crash

**Note; this only requires a pull from Emily's prototype. It is already fixed there.**

Weird empty bar on the bottom of our pages appeared after removing the top warning bar

![Image](https://user-images.githubusercontent.com/1572885/202225202-fc3cecf4-c7c0-430d-a8a3-e9018f59f237.png)

## Solution

Get new css from Emily prototype https://github.com/ugent-library/biblio-ugent-prototype

**Comment by nicolasfranck** [comment]
@mietcls the white space bar is actually always there, as stated in the css for element `main`:

```

main {
    background-color: #fafafa;
    height: calc(100% - 4.8rem);
    overflow: hidden;
    width: 100%;
}
```

When you resize the height (e.g. by opening the javascript console),
the space used for the side bar also becomes smaller.

When I remove that line with `height`, the full height is always used for the side bar,
even when I open the javascript console.

As the html body uses display `flex`, it should not be problematic to remove
the height property?

**Comment by mietcls** [comment]
@nicolasfranck It is fixed with the pull of Emily her prototype – we just need to update the css on this repo. We just did not notice it on the test environment because of the topbar. No need to fix it anymore!

**Comment by mietcls** [comment]
@nicolasfranck is this something you can do, just updating the css (reeling it in from Emily's prototype)? Or does this need to be passed on to someone else?

**Comment by nics** [comment]
@mietcls i'll import it
@nicolasfranck i'll show you how next time we're in the bt
