### ISSUE TITLE
Open access not shown even when there is an open access full text available

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#823]
# Bug description

When an open access full text is added, the record still shows as "closed - private access" in the overview

## Steps to reproduce

1. Go to back-office
2. Look for record number 8766142 or record 
3. See access level in overview
4. See access level in detail page

## Screenshots

Overview of record number 8766142
![Image](https://user-images.githubusercontent.com/1572885/202403761-e67fce43-c959-4a9e-9e12-44057c5abb0d.png)

Access levels of documents for 8766142 
![Image](https://user-images.githubusercontent.com/1572885/202403840-2ec0bbc4-a8fa-4e89-860a-491d6e9b73af.png)

Overview of record 8753675
![Image](https://user-images.githubusercontent.com/1572885/202403912-1295b8e4-183a-42fb-aeaa-19bde86353a4.png)

Access levels of documents for 8753675 
![Image](https://user-images.githubusercontent.com/1572885/202404002-def52c5b-f235-4375-a3fc-c8bec5913a44.png)

## Expected behaviour

We see the access level of "the most open" full text (UGent only, Open Access, Embargo).

Access level is defined by the full text. If there is...
- at least one full text defined as open access, show open access
- an embargo defined for a full text, show embargo
- is at least one full text defined as UGent only, show UGent only
- only a private / closed access full text available, show private / closed
- no full texts, show "Full text missing" (nuance in #828)

Note; the idea of a "main" file is not used at this point.

**Comment by nicolasfranck** [comment]
Note: currently the access level is based on the "primary file", i.e. the first file with relation "main_file" that also has an access level set.

That primary file is now used for thumbnails.

@mietcls @nics @netsensei if the file for thumbnail and the one for access level can be different, then there can be some confusion, not? And even worse that you're showing something private. Imagine showing a thumbnail of a file with private access in the detailed view of the frontoffice, and having  one file below it that has access level "open access"

**Comment by mietcls** [comment]
The notion of "primary file" is not used here. For thumbnails we'll also have to revise that.
