### ISSUE TITLE
Faulty language code

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#824]
# Bug description

By our colleague at GISMO:

> We hebben ook 2 nieuwe publicaties binnengekregen waarbij de taal niet conform is.  
> 
> oai:archive.ugent.be:01GJ0K1XVVNK9AKTCYQKEBTBBY en oai:archive.ugent.be:01GJ0JXHZ39P13A6PX1FBBRX25. 
> We krijgen hier :  <ns2:language> <ns2:languageTerm authority="iso639-2b" type="code">en</ns2:languageTerm> </ns2:language> 
> We verwachten hier echter de waarde eng. (is geen iso639-2b code, maar een iso639-1 code, dus ik denk dat hier iets mis is gegaan?)

## Context

We should only use 3-letter-codes

**Comment by nics** [comment]
caused by mapping bug in doi import

- [ ] fix bug
- [ ] fix record metadata

**Comment by nics** [comment]
fixed
