### ISSUE TITLE
Show cover pages of PDF files as images in the front-office and the back-office

### ISSUE THREAD

**Issue by netsensei** [ugent-library/biblio-backoffice#825]
**Epic**

As a user,  I can see a thumbnail of the first page (cover page) of an uploaded PDF file. 

* Cover pages are visible in the front-office and the back-office applications in various sizes (thumbnails, overview size,...).
* Cover pages are visible depending on the access level for the file (e.g. not shown when a file is closed access)
* A placeholder is shown if a cover page image can't be generated from a PDF file.

**Additional notes**

This feature should be implemented as a separate service which (a) generates JPG/PNG bitstreams from a PDF, in various sizes and (b) acts as a proxy server serving these bitstreams to the backoffice application.

* [imagor](https://github.com/cshum/imagor) is a proven generator for images from PDF's.
* We'll need a building block that manages traffic and access to/from imagor.
* Security, scalability and performance are important concerns.
* We'll need storage which can act as a persistent cache for images. 

**See also**

#698

**Comment by mietcls** [comment]
Will fix this later when we have a thumbnail and file preview strategy, open for a long time
