### ISSUE TITLE
[GRPC Client] Add Keycloak-based authentication

### ISSUE THREAD

**Issue by netsensei** [ugent-library/biblio-backoffice#829]
**Story**

Basic authentication in de gRPC server/client is too limited if we want to build a cli client which can be distributed / used outside our team.  Replace basic authentication by token based authentication which piggy backs on an identity provider: Keycloak. 

**Todo**

- [ ] check the python example provided by our service provider.
- [ ] timebox build of a prototype integration in our gRPC service.

**Comment by nicolasfranck** [comment]
return json web tokens with authorization encoded?

**Comment by netsensei** [comment]
@mietcls Updates this per the conversation yesterday

**Comment by mietcls** [comment]
As we are not going to build a CLI client that will be used outside of our team any time soon; we will not prioritise this now.
