### ISSUE TITLE
Link to "Add publications" broken on "My publications" page

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#833]
# Bug

Link to "Add publications" broken on "My publications" page

## Steps to reproduce

- Log in on biblio.ugent.be
- In the dropdown, click "My publications"
![Image](https://user-images.githubusercontent.com/1572885/203015941-2e85ab02-930b-430c-a0fb-9c432a401a1b.png)
- On that page, bottom left click "Add publications"
![Image](https://user-images.githubusercontent.com/1572885/203015939-026284a1-aa71-47b3-827d-296ce26a6e3e.png)
- See broken link
![Image](https://user-images.githubusercontent.com/1572885/203015940-93982e09-09e6-409c-bf48-8d1f65a0efc4.png)

**Comment by nicolasfranck** [comment]
See https://github.ugent.be/Universiteitsbibliotheek/biblio/pull/48

**Comment by nics** [comment]
fixed
