### ISSUE TITLE
Researcher gets "page not found" when clicking on "add a publication"

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#839]
# Bug

Researcher gets "page not found" when clicking on "add a publication"

## Details
- Person: https://telefoonboek.prd.rad.ugent.be/nl/people/000181256220
- This person _can_ be added via authors & editors

**Comment by netsensei** [comment]
See: #840

**Comment by mietcls** [comment]
This one is confirmed and corrected, the other one I'm tracking until I hear back from the reviewers who are awaiting an answer
