### ISSUE TITLE
Merge author (same person according to OASIS)

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#841]
# Bug

Mismatch in author according to OASIS and Biblio team.
- UGent ID: 802001834649 (found in Biblio and in phone book https://telefoonboek.ugent.be/en/people/802001834649)
- Student number: 01010555 (only appears in OASIS, with an extra middle name).

They now appear as two people, but they are one.

Find information of full name in OASIS here: https://ugentbe-my.sharepoint.com/:w:/g/personal/miet_claes_ugent_be/EcOItJ8FTeFGihvzIPVA8goBTx4MdqtzesKZM1y-wGT2gA?e=Cc56Uy

Look for this person in record [2912314](https://backoffice.biblio.ugent.be/publication/2912314?redirect-url=%2Fpublication%3Fq%3D2912314%26sort%3Ddate-updated-desc&show=contributors)

**Comment by nicolasfranck** [comment]
@mietcls fixed already. I can only find one?

**Comment by mietcls** [comment]
@nicolasfranck do we also keep student numbers as well for a person (the OASIS one)? Anniek asked me, I think both numbers are supposed to appear with this person.

**Comment by nics** [comment]
@mietcls the ugent ids that begin with 00 are 0 padded student id's

**Comment by mietcls** [comment]
TIL what padded IDs are. So we are supposed to find 1010555? I can not right now.

**Comment by nicolasfranck** [comment]
@mietcls I cannot find 01010555 in the authority record, also not in his historic ugent id's. Seems like only his staff number is known. Is it even trust worthy to use a student number?

**Comment by mietcls** [comment]
I think it was a matter of completeness. I will report that we do not have this information in Biblio, as it is no longer available in LDAP.
