### ISSUE TITLE
[filters] Apply filters when clicking on "apply" and when clicking next to dialogue box

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#844]
# Enhancement / UX crash

Apply filters when clicking on "apply" and when clicking _next_ to dialogue box.

## Context

You need to now click on the checkbox, and then click "confirm". This is not standard behaviour, and when having to add a lot of filters this is annoying.

The confirm button does _not_ need to go away, the affordance can remain.
 
![Image](https://user-images.githubusercontent.com/1572885/203295195-bb6d5cad-2c1d-4575-824e-f6faea0c4e43.png)

## Expected behaviour

- [x] When adapting filters, and clicking on "Apply" it applies the selected filters
- [x] When adapting filters, and clicking next to the filters, it applies the selected filters

### Examples

Try filtering in Zalando:
https://www.zalando.be/kleding/
![Screenshot 2023-09-07 at 16 52 44](https://github.com/ugent-library/biblio-backoffice/assets/1572885/42bbdffa-030f-42d4-a6dc-c8ced4683e7b)

**Comment by nicolasfranck** [comment]
And it makes extra space available ;-)

**Comment by nicolasfranck** [comment]
But, as the page reloads instantly after you've clicked a checkbox, the filter box will close also,
because the initial page state is entered.

**Comment by mietcls** [comment]
Is there a way we can only let it close if you click besides it (or on a x?)

**Comment by nicolasfranck** [comment]
@mietcls of course that is possible, but looks more like unclear behaviour

**Comment by mietcls** [comment]
I'll create an example.

**Comment by mietcls** [comment]
Going to make sure this fits in a larger overhaul, so it makes sense in #519. Back to refinement.

**Comment by mietcls** [comment]
Updated, did more research on other platforms and added examples. Removed my superfluous comments.
