### ISSUE TITLE
Cannot remove department from record 8769813

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#845]
# Bug description

Cannot remove department DI05* (ceased) from record 8769813

## Steps to reproduce

1. Go to record 8769813, go to people & affiliations, go to departments
![Image](https://user-images.githubusercontent.com/1572885/203319862-f441d55d-0377-4572-804b-5465959702ca.png)
2. Open menu with three dots on the right
![Image](https://user-images.githubusercontent.com/1572885/203320108-15c17a33-6cf5-4f0a-96bf-4626e5355e8c.png)
3. Click remove department from publication
![Image](https://user-images.githubusercontent.com/1572885/203320205-9ac86226-001f-4bcf-82cb-9cf2324edabf.png)
4. Confirm
5. See it is still there
![Image](https://user-images.githubusercontent.com/1572885/203320298-ef7bbecf-2dcb-4261-ae49-0b6bbc9de115.png)

## Expected behaviour

Removed department

**Comment by mietcls** [comment]
Just checked the record, I can still see it – can you?
<img width="1322" alt="Scherm­afbeelding 2022-11-24 om 16 52 49" src="https://user-images.githubusercontent.com/1572885/203824948-fc3b62cb-7b88-4057-8948-c71fb30a1a6f.png">

**Comment by netsensei** [comment]
@mietcls This works for me when testing. Can you try again?

Issues are closed through our git commit messages. But that doesn't mean those commits have been deployed yet. It takes some time for fixes to be deployed. So, you probably tested this while the fix hadn't yet been deployed.

**Comment by mietcls** [comment]
@netsensei now it worked! I thought it was deployed. Is there a way I can know what is deployed after it's closed? Can we make our release notes more verbose?

**Comment by netsensei** [comment]
@nics @mietcls Yes, we should take some time to consider working with https://keepachangelog.com/en/1.0.0/ and working with release notes whenever we tag a release.

As for the "when" a deployment happens: currently, by and large depends on the urgency of the bugs we're working on, what we're currently working on. It's still a manual process. We could ping you whenever we do a release.
