### ISSUE TITLE
Allow "select all" and "deselect all" in filters with checkbox options

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#850]
# UX crash

You can now only click "select all" – which is blocking when you've accidentally checked 50 filter boxes or want to work quickly. Allow "select all" and "deselect all" from filters button.

# Context

## Steps to reproduce

1. Open filter with checkbox options, such as "year"
![Image](https://user-images.githubusercontent.com/1572885/203565081-7b778b38-66f7-4463-a682-53101a536a64.png)
2. Click "select all"
![Image](https://user-images.githubusercontent.com/1572885/203565270-e9e80cc8-d0cc-4fb9-b04a-8d8a7e6653d5.png)
3. Selecting one year now requires you to
  - A: refresh the page, which resets all filters, and you have to completely start over with your filter set.
  - B: uncheck each box you accidentally activated, which can take ages as well.

![Image](https://user-images.githubusercontent.com/1572885/203565756-6501b5d9-a4a0-447b-96fb-84db11b4b895.png)

_Note; you could argue clicking next to the box without hitting "apply" and clearing the list, but this pattern is also counter-productive. See #844._ 

## Expected behaviour

Change the button to "deselect all"

![Image](https://user-images.githubusercontent.com/1572885/203566262-b55d901c-2ab3-4356-ae0f-4016d2ab2ba8.png)

**Comment by nicolasfranck** [comment]
@mietcls what you prefer as label at startup? 

i.e. you load the page with some filters already enabled. e.g. filter "biblio status" has been set to "draft".

Set to "deselect all" when any is checked?

**Comment by mietcls** [comment]
- On start (clean page, no bookmarks), there will be no filters enabled (and you will see all unfiltered results) -> "Select all"
- The moment some are selected (this also applies when you surf to a bookmarked page with filters) -> "Deselect all" (like a reset, as you suggested)
- When all of them are selected -> "Deselect all" (reset)
- When none of them are selected, after the "Deselect all" action (reset), it is the same as on start -> "Select all"

Does this help / is it clear?

**Comment by mietcls** [comment]
Is this one done?

**Comment by nicolasfranck** [comment]
I guess so.
