### ISSUE TITLE
Cannot add project to record

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#853]
# Bug

Cannot add project to record (is this a bug on our side or on GISMO side?)

Project EOS 30650939 cannot be added to record 8766130
Note: it is still "in red" at GISMO – might not be something on our side.

Edit: for record 8758670, edited in the old Biblio, it did work:
![Image](https://user-images.githubusercontent.com/1572885/203826660-6a16ff38-0aca-43c0-b13c-841e36e81535.png)

## Context
_"Er is info tekort zodat het niet op https://research.ugent.be/web/home/nl zichtbaar is, of niet naar fris gestuurd wordt. De onderzoeker zou dat zelf moeten in orde brengen, maar dat gebeurt niet. Daarom sturen de GISMO-collega's dan wat uitleg naar die onderzoeker. 95% van de rode gevallen zijn wel goed te koppelen met biblio"_

## Screenshots

Console log while trying to add the project to record 8766130:
![Image](https://user-images.githubusercontent.com/1572885/204483233-0d15f1bc-b25e-421e-84d9-1ad88de0c6f1.png)
![Image](https://user-images.githubusercontent.com/1572885/203749342-8bfb75be-5c4b-479c-8893-06519c3afea3.png)

Project added to record 8758670 in old Biblio:
![Image](https://user-images.githubusercontent.com/1572885/203758005-e57c9c0a-2840-4923-9a95-d4d563a27469.png)

**Comment by netsensei** [comment]
Looks like a problem in the Frontend:

When trying to add the project, the backoffice connects with the frontend and tries to fetch detailed information about the project on this path `/project/<project-id>?format=json`. This works for fine for most projects, but not for projects with a space character:

`/project/EOS 30650939?format=json` yields an error 404 "Sorry, this is the void" error page.

Also, `client` calls in `backends.biblio`  don't error check against HTTP status codes; as a result, a working HTTP call against the frontend which returns a non-2xx HTTP response isn't caught and gracefully dealt with. This causes the UI to seem unresponsive.

**Comment by nicolasfranck** [comment]
Identifiers with spaces? Honestly, can that even work? What if someone accidentally adds a space in between the "words", and so creates a new identifier (which are unique)? If GISMO is the source of these identifiers, then we also think about talking with GISMO. And maybe we should do any validation on the identifiers we accept, not?

**Comment by mietcls** [comment]
This has become a bit more urgent as the reviewers are supporting someone here for a EU funder. What is the status? Can we fix it?

**Comment by mietcls** [comment]
Or do I start a conversation with GISMO here?

**Comment by nics** [comment]
@miet gismo is not the source of these identifiers, they assign a uuid
the identifiers we use are iweto id's (old project db , predating gismo)

stop gap solution: fix route regex to allow id's with spaces
long term solution: use gismo  uuid's everywhere (or own id if not every project we have has a gismo id)

**Comment by nicolasfranck** [comment]
@nics the problem is also that we use those iweto_id's as our foreign key, so we would have to fix those records that already have projects.

**Comment by nicolasfranck** [comment]
See https://github.ugent.be/Universiteitsbibliotheek/biblio/pull/50

**Comment by nics** [comment]
@mietcls can you test?
