### ISSUE TITLE
When uploading files, the file does not always appear, or becomes a separate block

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#859]
# Bug

When uploading files:
- file does not always appear
- or becomes a separate block.

Reported a couple of times but nobody has been able to catch a console log.

# Steps to reproduce

Hard to reproduce!

Upload files within a publication in the full text & files tab, see what happens:
![Image](https://user-images.githubusercontent.com/1572885/203998789-37ca136f-966b-4103-86da-f73b0ccdc857.png)

**Comment by netsensei** [comment]
I could reproduce this for this particular id: 2012599

1. Upload a new PDF to the publication.
2. Reload the page.
3. Notice how there's a dangling file at the bottom of the page.

Also, deleting the publication doesn't remove the file from the page. Hitting "delete" again gives me a version conflict. I need to reload the page to see a refreshed list without the offending file.

**Comment by netsensei** [comment]
Caused by a stray `</div>` in a template which confused htmx.  Also, noticed that deleting a file didn't refresh the list of files: fixed that too.
