### ISSUE TITLE
Remove default values for environment variables & flags 

### ISSUE THREAD

**Issue by netsensei** [ugent-library/biblio-backoffice#860]
The application keeps its configuration in environment variables which are read at runtime.  When an environment variable isn't set, the application falls back to a hard-coded default value. This is may lead to accidental errors when executing commands.

e.g. When the publication index name isn't explicitly configured, the application will fall back tot he value `biblio_backend_publications`.  ElasticSearch will silently automatically / dynamically create an index with that name without an explicit mapping. When bulk indexing, this will erroneously index all documents to the default index instead of the intended target index. This - in turn - may trigger cryptic errors.

The goal is to:

* Remove the default values entirely.
* The application should fail loudly if a required environment variable isn't set.
* (Optional): Provide a flag or a command which will list the environment variables in stdout when a command is executed.

**Comment by nicolasfranck** [comment]
@netsensei it depends on the type of the variables. For names of indexes or database connection strings, it makes sense not to provide defaults, but not for host, port, mode ..
