### ISSUE TITLE
Cannot add project EOS 30650939 to record 8766130

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#861]
# Bug

Cannot add project EOS 30650939 to record 8766130

## Screenshots

![Image](https://user-images.githubusercontent.com/1572885/204482398-e540864c-4130-4762-9a51-9201f57305d4.png)

## Steps to reproduce: 

1. Go to 
2. Look for publication 8766130 and edit
3. Scroll to projects and try to add project EOS 30650939
4. See error; it does not react

**Comment by netsensei** [comment]
Related to #853.

**Comment by mietcls** [comment]
I accidentally added this as a double and removed it from he project but not deleted it. Will close.
