### ISSUE TITLE
Journal article 1892081: classification does not match in front office with back office

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#862]
# Bug

Journal article 1892081: classification does not match in front office with back office

Journal article classification:
- "U" in back office: https://backoffice.biblio.ugent.be/publication?q=1892081&sort=date-updated-desc
- "C1" in front office: https://biblio.ugent.be/publication/1892081

## Screenshots:
Back office
![Image](https://user-images.githubusercontent.com/1572885/204488588-025bdf1d-a4c8-4a35-a6ea-b8a4c1d676da.png)

Front office
![Image](https://user-images.githubusercontent.com/1572885/204488513-d13e6e5d-71f7-4606-9557-dd965dd70842.png)

**Comment by nics** [comment]
@mietcls fixed by reindexing
was one of a small set of records that had a wrong classification and was autocorrected
