### ISSUE TITLE
GISMO: editorial material references

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#868]
# Question

GISMO: editorial material references

## Context

Email by GISMO team member:

> Het issue omtrent het related item van een Editorial Material betreft het feit dat wij als verwijzing “host” binnen krijgen, terwijl voor een publicatie van het type misc “Series” en dus ook een series-titel wordt verwacht.
> Deze instelling is weliswaar lang geleden ooit besproken geweest.
> Als er redenen zijn dat dit anders moet, dan hoor ik dat graag, want dat wil betekenen dat wij aan onze kant de verwerking gaan moeten aanpassen en dan vraag ik me af of er zo nog gevallen zijn of mogelijks gaan opduiken… Vandaar mijn verzoek om het online efkes in een overlegmomentje uit te klaren.

Thoughts:
Probably a mapping issue in mods xml.

**Comment by nicolasfranck** [comment]
Are there any examples for this? What is exactly expected, and what goes wrong?

What I see in the old code and new: if there is any `publication`  or `publicationAbbreviation`
in the source record, it generates  a field `parent.title` or `parent.shortTitle` respectively,
no matter what type of publication

**Comment by mietcls** [comment]
This is a "decision" from the past not to let these types of records flow through, we need to let GISMO know what fields would differ from the others publications they receive so they know what to expect. Do you have an overview of the fields here @nicolasfranck?

**Comment by mietcls** [comment]
We will fix this later.

**Comment by mietcls** [comment]
Will fix later, needs to be thought through. Tracked in #1099
