### ISSUE TITLE
{filters} Keep filter options from variable filters created by user-input clean, by removing outdated options and mistakes

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#872]
# Bug

Unused filter values, are still visible in our filters.

Example: why does year 3000 appear, without any records – while no filters are added?

## Steps to reproduce

1. Go to backoffice
2. Choose the Librarian role
3. Click on year and see the empty values
![Image](https://user-images.githubusercontent.com/1572885/203296312-35226608-87f9-4192-b9ad-472a88a0e45d.png)
![Image](https://user-images.githubusercontent.com/1572885/203296387-eacccdf5-aa66-40c5-9413-774cfb1ba102.png)
4. Click on librarian tags and see the empty values
![Image](https://user-images.githubusercontent.com/1572885/203296239-12675fa1-461f-42af-af3a-de4bc81c6aee.png)

These values are not traceable to any records that are visible to anyone.

Note: do not activate any other filters.

## Context

Example:

Librarian tags for "Gregory" have not been used in ages. This is similar for tags used by reviewers that do not work with us anymore.
![Image](https://user-images.githubusercontent.com/1572885/203296239-12675fa1-461f-42af-af3a-de4bc81c6aee.png)

Some tags for older years and future years were mistakes: 
![Image](https://user-images.githubusercontent.com/1572885/203296312-35226608-87f9-4192-b9ad-472a88a0e45d.png)
![Image](https://user-images.githubusercontent.com/1572885/203296387-eacccdf5-aa66-40c5-9413-774cfb1ba102.png)

**Comment by mietcls** [comment]
@nicolasfranck do you have some background information here? Can we do this?

**Comment by nicolasfranck** [comment]
Mm one cannot simply filter out "mistakes".

Secondly, it is always possible that a filter value is presented with zero results;
that is often the results of filters of another type that are active (i.e. you've previously clicked
on status "draft", and there are 0 draft publications for "year" 2022)

**Comment by mietcls** [comment]
I am still observing the second behaviour you're talking about here: https://github.com/ugent-library/biblio-backoffice/issues/873 – we've got the same issue for library tags (I am not talking about the other filters). I mean filters that will never be used again (like the year 3000 was clearly a mistake).

**Comment by mietcls** [comment]
Extra info: we show all values that can be found throughout our records – even the ones we can't see in our search. TBD which ones we should show.

**Comment by mietcls** [comment]
@nicolasfranck is there a way we can show only the values of records that we can actually see / manipulate, depending on each role?

**Comment by nicolasfranck** [comment]
@mietcls yes, by setting `min_doc_count` to `1`. That determines when a facet value (to select) is returned. We set this now to `0`, so that these values are returned always, even if the number of matched documents is zero.

But it comes with a price: if you select one value, values from other facets may disappear. e.g. you select year "2020", but there are no publications with "wos type" of that year, so facet "wos type" becomes completely empty, even without select values. Sort of "drilling down the results". And it also conflicts with the way the facets with fixed values work (e.g. status, classification ..)

**Comment by mietcls** [comment]
My question is simpler than that; I'm talking about the records you have editing / viewing rights for.
I don't mean influencing other filters by selecting an other. I also don't mean to adapt anything for filters that have preselected options such as WoS type.

I'm referring to user-input-dependent filters such as year and librarian tags.

If you have 0 filters selected, starting with a clean slate, seeing all of the records you can edit, and you still see filter checkboxes that are not in use by the documents you have editing or viewing rights for – the information is confusing.
e.g. librarian tags (Gregory) or year (3000) – if you don't have librarian tags in use by any of your documents you will not be able to edit or ask someone else to edit them, because they will never show up. As you can never see them.

Does this make things more clear?

**Comment by mietcls** [comment]
Since our last meeting I noted down that it is apparently a filtering issue here. We show values that are not tied to any records that can be visible to librarians, thus cannot be fixed (for instance, perhaps values tied to deleted records).

Can we make sure we only see filter values applied to records that we can actually see (not deleted) for these variable user-generated filters (regardless what we filtered on)?

@nicolasfranck – and I think I need @nics to make sure I'm using the right terminology and not assuming anything incorrectly.

**Comment by nicolasfranck** [comment]
@mietcls that is what I tried to say in that other issue, namely that I can possibly tie the values to the scope of the current logged in user (there are maybe other types of records that a user cannot see, therefore some values may originate from non deleted records); but that requires an extra queries to collect these tokens as it is not directly possible in elasticsearch

**Comment by mietcls** [comment]
@nicolasfranck that's actually a nice possibility for researchers – that would be nice too. If you have any suggestions outside of this scope (as an admin-godmode-overview-of-everything-librarian, we see these values appear) we can start a new issue.

**Comment by nics** [comment]
see https://github.com/ugent-library/biblio-backoffice/tree/feature/better_facets for a possible solution

**Comment by mietcls** [comment]
I pushed this one down a while ago because there were other priorities, I'd like to put this one on our priority list again.

There's a bit too much info right now @nicolasfranck @nics:
- What is the status?
- Is there any information in the thread above that needs to be taken into account for the scope of this issue?

For scope clarity, please refer to the updated issue on top.
If possible, keep side information out of this thread (start a new issue and delete "note to self" comments).

**Comment by nicolasfranck** [comment]
@nics is your solution as implemented in branch https://github.com/ugent-library/biblio-backoffice/tree/feature/better_facets still valid/applicable?

**Comment by nicolasfranck** [comment]
Possible solutions:

* Set `min_doc_count: 1`. This applies to facets `year`, `wos_type` and `reviewer_tags`. Consequence: other filters will reduce the values in the list. Solution: add those mentioned in the request parameters and set the bucket value to 0. This to inform the user of checked values that are used but have no effect anymore. This would however create a weird behaviour.
* Create two queries:
  * get all valid facet values for that facet in a subquery (without fetching documents)
  * add all valid facet values to the `include` facet parameter of the main query.

**Comment by mietcls** [comment]
Solution number 2 seems the most user-friendly one
