### ISSUE TITLE
{filters} Do not show filter options with 0 records for filters with variable use input

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#873]
# Story

Do not show filter options with 0 records for filters with variable input.

**This is _not_ a dynamic filter. We do not expect filters to disappear when an other filter is turned on and the results become 0.**
Example: When you have a filter that has been used once (5 years ago for instance, or per accident), but it contains 0 records today it should not be shown, as it will never show results.

When there are 0 filters activated, we still see these filter options, while none of the visible/searchable records carry that metadata.
![Screenshot 2023-09-13 at 10 31 35](https://github.com/ugent-library/biblio-backoffice/assets/1572885/48b964e8-03c6-452e-940f-d8846fbbe7d9)

## Success criteria
- [ ] When, looking at the entire record base, there are no records in use for a variable, we do not retain it.
  - [ ] Year
  - [ ] Librarian tags
  - [ ] WoS type

### Notes on informing better

[later] The level up from this for "year" could be:
- a slider input that informs people in a better way while giving them control over the output.
![Screenshot 2023-09-13 at 10 33 19](https://github.com/ugent-library/biblio-backoffice/assets/1572885/020a0c62-02b4-4c1c-93b8-5704c326aa8b)
- giving people the option to show values in between that are hidden
![Screenshot 2023-09-13 at 10 39 59](https://github.com/ugent-library/biblio-backoffice/assets/1572885/d809a905-cf79-4d1f-9581-baed4ed44c26)

**Comment by nicolasfranck** [comment]
@mietcls well like I said in that referenced issue, the facet value "0" does not always reflect the total amount of publications for that filter value. It can also mean that filters of another type are active. Only allowing values with more than 0, would hide too much.

**Comment by mietcls** [comment]
I am still observing this case, it is in refinement.

But it is information that should not always be visible.
For example:
We could add a button that says "show filters with 0 records" (don't mind the copy) for example. But this is cognitive load that is not helpful, and the lack of the filter also gives information.

**Comment by mietcls** [comment]
I will make a visualisation here

**Comment by nicolasfranck** [comment]
@mietcls what is the status of this ticket?

**Comment by mietcls** [comment]
@nicolasfranck I need to refine it, see status "To refine"

**Comment by mietcls** [comment]
Will close this as when refining it, it became clear we need to fix #872 first and then go from there. Useful information still to be found in here.
