### ISSUE TITLE
Split up meta data to scan quicker

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#876]
# Story

Split up meta data to scan quicker
It now slows down the reviewers because all information looks like it's in one label.

Related #877 

## Current status

Examples:

![Image](https://user-images.githubusercontent.com/1572885/205112077-7ea57162-02ca-4f2c-9adf-97bbb9de613f.png)

![Image](https://user-images.githubusercontent.com/1572885/205111457-70810133-3b06-4407-96f6-c27ee7a17f3d.png)

![Image](https://user-images.githubusercontent.com/1572885/205111623-b6bd1a9a-22d9-4ca5-8c99-fdbf74df2011.png)

## Outcome

Examples:

![Image](https://user-images.githubusercontent.com/1572885/205111875-9a45d035-813e-475e-a38b-a6e3edfee697.png)

![Image](https://user-images.githubusercontent.com/1572885/205111845-159c9b8e-3662-48d1-a090-4237f51c4edb.png)

Implementation suggestion:
Put each piece of information in a `c-meta-item` inside the `c-meta-list c-meta-list-horizontal`
![Image](https://user-images.githubusercontent.com/1572885/205111934-f902b14d-2244-4bb9-80a3-fb7740c1848a.png)

**Comment by nicolasfranck** [comment]
Some context: this is the way that [Publication#Reference](https://github.com/ugent-library/biblio-backoffice/blob/dev/internal/models/publication.go#L241) is implemented. Which now looks like
a citation.

**Comment by netsensei** [comment]
@nicolasfranck fyi: the Reference function is straight port from a similar function in Librecat. So, that's how it worked in Librecat. It was implemented as a simple citation generator.

**Comment by mietcls** [comment]
@nicolasfranck the way to format them is in the implementation suggestion. The class `c-meta-item` adds space between the different blocks of information, if they are located in the `c-meta-list c-meta-list-horizontal` parent.

**Comment by nicolasfranck** [comment]
@mietcls is on its way to test server. @netsensei cannot see the changes yet. Was merged yesterday?
