### ISSUE TITLE
Port librecat person transfer command

### ISSUE THREAD

**Issue by netsensei** [ugent-library/biblio-backoffice#881]
**Story**

As an adminstrator, I'm able to use a "transfer" command-line command which allows me to "transfer" publications between persons:

* Transfer the ownership of a record between persons (`User` field)
* Switch out person A for person B for a particular contributor role:
  * Authors
  * Editors
  * Supervisors 

**Success criteria**

- [x] Transfer ownership from person A to person B
- [x] Change person A to B in authors
- [x] Change person A to B in supervisors
- [x] Change person A to B in editors

**Additional information**

The command needs to be implemented using the non-grpc interface. It should look something like this, with first argument as the origin, and the last as the destination. Additional switches may control which parts of the records are affected.

```bash
$ ./biblio transfer <UUID> <UUID>
```

The command goes back to the Biblio Frontend Person API to fetch the person data based on the destination UUID. The new data is then interspersed in the record in a controlled fashion.

**Comment by nics** [comment]
@netsensei best to make it `biblio publication transfer`

**Comment by nics** [comment]
resolved by #885
