### ISSUE TITLE
LDAP sync: add field to person in Biblio which stores the current UGentID

### ISSUE THREAD

**Issue by netsensei** [ugent-library/biblio-backoffice#882]
**Story**

Add a field to the person model in Biblio Frontend API which stores the current UGentID.  For active users, this will make it less error prone to generate the phonebook link in the backoffice and frontend.

The field is populated when cron job triggers the nightly LDAP sync.

**Comment by mietcls** [comment]
Needs actionable example

**Comment by mietcls** [comment]
@netsensei Does this story belong in the person service? https://github.com/ugent-library/person-service

**Comment by nics** [comment]
@mietcls closing, already implemented in new person service
