### ISSUE TITLE
When adding an author, automatically put the cursor in the "first name" field

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#883]
# Enhancement

When adding an author, automatically put the cursor in the "first name" field.

Context: when librarians add people, it is an extra action to undertake and slows them down unnecessarily. If their cursor would already be in "first name" they can always use the tab to got "last name" if needed.

## Current behaviour

1. Go to any publication or dataset, and navigate to People & Affiliations
2. Click "Add (author, editor, supervisor, ...)"
3. To start searching for a person, first click on "first name"
![Image](https://user-images.githubusercontent.com/1572885/206179711-52eb1b3b-2635-4593-8ce0-ce05e1cf06ff.png)
4. Start typing
![Image](https://user-images.githubusercontent.com/1572885/206179785-351f3b2c-2343-42e0-9ff9-30af8d4d7eaf.png)

## Expected behaviour
1. Go to any publication or dataset, and navigate to People & Affiliations
2. Click "Add (author, editor, supervisor, ...)"
3. Immediately be able to start typing in the "first name" field
![Image](https://user-images.githubusercontent.com/1572885/206179785-351f3b2c-2343-42e0-9ff9-30af8d4d7eaf.png)

**Comment by nicolasfranck** [comment]
Why not for every form? This is done often.

**Comment by mietcls** [comment]
After discussing:

- We can focus on the input form where it makes sense
- The focus state on input, select, text area, .. each input field -> no exceptions. This needs to be in line with accessibility guidelines, HTML structure and tab order.
- For this we should probably make an epic and list the ones that need it (to be able to discuss with librarians/researchers if there's an issue or unclarity)
- the focus state needs to be more clear, which is a separate issue.

**Comment by nicolasfranck** [comment]
Some behaviour I noticed when autofocusing a select box:

![select_with_focus](https://user-images.githubusercontent.com/494636/206196933-7c143ed1-6b32-4021-a999-1cbfa28099aa.jpg)

Now use the scroll on your mouse:

![select_after_scroll](https://user-images.githubusercontent.com/494636/206196969-7e8bbd1f-93a8-4070-b080-5d4dac45c464.jpg)

So someone who uses his/her mouse to scroll down the page, accidentally scrolls down the selectbox.

To reproduce:

* type in the javascript console: `document.querySelector("select").focus()` and then close it
* scroll down or up

**Comment by mietcls** [comment]
Is this one done, or is there something missing?

**Comment by mietcls** [comment]
The first- and last name search boxes are now switched.

**Current behaviour:**

First name search box looks for last name, last name search box looks for first name.

**Expected behaviour:**

First name search box remains in first place and looks for first name, last name search box remains in last name place and looks for last name.
