### ISSUE TITLE
Handles do not resolve in front-office

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#887]
# Bug

Handles do not resolve in front-office for new biblio records. Probably only for datasets.

## Steps to reproduce

Example for datasets:

1. Go to https://biblio.ugent.be/publication/01GJT0ZR2N9Z940GGMX8QP5EYK
2. Click on the handle 
3. See it not resolve http://hdl.handle.net/1854/LU-01GJT0ZR2N9Z940GGMX8QP5EYK

![Image](https://user-images.githubusercontent.com/1572885/206657258-cd2f8da1-9b13-492c-8bef-3b7dc838127b.png)

## Context

Bug reported by our colleague:

> I'm not 100% sure yet if this is just a dataset thing right now (call it 95%), but I was looking at the front end of Biblio for our datasets, and I think something is broken in the generation/resolution of Handles for datasets published in new Biblio. 
> 
> For example, if you try to click the Handle on this entry (https://biblio.ugent.be/publication/01GJT0ZR2N9Z940GGMX8QP5EYK; which uses the new Biblio id) the Handle doesn't resolve. However, the Handles on older datasets, which were made in the old Biblio and have old Biblio ids, are fine (example: https://biblio.ugent.be/publication/8721401). 
> 
> I checked the publication side of things, and strangely, the Handles for publications with new Biblio ids work perfectly well, as do the old ones (new example: https://biblio.ugent.be/publication/01GKPDEMN5YQVPKXV7P9FFP4F0; old example: https://biblio.ugent.be/publication/8716798). Therefore, it seems to be a problem that is specifically affecting datasets made in new Biblio.

**Comment by nics** [comment]
embargoes are also not updated for datasets
