### ISSUE TITLE
'New open access publications' still mentions old OA policy & links to old webpage. Replace by "Ghent University has a policy setting out its vision and guidelines for scholarly publishing."

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#889]
# Story

Replace "Ghent University has implemented an Open Access mandate for scientific publications as of publication year 2010. Learn more" with

"Ghent University has a [policy ](https://www.ugent.be/intranet/en/research/impact/schol-publishing/policy-ugent.htm) setting out its vision and guidelines for scholarly publishing."

Current situation:
<img width="1440" alt="Scherm­afbeelding 2022-12-12 om 09 30 40" src="https://user-images.githubusercontent.com/1572885/206997820-4a4e2e30-9652-48e3-adc2-95a3a5b8c02c.png">

Desired situation:
https://www.ugent.be/intranet/en/research/impact/schol-publishing/policy-ugent.htm
<img width="1440" alt="Scherm­afbeelding 2022-12-12 om 09 33 11" src="https://user-images.githubusercontent.com/1572885/206998310-21bd8219-c858-4575-96c3-ea953fdc27cd.png">

## Implementation suggestion

```
<p class="mbottom-small">
  Ghent University has a
  <a href="https://www.ugent.be/intranet/en/research/impact/schol-publishing/policy-ugent.htm" target="_blank">policy setting out its vision and guidelines for scholarly publishing</a>
  .
</p>```

**Comment by nics** [comment]
fixed
