### ISSUE TITLE
Remove link to old demos and add support and trainings

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#892]
# Story

- [ ] Replace "Demo sessions" with "Support and trainings".
- [ ] Remove link to old demos and add support and trainings page.

## Context
<img width="1440" alt="Scherm­afbeelding 2022-12-12 om 09 48 40" src="https://user-images.githubusercontent.com/1572885/207001460-e0e1494a-c7a6-4a82-afe9-09472c140a60.png">

## Current link
Demo sessions:
<img width="1440" alt="Scherm­afbeelding 2022-12-12 om 09 45 26" src="https://user-images.githubusercontent.com/1572885/207000765-e651212c-e8ca-4e93-9ac0-5a324df5ab40.png">

## Desired link
Support and trainings: https://www.ugent.be/intranet/en/research/impact/schol-publishing/oa-support.htm

<img width="1291" alt="Scherm­afbeelding 2022-12-12 om 09 49 46" src="https://user-images.githubusercontent.com/1572885/207001659-dbaf0ac3-51f8-4e53-a385-47b0a33527eb.png">

<img width="1440" alt="Scherm­afbeelding 2022-12-12 om 09 45 39" src="https://user-images.githubusercontent.com/1572885/207000822-845804da-6cfd-4963-aadf-6955cf1e9d5a.png">

**Comment by nics** [comment]
fixed by https://github.ugent.be/Universiteitsbibliotheek/biblio/pull/65
