### ISSUE TITLE
Link "Publications" in footer does not work

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#894]
# Bug

Link "Publications" in footer does not work
<img width="481" alt="Scherm­afbeelding 2022-12-12 om 10 04 50" src="https://user-images.githubusercontent.com/1572885/207004959-e3b70aa5-c054-4c69-92c4-61dc7f6d55ae.png">

Questions:
- Where is it supposed to go?
- Can we do something similar for datasets?

## Steps to reproduce

1. Go to biblio.ugent.be
2. Scroll down to the footer
3. Click on "publications"

<img width="1440" alt="Scherm­afbeelding 2022-12-12 om 10 06 47" src="https://user-images.githubusercontent.com/1572885/207005323-9fef6177-1a72-4c53-8364-eb9b2814b5ae.png">

**Comment by nics** [comment]
fixed
