### ISSUE TITLE
Replace "Search publications" with "Search publications and datasets" in search bar

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#895]
# Story
Replace "Search publications" with "Search publications and datasets" in search bar

## Current situation
<img width="1440" alt="Scherm­afbeelding 2022-12-12 om 10 09 01" src="https://user-images.githubusercontent.com/1572885/207005792-01c784f3-3ed2-4fab-a951-e9e752c278a2.png">

## Desired situation
<img width="1108" alt="Scherm­afbeelding 2022-12-12 om 10 09 59" src="https://user-images.githubusercontent.com/1572885/207005997-e3ef27a5-b538-498c-b13d-2406799cb188.png">

**Comment by nics** [comment]
fixed by https://github.ugent.be/Universiteitsbibliotheek/biblio/pull/65
