### ISSUE TITLE
Make sure Biblio front-office also highlights datasets

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#896]
# Story

Make sure Biblio front-office also highlights open access datasets.

_[Help wanted] Is there a way to list open access datasets via a query or is this information that still needs to be added to the front-office?_

## Implementation suggestion

![Scherm­afbeelding 2023-04-06 om 10 38 15](https://user-images.githubusercontent.com/1572885/230323186-651810d8-02aa-47e7-a1e5-b9f075e420b0.png)

### Success criteria
_See code blocks below._

Replace text:
- [x] Change title on top "Recently added research" (from "publications and datasets")
- [x] Change subtitle "New open access publications and datasets" (add "and datasets")
- [x] Adapt line below research output list "View all open access publications and datasets."
  - [x] link to overview of publications (current existing link)
  - [x] link to subview of datasets

Change research output shown:
- [x] Show top 3 open access publications (you now see 5 items)
- [x] Show top 3 open access datasets (these are added)

Picture and credit
- [x] Change picture to scaleable picture and centre it (https://unsplash.com/photos/_kdTyfnUFAc)
- [x] Add credit link to photographer

#### Line below research output list

[Help wanted] Is there a way to list open access datasets via a query or is this information that still needs to be added to the front-office?

```
<ul class="list-unstyled mtop-default">
  <li>View all open access <a href="https://biblio.ugent.be/publication?q=file.access+exact+open+and+external+%3C%3E+1">publications</a>&nbsp;and&nbsp;<a href="https://biblio.ugent.be/publication?q=type%20any%20%22researchData%22&sort=year.desc&sort=relevance.desc&limit=10">datasets</a>.</li>
</ul>
```

#### Picture and credit

https://unsplash.com/photos/_kdTyfnUFAc

```
<div class="col-xs-12 col-ms-6 col-sm-6 image-container">
      <div class="bg-image-container bg-primary" style="background-image: url(/path/to/picture); background-position: center;"></div>
    <p class="mtop-small" style="z-index: 100; position: absolute; color:white; bottom:1rem; right:1rem;">Photo by <a href="https://unsplash.com/@ale_s_bianchi?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText" style="color:white; border-bottom-color:white;">Alessandro Bianchi</a> on Unsplash.</p>
</div>
```

## Context

The current Biblio front office does not highlight the datasets that are registered in the Biblio back office. This would make sure people have more awareness and appreciates our researchers work.

Where is it missing:
- Above the fold: only publications
<img width="1440" alt="Scherm­afbeelding 2022-12-12 om 10 14 55" src="https://user-images.githubusercontent.com/1572885/207007040-05f446b8-5c76-4d1a-86a2-fa663f950e7b.png">

- In the footer: no "datasets" link
<img width="1317" alt="Scherm­afbeelding 2022-12-12 om 10 15 17" src="https://user-images.githubusercontent.com/1572885/207007121-a15f530c-e876-4b65-8179-f89cb7b56f95.png">

Related #897

**Comment by verheyenkoen** [comment]
@mietcls Have any idea of how that should look? A new block below the publications block, like this:

<img width="1293" alt="image" src="https://user-images.githubusercontent.com/599538/230310930-c9b758a0-cd6c-4e2a-8722-252f4df76820.png">

**Comment by mietcls** [comment]
@verheyenkoen thanks for inspiring me!

I've created a mock-up based on your input – and took the liberty to fix the fact that everybody hates the skeleton. We'll see what the feedback is later, if it'll stir up some emotions ;-)

I'll adapt the issue!

![Scherm­afbeelding 2023-04-06 om 10 38 15](https://user-images.githubusercontent.com/1572885/230322870-b8499703-1817-4c09-8a40-2f7e6fb14077.png)

**Comment by verheyenkoen** [comment]
@mietcls I noticed none of the current publications of the "Research Data" publication type are open access. If you [filter for this type](https://biblio.ugent.be/publication?limit=10&type=researchData), the "Access" face type is gone. If you [filter for "open access"](https://biblio.ugent.be/publication?limit=10&file_access=open), the "Research data" facet is gone from the "Publication type" facet type.

So if "open access" is important for the highlighted section, I guess we should delay this ticket until we get some applicable data. Otherwise some of the labels may need to be changed.

**Comment by nics** [comment]
@mietcls @verheyenkoen to fix the filters you can now search on. dataset access level:
```
accesslevel exact "info:eu-repo/semantics/openAccess"
```

**Comment by verheyenkoen** [comment]
@nics So this should be the query behind the datasets hyperlink? https://bibliotest.ugent.be/advanced-search?limit=&q=type+exact+researchData+and+accesslevel+exact+%22info%3Aeu-repo%2Fsemantics%2FopenAccess%22

**Comment by nics** [comment]
@verheyenkoen yes, if you only want to link to open access datasets

**Comment by mietcls** [comment]
This seems to work as expected! Anything missing @verheyenkoen?

**Comment by verheyenkoen** [comment]
Don't think so. Is already being tested by Cypress (on bibliotest) btw: https://cloud.cypress.io/projects/or6diq/runs/1126/test-results/c01ba14c-ee2c-47fb-b5a3-d850c0e6cb30

**Comment by mietcls** [comment]
Great. Looks good on test as well. The honour is yours to check off the work you've finished! Then I know that I can test it for errors, and we can launch it.

**Comment by nics** [comment]
@mietcls this can be closed?
