### ISSUE TITLE
ORCID "Learn more" link is broken on https://biblio.ugent.be/orcid

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#899]
# Bug
ORCID "Learn more" link is broken on https://biblio.ugent.be/orcid

## Steps to reproduce

1. Go to https://biblio.ugent.be/orcid
2. Click "Learn more"
<img width="1440" alt="Scherm­afbeelding 2022-12-12 om 10 24 13" src="https://user-images.githubusercontent.com/1572885/207009080-78922cc9-5f74-45b7-87e1-a8000f3bd802.png">
3. See broken link
<img width="1440" alt="Scherm­afbeelding 2022-12-12 om 10 24 27" src="https://user-images.githubusercontent.com/1572885/207009124-f155bd24-e2fe-467f-b9d8-dcbedb73fd85.png">

## Desired situation
Link to https://www.ugent.be/intranet/en/research/impact/schol-publishing/orcid.htm

**Comment by nics** [comment]
fixed
