### ISSUE TITLE
Empty list item spotted in authors and editors – probably for UGent ID

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#900]
# Bug

There is an empty "li" item

## Steps to reproduce

- Go to Biblio, and choose a publication or dataset
- Go to people or affiliation
- Add author https://telefoonboek.prd.rad.ugent.be/nl/people/802004145067

![Image](https://user-images.githubusercontent.com/1572885/207019195-49d99376-9e29-4872-824e-f739df4f6834.png)

**Comment by netsensei** [comment]
The empty `<li>` shoul d contain the UGentID(s) of that person. The code assumes that UGent contributors always have an UGentID. However, if the data we receive contains an inconsistency, no UGentID(s), then an empty `<li>` will be shown.

I've added a check which will omit the `<li>` unless there's one more UGentID(s) present.
