### ISSUE TITLE
WoS import sometimes shows "J" instead of WoS type

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#903]
# Bug

In the new Biblio, whenever importing records via WoS, it does not always import the WoS type – even when it is available.

## Steps to reproduce
- Go to publications
- Import a set of records via WoS https://ugentbe-my.sharepoint.com/:t:/g/personal/miet_claes_ugent_be/EaUZbpjO1_pJpK1qoVKTUhEB54v8lozXK_x4Kmk3j14gmw?e=VyBxZC
- Go to publication details of one example record (in my case:(https://backoffice.bibliotest.ugent.be/publication/01GM2YYBE3KE98DXE28DC1F0QQ), scroll to WoS type
![Image](https://user-images.githubusercontent.com/1572885/207028316-6db3b25b-18ce-4721-88e8-4bc6750b019d.png)

- Double check one of the examples and see the language available in WoS (in my case: https://www.webofscience.com/wos/woscc/full-record/WOS:000717291300001)
![Image](https://user-images.githubusercontent.com/1572885/207028576-97b2628f-128c-49e1-bf45-59751cce251c.png)

## Context
Test example with 22 examples, none have language imported: https://ugentbe-my.sharepoint.com/:t:/g/personal/miet_claes_ugent_be/EaUZbpjO1_pJpK1qoVKTUhEB54v8lozXK_x4Kmk3j14gmw?e=VyBxZC

Record example in test environment (no edits done): https://backoffice.bibliotest.ugent.be/publication/01GM2YYBE3KE98DXE28DC1F0QQ
Record number in production environment (in review, probably edited): under construction

**Comment by netsensei** [comment]
@mietcls @nics Seems to work as intended?

WOS Type contains the type from the TY, DT and PT fields in the WoS import file.  The PT field contains values like "J", "C", "S" and others.  "J" stands for "Journal Article" per the documentation: https://images.webofknowledge.com/images/help/WOS/hs_wos_fieldtags.html

The old Librecat application has a fix which implements a WoS to Biblio mapping. I could give the decoder logic more scrutiny to see if the mappings happens correctly. Assuming that the imported data is consistent of course.

**Comment by mietcls** [comment]
@netsensei I'll put this on my name, need to investigate some side effects...

**Comment by mietcls** [comment]
Thanks for the input, we've come to the conclusion we will not fix this (especially with the "not starting from 0" mindset of the future in mind).
