### ISSUE TITLE
[manual datasets] Add field "Identifier type" for datasets

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#904]
# Story

Add field "Identifier type" to figure out which persistent identifier has been used to import or register a dataset. This way we can analyse which identifiers have been used most, so we can prioritise accordingly in the future.

## Expected behaviour
- [x] The label says "Identifier type"
  - [x] Whenever I import a dataset via DOI, the persistent identifier field is automatically set to **"DOI"**
  - [x] Whenever I manually add a dataset, the default is set to **"empty"**
- [x] List of identifiers visible (see more information about identifiers URLs in heading "List of identifiers and URLs":
  - [x] BioProject
  - [x] BioStudies
  - [x] DOI _(needed upon edit, so we can reuse this form)_
  - [x] ENA
  - [x] Ensembl
  - [x] Handle
- [x] Hide following identifiers for now:
  - [x] URN (needs a resolver)
  - [x] ARK (needs a resolver)
  - [x] arXiv (only for publications)
  - [x] BioSample (for samples)
  - [x] Genome
  - [x] GND (not sure for what)
  - [x] LSID
  - [x] PMID (only for publications)
  - [x] PMCID (only for publications)
  - [x] PURL (needs a resolver)
  - [x] RefSeq
  - [x] SRA
  - [x] UniProt (for data items)
  - [x] ORCID (only for persons)
  - [x] URL, URI?
- [x] The new field is positioned below the title, inside the dataset details
  - [x] In the detail page "view"
  - [x] In the detail page "edit" modal
- [x] Display identifier type in search page, in the record card meta-list – before the "View in external repository" link
- [x] Existing records have a "DOI" field, this needs to be migrated to the new Identifiers field

## List of identifiers and URLs

```
DOI
  URL scheme:   {scheme}://doi.org/{pid}
  PID example:  10.17605/OSF.IO/WDETY
  URL example:  https://doi.org/10.17605/OSF.IO/WDETY

BioProject  
  URL scheme:  {scheme}://www.ebi.ac.uk/ena/data/view/{pid} 
  PID example: HBJG01006080.1:17..107:rRNA
  URL example: http://ebi.ac.uk/ena/data/view/HBJG01006080.1:17..107:rRNA

BioStudies  
  URL schemes: www.ebi.ac.uk/biostudies/studies/{pid}
               www.ebi.ac.uk/biostudies/arrayexpress/studies/{pid}
               www.ebi.ac.uk/biostudies/bioimages/studies/{pid}
               _(they all resolve to the same structure, with or without extra prefix)_
  PID example: S-BSST7
  URL example: https://www.ebi.ac.uk/biostudies/studies/S-BSST7  

ENA 
  URL scheme:  {scheme}://www.ebi.ac.uk/ena/data/view/{pid} 
  PID example: LR796137
  URL example: https://www.ebi.ac.uk/ena/browser/view/LR796137

Ensembl 
  URL scheme:  {scheme}://www.ensembl.org/id/{pid}
  PID example: ENSG00000139618
  URL example: https://www.ensembl.org/id/ENSG00000139618

Handle 
  URL scheme:   {scheme}://hdl.handle.net/{pid}
  PID examples: 1854/LU-01H03BX2HH1YNS0KJHBK0T1WYV
                11509/142
  URL examples: http://hdl.handle.net/1854/LU-01H03BX2HH1YNS0KJHBK0T1WYV
                http://hdl.handle.net/11509/142

URN
  URL scheme:  {scheme}://nbn-resolving.org/{pid}
  PID example: urn:nbn:de:bvb:19-146642
  URL example: https://nbn-resolving.org/urn:nbn:de:bvb:19-146642
```

### On view
<img width="1006" alt="Scherm­afbeelding 2023-04-26 om 11 29 12" src="https://user-images.githubusercontent.com/1572885/234533721-f3bb9f35-0a2e-4992-918a-edb32a8eb7bc.png">

### On edit

For identifiers that can auto-generate links such as DOI
<img width="1256" alt="Scherm­afbeelding 2023-04-26 om 11 31 59" src="https://user-images.githubusercontent.com/1572885/234534398-b09d5ebc-e937-4a3c-9b23-64ad7f89c6a4.png">
For identifiers that can _not_ auto-generate links
<img width="1298" alt="Scherm­afbeelding 2023-04-26 om 11 32 26" src="https://user-images.githubusercontent.com/1572885/234534516-62e82110-0403-4ac2-9776-33548ea24052.png">

### In the search overview
<img width="871" alt="Scherm­afbeelding 2022-12-12 om 16 27 43" src="https://user-images.githubusercontent.com/1572885/207084865-0887bac3-b0c2-4668-bc05-281907506e87.png">
Use the `c-meta-list-item` class inside the `c-meta-list c-meta-list-horizontal`

## Extra information
[Datasite property](https://support.datacite.org/docs/schema-mandatory-properties-v43#1-identifier) – also used by FRIS
Gathered information from curators: [improvements](https://ugentbe-my.sharepoint.com/:w:/g/personal/miet_claes_ugent_be/Eeihtd6JCbhCkmHX-bKvxXsBUAFHxpfAEW5O0Jjzo1XwtA?e=Ht2bxX) and [structures](https://ugentbe-my.sharepoint.com/:x:/g/personal/miet_claes_ugent_be/EbMAiCQMYbRGgDn9eSxBJ7ABDHblAroSGQgloHAOlW6Bkg?e=Kixr8C)

**Comment by nics** [comment]
@mietcls question: do we really want an Other type? It's pretty easy to expand the list of known types.

**Comment by mietcls** [comment]
@nics thanks for the discussion this morning. I will incorporate the feedback and apply "fix it when it happens" 👌.

Question: I've added some of the PIDs that have been communicated in an [issue in the past](https://github.com/ugent-library/biblio-backoffice/issues/116). However I am not sure what we understand under this term (Global VS persistent? Aggregator VS repository?) from a development perspective (which seems different from the data curation perspective).

For instance, do we allow unique identifiers that point to that repository, like Handle (example http://hdl.handle.net/10934/RM0001.COLLECT.5223)? What's the difference between globally unique and persistent?

Some examples from the previous issues:
- http://hdl.handle.net/10934/RM0001.COLLECT.5223
- https://www.ebi.ac.uk/ena/browser/view/LR796137
- https://hdl.handle.net/21.11115/0000-000C-E12A-7
- https://ega-archive.org/datasets/EGAD00000000001

**Comment by nics** [comment]
We'll also have to look at naming consistency
PubMed ID, PubMed Central ID
vs
PMID, PMCID

**Comment by mietcls** [comment]
@nics I adapted the list of identifiers and added the needed information (examples, URL structures) under "List of identifiers and URLs". The naming has also been corrected for this list.

The identifiers that can be left behind for now I listed (and unchecked) in the list "Hide following identifiers for now:". 

Is this sufficient information or is something still missing for this issue?
