### ISSUE TITLE
[manual datasets] Add filters for identifier type for datasets

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#909]
# Story

Add filters in datasets for persistent identifier type

## Success criteria
- [x] It is added only for datasets
- [x] It is only visible for librarians
- [x] You can filter on identifier type, as described in #904  
- [x] It is added at the end of the row

# Screenshots
<img width="1310" alt="Scherm­afbeelding 2022-12-12 om 17 16 45" src="https://user-images.githubusercontent.com/1572885/207097413-3eaccad9-cb30-48e5-880f-23ae6c2384fd.png">

<img width="389" alt="Scherm­afbeelding 2022-12-12 om 17 16 37" src="https://user-images.githubusercontent.com/1572885/207097329-db8f4582-b27c-486b-b237-9598614ba36d.png">

**Comment by nicolasfranck** [comment]
TODO: 
* add index only field like "identifier_type" (multi valued). 
* recreate index

**Comment by mietcls** [comment]
This one does not work yet, when I reset filters it is still greyed out:

<img width="390" alt="Scherm­afbeelding 2023-06-05 om 18 00 08" src="https://github.com/ugent-library/biblio-backoffice/assets/1572885/8b5f9a3f-c56f-44c7-9386-10848ac6d769">

**Comment by nics** [comment]
@mietcls needed a reindex, works now

**Comment by mietcls** [comment]
Does work on Bibliotest, not on dev. Reindex needed on Biblio dev, not urgent.
