### ISSUE TITLE
Make "Document type" by default "Full text"

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#910]
# Story – Question

Can we make "Document type" by default full text?

## Context

We get a lot of helpdesk request that ask why our app keeps saying "full text missing" when they uploaded a file. It confuses them because in the old Biblio this was not an issue.

## Preferred solution

We will make the full text the default type.

### Current situation

![Image](https://user-images.githubusercontent.com/1572885/207261278-135b2550-1e73-4333-91b8-2d8cc0c55d49.png)

### Desired situation

![Image](https://user-images.githubusercontent.com/1572885/207259806-051163b2-3a19-4ad4-9fb8-a63ed13eaedb.png)

## Notes

We could
- make the document type by default "Full text" -> preferred
- make the document type field required
- create a different section for "other" files

**Comment by mietcls** [comment]
Problem:

When full text is selected, the second dropdown does not appear anymore.

What does work: full text is automatically selected
![Image](https://user-images.githubusercontent.com/1572885/208706415-428408bc-1524-4a98-a173-4ee639410d66.png)

Second dropdown only appears when you manually select something else, and then select "full text" once again:
![Image](https://user-images.githubusercontent.com/1572885/208706580-2cc9c418-5fd8-4b65-9c35-9ae57671ab1f.png)

**Comment by nicolasfranck** [comment]
So in this case we abandon the premise "do not preselect default values", right?

**Comment by mietcls** [comment]
@nicolasfranck no we do not, we make sure the second dropdown does appear when full text is preselected.
