### ISSUE TITLE
frontoffice handler: argument `updated_since` does not always work

### ISSUE THREAD

**Issue by nicolasfranck** [ugent-library/biblio-backoffice#911]
In the frontoffice handler to retrieve all publications or all datasets,
you can supply a parameter `updated_since`. This is compared to
the string field `date_updated` in the jsonb field in postgres.

Problem is though that `date_updated` is a regular string field,
and that is both contains timestamps formatted in zulu time or with
the time zone appended (vb. +02:00). The argument `updated_since`
is also a string field, so there are mismatches possible.

How to fix this?

Fix old formats (in zulu time) in place by casting them?
This would make the sorting correct

**Comment by mietcls** [comment]
I'll add issues to the biblio project in "to prioritise", in the future, could you add them as well? If it is not finished yet, you can always add them to "in refinement".

**Comment by mietcls** [comment]
@nicolasfranck what is the impact here on researchers and librarians, so we can help prioritise this issue?

**Comment by nics** [comment]
closing this, works correctly for our current limited use case
