### ISSUE TITLE
Cannot edit authors in record 01GM39KW0452VRM4T4QBRNT9XM

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#912]
# Bug

Cannot edit authors in record [01GM39KW0452VRM4T4QBRNT9XM](https://backoffice.biblio.ugent.be/publication/01GM39KW0452VRM4T4QBRNT9XM?redirect-url=%2Fpublication%3Fq%3D01GM39KW0452VRM4T4QBRNT9XM%26sort%3Ddate-updated-desc&show=contributors)

## Steps to reproduce

1. Go to record [01GM39KW0452VRM4T4QBRNT9XM](https://backoffice.biblio.ugent.be/publication/01GM39KW0452VRM4T4QBRNT9XM?redirect-url=%2Fpublication%3Fq%3D01GM39KW0452VRM4T4QBRNT9XM%26sort%3Ddate-updated-desc&show=contributors)
2. Go to people & affiliations
3. Check out the [missing] authors
4. Try to edit
5. See no reaction

![Image](https://user-images.githubusercontent.com/1572885/207324194-fffb86b9-b226-47fa-a8d6-1c47c135c9bb.png)

**Comment by nics** [comment]
fixed by https://github.ugent.be/Universiteitsbibliotheek/biblio/commit/f7c35e93291d804bc8457c06db1ebbabbee36176
