### ISSUE TITLE
"Ghost user" cannot log in

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#913]
# Bug

"Ghost user" cannot log in

A person is selected as an author in record https://backoffice.biblio.ugent.be/publication/8772003?redirect-url=%2Fpublication%3Fq%3Djurgen%2Bvan%2Blimmen%26sort%3Ddate-updated-desc&show=contributors

For more information, to protect GDPR, please ask access to this document (open to suggestions if there are better ways to share this information):
https://ugentbe-my.sharepoint.com/:w:/r/personal/miet_claes_ugent_be/Documents/Person%20management/Person-management-JVL-case.docx?d=wf9f0252c4979493bbfe782d6543e5d14&csf=1&web=1&e=P6MvUx

Detected problems:

- Cannot be found in our phone book
- Is selected as a UGent author – but without an ID
- There is an other person with the same name, with an ID
- There is a third ID floating around somewhere else

**Comment by nics** [comment]
fixed, user had multiple conflicting profiles
