### ISSUE TITLE
Project name appears with % character

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#917]
# Bug

Project name appears with % character.

Is this something we should solve structurally? It only appears once for now.

## Steps to reproduce
1. Go to record https://backoffice.biblio.ugent.be/publication/8762760?redirect-url=%2Fpublication%3Fq%3D8762760%26sort%3Ddate-updated-desc
2. Scroll to projects and see percentage here ![Image](https://user-images.githubusercontent.com/1572885/207384553-d5d2a65f-54f9-4eae-afc6-e330bb4813cc.png)
3. Try to add department, see it without %
![Image](https://user-images.githubusercontent.com/1572885/207385148-d155551b-7ad7-4afc-ac5f-31d42bce6d4a.png)

**Comment by netsensei** [comment]
We had some issues retrieving projects with spaces in EOS project codes (e.g. "EOS 000123456") from Biblio Frontend  initially.  The `%20` is an URL encoded space which seems to have found its way into the record.

Presently, adding the same project with the same EOS project code doesn't cause issues.

I also see that the same project has been added twice to the record: once with `%20` and once with a normal space. Removing the one with `%20` should be enough to fix this.

**Comment by mietcls** [comment]
@netsensei Okay, we can consider it fixed and refer to this issue might it ever happen again?

**Comment by netsensei** [comment]
@mietcls Yep. Let's close this one.
