### ISSUE TITLE
Wrong copyright statement is shown in Biblio front for record 01GKCEMZAK8H4P4WNWCRPC9ERT

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#918]
# Bug

The record 01GKCEMZAK8H4P4WNWCRPC9ERT has an open access full text, with a CC-by license.
All the information flows through correct, but the copyright statement: it shows no copyright.

## In the backoffice, the access level
https://backoffice.biblio.ugent.be/publication/01GKCEMZAK8H4P4WNWCRPC9ERT?redirect-url=%2Fpublication%3Fq%3D01GKCEMZAK8H4P4WNWCRPC9ERT%26sort%3Ddate-updated-desc
![Image](https://user-images.githubusercontent.com/1572885/207386300-bbb47793-d64b-41ae-817a-8d8ea1b33dab.png)

### Uploaded open access file
![Image](https://user-images.githubusercontent.com/1572885/207388654-c9e16c53-91e8-4deb-8ba0-42ee0de82742.png)

### Selected license
![Image](https://user-images.githubusercontent.com/1572885/207388930-b32c3e34-50e8-425d-bc8a-ba414a10c65b.png)

## In the front-office
https://biblio.ugent.be/publication/01GKCEMZAK8H4P4WNWCRPC9ERT

### Copyright statement
![Image](https://user-images.githubusercontent.com/1572885/207389120-9d66cc0c-a008-49f2-99f0-f9ff410d821d.png)

## Expected behaviour

The copyright statement is defined by the access level of the record.

- For publications, the access level of the record is defined by the full text, which you can see here: https://github.com/ugent-library/biblio-backoffice/issues/823 (see "expected behaviour")
- More information about publication licenses can be found here:
https://github.com/ugent-library/biblio-backoffice/issues/659

- For datasets, the access level is already on record level.
- More information about datasets licenses can be found here: https://github.com/ugent-library/biblio-backoffice/issues/734

**Comment by nics** [comment]
@miet fixed, publications now get the most open license as copyright statement
