### ISSUE TITLE
[urgent] "Roepnaam" does not flow through anymore in Biblio front

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#919]
# Bug

"Roepnaam" does not flow through anymore in Biblio front.

Example:
A while back, the "Roepnaam" has been edited by https://telefoonboek.prd.rad.ugent.be/nl/people/801002044030 in Apollo. This flowed through correctly in the Biblio front, until now.

## Context

Ticket number: 6919726

Geachte,
Een aantal jaar geleden contacteerde ik u met de vraag hoe we de weergave van de titel van Prof. ##### konden aanpassen. Onderstaand antwoord mochten wij toen ontvangen.

> Beste ####,
> De wijze waarop de naam van de onderzoeker wordt weergegeven in de auteurslijst van Biblio, wordt overgenomen uit het elektronisch telefoonboek. Indien u een wijziging wenst, kan u uw roepnaam wijzigen in Apollo (Personeel > Mijn gegevens > Persoonlijke gegevens > Persoonsgegevens: in dit vak rechts onderaan: Roepnaam wijzigen. Indien dat niet voldoende is dient u contact op te nemen met de collega's van DPO.
> Met vriendelijke groet,
> ####

Dit heeft Prof. #### gedaan, en dat was toen ook in orde.
 
Sinds enkele dagen staan nu echter enkele zaken dubbel vermeld, zie sceenshot in attachment `I can provide this, the last name is now repeated`.
 
Weet u hoe dit toch opnieuw kan aangepast worden ? Ze heeft reeds bovenstaande opnieuw gebruikt/heringesteld maar het gewenste resultaat blijft uit.

**Comment by mietcls** [comment]
An extra case popped up:

"De auteur wilt Lucero-Mareydt aangepast zien naar Lucero, maar in het systeem zit het dus juist (DPO) en in Biblio niet."

**Comment by nics** [comment]
@mietcls first case seems ok now?
second one is no longer active at ugent, so we don't get updates via ldap anymore; for these cases we can input an override in our db  (preferred_last_name) -> done

**Comment by mietcls** [comment]
@nics [First case](https://biblio.ugent.be/person/F7EB1496-F0ED-11E1-A9DE-61C894A0A6B4) indeed seems fine now, is this because of the sync?

The second case still shows the full name here: ![Scherm­afbeelding 2023-01-25 om 13 20 33](https://user-images.githubusercontent.com/1572885/214561806-a35bd425-3516-4171-9a40-aff83f2b9d25.png) – but the title seems correct. However, the title says it does not have any affiliation with UGent. https://biblio.ugent.be/person/FC3BA5D8-F0ED-11E1-A9DE-61C894A0A6B4
![Scherm­afbeelding 2023-01-25 om 13 23 59](https://user-images.githubusercontent.com/1572885/214562505-0ce34ec4-e952-49e6-864a-942438725439.png)

**Comment by nics** [comment]
@mietcls probably just took some time to filter down everywhere

Second case: name on person page is already ok, name in publication will be ok after reindex

**Comment by nics** [comment]
@mietcls probably just took some time to filter down everywhere

Second case: name on person page is already ok, name in publication will be ok after reindex

**Comment by mietcls** [comment]
Thank you for the clarification! Will follow up.
