### ISSUE TITLE
Certain fields are not included in xlsx export of biblio backoffice (by 16 January if possible)

### ISSUE THREAD

**Issue by dendpj** [ugent-library/biblio-backoffice#921]
**Describe the bug**
There are certain fields missing in the xlsx export in the biblio backoffice (librarian mode). 

**To Reproduce**
If I export excel files from the backoffice (in 'librarian' mode, biblio publications) with a tag e.g. 'ut to be confirmed', I get an excel file with more fields than before the migration. But certain 'old' fields are not included in the new export: 
- affiliation
- extern
- reviewer_note
- reviewer_tags
- status
- ugent_authors
- vabb_year

**Expected behavior**
It would be handy to still include 'affiliation', 'status' and 'reviewer_tags' in the export.

**Context**
fields in old export:
`['type', 'id', 'status', 'publication_status', 'classification', 'title',
       'year', 'isbn', 'issn', 'vabb_id', 'vabb_type', 'vabb_approved',
       'vabb_year', 'wos_id', 'wos_type', 'reviewer_note', 'reviewer_tags',
       'extern', 'doi', 'affiliation', 'esci_id', 'ugent_authors',
       'project_id', 'external', 'has_file', 'has_open_access_file']`

fields in new export:
`['id', 'type', 'author', 'ugent_author', 'editor', 'ugent_editor',
       'supervisor', 'ugent_supervisor', 'department', 'title',
       'alternative_title', 'publisher', 'place_of_publication', 'page_count',
       'page_first', 'page_last', 'isbn', 'issn', 'wos_id', 'wos_type',
       'classification', 'year', 'research_field', 'keyword', 'publication',
       'publication_abbreviation', 'series_title', 'volume', 'issue',
       'issue_title', 'edition', 'conference_name', 'conference_organizer',
       'conference_start_date', 'conference_end_date', 'conference_location',
       'defense_date', 'defense_location', 'journal_article_type',
       'miscellaneous_type', 'conference_type', 'license', 'other_license',
       'publication_status', 'language', 'doi', 'date_created', 'date_updated',
       'external', 'has_file', 'has_open_access_file', 'jcr_eigenfactor',
       'jcr_immediacy_index', 'jcr_impact_factor', 'jcr_impact_factor_5year',
       'jcr_total_cites', 'jcr_category_quartile', 'jcr_prev_impact_factor',
       'jcr_prev_category_quartile', 'project_id', 'project_title',
       'project_start_date', 'project_end_date', 'project_eu_id',
       'project_eu_call_id', 'project_eu_acronym', 'vabb_id', 'vabb_type',
       'vabb_approved', 'article_number', 'jcr_category', 'jcr_category_rank',
       'jcr_category_decile', 'jcr_prev_category_decile',
       'jcr_category_vigintile', 'jcr_prev_category_vigintile', 'esci_id',
       'locked']`

**Comment by mietcls** [comment]
@dendpj this was not picked up in time – the holidays and illnesses did not help. How much trouble are you in?

**Comment by nicolasfranck** [comment]
References

* https://github.ugent.be/Universiteitsbibliotheek/librecat/blob/master/ugent/config/route.yml#L4
* https://github.ugent.be/Universiteitsbibliotheek/librecat/blob/master/ugent/fixes/to_reviewer_xlsx.fix

**Comment by mietcls** [comment]
Are you picking this one up @nicolasfranck? Can you communicate with @dendpj about this?

**Comment by nicolasfranck** [comment]
* `extern` seems to be renamed to `external` already in the old code
* `affiliation` has been renamed to `department`
* `status` is indeed missing? Understandingly as the code was based on the csv export of biblio (frontend!) which only has public records.
* `ugent_authors` is now `ugent_author`
* `vabb_year` is indeed missing
