### ISSUE TITLE
Cannot search on certain record parameters

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#926]
# Story

In the current interface, we cannot search yet on certain information. This was apparently possible in the old interface:

- [x] ISSN
e.g. 2049-3630
- [x] E-ISSN
e.g. 2049-3630
- [x] ISBN
e.g. 978-3-16-148410-0
- [x] E-ISBN
e.g. 978-3-16-148410-0
- [x] Web of Science ID (this one could be new)
e.g. 000503382400004

- [x] We should be able to search with and without dashes.

Question: are there any extra details that should be provided to be able to perform this search?

## Context

I am not sure whether it is a bug or a feature, as I thought it already was possible before.

## Screenshots

Results when searching for an ISBN 9789403026701
![Image](https://user-images.githubusercontent.com/1572885/207837450-26288e6a-19f8-4e9b-8cf7-e134daec6595.png)

**Comment by nicolasfranck** [comment]
[commit reference mentioned above](https://github.com/ugent-library/biblio-backoffice/commit/8c9f6c9f3be5278d64ef7467936e1578f4a60eba) is a typo

**Comment by nicolasfranck** [comment]
Notes:

* when searching on a specific field (e.g. isbn), the search should be specific enough without the requirement that dashes are needed (978-3-16-148410-0 and 9783161484100 should return the same documents)
* just copying this into the "all" field will not solve this. The all field will split on "-" where the dash is present, and not where not present. So if one document contains "978-3-16-148410-0", and another "9783161484100" they will not be seen as one and the same. "9783161484100" will never find "978-3-16-148410-0" as the last was split, and the first not.
* (e)isbn and (e)issn require some normalisation as done earlier for lib.ugent.be as there are versions with check digits and without.

**Comment by nicolasfranck** [comment]
cf. https://github.ugent.be/Universiteitsbibliotheek/solr-lib-lludss/tree/master/src/main/java/lludss/solr/analysis

**Comment by mietcls** [comment]
ISSN, E-ISSN, ISBN and E-ISBN work on biblio test (not on production). WoS ID does not – was this already taken into account?

I'll wait for feedback about the dashes from the reviewers and curators.
 
I don't have access to https://github.ugent.be/Universiteitsbibliotheek/solr-lib-lludss/tree/master/src/main/java/lludss/solr/analysis

**Comment by mietcls** [comment]
Okay, I'll leave the technical implementation to you ;-)

Would you prefer to leave this issue open until the WoS search has been implemented, or create a new story?

**Comment by nicolasfranck** [comment]
@mietcls maybe add other fields too? There are lots of fields. For some we can just copy the data to the common search field `all` (where search is less accurate or the search is limited in capability like search with or without dashes)

**Comment by mietcls** [comment]
Can you give me some examples? We can create a separate issue for this.
