### ISSUE TITLE
Create a publication/dataset assign command

### ISSUE THREAD

**Issue by netsensei** [ugent-library/biblio-backoffice#928]
**Improvement**

We'll need a new `publication assign [pubid] [userid] [userid]` command.  This allows us to transfer a single publication from one person to another person.

The new `publication transfer` command allows us to re-assign publications in bulk. Consider person A having 3 publications and user B having 5 publications, transferring from A to B will result in B having 8 publications. However, it's not possible to reverse that operation. Transferring from B to A, will result in all 8 publications being re-assigned to A.

A separate command would allow us to cherry-pick the 3 publications that originally belonged to A and return them to A.

**Comment by mietcls** [comment]
I cannot test this, who can confirm this works?

**Comment by mietcls** [comment]
@netsensei Can you confirm this works and someone tested it? I think it's been used recently?
