### ISSUE TITLE
I cannot edit a record that has been registered by me but is from an other researcher (without admin rights)

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#931]
## In progress – to be refined

Gathered input:
- We do not want to make the exception to make legacy records editable by researchers
- Some librarians or temporary librarians only have a "researcher" status
  - They actually help out with "old" records (postkotje) 
  - You cannot publish these records from scratch, because there are no UGent authors linked in the database – these are very old profiles
  - You cannot edit legacy records created by other people, because crucial data is missing

Anniek is okay with this not getting a priority right now – the persons infrastructure is more important.

We might want to add profiles with different layers of access / editing rights in the future. For example:
- librarians that help out with "postkotje", but no other records 
- interns
- people with temporary needs

# Bug

I cannot edit a record that has been registered by me but is from an other researcher (without admin rights)

If possible, can this be fixed by Tuesday? If not, I'll communicate some plans have to change.

## Steps to reproduce

1. Go to Biblio
2. View as https://telefoonboek.prd.rad.ugent.be/nl/people/801001529425
3. Search for publication number 8770669 https://backoffice.biblio.ugent.be/publication/8770669?redirect-url=%2Fpublication
4. Try to edit it

None of the publications that were added by this person are editable by them – even if they are not unlocked.

**Comment by netsensei** [comment]
This record is marked as "legacy".  These records can't be edited by researchers. They can be edited by librarians. This user doesn't have a librarian role.

![image](https://user-images.githubusercontent.com/105355/208381044-9e4badaf-faf7-4e51-9f40-4e8ef1ae6722.png)

A record can not be edited by a researcher when:

* its status is "deleted".
* it's marked as "legacy".
* it's locked.
* the user didn't create the record.
* the user isn't added as an author, editor or supervisor.

The record can be edited by librarians, except when it is marked as "deleted".  Deleted records are kept in the database as a tombstone and shouldn't be visible via the search index.

**Comment by mietcls** [comment]
Thanks @netsensei!

@nics was there a reason to not let researchers edit "legacy" records? The person that needs to edit is not allowed to have a librarian account.

If we could remove that for legacy records, that would be great. Reason:
- People from the public services help out with adding and editing old records (postkotje)
- A lot of those records are old records, created before the new Biblio.
- Some got flagged as "legacy"
- People from the public services, without a librarian account, cannot edit these records.

**Comment by mietcls** [comment]
This is a hierarchy and rights management issue
