### ISSUE TITLE
[Urgent] Researcher cannot see all of the 12 publications in the back-office in the front-office

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#934]
# Bug

- Researcher
https://telefoonboek.prd.rad.ugent.be/nl/people/802004158104 
- has 12 public publications in the back-office (assigned as author)
https://backoffice.biblio.ugent.be/publication?q=guido+bartolini&sort=date-updated-desc
- can only see one in the front-office
https://biblio.ugent.be/person/39eb8225-5a39-11ed-94f6-eae236849690

Is this a "person" bug?

**Comment by nics** [comment]
@mietcls not indexed in frontoffice for some reason, ok after reindexing
