### ISSUE TITLE
Uploaded time of files is off

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#935]
# Bug

Uploaded time of files is off

TODO:  create separate time epic

## Steps to reproduce

1. Go to Biblio
2. Go to full text & files
3. Look at the time
4. Upload a file
5. See the time is off by one hour

![Image](https://user-images.githubusercontent.com/1572885/208708308-57b143fb-1378-467a-8aba-618bd936d932.png)

![Image](https://user-images.githubusercontent.com/1572885/208708287-85b6fbaa-cff5-4e67-8828-40e9ea90d826.png)

**Comment by nicolasfranck** [comment]
I can confirm this. Timestamp is created correctly in UTC timezone, but shown incorrectly (it should convert from UTC to local time)

**Comment by mietcls** [comment]
@nicolasfranck It's still off unfortunately, it was 17:13 on my machine

<img width="1017" alt="Scherm­afbeelding 2023-02-07 om 17 13 57" src="https://user-images.githubusercontent.com/1572885/217300435-5cf6ff0b-69dd-42e7-8c87-ae994d54d5c9.png">

**Comment by nicolasfranck** [comment]
Same here: https://backoffice.bibliotest.ugent.be/publication/01GRRB1X35W7WE5FB7W8KQKX9J?redirect-url=%2Fpublication&show=files

file was upload at 13:56, but it shows 12:56. Apparently "local" time means something different on the server. Will try to force it to "Europe/Brussels"

**Comment by nics** [comment]
@mietcls what seems most intuitive to you?

- show utc time with timezone indication
- show brussels time
- show local time of the user (extract timezone from request)

**Comment by nicolasfranck** [comment]
I would always add timezone information at the end. 
Just keeping utc as our default would just anger 99% of our users, not? They would always have to do the math.

**Comment by mietcls** [comment]
@nics showing the local time of the user is the best option, as we don't know where they are. People usually point it out when they notice the hour is not the same on the device they are using. Devices use the local time as well.

**Comment by mietcls** [comment]
I'm also going to create an issue to fix the date notation for records later – the "9 months ago" is not useful for the reviewers nor researchers at this point (oldest record we can find)

**Comment by mietcls** [comment]
Was the global default already added?

This one was 2 hours off:

![Image](https://github.com/ugent-library/biblio-backoffice/assets/1572885/fedcd294-ef00-44e2-8a4d-f15c2f4e6b35)
![Image](https://github.com/ugent-library/biblio-backoffice/assets/1572885/dcb6455c-5e7f-451e-aff6-2d3c9496bca2)

**Comment by mietcls** [comment]
For documentation purposes: does this include daylight savings time? If not, it might be off:

![Image](https://github.com/ugent-library/biblio-backoffice/assets/1572885/856cffb2-d9fd-47e0-af93-92e03764277c)

**Comment by nics** [comment]
sprig date function was the culprit
