### ISSUE TITLE
[Urgent] "Updated by" is broken for publications

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#936]
# Bug

EDIT: "Updated by" is broken for publications
_– older issue: "Updated by" is broken for datasets and often does not work for publications_ -> this is no longer true for datasets. It now works. Reason unknown.

## Steps to reproduce

1. Go to Biblio
2. Go to publications
3. Scroll through the records

## Screenshots

Publications missing "updated by"

![Image](https://user-images.githubusercontent.com/1572885/208912701-8d8d49a3-056d-4d1d-847d-82481a7f5cfd.png)
![Image](https://user-images.githubusercontent.com/1572885/208912702-1c634d88-b8ff-488d-82d2-211fc16f577f.png)
![Image](https://user-images.githubusercontent.com/1572885/208912700-00cbccdd-2db7-44ba-87c3-114bb5aa3f9b.png)
![Image](https://user-images.githubusercontent.com/1572885/208912703-f969572b-d24b-4684-9153-48cffd61426d.png)

### Older information

On 21 December, datasets that had been updated 21 hours ago missed the "updated by". This is no longer the case.

![Image](https://user-images.githubusercontent.com/1572885/208912647-d8d50650-2ee6-48d8-bda3-ce69be20cd23.png)

**Comment by mietcls** [comment]
Something to shoot at:

Can we...
1. show a timeline of updates?
  1. Which information do we already have at hand? Is this feasible as a small first step?
2. show "automated system" updates?
  - What actually happens when "the system" updates? Can we word this more specific?
3. show the name of the last human being that updated the record, if an automated update happened?

Example:
![Image](https://user-images.githubusercontent.com/1572885/214292098-087607be-d10c-4868-a7cf-c7eb2d762e93.png)

More information we could show:
![Image](https://user-images.githubusercontent.com/1572885/214292027-585a0f36-c44c-40bb-8a28-0f0ea2e3a15e.png)

**Comment by nics** [comment]
@miet
we can already show a simple timeline page using database versioning

to show the correct last edited by in the search results we need two extra fields in the model:
- a new string field with the last human user id
- a new timestamp field with the time a human last touched the record

I would move messaging to another epic, so we can think about how best to approach this (add a simple inline array of comments, farm out to a chat system etc)

**Comment by mietcls** [comment]
@nics thanks for the background. I will start moving this topic. In the meantime, is there a way to approach the above issue without having to solve the entire system (messages, timeline, notifications, ... – this ties into a lot) already? Because the current workflow is holding review work back, as they don't know who was responsible for creation / updating the record last.

**Comment by nics** [comment]
@miet yes adding those 2 fields and updating some logic will fix that, i'll start looking into it

**Comment by nics** [comment]
@mietcls what is the difference in behaviour between datasets and publications?

**Comment by mietcls** [comment]
@nics Oddly enough, datasets does not seem to have this issue any longer? I am not sure what the "real" difference is. Now only publications have the issue. I am not sure why it is fixed in datasets now.

**Comment by nics** [comment]
@miet well, datasets don't nullify the user field on system update as publications do, but then the last edited date is not as expected. I'm fixing both.

**Comment by mietcls** [comment]
@nics thanks a bunch for finding that out and fixing it 🙏

**Comment by nics** [comment]
fixed, see commits above
