### ISSUE TITLE
Filter "non-UGent" does not work

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#937]
# Bug

Filter "non-UGent" does not work. We get irrelevant results

## Steps to reproduce

1. Go to biblio, publications
2. Use the filter "UGent", check "non UGent"
![Image](https://user-images.githubusercontent.com/1572885/208926290-110df266-06e5-479d-a166-d67ca43d775d.png)
3. Apply filter and click open the first result
https://backoffice.biblio.ugent.be/publication/01GMNAQC9425TKCGS784GNATPC?redirect-url=%2Fpublication%3Fq%3D%26f%255Bextern%255D%3Dfalse
4. See the checkbox has not been checked on the details page

![Image](https://user-images.githubusercontent.com/1572885/208926537-4895ec2a-8136-41fc-84af-0a74b7516fc9.png)

![Image](https://user-images.githubusercontent.com/1572885/208926570-393a3b52-c915-4018-9992-2f50da2a75dc.png)

5. See UGent authors in the people & affiliations tab

![Image](https://user-images.githubusercontent.com/1572885/208926630-620445d8-0e99-447d-a3d2-40d62e0f9377.png)

## Expected behaviour

1. When "non UGent" is checked, we expect to see only records that have the checkbox "Published while none of the authors and editors were employed at UGent" checked.

2. When "UGent" is checked, we expect to see only records that _do not_ have the checkbox "Published while none of the authors and editors were employed at UGent" checked.

**Comment by nicolasfranck** [comment]
That facet is currently based on the field `extern`, also known as `Published while none of the authors and editors were employed at UGent`. So the meaning needs to be swapped, or just derived from the authors/editors (we cannot support both)

**Comment by nicolasfranck** [comment]
See https://github.com/ugent-library/biblio-backoffice/pull/964. Probably my stupid mistake ;-)
