### ISSUE TITLE
Improved keywords

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#938]
# Keywords epic

The reviewers' time went up so much they decided not to add the keywords (some still do it because they feel a record should be complete). We did an interview and workshop during #871 and came up with the following solution based on developer and librarian input.

We need to find a good library for this. We can discuss a styling strategy when we have found this one.

## Success criteria

Layout:
- [ ] The label is "Keywords" `required`
- [ ] The input field is a text area `required`
- [ ] The text area grows with the number of keywords `required`

![Image](https://user-images.githubusercontent.com/1572885/208929767-492b0b46-7f04-43d7-8cd4-34da54a63980.png)
![Image](https://user-images.githubusercontent.com/1572885/208929837-761757ea-c4f7-49ae-86ab-fc50fc0c0241.png)

Input:
- [ ] You can type a keyword, and separate them with `;` (with or without spaces before or after the semicolon) `required`
_Not by `,` as sometimes there are keywords with decimals in them, or we have examples like **"ISM: dust, extinction"**. `required`_
- [ ] You can paste keywords in bulk, and separate them with a `;` (with or without spaces before or after the semicolon) `required`
- [ ] You can import keywords via an identifier, and separate them with a `;` (with or without spaces before or after the semicolon) `required`
- [ ] We do not overwrite keywords when adding another strip in bulk, it works like text `required`

![Image](https://user-images.githubusercontent.com/1572885/208928833-b1583f34-2fc6-4f1b-8bb4-1083a50be5a3.png)
![Image](https://user-images.githubusercontent.com/1572885/208928921-c5e7b22c-d924-411c-a310-723c55c0f3cd.png)

Editing:
- [ ] You can navigate _between_ the keywords by using your mouse, or arrows in your keyboard (like you would navigate between letters) `optional`
- [ ] You can remove keywords by using the backspace, or by clicking the `X` icon `required`
- [ ] `[TBD]` You can edit keywords by double clicking them: they become editable `optional`

![Image](https://user-images.githubusercontent.com/1572885/208929027-740c44fa-7b62-44a0-b41c-2ba98709a06d.png)

![Image](https://user-images.githubusercontent.com/1572885/208929399-a25a8184-fb30-4bac-96de-289603094d18.png)
To be discussed: editing

"Never look back":
- [ ] Custom capitalisation in keywords is kept, we do not fiddle with it `required`
- [ ] _Exact_ doubles are removed (case sensitive, if two keywords are the same word but have different capitalisations, both are kept) `required`

![Image](https://user-images.githubusercontent.com/1572885/208929485-a06142f0-61fc-419f-a439-fe71b5673c83.png)

**Comment by nicolasfranck** [comment]
@mietcls if we are working with a text-area, why not simply interpret a line as a keyword,
and then so split on newline? That way there is no need for a special library or allowance
of special characters (e.g. quotes or no quotes).

And for those who need a newline in their keyword, there is a special place in hell.

**Comment by mietcls** [comment]
@nicolasfranck I'm not sure what you mean with this suggestion.
- If it's about showing each keyword on a newline: this will probably create a very long vertical list. People usually add keywords in our case, they do not remove. So having the overview is not as important as having a compact view.
- if it is about splitting keywords on a newline: we also import keywords – so we have to interpret characters such as comma's and semi-colons.

If it's none of the above, I need some more context.
Also – we prefer to work with standard design patterns, or things people know from other products they use. Inventing new ones can influence the way our tooling gets understood, so we should use that sparingly.

**Comment by nicolasfranck** [comment]
@mietcls well yes, having all of the keywords in one textarea is more risky as you can accidentally remove older keywords. Or is it also possible in your proposal to remove keywords with the use of the backspace (you can put your cursor inside that area, so people will use it to remove keywords instead of using the "x")?

It all depends on your source. If you often copy and paste keywords from an external list (excel column?), it is handy to have this behaviour of "split on newline" (as this colon is somewhat unusual). I would suggest to use a textarea as a way
to add only keywords, after which they are added below it (with an "x" added to it), and the textarea cleared. Or a simple input would suffice too, if it adds "on enter"?

About the imports: yes we do import, but we split during that import; we do not leave any colons inside a separate keyword. At least that is not the intention (and keeping it would hide defects in the data).

**Comment by nicolasfranck** [comment]
cf. https://yaireo.github.io/tagify/

**Comment by mietcls** [comment]
Looks reaaaally nice.

**What it does:**
✅ The text area grows with the number of keywords, or is large enough to hold at least 4 lines
✅ Custom separators
✅ Pasting keywords
✅ You can remove keywords by using the backspace, or by clicking the X icon
✅ Does not allow exact doubles (capitalisation = different = kept)

**Things I cannot test:**
? Import via identifier
? Not overwriting when importing / adding in bulk
? Custom capitalisation in keywords is kept, we do not fiddle with it
? removing exact doubles (capitalisation is kept) on import

**Things that are not possible, but we can overcome:**
I'll figure it out
- You can navigate between the keywords by using your mouse, or arrows in your keyboard (like you would navigate between letters)
- You can edit keywords by double clicking them: they become editable

**Comment by nicolasfranck** [comment]
cf. https://sean.is/poppin/tags

also adds on "enter"

**Comment by mietcls** [comment]
Tagify has a setting that can do the same!

Taggle also allows to jump between keywords (not a big issue, we do not _need_ that). It does however seem a little less versatile.

**Comment by nicolasfranck** [comment]
https://github.com/lekoala/bootstrap5-tags

**Comment by nicolasfranck** [comment]
https://github.com/erwinheldy/tagin

**Comment by nicolasfranck** [comment]
[tagify_mockup.zip](https://github.com/ugent-library/biblio-backoffice/files/10532975/tagify_mockup.zip)

@mietcls I have prepared mockup for tagify where the bootstrap css of biblio-backoffice
is used. Just load the `index.html`. Documentation is inline. I tried to mimic the badge style
to style the tags.

**Comment by mietcls** [comment]
Great, thanks @nicolasfranck! Very nice that the edit even works (even if this is not a breaking feature).
Can we fix the functionalities with an ❌, or does it seem too much?

Bullets with ✅ = ok
Bullets with ❌ = we need to find a solution
Bullets with ❔ = we need to take a look at this
Bullets with 🆗 = it's definitely ok that this is not a feature

- ✅ The text area grows with the number of keywords, or is large enough to hold at least 4 lines
- ✅ You can type a keyword, and separate them with ; (with or without spaces before or after the semicolon)
- ❌ Do not separate by `,` as sometimes there are keywords with decimals in them, or we have examples like "ISM: dust, extinction".
- ✅ You can paste keywords in bulk, and separate them with a ; (with or without spaces before or after the semicolon)
- ✅ You can remove keywords by using the backspace, or by clicking the X icon
- ✅ You can edit keywords by double clicking them: they become editable
- ✅ Custom capitalisation in keywords is kept
- ❌ Exact doubles are removed (case sensitive, if two keywords are the same word but have different capitalisations, both are kept)

- ❔ You can import keywords via an identifier, and separate them with a ; (with or without spaces before or after the semicolon)
- ❔ We do not overwrite keywords when adding another strip in bulk

- [not in there but that's 🆗, no need to develop this] You can navigate between the keywords by using your mouse, or arrows in your keyboard (like you would navigate between letters)

**Comment by mietcls** [comment]
@nicolasfranck any idea if we can fix the ones with the ❌ above? If so, we can proceed with your demo!
