### ISSUE TITLE
Biblio sometimes does not react when saving

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#939]
# Story

Biblio sometimes does not react when saving.

Has become blocking as certain reviewers cannot adapt supervisor sequences at all.

- It happens at random moments – it is hard to reproduce
- It happens in random places (adding an author, switching supervisors from location, editing details, editing a biblio message, locking, ...)
- Nothing is in the console log when it happens to be open
- For old and new records

## Examples

- Record [8764527](https://backoffice.biblio.ugent.be/publication/8764527?redirect-url=%2Fpublication%3Fq%3DVulnerability%2BMapping%2Bof%2BGroundwater%2BResources%2Bof%2BMekelle%2BCity%2Band%2BSurroundings%252C%2BTigray%2BRegion%252C%2BEthiopia%26sort%3Ddate-updated-desc&show=activity) in Biblio message tab, editing a librarian note – lag for 5-10 seconds
- Record [01GMQSC1D0EW10Q4GHB9JEW2Z8](https://backoffice.biblio.ugent.be/publication/01GMQSC1D0EW10Q4GHB9JEW2Z8?redirect-url=%2Fpublication%3Fq%3D01GMQSC1D0EW10Q4GHB9JEW2Z8%26sort%3Ddate-updated-desc&show=contributors) in people & affiliations tab, trying to switch supervisors from place
_(did not work for a reviewer at all, did work for me after 2-3 seconds)_
- Record [01GMT1K1HSC0RSNQAV3QY4T4ZN](https://backoffice.biblio.ugent.be/publication/01GMT1K1HSC0RSNQAV3QY4T4ZN?redirect-url=%2Fpublication&show=contributors) in people & affiliations tab, trying to switch supervisors from place
_(did not work for a reviewer at all, did work for me)_
- Other examples without record number, between 3-10 seconds waiting time:
  - locking
  - adapting license info
  - adapting details
  - editing a biblio message
  - adding an author

Gathering more details here: https://ugentbe-my.sharepoint.com/:x:/g/personal/miet_claes_ugent_be/EZfU0_YzuThFh5LhHqp_OygBOZ8PqtcXQUlOpAdylK05ow?e=w9eraK&nav=MTVfezVDMkQ1QzAyLUY3MzQtNEQ5Mi04N0E4LUREMTBBNUE5OERGQX0

**Comment by mietcls** [comment]
Adding two screenshots that show saving issues dating from November. Not sure if they are related, or if this is already fixed, but it might help with finding out what goes wrong.

On the detail page:
![Image](https://user-images.githubusercontent.com/1572885/210341325-a3293558-37a4-40b0-86b9-cd6194905cb1.png)

When adding authors:
![Image](https://user-images.githubusercontent.com/1572885/210341382-aac0244d-408e-4018-b568-b5f307293589.png)

**Comment by nicolasfranck** [comment]
Related? https://github.com/ugent-library/biblio-backoffice/issues/958

**Comment by mietcls** [comment]
Opening a record also takes 5+ seconds now, even on test.

**Comment by mietcls** [comment]
This record: https://backoffice.bibliotest.ugent.be/publication/01GPB80KP5PJ9EVA0CJ1KNPYQX?redirect-url=%2Fpublication&show=description#projects – but it is alway sporadic and untraceable via the console. I didn't catch the event time line in time to show the duration.

**Comment by nicolasfranck** [comment]
@mietcls in that it is better to wait until the direct integration with the biblio frontend has been replaced by the direct integration with ES. There is some expansion of data going on during page load, and the associated records (mostly departments) are loaded into an internal cache which can different from request worker to request worker..

@nics right?

**Comment by mietcls** [comment]
Yes, of course! Just writing some things down to make sure I can follow up later and see which cases the fix covers.

**Comment by mietcls** [comment]
Closing this for now, people have been positive about the changes.
