### ISSUE TITLE
To view research output in biblio via lib: make sure people know they have to be on the intranet or go via VPN

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#942]
"Als ik op “view online” klik hier: https://lib.ugent.be/catalog/pug01:8584080 krijg ik “Forbidden” (e.g. https://backoffice.biblio.ugent.be/download/8772308/8772309-test)" -> has to be more transparant, available via VPN or intranet

Example: 
https://lib.ugent.be/404
https://github.ugent.be/Universiteitsbibliotheek/grim-services/blob/master/views/downloads/access_denied.tt

But in Biblio style

Text example
```
<div id="content">
  <h1>This content is only available for members of the University of Ghent.</h1>
  <p>You can access this content:</p>
  <ul>
    <li>from any computer in the university</li>
    <li>.. or by connecting to the network <a href="http://helpdesk.ugent.be/eduroam/">Eduroam</a></li>
    <li>.. or by connecting to the <a href="http://helpdesk.ugent.be/vpn">UGent VPN</a></li>
  </ul>
  <p>Please consult the content via one one of the above options.</p>
</div>
```

**Comment by nics** [comment]
@mietcls this should be handled by lib.ugent.be; why does the button even work when not within ugent

**Comment by mietcls** [comment]
Issue here: https://github.ugent.be/Universiteitsbibliotheek/lludss-interface/issues/536
