### ISSUE TITLE
Add classes to thumbnail so it is hidden on split screen

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#944]
# Story

Add classes to thumbnail so it is hidden on split screen

## Current problem

![Image](https://user-images.githubusercontent.com/1572885/210210530-7409e8d6-6357-466b-bb69-a58ca4a0c6e4.png)

## Desired situation

![Image](https://user-images.githubusercontent.com/1572885/210210640-09f79323-c3de-47e0-a7d0-bd1f9d9a81e9.png)
![Image](https://user-images.githubusercontent.com/1572885/210210643-4185395c-8c5e-4c85-8635-4643863ff97d.png)
![Image](https://user-images.githubusercontent.com/1572885/210210642-8c5ff6e2-e42d-4993-bd73-69ec26112617.png)

## Proposed solution

Add `d-none d-lg-block` to the thumbnail in the overview
![Image](https://user-images.githubusercontent.com/1572885/210210641-ce555f8e-d49e-409f-9bc1-d568fed1fae8.png)

**Comment by nicolasfranck** [comment]
@mietcls this looks ready to build?

**Comment by mietcls** [comment]
This specific part is okay, but I'd have to align all cards in the end (after import when looking at the different steps for example). If we don't mind rework we can already do it, but it will not be done yet.
