### ISSUE TITLE
User cannot log in

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#945]
# Story

This person cannot log in: https://telefoonboek.prd.rad.ugent.be/nl/people/000181461637

## Context

- Cannot find this person in "view as"
- I *can* find this person when trying to add them as an author, when typing their first name. However, you can see them twice and with two different UGent IDs, not sure if this is the same person.

Name removed for privacy purposes

![Image](https://user-images.githubusercontent.com/1572885/210365057-20c3e506-917a-4bf6-87ab-48813738f871.png)

**Comment by nicolasfranck** [comment]
@mietcls Adding authors/contributors to a publication or dataset is entirely different from logging in as that user. The user in question needs to be flagged as `active` and needs the right roles in the authority table "person". That user does not seem to be active: https://biblio.ugent.be/person/25FBF1D8-25AE-11E9-B63B-07AE5607D3EF?format=json. Not sure who decides to make someone active.

**Comment by nics** [comment]
@mietcls should be ok now, had 2 conflicting profiles
