### ISSUE TITLE
[Urgent] Front office returns 500 and 404s for authors attached to specific records

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#946]
# Bug

Front office returns 500 and 404s for authors attached to specific records

## Steps to reproduce

1. Search for https://telefoonboek.prd.rad.ugent.be/nl/people/001995048308 in http://biblio.ugent.be
2. See all search results. There are two people found:
  2.1. https://biblio.ugent.be/person/FFA3F874-F0ED-11E1-A9DE-61C894A0A6B4
  2.2 https://biblio.ugent.be/person/26601476-38e0-11eb-9f20-922c3b627285
3. Click the authors, such as https://telefoonboek.prd.rad.ugent.be/nl/people/001995048308, or other authors.
  3.1. Some return a status 500, some a 404.
  3.2. None return a research page with ORCID
![Image](https://user-images.githubusercontent.com/1572885/210520133-70e11ab1-5052-4281-8fd6-f0d0f7bd5ee4.png)
![Image](https://user-images.githubusercontent.com/1572885/210519467-8226e3dd-8901-4fb7-8195-6d1f8e89a7d4.png)
4. When I search for an other researcher this problem does not happen

## Related

- [x] #945

**Comment by nicolasfranck** [comment]
e.g. go to https://biblio.ugent.be/person/1A8A0462-F0EE-11E1-A9DE-61C894A0A6B4 and it crashes like this, with this error in `/var/log/biblio/deployment.log`:

```
[15681] error @0.206455> [hit #21]request to GET /person/1A8A0462-F0EE-11E1-A9DE-61C894A0A6B4 crashed: core - template - undef error - Can't use string ("") as a HASH ref while "strict refs" in use at /opt/biblio/lib/Biblio/AppHelper/Routes.pm line 39.
 at local/lib/perl5/Dancer/Template/Abstract.pm line 91. in local/lib/perl5/Dancer/Handler.pm l. 98
```

**Comment by nicolasfranck** [comment]
ok, I can reproduce this locally with the copied and pasted index from production.

Note to self:
has nothing to do with that call to `person_url` in the view, but all with that automatic
installed subroutine (so hard to find) `person_url` [here](https://github.ugent.be/Universiteitsbibliotheek/biblio/blob/master/lib/Biblio/AppHelper/Routes.pm#L156)

**Comment by nicolasfranck** [comment]
Found it: https://github.ugent.be/Universiteitsbibliotheek/biblio/blob/master/views/person.tt#L83. One of the persons in the list of co authors could not be found in the authority database, but the code in this view ignored that and called person_path anyway, leading to above error.

Some context: you can find the list of co-authors in the blue right bar under the title "Frequent UGent co-authors".

**Comment by nicolasfranck** [comment]
e.g. https://biblio.ugent.be/person/11466D46-F0EE-11E1-A9DE-61C894A0A6B4: co-author "Jurgen van Limmen" with identifier "26601476-38e0-11eb-9f20-922c3b627285" does not exist with that id in the authority table "person"

**Comment by nicolasfranck** [comment]
@nics I tried looping over the production publication records (using the `/frontoffice/publication` handler) to check if there are other contributor id's that cannot be found in the authority table "person", and there seem to be a lot. My script stalled at around 22000 contributors not found, as the handler returned a "bad gateway", so I am not sure how many more there are (see issue #958 ) for that. Or am I checking this in the wrong way?

**Comment by nicolasfranck** [comment]
@nics whoops, there was a bug in my check script that caused that high number (which was unprobable). Will give you an update.

**Comment by nicolasfranck** [comment]
32061 out of 33122 referenced contributors (or 96.80%) were found in the authority table.

See the 1061 referenced contributors that could not be found here: 
[biblio_referenced_contributors_not_found.csv](https://github.com/ugent-library/biblio-backoffice/files/10361338/biblio_referenced_contributors_not_found.csv)

**Comment by nicolasfranck** [comment]
[check_authors_exist_es.pl.txt](https://github.com/ugent-library/biblio-backoffice/files/10361475/check_authors_exist_es.pl.txt)

this was my test script that returned that csv result

**Comment by nics** [comment]
@nicolasfranck seems like an indexing problem?

e.g. https://biblio.ugent.be/publication/8759239 references the nonexisting person id FFA3F874-F0ED-11E1-A9DE-61C894A0A6B4
while the same record in the backoffice metadata references the correct id 26601476-38e0-11eb-9f20-922c3b627285

can you investigate how to best fix the index (without losing the gismo timestamps)?

**Comment by nicolasfranck** [comment]
@nics unfortunately not. I redid the same check, but now using the frontoffice handler. I did not exhaust it (as it would return a "bad gateway").

See these examples:

```
person_id,example_publication_id
6D1420E2-B25E-11E6-B104-2D2FD0AF0289,257322
6D05710A-B25E-11E6-B104-2D2FD0AF0289,222949
6D0AD80C-B25E-11E6-B104-2D2FD0AF0289,223459
8F6A35F0-B25E-11E6-B104-2D2FD0AF0289,381985
6EFC83FE-B25E-11E6-B104-2D2FD0AF0289,243562
7098EB9E-B25E-11E6-B104-2D2FD0AF0289,376631
8A88E126-B25E-11E6-B104-2D2FD0AF0289,438658
8CF86A08-B25E-11E6-B104-2D2FD0AF0289,335906
6D08DEE4-B25E-11E6-B104-2D2FD0AF0289,229269
6DB8AED2-B25E-11E6-B104-2D2FD0AF0289,311300
7313A292-B25E-11E6-B104-2D2FD0AF0289,365688
7135C1D0-B25E-11E6-B104-2D2FD0AF0289,393091
711BB830-B25E-11E6-B104-2D2FD0AF0289,391317
79FCC1E2-B25E-11E6-B104-2D2FD0AF0289,369572
7E8CE07A-B25E-11E6-B104-2D2FD0AF0289,375318
74AE77DA-B25E-11E6-B104-2D2FD0AF0289,393563
870E6004-C053-11E6-8B10-4038B5D1D7B1,663059
6FC6CF56-B25E-11E6-B104-2D2FD0AF0289,427757
95C402DC-B25E-11E6-B104-2D2FD0AF0289,423553
6D144FEA-B25E-11E6-B104-2D2FD0AF0289,445749
6DC0419C-B25E-11E6-B104-2D2FD0AF0289,437337
6D2F9C14-B25E-11E6-B104-2D2FD0AF0289,445049
6DF5CF42-B25E-11E6-B104-2D2FD0AF0289,443322
6D146624-B25E-11E6-B104-2D2FD0AF0289,445789
6DF7C0C2-B25E-11E6-B104-2D2FD0AF0289,435230
6DF56804-B25E-11E6-B104-2D2FD0AF0289,439908
6D2F4DD6-B25E-11E6-B104-2D2FD0AF0289,444750
87E91DFC-C053-11E6-8B10-4038B5D1D7B1,848993
711A7D8A-B25E-11E6-B104-2D2FD0AF0289,251450
73C3CFC8-B25E-11E6-B104-2D2FD0AF0289,430690
8C0DBF76-B25E-11E6-B104-2D2FD0AF0289,369265
8C0DC020-B25E-11E6-B104-2D2FD0AF0289,369265
8C0DC084-B25E-11E6-B104-2D2FD0AF0289,369265
6CC31DF0-B25E-11E6-B104-2D2FD0AF0289,906568
834532DE-B25E-11E6-B104-2D2FD0AF0289,363401
94597A12-B25E-11E6-B104-2D2FD0AF0289,369269
6EAEA22E-B25E-11E6-B104-2D2FD0AF0289,419439
770C0B3C-B25E-11E6-B104-2D2FD0AF0289,426390
9459D868-B25E-11E6-B104-2D2FD0AF0289,369567
8AE3CEF6-B25E-11E6-B104-2D2FD0AF0289,370343
7518E7BE-B25E-11E6-B104-2D2FD0AF0289,345588
817340FE-B25E-11E6-B104-2D2FD0AF0289,351259
947E1BA6-B25E-11E6-B104-2D2FD0AF0289,358623
```

First publication here https://backoffice.biblio.ugent.be/frontoffice/publication/257322 
reference author `6D1420E2-B25E-11E6-B104-2D2FD0AF0289` who is NOT in
the authority table person

**Comment by nicolasfranck** [comment]
[check_authors.csv](https://github.com/ugent-library/biblio-backoffice/files/10502250/check_authors.csv)

this is a list of publications (based on previously imported data) compared with
with live authority table persons. The publications are not live, but as I understood,
these problems only exist in older records.

Interpretation:

* publication_id: publication identifier (can be repeated)
* person_id: person identifier as found in the publication record
* role: person role as found in the publication record
* fixed_person_id: new person identifier. This is done either by matching on ugent_id (rare, sometimes found in contributor, and matches rarely), or by matching on both first_name and last_name.
* match_strategy: matching strategy used (ugent_id or name)
* match_hint: match value used in the matching
* match_error: when matching failed, why. Can be "zero_results" or "multiple_results" (where there are more than 1 results)

**Comment by nicolasfranck** [comment]
@mietcls I cannot "solve" this without a manual check. Most of the fixed authors (half of it) were fixed by matching on their first and last name, and making sure there were only one. Can a reviewer have a check on this?

**Comment by mietcls** [comment]
@nics I can ask them for help and assist as well. These are 3000 records – what should they check on specifically so I can give them a good briefing to fix it and help them figure out whether/in which timeframe this is feasible (they have deadlines)?

**Comment by mietcls** [comment]
@nicolasfranck I can ask them for help and assist as well. These are 3000 records – what should they check on specifically so I can give them a good briefing to fix it and help them figure out whether/in which timeframe this is feasible (they have deadlines)?

**Comment by nicolasfranck** [comment]
@mietcls mm, I will maybe add a link to the phonebook. There are a lot of them, but if you sort on person_id you will see a lot of repetition (one line per found contributor per publication).

**Comment by nicolasfranck** [comment]
This time with phonebook links: 
[check_authors.csv](https://github.com/ugent-library/biblio-backoffice/files/10518075/check_authors.csv)

A lot of them are not in the phonebook anymore (inactive), so I do not know if that helps.

**Comment by netsensei** [comment]
@nicolasfranck @mietcls 

The idea here is to have the review team loop over the CSV file - publication by publication - and replace the old, defunct  contributors with a new one for each publication.  The CSV file gives a hint / suggests which contributor might be a suitable replacement for an old, defunct contributor.

If you pick an publication from the CSV file, go the "contributors" tab and then try to edit the corresponding contributor, you'll notice that it will error with a request id popup.  (e.g. first item in the list 1029837 / Bouquerel => check it out in Biblio Backoffice).

The vast majority of suggestions in the CSV file are generated by going through the current list of persons in the person service, and looking for an alternative through matching the "first name / last name" of the old, defunct contributor. The problem to this approach is that this is prone to errors (e.g. potential for multiple "Jan Jannsens" who aren't the same person). 

Fixing requires manually verifying if the proposed alternative in the CSV list is the exact, same person to the original contributor. So, this has the potential to gobble up a lot of time. I also expect that it won't be possible to solve all cases the CSV list either.

The popup error with the instruction to "send the request to the biblio team" + the `biblio transfer` commands help us mitigate these issues as they gradually appear; instead of pro-actively trying to fix them all in one go.

I think we need to discuss this in person / via slack before we proceed.

**Comment by mietcls** [comment]
OK TBD on Wednesday

**Comment by mietcls** [comment]
We will split this up into actionable tickets, this ticket has become too vague

**Comment by mietcls** [comment]
Not able to reproduce, we will have to fix this with the person service if it happens again. @nicolasfranck do you still have any news about your CSV?
