### ISSUE TITLE
{filters} Split up WoS type filter options

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#955]
# Story

Split up WoS type filter options

## Current situation

Filter options are now listed as is on input: with comma's and semicolons:
![Scherm­afbeelding 2023-01-06 om 14 43 22](https://user-images.githubusercontent.com/1572885/211024142-328060af-a8e0-4e55-91fd-98f922902e1c.png)

## Expected behaviour

We expect to see a list with all types, split up such as here:
![Scherm­afbeelding 2023-01-06 om 14 46 14](https://user-images.githubusercontent.com/1572885/211024619-9bcd3d54-f3e7-4877-a2fa-15633c115217.png)

## Success criteria

- [ ] Each type is one filter option (no combined options)
- [ ] Types are split by comma (with or without spaces) and semicolon (with or without spaces)
- [ ] Filter options remain sorted alphabetically

**Comment by nicolasfranck** [comment]
I would be cautious though not to "fix" every value as we once did in the old librecat (see [here](https://github.ugent.be/Universiteitsbibliotheek/librecat/blob/master/ugent/lib/Catmandu/Fix/clean_wos_type.pm#L16)).
Just splitting and trimming should suffice. More fixing would simply hide weird values.
