### ISSUE TITLE
{filters} Make contrast between active, inactive, enabled an disabled filters more clear

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#956]
# Story

Part of #954 

Right now, it is hard to easily scan which filters are in use without having to read everything and squint your eyes. This is not accessible for people with visible impairments.

![Scherm­afbeelding 2023-01-06 om 15 33 16](https://user-images.githubusercontent.com/1572885/211032797-8a2f2f78-b1d6-4159-8e0c-65dc860e26b6.png)

## Proposed solution
- Make filters **with** selected options bright blue (even if they have 0 results)
- Make filters _without_ selected options, **with** available options light blue
- Make filters _without_ selected options, _without_ available options light gray

![Scherm­afbeelding 2023-01-06 om 15 46 52](https://user-images.githubusercontent.com/1572885/211035417-2d7006ff-e614-43c5-8d21-fdf733fe3940.png)

### Context for filters _without_ selected options, _without_ available options light gray:
Sometimes we can combine filters in a way that causes other filters become "unfruitful", and they will look like this:
<img width="340" alt="Scherm­afbeelding 2023-01-19 om 11 57 37" src="https://user-images.githubusercontent.com/1572885/213424937-ed513506-9f31-4c41-9722-be0b43658c30.png">

We want to make sure the user knows these are not "fruitful".
We will make exceptions for
- "created since" and "updated since" – as we cannot make the distinction here.
- filters that "_became unfruitful_" during selection and return filter options with 0 – they remain bright blue

### Success criteria
- [ ] Filters that _do_ have one or more filter options available
and _does not have_ any filter options are selected
**appear as "default", light blue**
- [ ] Filters that _do_ have one or more filter options available
and _does have_ filter options selected
**appear as "primary", bright blue**
- [ ] Filters that _do not_ have any fruitful filter options available (clicking options = 0 results)
and _does have_ one or more filter options selected
**appear as "primary", bright blue**
- [ ] Filters that _do not_ have any fruitful filter options available (clicking options = 0 results)
and _does not have_ any  one or more filter options selected
**appear as "secondary", light gray**
  - [ ] Exception for "created since" and "updated since" – as we cannot make the distinction of "fruitfulness" for these filters.

## Implementation suggestion
Find the badges layouts here: https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-badges.html

### Default: non-active filter + filter options available 
`badge-default`
![Scherm­afbeelding 2023-01-06 om 15 53 04](https://user-images.githubusercontent.com/1572885/211036655-65dad1bd-c5de-46f5-a066-3c6f25e42451.png)
```
<div class="dropdown">
    <a class="badge badge-default mr-3" data-toggle="dropdown" data-persist="true" aria-haspopup="true" aria-expanded="false" role="button">
        <span class="badge-text">Biblio status</span>
        <i class="if if-caret-down"></i>
    </a>
</div>
```

### Active filter
`badge-primary`
![Scherm­afbeelding 2023-01-06 om 15 53 17](https://user-images.githubusercontent.com/1572885/211036695-aa0b4cda-bd65-4667-aeae-2a5b8d133d7f.png)
```
<div class="dropdown">
    <a class="badge badge-primary mr-3" data-toggle="dropdown" data-persist="true" aria-haspopup="true" aria-expanded="false" role="button">
        <span class="badge-text">Biblio status</span>
        <i class="if if-caret-down"></i>
    </a>
</div>
```

### Non-active filter + no filter options available
`badge-secondary`
![Scherm­afbeelding 2023-01-06 om 15 53 28](https://user-images.githubusercontent.com/1572885/211036724-f0700b91-74f1-4bd9-95db-9fdfc6a71cc3.png)
```
<div class="dropdown">
    <a class="badge badge-secondary mr-3" data-toggle="dropdown" data-persist="true" aria-haspopup="true" aria-expanded="false" role="button">
        <span class="badge-text">Biblio status</span>
        <i class="if if-caret-down"></i>
    </a>
</div>
```

## More context

Decided not to block anyone from clicking a filter box when there are no filter options available to check. It would require more complex rules and unnecessary blocks.

**Comment by nicolasfranck** [comment]
@mietcls do you have an example of a situation where there is a filter without filter options? Seems odd to me.

**Comment by mietcls** [comment]
@nicolasfranck when you've selected filter options in an other filter, that cause the filter options in that particular filter to all go to "0". Example:
<img width="340" alt="Scherm­afbeelding 2023-01-19 om 11 57 37" src="https://user-images.githubusercontent.com/1572885/213424937-ed513506-9f31-4c41-9722-be0b43658c30.png">

We need to show the user in that case it would be useless to open that filter to select any filter options in there.

**Comment by nicolasfranck** [comment]
@mietcls for input field like "Created since" and "Updated since", I cannot make the difference between "fruitful" and "not fruitfull"

**Comment by mietcls** [comment]
@nicolasfranck Okay, we can always keep those active then. I'll adapt the issue.
