### ISSUE TITLE
{filters} Show top 3 of which filters have been activated

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#957]
# Story

Part of #954 

Right now, we cannot see which filter options have been selected. We only get an indication that a number of filter options has been selected. Showing all of them however would also cause information overload.

<img width="163" alt="Scherm­afbeelding 2023-01-06 om 16 06 24" src="https://user-images.githubusercontent.com/1572885/211039262-302f491f-8958-4337-a6a0-590389de83ed.png">

## Proposed solution
<img width="404" alt="Scherm­afbeelding 2023-01-06 om 16 18 39" src="https://user-images.githubusercontent.com/1572885/211041597-ffebc97f-2e87-4cbf-9ddd-211bdb88661e.png">

- Show the first three filter options that have been selected, and cap the rest.
- When possible, shorten filter option values shown. `Help wanted – see "Success criteria shortening filter option values"`

### Success criteria filter options
- [ ] When no filter option has been selected, you can only see the filter label
- [ ] When one or more filter options have been selected, you can see the filter label and the first three filter options a badge value, starting with a dash ('-').
- [ ] If there are more than 3 filter options selected, ', ...' is added at the end of the badge value

<img width="342" alt="Scherm­afbeelding 2023-01-06 om 16 36 11" src="https://user-images.githubusercontent.com/1572885/211045001-19146094-c17a-49dc-8e37-7a7b189e38aa.png">

<img width="325" alt="Scherm­afbeelding 2023-01-06 om 16 14 05" src="https://user-images.githubusercontent.com/1572885/211040700-f64becea-9dc2-4d3b-8e2a-d437a8bedb5a.png">

<img width="417" alt="Scherm­afbeelding 2023-01-06 om 16 16 08" src="https://user-images.githubusercontent.com/1572885/211041112-a764347f-b1cc-4999-be21-319c8e955ba6.png">

#### Implementation suggestion filter options

- Add a 'badge-value' span with the selected filter options in, between the filter label and the dropdown caret.
- Remove the counter span.
<img width="404" alt="Scherm­afbeelding 2023-01-06 om 16 18 39" src="https://user-images.githubusercontent.com/1572885/211041597-ffebc97f-2e87-4cbf-9ddd-211bdb88661e.png">

Find the badges layouts here: https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/b-badges.html
Find an example of a similar layout here: https://biblio-ugent-prototype-emily-v2.vercel.app/biblio/reviewer/publications/overview.html

```
<div class="dropdown">
    <a class="badge badge-default mr-3" data-toggle="dropdown" data-persist="true" aria-haspopup="true" aria-expanded="false" role="button">
        <span class="badge-text">Biblio status</span>
        <i class="if if-caret-down"></i>
    </a>
</div>
```

### Success criteria shortening filter option values

- [ ] `TBD` For classification, only show code, not the entire value
![Scherm­afbeelding 2023-01-06 om 16 32 11](https://user-images.githubusercontent.com/1572885/211044136-2c61381a-5416-4911-b178-4354e7380af3.png)

- [ ] `TBD` For faculty, only show code, not the entire value
![Scherm­afbeelding 2023-01-06 om 16 31 14](https://user-images.githubusercontent.com/1572885/211043952-06e1c626-df89-4734-8b16-eea3a3ebc08d.png)

Related stories: #959 and #960

**Comment by nicolasfranck** [comment]
@mietcls wouldn't that clutter up the space even more? Even with only three values..

Proposal: inside the facet box, put the selected on top (in sorted order), and the rest
below? Not sure how to make this visible make sense.

**Comment by mietcls** [comment]
@nicolasfranck yes, it would make it more busy, but people need to now open and close each filter to know what they selected for each filter. This is a minimum of 2 clicks – which is a lot if you filter on a couple of values. This has been checked with the reviewers and checked with UX standards.

I'm not sure if I understand your proposal, so I don't know if it would solve the above issue. Can you give me a visual example? Have you seen this somewhere?

**Comment by nicolasfranck** [comment]
```
<field>
[x] VABB-1 (2)
[x] VABB-3 (4)
<empty line>
[ ] VABB-2 (1)
[ ] VABB-10 (10)
```
