### ISSUE TITLE
request timeout of (production) frontend traefik probably too low.

### ISSUE THREAD

**Issue by nicolasfranck** [ugent-library/biblio-backoffice#958]
I tried looping over all of the publications using the `/frontoffice/publication`
handler in biblio-backend, as a test for the reindexation. But after some deep
paging, I got a "Bad gateway" (http status code 502) from this handler.

In development (and locally) this url works: https://backoffice.bibliotest.ugent.be/frontoffice/publication?offset=218200&limit=200

In production it always fails with status code 502: https://backoffice.biblio.ugent.be/frontoffice/publication?offset=218200&limit=200

I guess there are other request timeout limits in place for production? Or are the lower limits a means
to fallback to another backend when one does not react in time (like golding does for
the solr backends).

**Comment by nics** [comment]
was a memory problem (solved)
