### ISSUE TITLE
Export from biblio for datasets does not return non-UGent authors in authors column

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#966]
# Bug

Export from biblio for datasets does not return non-UGent authors in authors column.
Important question: Is this only the case in the excel?

## Steps to reproduce

1. Go to biblio, datasets
2. Click "Export to Excel"
![Image](https://user-images.githubusercontent.com/1572885/211350426-ce1e3a06-daf2-44a6-8a01-8396e55673a6.png)
3. Check download and see semicolons for certain records
![Image](https://user-images.githubusercontent.com/1572885/211351380-fde65fde-dbfa-421e-95c2-1aed17ed1bf8.png)
4. Double check record and see non-UGent authors missing for https://backoffice.biblio.ugent.be/dataset/01GKNDDXH1AVBSAQH8NTGK1GEE?redirect-url=%2Fdataset&show=contributors

**Comment by nicolasfranck** [comment]
Well ... it returns authors, you can see it by the colon separators in place,
but there is nothing useful in it.

It appears that the full_name attribute is empty for those contributors (I checked in
the raw data). Only first_name and last_name is present. If you reimport the
data, all is fine. At least, here locally.

I see that full_name is set for datacite and crossref imports, but not sure
if that is active on production. 

As this is data problem, how to continue on this? Relying on the combination of first_name and last_name
as a fallback is a bit tricky as that does not work for everyone. The import at least
draws from a filled in resource..

**Comment by mietcls** [comment]
@nicolasfranck Can you also discover whether this data is missing when we send it to FRIS? Because apparently that information is missing there as well (Not sure if the problem is related. If not, this needs to be split off into a different issue)

**Comment by nicolasfranck** [comment]
@mietcls If I am correct, FRIS uses the OAI interface from the biblio frontend to draw records from. I suppose they use the mods or the mods_36 format. The first does not show the full name, the latter does.

Compare https://biblio.ugent.be/oai?verb=GetRecord&metadataPrefix=mods_36&identifier=oai:archive.ugent.be:01GKNDDXH1AVBSAQH8NTGK1GEE to https://biblio.ugent.be/oai?verb=GetRecord&metadataPrefix=mods&identifier=oai:archive.ugent.be:01GKNDDXH1AVBSAQH8NTGK1GEE

The mods_36 one has `displayForm` to use for the full name. It is stored as such in the biblio frontend index. If I look at the the source https://backoffice.biblio.ugent.be/frontoffice/dataset/01GKNDDXH1AVBSAQH8NTGK1GEE, and its code, I see that the frontoffice does not uses FullName to construct the full name, but rather concatenates first name and last name (for historical reasons).

Do you have an example where it fails to show the full name?

**Comment by mietcls** [comment]
@nicolasfranck I asked for an example from Stefanie. This is the answer:

> [This file](https://ugentbe.sharepoint.com/:x:/r/teams/CA20.DataStewardTeam/RDM%20services%20%20projects/DataRegister_Biblio/biblio_testing/researchData/transfer_to_FRIS/datasets_2023-01-09_15-10-04.xlsx?d=wd9daf6a7d2d5447fa8331342841f1fb4&csf=1&web=1&e=xi5gn3)https://ugentbe.sharepoint.com/:x:/r/teams/CA20.DataStewardTeam/RDM%20services%20%20projects/DataRegister_Biblio/biblio_testing/researchData/transfer_to_FRIS/[datasets_2023-01-09_15-10-04.xlsx](https://ugentbe.sharepoint.com/:x:/r/teams/CA20.DataStewardTeam/RDM%20services%20%20projects/DataRegister_Biblio/biblio_testing/researchData/transfer_to_FRIS/datasets_2023-01-09_15-10-04.xlsx?d=wd9daf6a7d2d5447fa8331342841f1fb4&csf=1&web=1&e=xi5gn3)?d=wd9daf6a7d2d5447fa8331342841f1fb4&csf=1&web=1&e=xi5gn3 contains the complete comparison of FRIS vs Biblio. Inge is in discussion with the GISMO team on this topic as well. For some cases, it is not clear whether the cause is at level of FRIS, GISMO or Biblio. We learned from the GISMO team that if not all mandatory fields (according to the FRIS metadata model) are provided the dataset is rejected altogether. The file contains such cases as well (e.g. due to missing keywords).

> Column 1 and 2: Titel and creators of datasets from FRIS export
> Column 3: comments on what is wrong and what could be causing it
> following columns: metadata of datasets from Biblio export

> blue rows: datasets missing in FRIS (14 cases)
> green rows: datasets available in FRIS but not correct (affiliation not correct: 1 case, list of creators not complete: 5 cases)

Here are some examples:
- Available in FRIS, but missing creators: https://backoffice.biblio.ugent.be/dataset/01GM8HQDJGB52QQBJRRZ160AKV
- Not available in FRIS at all (probably rejected): https://backoffice.biblio.ugent.be/dataset/01GK17T0R6A84EEZJKMMNZK4WA
