### ISSUE TITLE
Cannot add department CA08 to record 01GMVAZ17ZFESQDTMDP7A0GDH6

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#968]
# Question

Cannot add department [CA08](https://phonebook.ugent.be/en/faculties/CA08) (Academic Director of Internationalization) to record [01GMVAZ17ZFESQDTMDP7A0GDH6](https://backoffice.biblio.ugent.be/publication/01GMVAZ17ZFESQDTMDP7A0GDH6?redirect-url=%2Fpublication%3Fq%3D01GMVAZ17ZFESQDTMDP7A0GDH6%26sort%3Ddate-updated-desc).

## Steps to reproduce

1. Go to record [01GMVAZ17ZFESQDTMDP7A0GDH6](https://backoffice.biblio.ugent.be/publication/01GMVAZ17ZFESQDTMDP7A0GDH6?redirect-url=%2Fpublication%3Fq%3D01GMVAZ17ZFESQDTMDP7A0GDH6%26sort%3Ddate-updated-desc)
2. Go to [people & affiliations, departments](https://backoffice.biblio.ugent.be/publication/01GMVAZ17ZFESQDTMDP7A0GDH6?redirect-url=%2Fpublication%3Fq%3D01GMVAZ17ZFESQDTMDP7A0GDH6%26sort%3Ddate-updated-desc&show=contributors#departments)
3. Try adding department CA08 and see results disappear
![Image](https://user-images.githubusercontent.com/1572885/211562363-be5f5152-c02e-4fc3-a250-6be1f9d9028e.png)
![Image](https://user-images.githubusercontent.com/1572885/211562362-8f594d4c-79c8-40e0-adce-a3b61583c2c9.png)

**Comment by nicolasfranck** [comment]
@mietcls that department is not anywhere to be found in the data.
@nics departments are now "hardcoded" into the biblio frontend catmandu.list.yml. Because there is no source to draw from?

**Comment by mietcls** [comment]
We also had a conversation about it on Slack: they are now manually added. TBD if we can automate this by drawing it from a source at some point.

**Comment by nicolasfranck** [comment]
probably, I forgot about it probably 🐟

**Comment by nics** [comment]
resolved by https://github.ugent.be/Universiteitsbibliotheek/biblio/commit/a982afaac70c3099c4e643fd5008f4e6d6e53c10

@mietcls @nicolasfranck static list for now, will be replaced by service fed by gismo data

**Comment by mietcls** [comment]
@nics Will this work with the new release or should this already work?

**Comment by nics** [comment]
@mietcls i forgot to reindex, ok now
