### ISSUE TITLE
Make it possible, when adding a project to a record, to search on project acronym

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#969]
# Story

Make it possible, when adding a project to a record, to search on project acronym.

`is this true?` Currently it's only possible to search for the name and GISMO code of a project. However, researchers mostly know projects by the acronym.

**Comment by mietcls** [comment]
Note; It's probably better to focus on automatisation instead of this

**Comment by nicolasfranck** [comment]
These are the fields that you can search on currently: https://github.ugent.be/Universiteitsbibliotheek/biblio/blob/master/lib/Biblio/Helper.pm#L985 (and also in my new PR directly in biblio-backoffice: https://github.com/ugent-library/biblio-backoffice/blob/fix_issue_923/internal/backends/authority/project.go#L52)

So enough parameters to search on, and all identifiers are copied to the "all" field
that has a lot of analysis

So I guess..

* ... the project is not in the database
* ... there is something "off" in their search query

Do you have an example?

What do you mean by automatisation?

**Comment by mietcls** [comment]
Thanks for the context! An example would be the acronym [CROPDIVA which is the acronym for "Climate Resilient Orphan croPs for increased DIVersity in Agriculture"](https://research.ugent.be/web/result/project/8ccbb923-e4b6-46ff-913b-e7bb40f48f13/details/cropdiva-41e08921-climate-resilient-orphan-crops-for-increased-diversity-in-agriculture/en)

So after this PR we can look for those acronyms as well?

When I meant by focus on automatisation: making sure researchers would not have to input that data themselves. If we can automatically connect this information, the issue above mostly disappears.

**Comment by nicolasfranck** [comment]
@mietcls no that PR simply mimics the same behaviour.

This is more a data problem.

This is how it looks like in biblio: https://biblio.ugent.be/project/41E08921
This is how it looks like in the backend mongo database:

```
{
   "iweto_id" : "41E08921",
   "title" : "Climate Resilient Orphan croPs for increased DIVersity in Agriculture",
   "end_date" : "2025-08-31",
   "_id" : "41E08921",
   "abstract" : "<p>Agrobiodiversity is a crucial prerequisite for ecologically and economically sustainable agricultural and food systems and is an important tool for ecological intensification of agricultural systems. However, agrobiodiversity is a complex concept that is the result of the interaction between the environment, genetic resources and management systems used by culturally diverse people. CROPDIVA will reinforce agrobiodiversity in European agricultural cropping systems on different levels and along distinct geographic and socio-economic areas resulting in resilient food and feed production systems. To realise the project objectives CROPDIVA will focus on (1) the promotion of six underutilised crops: oats, triticale, hull-less barley, narrow-leafed lupin, buckwheat and faba bean in various cropping systems and (2) on the creation of new value chains. The selected crops have unique features. Firstly, the six underutilised crops are characterised by a broad genepool, which serves as a reservoir for important traits related to e.g. resilience to (a)biotic stress as well as nutritional quality. This great genetic diversity ensures the development of climate resilient varieties. Secondly, the selected crops have great ecological benefits and advantages for a sustainable crop management system. For example, many of them produce nectar rich flowers and/or biologically fix nitrogen. Others result in early stubble, which allow to sowing cover/catch crops as a second crop or they mature early leading to a lower transpiration coefficient and less water use. Thirdly, these crops possess a high nutritious and food technological value, which create many possibilities to develop new food/feed and non-food products; a more diversified value chain will provide new market opportunities for the local food/feed and associated non-food industry and will provide opportunities for new innovative products tailored to the local demand.</p>",
   "gismo_id" : "8ccbb923-e4b6-46ff-913b-e7bb40f48f13",
   "start_date" : "2021-09-01"
}
```

@nics I see a catmandu command `import_gismo_projects` available, but I cannot find any reference to it in any cronjob on production (persse). So I guess this is data problem: the projects are out of date?

**Comment by nicolasfranck** [comment]
@mietcls still not working?

**Comment by nics** [comment]
@nicolasfranck yes it's a manual job at the moment
