### ISSUE TITLE
(new?) link to wos record does not work in "older" browsers

### ISSUE THREAD

**Issue by nicolasfranck** [ugent-library/biblio-backoffice#974]
**Describe the bug**

The link to the wos record, that you can find in the action menu of a record in the publication
list, links to a WOS record, that in older browsers results in an error "something" went wrong.

**To Reproduce**

1. Go to list of publications and filter on classification type "A1"
2. Go the action menu of one of the resulting publications, and click on the link "WOS"
3. In more modern browsers, that link will work perfectly (and also chrome), but for example the latest firefox (with "esr" or "extended support") it does not work.

**Notes**

Example: https://www.webofscience.com/wos/woscc/full-record/000257021600002

* If you visit this record with curl, you see:

```
< HTTP/2 403
< server: AkamaiGHost
< mime-version: 1.0
< content-type: text/html
< content-length: 322
< expires: Fri, 13 Jan 2023 13:28:28 GMT
< date: Fri, 13 Jan 2023 13:28:28 GMT
< server-timing: cdn-cache; desc=HIT
< server-timing: edge; dur=1
< link: <https://www.webofscience.com/_sec/cp_challenge/sec-3-8.css>; rel=preload; as=style, <https://www.webofscience.com/_sec/cp_challenge/sec-cpt-3-8.js>; rel=preload; as=script
<
<HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD><BODY>
<H1>Access Denied</H1>
```

So no redirect to find in the request response. The only thing I can think of, is that that link header in the response is responsible for the redirect, but that seems like a modern feature..

The old way of creating link maybe works?

http://ws.isiknowledge.com/cps/openurl/service?url_ver=Z39.88-2004&rft_id=info:ut/000257021600002

**Comment by nicolasfranck** [comment]
that "full-record" link seems to be way to go, if you look at the documentation page

https://support.clarivate.com/ScientificandAcademicResearch/s/article/Web-of-Science-Core-Collection-URL-format-to-link-to-specific-record?language=en_US

and it is also what users probably copy and paste from the url bar?

I'm in contact with the helpdesk of web of science. Issue is sent to their technical team.

**Comment by mietcls** [comment]
Thank you for getting in touch with WoS!

This is the information I got:
- In beide gevallen krijg ik een foutmelding ; ik heb deze geprobeerd https://www.webofscience.com/wos/woscc/full-record/000900069600003
- Het lukt wel als ik "WOS:" toevoeg -> https://www.webofscience.com/wos/woscc/full-record/WOS:000900069600003

Does this clarify it?

**Comment by nicolasfranck** [comment]
Clarivate has made some changes, and according to Anniek, the url seem to be working now in the latest enterprise version of Firefox

**Comment by mietcls** [comment]
@nicolasfranck I will also check with Rien.

**Comment by mietcls** [comment]
@nicolasfranck it is not fixed for Rien yet in Firefox. I will report.

**Comment by mietcls** [comment]
Rien is not on the latest FFesr version (on 2.6.0 instead of 2.7.0) but needs to ask Brecht to update it for him. Brecht is back on Monday. Will follow up.

**Comment by nics** [comment]
fyi @mietcls @nicolasfranck this is the wos url pattern that wikidata uses: https://www.wikidata.org/wiki/Property:P8372

**Comment by nicolasfranck** [comment]
@mietcls I am not sure if we can take any further steps, given the fact that Clarivate can only really fix this and they have done so in a way (see above).
