### ISSUE TITLE
[urgent] Not all projects flow through to Research explorer

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#975]
# Story 

Not all projects flow through to Research explorer

- 5 records were modified, in Biblio,
with the project 01n14219 The DNA of digital business processes.: https://backoffice.biblio.ugent.be/publication?q=Pooria+Jafari&sort=date-updated-desc
  - 8763722
  - 8762406
  - 8762414
  - 8762400
  - 8694914
- They have now neatly flown through to the front office, together with the project:
  - https://biblio.ugent.be/publication/8694914
  - https://biblio.ugent.be/publication/8762406
  - https://biblio.ugent.be/publication/8762414
  - https://biblio.ugent.be/publication/8762400
  - https://biblio.ugent.be/publication/8694914
- However, for some reason only 2 of those 5 show up in the research portal when you search for the project:
https://research.ugent.be/web/result/project/be8beafd-a79f-11e9-bcd2-c58490666d27/output/01n14219-het-dna-van-digitale-bedrijfsprocesses/nl
  - https://biblio.ugent.be/publication/8763722
  - https://biblio.ugent.be/publication/8694914

What are the parameters here? What does not flow through?

Possibly related to:
- #977 
- https://github.com/ugent-library/biblio-backoffice/issues/967

**Comment by netsensei** [comment]
fwiw:  


    8763722
    8762406
    8762414
    8762400
    8694914


https://biblio.ugent.be/oai?verb=GetRecord&identifier=8694914&metadataPrefix=mods
https://biblio.ugent.be/oai?verb=GetRecord&identifier=8694914&metadataPrefix=mods
https://biblio.ugent.be/oai?verb=GetRecord&identifier=8694914&metadataPrefix=mods
https://biblio.ugent.be/oai?verb=GetRecord&identifier=8694914&metadataPrefix=mods

**Comment by nics** [comment]
@netsensei gismo is harvesting MODS 3.6 output not the older MODS format:

https://biblio.ugent.be/oai?verb=GetRecord&identifier=8694914&metadataPrefix=mods_36

@miet Pascal gave me the reason why these haven't been picked up by gismo:

```
[15:45] Pascal Vandaele
Het probleem zit in het feit dat er aan de publicaties een "no license (in copyright)" waarde hangt. Dat wordt door GISMO niet aanvaard, omdat dit een waarde was voor datasets.  Voor zover ik kan terugvinden inails en analyses was dit niet bedoeld voor publicaties.
```

**Comment by mietcls** [comment]
@nics In this issue we mapped what changed how: https://github.com/ugent-library/biblio-backoffice/issues/659

A snippet:
| Old back-office | New back-office | Front-office | Info |
-- |-- | -- | -- |
_Empty selection_  | _Empty selection_ | **In copyright (no license)** | Reason: in the past this one has been used to indicate "other license" as well |
I have retained and own the full copyright for this publication <br> <br> I have transferred the copyright for this publication to the publisher <br> <br> `The above options are merged`| In copyright (no license) | **In copyright (no license)** | _This does not exist for datasets_ |

These were the old options that are similar:
<img width="573" alt="Scherm­afbeelding 2023-01-18 om 16 09 46" src="https://user-images.githubusercontent.com/1572885/213207962-4e156813-c4a5-4f55-ba80-e6c7ee6ffa08.png">

I thought "no license (in copyright)" did exist, because in the past they mentioned they defaulted to "no license" or something similar when it was empty. I'll look into notes from our meetings.

Two questions:
- Does GISMO use the information from the front-office directly, or is there an other translation somewhere?
- Is it okay if I pick it up further with Pascale to get some documentation, and figure out what they translate and how?

**Comment by nics** [comment]
@mietcls yes please
you can use links like these to see what gismo harvests:
https://biblio.ugent.be/oai?verb=GetRecord&identifier=8694914&metadataPrefix=mods_36

**Comment by mietcls** [comment]
Note; these are not issue editor types – which is something GISMO currently rejects.

**Comment by mietcls** [comment]
Fixed by the recent changes that were made in our MOS
