### ISSUE TITLE
Should these pages in Biblio be indexed by Google Scholar?

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#976]
# Question

Should these pages in Biblio be indexed by Google Scholar?

A researcher noticed that these pages are indexed by Google Scholar: https://scholar.google.com/scholar?oi=bibs&hl=en&cluster=13209559354802650257

If so, please let me know why, if not, can we influence it?

**Comment by nicolasfranck** [comment]
@mietcls apparently not anymore. That link show no results

**Comment by nicolasfranck** [comment]
https://github.ugent.be/Universiteitsbibliotheek/biblio/commit/110e226c18e9af42cc7310ef86d6adc57fa4e1fe?

Apparently the sitemap was broken, so I guess biblio wasn't reindexed by Google (not sure for how long)? @nics 
Just guessing here

**Comment by nics** [comment]
don't think so, they don't only use the sitemap
@mietcls this can be closed?
