### ISSUE TITLE
[urgent] New projects do not flow through

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#977]
# Bug

Update: [urgent] New projects do not flow through:

- Cannot add project 178BL2022 to any records.
- Cannot add project 01CD2122 to any records.

## Steps to reproduce

1. Go to biblio, record https://backoffice.biblio.ugent.be/publication/8770824?redirect-url=%2Fpublication%3Fq%3D8770824%26sort%3Ddate-updated-desc#projects

3. 2. Go to projects
![Image](https://user-images.githubusercontent.com/1572885/212882704-44dd281e-5ae3-454b-b6e4-1cc3d9254924.png)

3. Try to find project 178BL2022 or 01CD2122
![Image](https://user-images.githubusercontent.com/1572885/212882672-f82d3f73-950c-43aa-b8aa-b2ca5294e542.png)
![Image](https://user-images.githubusercontent.com/1572885/212901644-2daa9c74-bd85-40c4-aa51-092b88c96590.png)

**Comment by nics** [comment]
@miet projects added
i'll add the procedure to the biblio repo readme for future reference

**Comment by mietcls** [comment]
I'll inform the reviewers, thanks

**Comment by mietcls** [comment]
@nics is it possible this needs to happen separately for the bibliotest environment? It does work for production.

**Comment by nics** [comment]
@mietcls yes, it's a manual thing
