### ISSUE TITLE
Follow up Cloud infrastructure Inuits

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#981]
# Improvement report

Follow up Cloud infrastructure Inuits. Placing:

- [ ] UIs
- [ ] Vault
- [ ] Logging
- [ ] Monitoring

**Comment by mietcls** [comment]
@netsensei I think this is one that we've created together, but I cannot seem to recall the specifics. It feels like this is a double story by now – is that true?

**Comment by netsensei** [comment]
This one was created after one of the weekly calls with our vendor. These were high-level bullets of things that still needed / need to be put in place. It's an epic, rather then a direct actionable issue. Needs to be hashed out in actionable bullet points, so we can track progress and close it.

**Comment by mietcls** [comment]
@netsensei do you already have enough information to split off these stories? We've been tracking this in a milestone (that is past due date), but since this is an epic without actionable points we cannot really follow up on it.

**Comment by netsensei** [comment]
Let's close this one. We'll need a separate board / tracker on our other GitHub to track infrastructure changes.
