### ISSUE TITLE
[urgent] Certain projects cannot be selected any longer

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#984]
# Bug

[urgent] Certain projects cannot be selected any longer

## Steps to reproduce

Edit: new cases arised

Cannot add project 179P02516 to record [01GJG4K3Y9MV4567KWF9VKZAPR](https://backoffice.biblio.ugent.be/publication/01GJG4K3Y9MV4567KWF9VKZAPR?redirect-url=%2Fpublication%3Fq%3D01GJG4K3Y9MV4567KWF9VKZAPR%26sort%3Ddate-updated-desc#projects)

Throwing 500s the moment I start typing 01, 02, 03, 05, 06, 07, 09, 11, 13, 14, 16, 17 or 18 (the list keeps going) but not all numbers throw the errors (for instance not 04, 08, 10, 12, 19). It seems to be random.

![Scherm­afbeelding 2023-01-20 om 10 17 50](https://user-images.githubusercontent.com/1572885/213659504-a7e37450-7829-4548-b2ae-1c48376065a4.png)

![Scherm­afbeelding 2023-01-20 om 10 18 37](https://user-images.githubusercontent.com/1572885/213659595-6ea6951f-8b59-4d3b-85e2-7a704fa637c4.png)

Previous strike:
- Take any record, for example https://backoffice.biblio.ugent.be/publication/01GJMNS44XHYH8Y0RV85WPBM3H#projects and go to projects
- Try linking one of the following projects:
  - 01XP1717
  - 01P03420
  - 3E009419
  - 41E06721
  - 01IB1020
  - 41H00120

![Image](https://user-images.githubusercontent.com/1572885/213423723-bf6e548a-3e2e-45d8-9ec1-68ffe9b25703.png)

## Extra info

This happens with projects that are in red and in green in GISMO.

> project 01P03420 lukt ook niet in record 01GJMSN62REW89VCN37N7NP9VW, terwijl project 1513719N wel direct ging in ditzelfde record (toeval of niet: 01XP1717 en 01P03420 die niet lukken zijn groen in GISMO vs 1513719N die wel lukt is rood in GISMO?)"

> project 3E009419 lukt ook niet in record 01GJMV6ERD5F90SZ4NCB15N3QJ (wel rood in GISMO, dus GISMO rood/groen lijkt ongerelateerd aan project invoer in Biblio)

**Comment by mietcls** [comment]
I've tested with several projects in test, but somehow they did not catch this bug. Suddenly there are a lot of projects not working anymore.

**Comment by nics** [comment]
@mietcls fixed

**Comment by mietcls** [comment]
Something startled our projects:

Cannot add project 179P02516 to record [01GJG4K3Y9MV4567KWF9VKZAPR](https://backoffice.biblio.ugent.be/publication/01GJG4K3Y9MV4567KWF9VKZAPR?redirect-url=%2Fpublication%3Fq%3D01GJG4K3Y9MV4567KWF9VKZAPR%26sort%3Ddate-updated-desc#projects)

Throwing 500s _the moment_ I start typing "11", "13", "14", "17" or "18"
![Scherm­afbeelding 2023-01-20 om 10 17 50](https://user-images.githubusercontent.com/1572885/213659504-a7e37450-7829-4548-b2ae-1c48376065a4.png)

![Scherm­afbeelding 2023-01-20 om 10 18 37](https://user-images.githubusercontent.com/1572885/213659595-6ea6951f-8b59-4d3b-85e2-7a704fa637c4.png)

**Comment by mietcls** [comment]
Context: it worked yesterday. One of our reviewers was able to add all the missing projects they listed as broken before. Now it is back.

**Comment by nics** [comment]
some projects have no title, fixed
