### ISSUE TITLE
Cannot replace external author with internal UGent author

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#991]
# Story

Cannot replace external author with internal UGent author for record [195916](https://backoffice.biblio.ugent.be/publication/195916?redirect-url=%2Fpublication%3Fq%3D195916%26sort%3Ddate-updated-desc&show=contributors)

-> first person in the list with ID 801000757869

## Speculation

This person has probably been removed from the internal phone book?
Low priority because this is an older record.

**Comment by nicolasfranck** [comment]
From the log files:

```
btnomaddev1.ugent.be/dev-nomad-job-biblio-backoffice-app-dev.log:Jan 24 09:56:06 btnomaddev1.ugent.be dev-nomad-job-biblio-backoffice-app-dev[1430261]: 2023-01-24T08:56:06.941Z#011ERROR#011handlers/base.go:198#011[error: 01GQHFVR0XZC356NBY9SRHHQXS] edit publication contributor: could not generate contributor from person#011{"errors": "Loader panics: interface conversion: interface {} is int64, not int32", "publication": "195916", "user": "0DCE4DB4-F0EE-11E1-A9DE-61C894A0A6B4"}
```

**Comment by nicolasfranck** [comment]
Code [here](https://github.com/ugent-library/biblio-backoffice/blob/dev/internal/backends/authority/person.go#L93) expects attribute `active` to be a `int32`.

In the mongo database, this is sometimes stored as a `Long`??

```
rs0:PRIMARY> db.person.find({ ugent_id: "801000757869" }).pretty()
{
	"_id" : "6D66C4BE-B25E-11E6-B104-2D2FD0AF0289",
	"date_updated" : "2016-11-25T09:36:46Z",
	"date_created" : "2016-11-25T09:36:46Z",
	"ugent_id" : [
		"801000757869"
	],
	"active" : NumberLong(0),
	"_version" : NumberLong(1),
	"last_name" : "Geerts",
	"first_name" : "Peter",
	"publication_count" : 3
}
```

It is not the first time I have seen these long values in that attribute
Besides `_version` also should be a string, not a Long.

@nics fix in the database?

**Comment by nicolasfranck** [comment]
Mongodb does not seem to make a difference:

```
rs0:PRIMARY> db.person.find({ active: NumberInt(1) }).count()
104764
rs0:PRIMARY> db.person.find({ active: 1 }).count()
104764
rs0:PRIMARY> db.person.find({ active: NumberLong(1) }).count()
104764
```

**Comment by nics** [comment]
@nicolasfranck if we can make sure that a perl value doesn't get transliterated to a long anymore
