### ISSUE TITLE
Let "Other license" field with SPDX value flow through from datasets to MODS36 <dcterms:license> field

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#992]
# Story 

Let "Other license" field with SPDX value flow through from datasets to MODS36 <dcterms:license> field.

Example:
https://biblio.ugent.be/oai?verb=GetRecord&identifier=01GQM4W28VTV2SAE0GM4MBANJ4&metadataPrefix=mods_36

Correct: `<accessCondition lang="eng" type="useAndReproduction">A specific license has been chosen by the rights holder. Get in touch with the rights holder for reuse rights.</accessCondition>`
**Incorrect: `<dcterms:license>LicenseNotListed</dcterms:license>`**

Expected: should, in case of example, show `<dcterms:license>AGPL-3.0</dcterms:license>`.
This value comes from the field field out in "other license"
![Image](https://user-images.githubusercontent.com/1572885/213702492-9d8d33fa-4d2a-45fd-be91-36a52e44cc36.png)

___

## Extensive context

When selecting `The license is not listed here` as datasets license, and filling out the "other license" field with an SPDX license such as `CC-BY-NC-3.0` (or an other value)
![Image](https://user-images.githubusercontent.com/1572885/213702492-9d8d33fa-4d2a-45fd-be91-36a52e44cc36.png)

...it now shows the value "The license is not listed here" in the `<accessCondition type="useAndReproduction">` output (correct)
![Image](https://user-images.githubusercontent.com/1572885/213702729-56c992a7-1cb0-41b0-bf15-ee752c538d99.png)

... and it shows `LicenseNotListed`  in the `<dcterms:license>` field (unexpected)
![Image](https://user-images.githubusercontent.com/1572885/213703051-60f683e7-185a-41a4-9dfd-2b6cfa769919.png)

## Expected behaviour
Same as above, only change:

... and it shows `CC-BY-NC-3.0` (or an other value) in the `<dcterms:license>` field
![Image](https://user-images.githubusercontent.com/1572885/213703250-87c4d0f8-2bbd-46f1-b1c2-6b49728043d8.png)

## Context

GISMO will connect the field value of `<dcterms:license>` to the SPDX values they understand, if not, they will fall back to the `<accessCondition type="useAndReproduction">` value, which will be `The license is not listed here`

More background: https://booktower.gitbook.io/product-docs/producten-en-diensten/biblio-academische-bibliografie-en-repository/licenties-en

**Comment by nicolasfranck** [comment]
@mietcls yes, that is the result of [removing LicenseNotListed](https://github.com/ugent-library/biblio-backoffice/commit/9652e6d52d7075bf5dea665c6fe8a9c15b936af7#diff-6d2351e1fd7f4e11a05500c73f2f60186dc76929ea29a1b5ddc41b3689c74252L55) from `hiddenLicenses`.

I would suggest:

* add `LicenseNotListed` back to hidden licenses so it doesn't show up again in `useAndReproduction` (so attribute `copyrightStatement` is empty)
* overwrite `License` with value of `OtherLicense` if `License == "OtherLicense"` (OtherLicense is not used in biblio anyway). Warning: the value that originates from this field can be anything. In the above it was a "code", but can be an url, depending on what the reviewers have set their mind to.

**Comment by mietcls** [comment]
Does [this](https://github.com/ugent-library/biblio-backoffice/commit/9652e6d52d7075bf5dea665c6fe8a9c15b936af7#diff-6d2351e1fd7f4e11a05500c73f2f60186dc76929ea29a1b5ddc41b3689c74252L55) influence behaviour for publications as well? Or is this only for Datasets? Because we need to see the value for publications.

**Comment by nicolasfranck** [comment]
Only for datasets. This ticket is about datasets ;-)

**Comment by nicolasfranck** [comment]
@mietcls is this ok now?

**Comment by mietcls** [comment]
@nicolasfranck unfortunately not, I've tried on test and on production.

Good example of dataset record: 01GQM4W28VTV2SAE0GM4MBANJ4
- https://biblio.ugent.be/oai?verb=GetRecord&identifier=01GQM4W28VTV2SAE0GM4MBANJ4&metadataPrefix=mods_36
  - Correct: `<accessCondition lang="eng" type="useAndReproduction">A specific license has been chosen by the rights holder. Get in touch with the rights holder for reuse rights.</accessCondition>`
  - Incorrect: `<dcterms:license>LicenseNotListed</dcterms:license>`
- License shows 
  - As expected "The license is not listed here"
  - Not visible in OAI: AGPL-3.0

**Comment by nics** [comment]
fixed by https://github.ugent.be/Universiteitsbibliotheek/biblio/pull/72
