### ISSUE TITLE
[Urgent] Split personality for researcher in Biblio

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#995]
# Story

Split personality for researcher in Biblio

## Context

https://telefoonboek.prd.rad.ugent.be/nl/people/800000028572
https://telefoonboek.prd.rad.ugent.be/nl/people/802001357329

These two people are the same, the person in case let us know they have two personalities in Biblio right now. In GISMO however this person has two different birth dates, but we think they might have made a mistake there.

![Image](https://user-images.githubusercontent.com/1572885/214267458-01790d6f-1b31-47cc-9e1f-fd82e486369b.png)

### Back office

One of his profiles is connected to an older department (EB02), which makes it seem they are not active anymore:
![Image](https://user-images.githubusercontent.com/1572885/214267611-ab0bf227-260a-4bfc-9673-4bde4383d0cf.png)

![Image](https://user-images.githubusercontent.com/1572885/214267966-28c727ec-8a7e-4be9-9f3f-a98a023d69a9.png)

### Front office

When looking up the publications in the front-office **for the older UGent ID, you can find publications**, but for **the newer ID you cannot find any publications**:

![Image](https://user-images.githubusercontent.com/1572885/214268397-2b4e5d0d-6af2-49f4-aae4-f522985450a3.png)

**Comment by nics** [comment]
@miet These are 2 different people

**Comment by mietcls** [comment]
@nics thank you for investigating. There was a hunch there was a mistake in GISMO because of several reasons. Apparently some records have been added to the wrong person the reviewers noticed now, creating the illusion of being the same (a secretary assistant asked us). I'll keep an eye out.
